package chat.oldy;
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.media.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.concurrent.*;

public class AudioLabActivity extends Activity {
 final ExecutorService work=Executors.newSingleThreadExecutor();final Handler ui=new Handler(Looper.getMainLooper());
 short[] original,processed;File sourceFile,resultFile,recording;MediaRecorder recorder;MediaPlayer player;
 TextView status,recordKey;ProgressBar progress;SeekBar strength;int effect=1,generation;boolean busy;long started;AudioWave wave;LinearLayout root,actions;
 int bg=0xff0e1220,card=0xff20283d,text=0xffeef4ff,accent=0xff72eee1;
 final Runnable meter=new Runnable(){public void run(){if(recorder==null)return;long seconds=(SystemClock.elapsedRealtime()-started)/1000;status.setText(I18n.t("Запись · ")+seconds+I18n.t(" / 120 с"));try{wave.level(recorder.getMaxAmplitude());}catch(Exception ignored){}ui.postDelayed(this,70);}};
 public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(bg);getWindow().setNavigationBarColor(bg);root=new LinearLayout(this);root.setOrientation(1);root.setPadding(dp(18),dp(14),dp(18),dp(18));root.setBackgroundColor(bg);setContentView(root);if(Build.VERSION.SDK_INT>=35)root.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets x=insets.getInsets(WindowInsets.Type.systemBars());v.setPadding(dp(18)+x.left,dp(12)+x.top,dp(18)+x.right,dp(16)+x.bottom);return insets;});
  ScrollView scroll=new ScrollView(this);LinearLayout body=new LinearLayout(this);body.setOrientation(1);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));body.addView(button(I18n.t("‹  Приложения и игры"),this::finish));body.addView(label(I18n.t("Аудиомастерская"),27));body.addView(label(I18n.t("Очисти запись, добавь эффект и сравни результат. Всё обрабатывается на телефоне."),14));space(body,18);wave=new AudioWave(this);body.addView(wave,new LinearLayout.LayoutParams(-1,dp(90)));status=label(I18n.t("Выбери аудио или запиши голос · до 2 минут"),14);body.addView(status);progress=new ProgressBar(this);progress.setVisibility(View.GONE);body.addView(progress,new LinearLayout.LayoutParams(-1,dp(32)));
  body.addView(button(I18n.t("Открыть аудиофайл"),()->{if(busy||recorder!=null)return;startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("audio/*").addCategory(Intent.CATEGORY_OPENABLE),1);}));recordKey=button(I18n.t("Записать голос"),this::record);body.addView(recordKey);space(body,16);
  body.addView(label(I18n.t("ОБРАБОТКА"),11));Spinner effects=new Spinner(this);String[] names={I18n.t("Оригинал"),I18n.t("Убрать фоновый шум"),I18n.t("Радио"),I18n.t("Робот"),I18n.t("Эхо")};effects.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,names));effects.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?> p){}public void onItemSelected(android.widget.AdapterView<?> p,View v,int at,long id){effect=at;if(v instanceof TextView)((TextView)v).setTextColor(text);}});effects.setSelection(1);body.addView(effects,new LinearLayout.LayoutParams(-1,dp(50)));
  strength=new SeekBar(this);strength.setMax(100);strength.setProgress(55);body.addView(label(I18n.t("Сила эффекта"),12));body.addView(strength,new LinearLayout.LayoutParams(-1,dp(44)));body.addView(button(I18n.t("Обработать звук"),this::process));space(body,12);
  actions=new LinearLayout(this);actions.setOrientation(1);actions.addView(button(I18n.t("▶ Послушать оригинал"),()->play(sourceFile)));actions.addView(button(I18n.t("▶ Послушать результат"),()->play(resultFile)));actions.addView(button(I18n.t("■ Остановить"),this::stopPlayer));actions.addView(button(I18n.t("Сохранить результат WAV"),()->{if(resultFile==null||busy)return;startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("audio/wav").putExtra(Intent.EXTRA_TITLE,"Oldy-audio.wav").addCategory(Intent.CATEGORY_OPENABLE),2);}));body.addView(actions);
  body.addView(label(I18n.t("Шумоподавление уменьшает ровный фоновый шум и гул. Чем выше сила, тем заметнее может меняться голос."),12));
 }
 int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
 TextView label(String s,int size){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(text);v.setPadding(0,dp(8),0,dp(8));return v;}
 TextView button(String s,Runnable action){TextView v=label(s,15);v.setGravity(Gravity.CENTER);GradientDrawable d=new GradientDrawable();d.setColor(card);d.setCornerRadius(dp(16));v.setBackground(d);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(48));lp.bottomMargin=dp(8);v.setLayoutParams(lp);v.setOnClickListener(x->action.run());return v;}
 void space(LinearLayout body,int h){body.addView(new View(this),new LinearLayout.LayoutParams(1,dp(h)));}
 void state(boolean working,String message){busy=working;progress.setVisibility(working?View.VISIBLE:View.GONE);status.setText(message);}
 void record(){if(busy)return;if(recorder!=null){finishRecording();return;}if(checkSelfPermission(android.Manifest.permission.RECORD_AUDIO)!=android.content.pm.PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{android.Manifest.permission.RECORD_AUDIO},3);return;}if(LiveCall.current!=null){status.setText(I18n.t("Заверши звонок перед записью"));return;}stopPlayer();try{recording=new File(getCacheDir(),"lab-record-"+System.currentTimeMillis()+".m4a");recorder=new MediaRecorder();recorder.setAudioSource(MediaRecorder.AudioSource.MIC);recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);recorder.setAudioSamplingRate(32000);recorder.setAudioChannels(1);recorder.setAudioEncodingBitRate(96000);recorder.setMaxDuration(120000);recorder.setOutputFile(recording.getAbsolutePath());recorder.setOnInfoListener((r,w,e)->{if(w==MediaRecorder.MEDIA_RECORDER_INFO_MAX_DURATION_REACHED)finishRecording();});recorder.prepare();recorder.start();started=SystemClock.elapsedRealtime();recordKey.setText(I18n.t("■ Закончить запись"));ui.post(meter);}catch(Exception e){releaseRecorder();status.setText(I18n.t("Не удалось начать запись. Проверь доступ к микрофону."));}}
 void finishRecording(){File file=recording;boolean valid=false;try{recorder.stop();valid=file!=null&&file.length()>500&&SystemClock.elapsedRealtime()-started>700;}catch(Exception ignored){}releaseRecorder();if(valid)load(Uri.fromFile(file));else status.setText(I18n.t("Запись слишком короткая. Попробуй ещё раз."));}
 void releaseRecorder(){ui.removeCallbacks(meter);if(recorder!=null){try{recorder.release();}catch(Exception ignored){}recorder=null;}if(recordKey!=null)recordKey.setText(I18n.t("Записать голос"));}
 void load(Uri uri){stopPlayer();state(true,I18n.t("Открываем аудио…"));final int seq=++generation;work.execute(()->{try{short[] data=AudioCodec.decode(this,uri);File file=new File(getCacheDir(),"lab-original-"+seq+".wav");AudioCodec.wav(file,data,AudioCodec.RATE);runOnUiThread(()->{if(isDestroyed()||seq!=generation){file.delete();return;}if(sourceFile!=null)sourceFile.delete();if(resultFile!=null)resultFile.delete();sourceFile=file;resultFile=null;original=data;processed=null;wave.samples(data);state(false,I18n.t("Аудио готово · ")+String.format(java.util.Locale.ROOT,"%.1f",data.length/(float)AudioCodec.RATE)+I18n.t(" с"));});}catch(Exception e){runOnUiThread(()->state(false,Api.message(e)));}});}
 void process(){if(original==null||busy||recorder!=null)return;stopPlayer();final int mode=effect,seq=++generation;final float amount=strength.getProgress()/100f;final short[] input=original;state(true,I18n.t("Обрабатываем звук…"));work.execute(()->{try{short[] data=AudioDsp.process(input,AudioCodec.RATE,mode,amount);File output=new File(getCacheDir(),"lab-result-"+seq+".wav");AudioCodec.wav(output,data,AudioCodec.RATE);runOnUiThread(()->{if(isDestroyed()||seq!=generation){output.delete();return;}if(resultFile!=null)resultFile.delete();processed=data;resultFile=output;wave.samples(data);state(false,I18n.t("Готово. Сравни оригинал и результат."));});}catch(Exception e){runOnUiThread(()->state(false,Api.message(e)));}});}
 void play(File file){if(file==null||busy||recorder!=null)return;stopPlayer();try{player=new MediaPlayer();player.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_MEDIA).setContentType(AudioAttributes.CONTENT_TYPE_SPEECH).build());player.setDataSource(file.getAbsolutePath());player.setOnPreparedListener(MediaPlayer::start);player.setOnCompletionListener(p->stopPlayer());player.prepareAsync();}catch(Exception e){status.setText(I18n.t("Не удалось воспроизвести запись"));}}
 void stopPlayer(){if(player!=null){try{player.release();}catch(Exception ignored){}player=null;}}
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();if(request==1)load(uri);if(request==2&&resultFile!=null){final File file=resultFile;state(true,I18n.t("Сохраняем…"));work.execute(()->{try(InputStream in=new FileInputStream(file);OutputStream out=getContentResolver().openOutputStream(uri)){byte[] block=new byte[16384];int n;while((n=in.read(block))>=0)out.write(block,0,n);runOnUiThread(()->state(false,I18n.t("Файл сохранён")));}catch(Exception e){runOnUiThread(()->state(false,I18n.t("Не удалось сохранить файл")));}});}}
 public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==3&&g.length>0&&g[0]==0)record();}
 protected void onPause(){stopPlayer();if(recorder!=null)finishRecording();super.onPause();}
 protected void onDestroy(){generation++;releaseRecorder();stopPlayer();work.shutdownNow();if(sourceFile!=null)sourceFile.delete();if(resultFile!=null)resultFile.delete();if(recording!=null)recording.delete();super.onDestroy();}
 static final class AudioWave extends View{float[] values=new float[70];final Paint p=new Paint(3);AudioWave(Context c){super(c);}void level(int value){System.arraycopy(values,1,values,0,values.length-1);values[values.length-1]=VoiceCapture.Wave.normalized(value);invalidate();}void samples(short[] data){for(int i=0;i<values.length;i++){int start=i*data.length/values.length,end=(i+1)*data.length/values.length;float peak=0;for(int j=start;j<end;j++)peak=Math.max(peak,Math.abs((int)data[j])/32768f);values[i]=peak;}invalidate();}protected void onDraw(Canvas c){p.setColor(0xff72eee1);p.setStrokeWidth(Math.max(2,getWidth()/105f));p.setStrokeCap(Paint.Cap.ROUND);for(int i=0;i<values.length;i++){float x=(i+.5f)*getWidth()/values.length,h=Math.max(3,values[i]*getHeight()*.85f);c.drawLine(x,(getHeight()-h)/2,x,(getHeight()+h)/2,p);}}}
}
