package chat.oldy;
import android.content.*;import android.media.*;import android.net.Uri;import java.io.*;import java.nio.*;

final class AudioCodec {
 static final int RATE=32000,MAX_SECONDS=120;
 static short[] decode(Context context,Uri uri)throws Exception{
  MediaExtractor extract=new MediaExtractor();MediaCodec codec=null;
  try{extract.setDataSource(context,uri,null);MediaFormat format=null;for(int i=0;i<extract.getTrackCount();i++){MediaFormat f=extract.getTrackFormat(i);if(f.getString(MediaFormat.KEY_MIME).startsWith("audio/")){format=f;extract.selectTrack(i);break;}}if(format==null)throw new IOException(I18n.t("В файле нет аудиодорожки"));
   if(format.containsKey(MediaFormat.KEY_DURATION)&&format.getLong(MediaFormat.KEY_DURATION)>MAX_SECONDS*1000000L)throw new IOException(I18n.t("Выбери аудио длительностью до 2 минут"));
   codec=MediaCodec.createDecoderByType(format.getString(MediaFormat.KEY_MIME));codec.configure(format,null,null,0);codec.start();boolean inputDone=false,outputDone=false;MediaCodec.BufferInfo info=new MediaCodec.BufferInfo();ByteArrayOutputStream pcm=new ByteArrayOutputStream();int rate=format.getInteger(MediaFormat.KEY_SAMPLE_RATE),channels=format.getInteger(MediaFormat.KEY_CHANNEL_COUNT),encoding=AudioFormat.ENCODING_PCM_16BIT;long sourceFrames=0,outputFrames=0,deadline=android.os.SystemClock.elapsedRealtime()+60000;
   while(!outputDone){if(Thread.currentThread().isInterrupted())throw new java.util.concurrent.CancellationException();if(android.os.SystemClock.elapsedRealtime()>deadline)throw new IOException(I18n.t("Обработка файла заняла слишком много времени"));
    if(!inputDone){int index=codec.dequeueInputBuffer(10000);if(index>=0){ByteBuffer buffer=codec.getInputBuffer(index);int size=extract.readSampleData(buffer,0);if(size<0){codec.queueInputBuffer(index,0,0,0,MediaCodec.BUFFER_FLAG_END_OF_STREAM);inputDone=true;}else{codec.queueInputBuffer(index,0,size,extract.getSampleTime(),0);extract.advance();}}}
    int index=codec.dequeueOutputBuffer(info,10000);if(index==MediaCodec.INFO_OUTPUT_FORMAT_CHANGED){MediaFormat out=codec.getOutputFormat();rate=out.getInteger(MediaFormat.KEY_SAMPLE_RATE);channels=out.getInteger(MediaFormat.KEY_CHANNEL_COUNT);encoding=out.containsKey(MediaFormat.KEY_PCM_ENCODING)?out.getInteger(MediaFormat.KEY_PCM_ENCODING):AudioFormat.ENCODING_PCM_16BIT;if(encoding!=AudioFormat.ENCODING_PCM_16BIT&&encoding!=AudioFormat.ENCODING_PCM_FLOAT)throw new IOException(I18n.t("Неподдерживаемый формат звука"));}
    else if(index>=0){ByteBuffer buffer=codec.getOutputBuffer(index);buffer.position(info.offset);buffer.limit(info.offset+info.size);buffer.order(ByteOrder.LITTLE_ENDIAN);int bytes=encoding==AudioFormat.ENCODING_PCM_FLOAT?4:2;while(buffer.remaining()>=channels*bytes){double mono=0;for(int c=0;c<channels;c++)mono+=encoding==AudioFormat.ENCODING_PCM_FLOAT?buffer.getFloat():buffer.getShort()/32768.0;mono/=channels;sourceFrames++;while(outputFrames*rate<(sourceFrames*(long)RATE)){int sample=(int)Math.round(Math.max(-1,Math.min(1,mono))*32767);pcm.write(sample&255);pcm.write((sample>>>8)&255);outputFrames++;if(outputFrames>MAX_SECONDS*(long)RATE)throw new IOException(I18n.t("Выбери аудио длительностью до 2 минут"));}}
     outputDone=(info.flags&MediaCodec.BUFFER_FLAG_END_OF_STREAM)!=0;codec.releaseOutputBuffer(index,false);}
   }
   byte[] bytes=pcm.toByteArray();if(bytes.length<2000)throw new IOException(I18n.t("В аудиофайле слишком мало звука"));short[] samples=new short[bytes.length/2];ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN).asShortBuffer().get(samples);return samples;
  }finally{if(codec!=null){try{codec.stop();}catch(Exception ignored){}codec.release();}extract.release();}
 }
 static void wav(File file,short[] data,int rate)throws IOException{try(FileOutputStream out=new FileOutputStream(file)){ByteBuffer header=ByteBuffer.allocate(44).order(ByteOrder.LITTLE_ENDIAN);header.put("RIFF".getBytes("US-ASCII")).putInt(36+data.length*2).put("WAVEfmt ".getBytes("US-ASCII")).putInt(16).putShort((short)1).putShort((short)1).putInt(rate).putInt(rate*2).putShort((short)2).putShort((short)16).put("data".getBytes("US-ASCII")).putInt(data.length*2);out.write(header.array());byte[] block=new byte[16384];int used=0;for(short sample:data){block[used++]=(byte)sample;block[used++]=(byte)(sample>>8);if(used==block.length){out.write(block);used=0;}}if(used>0)out.write(block,0,used);}}
}
