package chat.oldy;
import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.view.*;import android.widget.*;
public class CallActivity extends Activity {
 LiveCall.Session call;TextView state;Handler ui=new Handler(Looper.getMainLooper());
 public void onCreate(Bundle b){super.onCreate(b);call=LiveCall.current;if(call==null||getIntent().hasExtra("sid")&&!call.sid.equals(getIntent().getStringExtra("sid"))){finish();return;}getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setGravity(Gravity.CENTER);root.setPadding(dp(24),dp(40),dp(24),dp(40));root.setBackground(new android.graphics.drawable.GradientDrawable(android.graphics.drawable.GradientDrawable.Orientation.TL_BR,new int[]{0xff15233a,0xff243857,0xff312742}));Art face=new Art(this,avatar());root.addView(face,new LinearLayout.LayoutParams(dp(122),dp(122)));root.addView(text("@"+call.peer,27));state=text(call.state,17);root.addView(state);if(call.incoming&&!call.accepted){TextView accept=text("Ответить",22);accept.setOnClickListener(v->{accept();accept.setVisibility(View.GONE);});root.addView(accept);}TextView mic=text("🎙 Микрофон включён",17);mic.setOnClickListener(v->{call.mute();mic.setText(call.muted?"Микрофон выключен":"🎙 Микрофон включён");});root.addView(mic);TextView speaker=text("Громкая связь",17);speaker.setOnClickListener(v->{call.speaker();speaker.setText(call.speaker?"Громкая связь включена":"Громкая связь выключена");});root.addView(speaker);TextView end=text("Завершить звонок",20);end.setTextColor(0xffff91a3);end.setOnClickListener(v->{call.end("Звонок завершён",true);finish();});root.addView(end);setContentView(root);if((!call.incoming||getIntent().getBooleanExtra("accept",false))&&!call.accepted)accept();tick();}
 int dp(int value){return Math.round(value*getResources().getDisplayMetrics().density);}
 String avatar(){try{org.json.JSONObject p=call.vault.peer(call.peer);return p==null?"preset:0":p.optString("avatar","preset:0");}catch(Exception e){return "preset:0";}}
 TextView text(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextColor(0xffdceaff);t.setTextSize(size);t.setPadding(20,22,20,22);t.setGravity(Gravity.CENTER);return t;}
 void accept(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},80);return;}getSystemService(NotificationManager.class).cancel(410);call.start();}
 public void onRequestPermissionsResult(int r,String[] p,int[] v){super.onRequestPermissionsResult(r,p,v);if(r==80&&v.length>0&&v[0]==PackageManager.PERMISSION_GRANTED)accept();else call.end("Нет доступа к микрофону",true);}
 void tick(){if(isFinishing())return;if(call.ended){finish();return;}long seconds=call.connected?(SystemClock.elapsedRealtime()-call.connectedAt)/1000:0;state.setText(call.connected&&call.state.equals("На связи")?String.format(java.util.Locale.ROOT,"На связи · %d:%02d",seconds/60,seconds%60):call.state);ui.postDelayed(this::tick,500);}
 protected void onDestroy(){ui.removeCallbacksAndMessages(null);super.onDestroy();}
}
