package chat.oldy;
import android.app.*;import android.content.*;import android.database.Cursor;import android.graphics.*;import android.media.MediaMetadataRetriever;import android.net.Uri;import android.provider.OpenableColumns;import android.view.WindowManager;import android.widget.*;import org.json.*;import java.io.*;import java.net.*;import java.security.*;import java.util.*;import java.util.concurrent.*;import javax.net.ssl.*;
final class CreatorVideo {
 static final ExecutorService io=Executors.newSingleThreadExecutor();static volatile boolean busy,cancel;
 static void upload(MainActivity a,Uri uri,String target,String caption){if(busy){a.error("Дождись завершения текущей загрузки");return;}if(!target.startsWith("room:")){a.error("Выбери свой канал");return;}final Vault account=a.vault;busy=true;cancel=false;LinearLayout b=a.col();a.pad(b,20);TextView text=a.label("Готовим видео…",14,a.TEXT);ProgressBar progress=new ProgressBar(a,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);b.addView(text);b.addView(progress);a.paragraph(b,"Загрузка по частям. Не закрывай приложение. При обрыве выбери этот файл снова — загрузка продолжится.");AlertDialog dialog=a.dialog().setTitle("MP4 в твой канал").setView(b).setNegativeButton("Остановить",(d,w)->cancel=true).create();dialog.setCancelable(false);dialog.show();a.getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);
  io.execute(()->{String vid="";try{long size=-1;String name="Видео.mp4";try(Cursor c=a.getContentResolver().query(uri,new String[]{OpenableColumns.DISPLAY_NAME,OpenableColumns.SIZE},null,null,null)){if(c!=null&&c.moveToFirst()){name=c.getString(0);size=c.getLong(1);}}if(size<12||size>2147483648L||name==null||!name.toLowerCase(Locale.ROOT).endsWith(".mp4"))throw new Exception("Выбери MP4 размером до 2 ГБ");Api api=new Api(a);String token=account.token(),rid=Conversation.room(target);android.content.SharedPreferences prefs=Notices.prefs(a);String saved=prefs.getString("video-upload-"+account.nick(),"");JSONObject upload=null;if(!saved.isEmpty())try{JSONObject old=new JSONObject(saved);if(old.optString("uri").equals(uri.toString())&&old.optString("room").equals(rid)&&old.optLong("size")==size)upload=api.call("/video-status/"+old.getString("id"),null,token);}catch(Exception ignored){}if(upload==null){upload=api.call("/videos/start",new JSONObject().put("room",rid).put("size",size).put("name",name),token);prefs.edit().putString("video-upload-"+account.nick(),new JSONObject().put("id",upload.getString("id")).put("uri",uri.toString()).put("room",rid).put("size",size).toString()).apply();}vid=upload.getString("id");long offset=upload.optLong("received");if(upload.optBoolean("ready"))offset=size;MessageDigest digest=MessageDigest.getInstance("SHA-256");long at=0;byte[] buffer=new byte[524288];
   try(InputStream in=a.getContentResolver().openInputStream(uri)){if(in==null)throw new IOException();while(at<size){if(cancel)throw new InterruptedIOException("Загрузка приостановлена");int length=(int)Math.min(buffer.length,size-at),got=0;while(got<length){int n=in.read(buffer,got,length-got);if(n<0)throw new IOException("Файл изменился");got+=n;}digest.update(buffer,0,length);if(at>=offset){int retries=0;while(true){try{offset=chunk(api,token,vid,at,buffer,length);break;}catch(Exception e){if(++retries>3)throw e;JSONObject state=api.call("/video-status/"+vid,null,token);long received=state.getLong("received");if(received==at+length){offset=received;break;}if(received!=at)throw new IOException("Позиция загрузки изменилась");}}}at+=length;final int percent=(int)(at*100/size);a.runOnUiThread(()->{progress.setProgress(percent);text.setText("Загружено "+percent+"%");});}}
   api.call("/videos/finish",new JSONObject().put("id",vid),token);String thumb=thumbnail(a,uri);JSONObject payload=new JSONObject().put("kind","file").put("mime","video/mp4").put("cloud_video",vid).put("size",size).put("name",name).put("sha256",Crypto.hex(digest.digest()).toLowerCase(Locale.ROOT)).put("thumb",thumb).put("text",caption.substring(0,Math.min(2000,caption.length())));if(a.vault!=account)throw new IOException("Аккаунт изменился");a.prepareRoom(target);String mid=account.queuePayload(target,payload,null);ChatService.register(api,account,account.message(mid));try{api.call("/threads",new JSONObject().put("room",rid).put("post",mid),token);}catch(Exception deferred){}prefs.edit().remove("video-upload-"+account.nick()).apply();a.runOnUiThread(()->{dialog.dismiss();if(a.compose!=null&&a.chat.equals(target))a.compose.setText("");a.renderMessages();Toast.makeText(a,"Видео опубликовано",Toast.LENGTH_LONG).show();});
  }catch(Exception e){a.runOnUiThread(()->{dialog.dismiss();a.error(cancel?"Загрузка приостановлена. Выбери тот же MP4, чтобы продолжить.":Api.message(e));});}finally{busy=false;a.runOnUiThread(()->a.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON));}});
 }
 static long chunk(Api api,String token,String id,long offset,byte[] bytes,int length)throws Exception{String base=Api.live.isEmpty()?api.url():Api.live;HttpsURLConnection c=(HttpsURLConnection)new URL(base+"/video-chunk/"+id).openConnection();c.setSSLSocketFactory(api.factory());c.setInstanceFollowRedirects(false);c.setConnectTimeout(18000);c.setReadTimeout(40000);c.setRequestMethod("POST");c.setRequestProperty("Authorization","Bearer "+token);c.setRequestProperty("X-Upload-Offset",Long.toString(offset));c.setRequestProperty("Content-Type","application/octet-stream");c.setDoOutput(true);c.setFixedLengthStreamingMode(length);try{try(OutputStream out=c.getOutputStream()){out.write(bytes,0,length);}int status=c.getResponseCode();JSONObject result=new JSONObject(Api.read(status<400?c.getInputStream():c.getErrorStream(),10000));if(status!=200)throw new Api.Failure(status,result.optString("error","Ошибка загрузки"));return result.getLong("received");}finally{c.disconnect();}}
 static String thumbnail(MainActivity a,Uri uri){MediaMetadataRetriever r=new MediaMetadataRetriever();Bitmap frame=null,small=null;try{r.setDataSource(a,uri);frame=r.getFrameAtTime(1000000);if(frame==null)frame=r.getFrameAtTime(0);if(frame==null)return "";int edge=280;for(int pass=0;pass<4;pass++){float scale=Math.min(1f,(float)edge/Math.max(frame.getWidth(),frame.getHeight()));small=Bitmap.createScaledBitmap(frame,Math.max(1,Math.round(frame.getWidth()*scale)),Math.max(1,Math.round(frame.getHeight()*scale)),true);for(int quality:new int[]{70,50,35,20}){ByteArrayOutputStream out=new ByteArrayOutputStream();small.compress(Bitmap.CompressFormat.JPEG,quality,out);if(out.size()<=7800)return Crypto.b64(out.toByteArray());}if(small!=frame)small.recycle();small=null;edge=Math.max(72,edge*3/4);}return "";}catch(Exception e){return "";}finally{if(small!=null&&small!=frame)small.recycle();if(frame!=null)frame.recycle();try{r.release();}catch(Exception ignored){}}}
} 
