package chat.oldy;

import android.app.*;import android.content.*;import android.content.pm.ServiceInfo;import android.net.*;import android.os.*;import android.system.OsConstants;import java.io.*;import java.util.concurrent.*;import hev.htproxy.TProxyService;

/** Local-only per-app split VPN. No default route and no remote tunnel endpoint. */
public final class LocalTunnelService extends VpnService {
 static final String ACTION_START="chat.oldy.YOUTUBE_START",ACTION_IDLE="chat.oldy.YOUTUBE_IDLE",ACTION_STOP="chat.oldy.YOUTUBE_STOP",ACTION_TOUCH="chat.oldy.YOUTUBE_TOUCH";
 static volatile java.util.concurrent.CountDownLatch cleanup=new java.util.concurrent.CountDownLatch(0);
 final ExecutorService work=Executors.newSingleThreadExecutor();final Handler ui=new Handler(Looper.getMainLooper());volatile ParcelFileDescriptor tun;LocalSocksRelay relay;volatile boolean stopping;long lastUse;boolean viewer;Network underlying;
 final Runnable tick=new Runnable(){public void run(){if(stopping)return;if(tun!=null){boolean nativeOn;try{nativeOn=TProxyService.TProxyIsRunning();}catch(Throwable failure){nativeOn=false;}if(!nativeOn){fail("LOCAL_MODULE_STOPPED");return;}Network now=NetworkDiagnostics.physical(LocalTunnelService.this);if(now==null){fail("NETWORK_LOST");return;}if(!now.equals(underlying)){fail("NETWORK_CHANGED_RECONNECT");return;}long[] stats=TProxyService.TProxyGetStats();if(stats!=null&&stats.length==4){TunnelStateRepository.txBytes=stats[1];TunnelStateRepository.rxBytes=stats[3];}TunnelStateRepository.set("ON");}if(SystemClock.elapsedRealtime()-lastUse>(viewer?45000:30000)){stopSelf();return;}ui.postDelayed(this,1500);}};
 static void start(Context c){c.startForegroundService(new Intent(c,LocalTunnelService.class).setAction(ACTION_START));}
 static void idle(Context c){if(TunnelStateRepository.on())try{c.startService(new Intent(c,LocalTunnelService.class).setAction(ACTION_IDLE));}catch(RuntimeException ignored){}}
 static void touch(Context c){if(TunnelStateRepository.on())try{c.startService(new Intent(c,LocalTunnelService.class).setAction(ACTION_TOUCH));}catch(RuntimeException ignored){}}
 static void stop(Context c){c.stopService(new Intent(c,LocalTunnelService.class));}
 public int onStartCommand(Intent intent,int flags,int id){if(intent==null){stopSelf();return START_NOT_STICKY;}String action=intent.getAction();if(ACTION_STOP.equals(action)){stopSelf();return START_NOT_STICKY;}if(ACTION_TOUCH.equals(action)){if(tun==null){stopSelf();return START_NOT_STICKY;}viewer=true;lastUse=SystemClock.elapsedRealtime();return START_NOT_STICKY;}if(ACTION_IDLE.equals(action)){if(tun==null){stopSelf();return START_NOT_STICKY;}viewer=false;lastUse=SystemClock.elapsedRealtime();return START_NOT_STICKY;}if(!ACTION_START.equals(action)){stopSelf();return START_NOT_STICKY;}
  viewer=true;lastUse=SystemClock.elapsedRealtime();if(tun!=null)return START_NOT_STICKY;if(TunnelStateRepository.state.equals("STARTING"))return START_NOT_STICKY;
  try{NotificationManager nm=getSystemService(NotificationManager.class);nm.createNotificationChannel(new NotificationChannel("youtube-local",I18n.t("Локальный просмотр YouTube"),NotificationManager.IMPORTANCE_LOW));PendingIntent stop=PendingIntent.getService(this,620,new Intent(this,LocalTunnelService.class).setAction(ACTION_STOP),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);
   Notification n=new Notification.Builder(this,"youtube-local").setSmallIcon(android.R.drawable.ic_lock_lock).setContentTitle(I18n.t("YouTube · локальный режим Oldi")).setContentText(I18n.t("Видео идёт напрямую на ваше устройство")).setOngoing(true).addAction(new Notification.Action.Builder(null,I18n.t("Отключить"),stop).build()).build();if(Build.VERSION.SDK_INT>=34)startForeground(620,n,ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE);else startForeground(620,n);
  }catch(Exception failure){fail("FOREGROUND_START_DENIED");return START_NOT_STICKY;}
  stopping=false;java.util.concurrent.CountDownLatch previousCleanup=cleanup;TunnelStateRepository.set("STARTING");work.execute(()->{try{if(!previousCleanup.await(3,TimeUnit.SECONDS))throw new IOException();YouTubeDomainRules rules=YouTubeDomainRules.load(this);if(!rules.enabled)throw new IOException();underlying=NetworkDiagnostics.physical(this);if(underlying==null)throw new IOException();relay=new LocalSocksRelay(this,new TrafficClassifier(rules));
   File config=new File(getFilesDir(),"youtube-local.yml");String yaml="tunnel:\n  mtu: 1280\n  ipv4: 198.18.0.2\n  ipv6: 'fd66:6f6c:6479::2'\nsocks5:\n  address: 127.0.0.1\n  port: "+relay.port()+"\n  udp: udp\n  username: oldy\n  password: '"+relay.password+"'\nmisc:\n  max-session-count: 64\n  connect-timeout: 10000\n  tcp-read-write-timeout: 120000\n  udp-read-write-timeout: 30000\n  log-file: '/dev/null'\n  log-level: error\n";try(FileOutputStream out=new FileOutputStream(config)){out.write(yaml.getBytes(java.nio.charset.StandardCharsets.UTF_8));}
   Builder builder=new Builder().setSession("Oldi · YouTube local").setMtu(1280).addAllowedApplication(getPackageName()).addAddress("198.18.0.2",32).addAddress("fd66:6f6c:6479::2",128).addDnsServer(TrafficClassifier.DNS).addRoute("198.18.0.0",16).addRoute("fd66:6f6c:6479::",64).allowFamily(OsConstants.AF_INET).allowFamily(OsConstants.AF_INET6).allowBypass().setBlocking(false);builder.setUnderlyingNetworks(new Network[]{underlying});if(Build.VERSION.SDK_INT>=29){NetworkCapabilities caps=getSystemService(ConnectivityManager.class).getNetworkCapabilities(underlying);builder.setMetered(caps==null||!caps.hasCapability(NetworkCapabilities.NET_CAPABILITY_NOT_METERED));}
   if(stopping)return;tun=builder.establish();if(tun==null||!TProxyService.TProxyStartService(config.getAbsolutePath(),tun.getFd()))throw new IOException();ui.post(tick);
  }catch(Throwable failure){ui.post(()->fail("LOCAL_START_FAILED"));}});return START_NOT_STICKY;
 }
 void relayFailed(){ui.post(()->fail("LOCAL_RELAY_FAILED"));}
 void fail(String reason){TunnelStateRepository.fail(this,reason);stopSelf();}
 public void onRevoke(){TunnelStateRepository.fail(this,"VPN_PERMISSION_REVOKED");stopSelf();}
 public void onDestroy(){stopping=true;ui.removeCallbacksAndMessages(null);TunnelStateRepository.set("OFF");java.util.concurrent.CountDownLatch pending=new java.util.concurrent.CountDownLatch(1);cleanup=pending;work.execute(()->{try{try{TProxyService.TProxyStopService();}catch(Throwable ignored){}if(relay!=null)relay.close();if(tun!=null)try{tun.close();}catch(Exception ignored){}new File(getFilesDir(),"youtube-local.yml").delete();}finally{pending.countDown();}});work.shutdown();stopForeground(STOP_FOREGROUND_REMOVE);super.onDestroy();}
}
