package chat.oldy;

import android.app.*;import android.content.*;import android.content.pm.ServiceInfo;import android.net.*;import android.os.*;import android.system.OsConstants;import java.io.*;import java.util.concurrent.*;import hev.htproxy.TProxyService;

/** Local-only per-app split VPN. No default route and no remote tunnel endpoint. */
public final class LocalTunnelService extends VpnService {
 static final String ACTION_START="chat.oldy.YOUTUBE_START",ACTION_IDLE="chat.oldy.YOUTUBE_IDLE",ACTION_STOP="chat.oldy.YOUTUBE_STOP",ACTION_TOUCH="chat.oldy.YOUTUBE_TOUCH",ACTION_BROWSER="chat.oldy.YOUTUBE_BROWSER";
 static volatile java.util.concurrent.CountDownLatch cleanup=new java.util.concurrent.CountDownLatch(0);
 final ExecutorService work=Executors.newSingleThreadExecutor();final Handler ui=new Handler(Looper.getMainLooper());volatile ParcelFileDescriptor tun;LocalSocksRelay relay;LocalDpiEngine dpi;LocalWebProxy webProxy;String strategy="auto";String browserPackage="",restartBrowser="";boolean browserVisible;volatile boolean stopping;long lastUse;boolean viewer,restartRequested;Network underlying;
 final Runnable tick=new Runnable(){public void run(){if(stopping)return;if(tun!=null){boolean nativeOn;try{nativeOn=TProxyService.TProxyIsRunning();}catch(Throwable failure){nativeOn=false;}if(!nativeOn||dpi==null||!dpi.alive()){fail("LOCAL_MODULE_STOPPED");return;}Network now=NetworkDiagnostics.physical(LocalTunnelService.this);if(now==null){fail("NETWORK_LOST");return;}if(!now.equals(underlying)){fail("NETWORK_CHANGED_RECONNECT");return;}long[] stats=TProxyService.TProxyGetStats();if(stats!=null&&stats.length==4){TunnelStateRepository.txBytes=stats[1];TunnelStateRepository.rxBytes=stats[3];}if(webProxy!=null){TunnelStateRepository.webConnections=webProxy.connections;TunnelStateRepository.webRx=webProxy.received;}TunnelStateRepository.set("ON");}if(SystemClock.elapsedRealtime()-lastUse>(browserVisible?10800000:viewer?45000:30000)){shutdown();return;}ui.postDelayed(this,1500);}};
 static void start(Context c){c.startForegroundService(new Intent(c,LocalTunnelService.class).setAction(ACTION_START).putExtra("strategy",Notices.prefs(c).getString("youtube_dpi_strategy","auto")));}
 static void startBrowser(Context c,String browser){c.startForegroundService(new Intent(c,LocalTunnelService.class).setAction(ACTION_START).putExtra("browser",browser).putExtra("strategy",Notices.prefs(c).getString("youtube_dpi_strategy","auto")));}
 static void browser(Context c,boolean visible){try{c.startService(new Intent(c,LocalTunnelService.class).setAction(ACTION_BROWSER).putExtra("visible",visible));}catch(RuntimeException ignored){}}
 static void idle(Context c){if(TunnelStateRepository.on())try{c.startService(new Intent(c,LocalTunnelService.class).setAction(ACTION_IDLE));}catch(RuntimeException ignored){}}
 static void touch(Context c){if(TunnelStateRepository.on())try{c.startService(new Intent(c,LocalTunnelService.class).setAction(ACTION_TOUCH));}catch(RuntimeException ignored){}}
 static void stop(Context c){try{c.startService(new Intent(c,LocalTunnelService.class).setAction(ACTION_STOP));}catch(RuntimeException denied){c.stopService(new Intent(c,LocalTunnelService.class));}}
 public synchronized int onStartCommand(Intent intent,int flags,int id){if(intent==null){shutdown();return START_NOT_STICKY;}String action=intent.getAction();if(ACTION_STOP.equals(action)){restartRequested=false;shutdown();return START_NOT_STICKY;}if(stopping){if(ACTION_START.equals(action)){restartRequested=true;restartBrowser=YouTubeBrowser.validBrowser(this,intent.getStringExtra("browser"));}return START_NOT_STICKY;}if(ACTION_BROWSER.equals(action)){browserVisible=intent.getBooleanExtra("visible",false);viewer=browserVisible;lastUse=SystemClock.elapsedRealtime();return START_NOT_STICKY;}if(ACTION_TOUCH.equals(action)){if(tun==null){shutdown();return START_NOT_STICKY;}viewer=true;lastUse=SystemClock.elapsedRealtime();return START_NOT_STICKY;}if(ACTION_IDLE.equals(action)){if(tun==null){shutdown();return START_NOT_STICKY;}viewer=false;browserVisible=false;lastUse=SystemClock.elapsedRealtime();return START_NOT_STICKY;}if(!ACTION_START.equals(action)){shutdown();return START_NOT_STICKY;}
  String wanted=intent.getStringExtra("strategy");strategy=wanted!=null&&wanted.matches("auto|split|disorder|fake4|fake8")?wanted:"auto";browserPackage=YouTubeBrowser.validBrowser(this,intent.getStringExtra("browser"));viewer=true;lastUse=SystemClock.elapsedRealtime();if(tun!=null)return START_NOT_STICKY;if(TunnelStateRepository.state.equals("STARTING"))return START_NOT_STICKY;
  try{NotificationManager nm=getSystemService(NotificationManager.class);nm.createNotificationChannel(new NotificationChannel("youtube-local",I18n.t("Локальный просмотр YouTube"),NotificationManager.IMPORTANCE_LOW));PendingIntent stop=PendingIntent.getService(this,620,new Intent(this,LocalTunnelService.class).setAction(ACTION_STOP),PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);
   Notification n=new Notification.Builder(this,"youtube-local").setSmallIcon(android.R.drawable.ic_lock_lock).setContentTitle(I18n.t("YouTube · локальный режим Oldi")).setContentText(I18n.t("Видео идёт напрямую на ваше устройство")).setOngoing(true).addAction(new Notification.Action.Builder(null,I18n.t("Отключить"),stop).build()).build();if(Build.VERSION.SDK_INT>=34)startForeground(620,n,ServiceInfo.FOREGROUND_SERVICE_TYPE_SPECIAL_USE);else startForeground(620,n);
  }catch(Exception failure){fail("FOREGROUND_START_DENIED");return START_NOT_STICKY;}
  stopping=false;java.util.concurrent.CountDownLatch previousCleanup=cleanup;TunnelStateRepository.set("STARTING");work.execute(()->{try{if(!previousCleanup.await(3,TimeUnit.SECONDS))throw new IOException();YouTubeDomainRules rules=YouTubeDomainRules.load(this);if(!rules.enabled)throw new IOException();underlying=NetworkDiagnostics.physical(this);if(underlying==null)throw new IOException();dpi=new LocalDpiEngine(this);relay=new LocalSocksRelay(this,new TrafficClassifier(rules),dpi);
   File config=new File(getFilesDir(),"youtube-local.yml");String yaml="tunnel:\n  mtu: 1280\n  ipv4: 198.18.0.2\n  ipv6: 'fd66:6f6c:6479::2'\nsocks5:\n  address: 127.0.0.1\n  port: "+relay.port()+"\n  udp: udp\n  username: oldy\n  password: '"+relay.password+"'\nmisc:\n  max-session-count: 64\n  connect-timeout: 10000\n  tcp-read-write-timeout: 120000\n  udp-read-write-timeout: 30000\n  log-file: '/dev/null'\n  log-level: error\n";try(FileOutputStream out=new FileOutputStream(config)){out.write(yaml.getBytes(java.nio.charset.StandardCharsets.UTF_8));}
   Builder builder=new Builder().setSession("Oldi · YouTube local").setMtu(1280).addAllowedApplication(getPackageName()).addAddress("198.18.0.2",32).addAddress("fd66:6f6c:6479::2",128).addDnsServer(TrafficClassifier.DNS).addRoute("198.18.0.0",16).addRoute("fd66:6f6c:6479::",64).allowFamily(OsConstants.AF_INET).allowFamily(OsConstants.AF_INET6).allowBypass().setBlocking(false);if(!browserPackage.isEmpty())builder.addAllowedApplication(browserPackage);builder.setUnderlyingNetworks(new Network[]{underlying});if(Build.VERSION.SDK_INT>=29){NetworkCapabilities caps=getSystemService(ConnectivityManager.class).getNetworkCapabilities(underlying);builder.setMetered(caps==null||!caps.hasCapability(NetworkCapabilities.NET_CAPABILITY_NOT_METERED));}
   if(stopping)return;tun=builder.establish();if(tun==null||!TProxyService.TProxyStartService(config.getAbsolutePath(),tun.getFd()))throw new IOException();if(Build.VERSION.SDK_INT>=29){webProxy=new LocalWebProxy(this,relay);TunnelStateRepository.webPort=webProxy.port();}ui.post(tick);
  }catch(Throwable failure){ui.post(()->fail("LOCAL_START_FAILED"));}});return START_NOT_STICKY;
 }
 void relayFailed(){ui.post(()->fail("LOCAL_RELAY_FAILED"));}
 void fail(String reason){TunnelStateRepository.fail(this,reason);shutdown();}
 public void onRevoke(){TunnelStateRepository.fail(this,"VPN_PERMISSION_REVOKED");shutdown();}
 synchronized void shutdown(){
  if(stopping)return;stopping=true;ui.removeCallbacksAndMessages(null);TunnelStateRepository.webPort=0;TunnelStateRepository.set("OFF");
  // Android binds an established VpnService. stopSelf/stopService alone cannot
  // destroy that bound service: explicitly release the TUN before waiting for
  // onDestroy, otherwise its network and foreground notification remain alive.
  java.util.concurrent.CountDownLatch pending=new java.util.concurrent.CountDownLatch(1);cleanup=pending;
  work.execute(()->{try{if(webProxy!=null)webProxy.close();if(relay!=null)relay.close();if(dpi!=null)dpi.close();if(tun!=null){try{TProxyService.TProxyStopService();}catch(Throwable ignored){}try{tun.close();}catch(Exception ignored){}}new File(getFilesDir(),"youtube-local.yml").delete();}finally{pending.countDown();ui.post(()->{stopForeground(STOP_FOREGROUND_REMOVE);stopSelf();});}});
  work.shutdown();stopSelf();
 }
 public void onDestroy(){shutdown();stopForeground(STOP_FOREGROUND_REMOVE);super.onDestroy();if(restartRequested)ui.post(()->{try{startBrowser(this,restartBrowser);}catch(RuntimeException denied){TunnelStateRepository.fail(this,"VPN_RESTART_DENIED");}});}
}
