package chat.oldy;
import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.media.*;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
 int BG,CARD,GREEN,TEXT,MUTED,INK=0xff182416;
 final ExecutorService work=Executors.newSingleThreadExecutor();final Handler ui=new Handler(Looper.getMainLooper());
 Vault vault;Api api;LinearLayout root,content;ScrollView messagesScroll;TextView network,typing;EditText compose;String screen="",chat="",search="",avatarRoom="",mediaTarget="";
 VoiceCapture voice;VoicePlayer voicePlayer;LinearLayout emojiPanel;UiIcon sendKey;int selectedMotion=-1;boolean typingExpanded;String focusAccount="";
 boolean registeredReceiver,active,checkedUpdate;String backupText;char[] restorePassword;MediaRecorder recorder;File recording;MediaPlayer player;long lastTyping;int filter;Dialog activeSheet;JSONObject replyTo;LinearLayout pinBar,replyBar;boolean light;final android.util.LruCache<String,Bitmap> mediaCache=new android.util.LruCache<String,Bitmap>(32*1024*1024){protected int sizeOf(String key,Bitmap image){return image.getAllocationByteCount();}};final Set<String> loadingImages=new HashSet<>();
 interface Job{void run()throws Exception;}
 final BroadcastReceiver refresh=new BroadcastReceiver(){public void onReceive(Context c,Intent i){if(network!=null)network.setText(ChatService.state);if(screen.equals("chats"))renderChats();if(screen.equals("chat")){try{if(Conversation.community(chat)&&vault.room(Conversation.room(chat))==null){chats();return;}if(Conversation.thread(chat)&&vault.isDeleted(Conversation.post(chat),Conversation.room(chat),"")){openChat("room:"+Conversation.room(chat));return;}}catch(Exception ignored){}renderMessages();}}};
 public void onCreate(Bundle b){super.onCreate(b);api=new Api(this);File[] stale=getCacheDir().listFiles((dir,name)->name.startsWith("voice-")&&name.endsWith(".m4a"));if(stale!=null)for(File f:stale)f.delete();try{vault=ChatService.vault(this);}catch(Exception e){dialog().setTitle("Не удалось открыть историю").setMessage("Данные сохранены. Попробуйте перезапустить приложение.").setPositiveButton("Закрыть",(d,w)->finish()).show();return;}
  if(!vault.token().isEmpty())startChat();
  if(b!=null){if(vault.token().isEmpty())auth(false);else{chats();String restore=b.getString("chat","");if(!restore.isEmpty())openChat(restore);else openFromIntent(getIntent());}}
  else{splash();ui.postDelayed(()->{if(isFinishing()||isDestroyed()||!screen.equals("splash"))return;root.animate().alpha(0f).setDuration(160).withEndAction(()->{if(isFinishing()||isDestroyed())return;if(vault.token().isEmpty())auth(false);else{chats();openFromIntent(getIntent());}}).start();},2500);}
 }
 protected void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);if(screen.equals("chat"))b.putString("chat",chat);}
 public void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);if(vault!=null&&!vault.token().isEmpty())openFromIntent(i);}
 long shownRevision=-1;final Runnable liveTick=new Runnable(){public void run(){if(!active)return;if(screen.equals("chat")){try{if(Conversation.community(chat)&&vault.room(Conversation.room(chat))==null){chats();return;}if(Conversation.thread(chat)&&vault.isDeleted(Conversation.post(chat),Conversation.room(chat),"")){openChat("room:"+Conversation.room(chat));return;}long revision=vault.messageRevision();if(revision!=shownRevision){shownRevision=revision;renderMessages();}}catch(Exception ignored){}}ui.postDelayed(this,350);}};
 protected void onResume(){super.onResume();if(vault!=null){ChatService.visibleChat=screen.equals("chat")?chat:"";shownRevision=-1;ui.removeCallbacks(liveTick);ui.post(liveTick);}}
 protected void onPause(){ui.removeCallbacks(liveTick);ChatService.visibleChat="";super.onPause();}
 final Runnable updateTick=()->{if(active&&!isFinishing()){if(!vault.token().isEmpty())Updates.check(this,false);updateLoop();}};
 void updateLoop(){ui.removeCallbacks(updateTick);ui.postDelayed(updateTick,60000);}
 void openFromIntent(Intent i){Uri link=i.getData();if(link!=null&&"oldy".equals(link.getScheme())&&"comments".equals(link.getHost())){java.util.List<String> parts=link.getPathSegments();if(parts.size()==2&&parts.get(0).matches("[a-f0-9-]{36}")&&parts.get(1).matches("[a-f0-9-]{36}")){openComments(parts.get(0),parts.get(1));return;}}String target=i.getStringExtra("chat");if(target!=null&&!target.isEmpty())openChat(target);}
 protected void onStart(){super.onStart();active=true;IntentFilter f=new IntentFilter("chat.oldy.CHANGED");if(Build.VERSION.SDK_INT>=33)registerReceiver(refresh,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(refresh,f);registeredReceiver=true;if(screen.equals("chat"))ChatService.visibleChat=chat;updateLoop();}
 protected void onStop(){if(voicePlayer!=null)voicePlayer.release();active=false;ui.removeCallbacks(updateTick);ChatService.visibleChat="";if(registeredReceiver){unregisterReceiver(refresh);registeredReceiver=false;}if(recorder!=null)stopRecording(false);if(voice!=null)voice.end(false);super.onStop();}
 public void onBackPressed(){if(screen.equals("chat")&&Conversation.thread(chat)){String r=Conversation.room(chat),post=Conversation.post(chat);openChat("room:"+r);ui.postDelayed(()->jump(post),100);return;}if(screen.equals("chat")||screen.equals("settings")||screen.equals("search")||screen.equals("verify")){if(vault.token().isEmpty())auth(false);else chats();}else super.onBackPressed();}
 void colors(){String theme=Notices.prefs(this).getString("theme","dark");light=theme.equals("light");BG=light?0xfff7f9fc:0xff111720;CARD=light?0xffffffff:0xff202a37;GREEN=light?0xffb8dbff:0xffa0ceff;TEXT=light?0xff19283d:0xfff0f5ff;MUTED=light?0xff718098:0xff9cacbf;INK=0xff173959;getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);getWindow().getDecorView().setSystemUiVisibility(light?View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR:0);}
 AlertDialog.Builder dialog(){return new AlertDialog.Builder(this,Notices.prefs(this).getString("theme","dark").equals("light")?android.R.style.Theme_Material_Light_Dialog_Alert:android.R.style.Theme_Material_Dialog_Alert);}
 int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
 GradientDrawable shape(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
 LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
 LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 void pad(View v,int p){v.setPadding(dp(p),dp(p),dp(p),dp(p));}
 void space(LinearLayout l,int h){l.addView(new View(this),new LinearLayout.LayoutParams(1,dp(h)));}
 TextView label(String s,int size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);return v;}
 TextView button(String s,boolean primary,Runnable action){TextView v=label(s,15,primary?INK:TEXT);v.setGravity(Gravity.CENTER);v.setTypeface(null,1);v.setIncludeFontPadding(false);v.setPadding(dp(13),dp(8),dp(13),dp(8));v.setMinHeight(dp(40));v.setBackground(shape(primary?GREEN:CARD,18));v.setContentDescription(s);v.setOnClickListener(w->{if(activeSheet!=null){activeSheet.dismiss();activeSheet=null;}action.run();});return v;}
 void base(String s){if(voicePlayer!=null)voicePlayer.release();if(voice!=null&&voice.running)voice.end(false);if(activeSheet!=null){activeSheet.dismiss();activeSheet=null;}emojiPanel=null;sendKey=null;screen=s;ChatService.visibleChat=s.equals("chat")&&active?chat:"";colors();root=col();root.setBackgroundColor(BG);root.setPadding(dp(18),dp(12),dp(18),dp(10));if(Build.VERSION.SDK_INT>=35)root.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets x=insets.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.ime());v.setPadding(dp(18)+x.left,dp(12)+x.top,dp(18)+x.right,dp(10)+x.bottom);return insets;});setContentView(root);network=null;typing=null;}
 View iconButton(String symbol,String description,Runnable action){UiIcon v=new UiIcon(this,symbol,light?0xff1469a1:0xff9ae6ff);v.setContentDescription(description);GradientDrawable bg=shape(light?0xffdef0ff:0xff1d3549,16);bg.setStroke(dp(1),light?0xffbfdcf4:0xff356783);v.setBackground(bg);v.setOnClickListener(x->action.run());return v;}
 void title(String s,Runnable back){LinearLayout r=row();if(back!=null){View b=iconButton("back","Назад",back);r.addView(b,new LinearLayout.LayoutParams(dp(44),dp(46)));}TextView t=label(s,25,TEXT);t.setTypeface(null,1);t.setPadding(dp(12),0,0,0);r.addView(t,new LinearLayout.LayoutParams(0,dp(56),1));t.setGravity(Gravity.CENTER_VERTICAL);root.addView(r);space(root,12);}
 void paragraph(LinearLayout l,String s){TextView t=label(s,13,MUTED);t.setLineSpacing(dp(3),1);l.addView(t);}
 EditText field(LinearLayout l,String hint,boolean password){EditText e=new EditText(this);e.setSingleLine(true);e.setTextSize(16);e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setHint(hint);pad(e,15);e.setBackground(shape(CARD,17));e.setInputType(password?129:1);l.addView(e,new LinearLayout.LayoutParams(-1,dp(56)));space(l,10);return e;}
 void task(Job job){work.execute(()->{try{job.run();}catch(Exception e){runOnUiThread(()->error(Api.message(e)));}});}
 void error(String s){if(!isFinishing())dialog().setTitle("OldЫ Chat").setMessage(s).setPositiveButton("Понятно",null).show();}
 Art art(String key,int size,LinearLayout l){Art a=new Art(this,key);l.addView(a,new LinearLayout.LayoutParams(dp(size),dp(size)));return a;}
 void splash(){base("splash");root.setGravity(Gravity.CENTER);root.setBackground(new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{0xff0d1228,0xff172851,0xff123443}));getWindow().getDecorView().setSystemUiVisibility(0);getWindow().setStatusBarColor(0xff142337);getWindow().setNavigationBarColor(0xff103b4d);WelcomeArt art=new WelcomeArt(this);int size=Math.min(dp(300),getResources().getDisplayMetrics().widthPixels-dp(48));root.addView(art,new LinearLayout.LayoutParams(size,size));space(root,22);TextView h=label("Добро пожаловать\nв OldЫ Chat",30,0xfff0f8ff);h.setGravity(Gravity.CENTER);h.setTypeface(Typeface.create("sans-serif-condensed",Typeface.BOLD));h.setLineSpacing(dp(3),1);root.addView(h);space(root,15);TextView sub=label("Общайтесь без цензуры.\nГоворите о том, что вам интересно.",15,0xffb8d5e8);sub.setGravity(Gravity.CENTER);sub.setLineSpacing(dp(5),1);root.addView(sub);if(android.animation.ValueAnimator.areAnimatorsEnabled()){h.setAlpha(0);h.setTranslationY(dp(10));h.animate().alpha(1).translationY(0).setStartDelay(140).setDuration(450).start();sub.setAlpha(0);sub.animate().alpha(1).setStartDelay(400).setDuration(400).start();}}
 void auth(boolean signup){base("auth");ScrollView s=new ScrollView(this);LinearLayout b=col();s.addView(b);root.addView(s);
  LinearLayout top=row();TextView brand=label("OldЫ Chat",23,TEXT);brand.setTypeface(null,1);top.addView(brand,new LinearLayout.LayoutParams(0,dp(48),1));top.addView(button("⚙",false,()->settings()));b.addView(top);space(b,14);
  Art a=new Art(this,"mascot");LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(dp(180),dp(180));ap.gravity=Gravity.CENTER_HORIZONTAL;b.addView(a,ap);space(b,18);
  TextView hello=label(signup?"Создать аккаунт":"Вход в OldЫ Chat",27,TEXT);hello.setTypeface(null,1);b.addView(hello);space(b,7);paragraph(b,"Сообщения, каналы и звонки.");space(b,20);
  LinearLayout tabs=row();tabs.addView(button("Войти",!signup,()->auth(false)),new LinearLayout.LayoutParams(0,dp(48),1));tabs.addView(button("Регистрация",signup,()->auth(true)),new LinearLayout.LayoutParams(0,dp(48),1));b.addView(tabs);space(b,18);
  EditText name=signup?field(b,"Как тебя зовут?",false):null;EditText nick=field(b,signup?"@ник · латиница, цифры, _":"E-mail или @ник",false);nick.setInputType(signup?145:33);TextView availability=signup?label("",12,MUTED):null;if(availability!=null){b.addView(availability,new LinearLayout.LayoutParams(-1,-2));space(b,12);}EditText email=signup?field(b,"E-mail",false):null;if(email!=null)email.setInputType(33);if(!vault.nick().isEmpty())nick.setText(vault.nick());EditText pass=field(b,"Пароль · минимум 8 символов",true);
  TextView submit=button(signup?"Получить код на почту →":"Войти в чат →",true,()->{});
  if(signup)SignupHandle.bind(this,nick,availability,submit);
  submit.setOnClickListener(v->{String n=nick.getText().toString().trim().replaceFirst("^@","").toLowerCase(Locale.ROOT),p=pass.getText().toString(),display=name==null?"":name.getText().toString().trim(),mail=email==null?"":email.getText().toString().trim();
   if(!(n.matches("[a-z0-9_]{3,24}")||!signup&&android.util.Patterns.EMAIL_ADDRESS.matcher(n).matches())||p.length()<8||p.length()>128||signup&&!android.util.Patterns.EMAIL_ADDRESS.matcher(mail).matches()){error("Проверь ник, e-mail и пароль: минимум 8 символов.");return;}
   submit.setEnabled(false);task(()->{try{api.check();if(signup){if(!api.call("/handles?handle="+n,null,"").optBoolean("available"))throw new Exception("Этот ник уже занят. Выбери другой.");JSONObject code=api.call("/signup/request",new JSONObject().put("email",mail).put("nick",n),"");runOnUiThread(()->verifySignup(n,p,display,mail,code.optString("ticket")));}else loginAccount(n,p,null);}finally{runOnUiThread(()->submit.setEnabled(true));}});
  });b.addView(submit);space(b,14);paragraph(b,"Вход по e-mail или нику. Регистрация — с подтверждением почты.");space(b,10);
 }
 void verifySignup(String nick,String password,String name,String email,String ticket){base("verify");title("Подтверди почту",()->auth(true));paragraph(root,"Мы отправили шестизначный код на "+email+". До подтверждения аккаунт не создаётся.");space(root,18);EditText code=field(root,"Код из письма",false);code.setInputType(2);root.addView(button("Подтвердить и создать аккаунт",true,()->{String value=code.getText().toString().trim();if(!value.matches("[0-9]{6}")){error("Введи шесть цифр из письма");return;}task(()->{JSONObject id=Crypto.identity();JSONObject body=new JSONObject().put("nick",nick).put("password",password).put("name",name).put("email",email).put("ticket",ticket).put("code",value).put("enc",id.getString("enc")).put("sig",id.getString("sig"));loginAccount(nick,password,new JSONObject().put("reply",api.call("/register",body,"")).put("identity",id));});}));space(root,12);root.addView(button("Прислать новый код",false,()->task(()->{JSONObject next=api.call("/signup/request",new JSONObject().put("email",email).put("nick",nick),"");runOnUiThread(()->verifySignup(nick,password,name,email,next.optString("ticket")));})));}
 void loginAccount(String login,String password,JSONObject signup)throws Exception{
  JSONObject reply=signup==null?api.call("/login",new JSONObject().put("nick",login).put("password",password),""):signup.getJSONObject("reply"),user=reply.getJSONObject("user");
  Vault next=new Vault(this,user.getString("nick"),signup!=null);if(signup!=null)next.data.put("identity",signup.getJSONObject("identity"));
  if(!Crypto.fingerprint(user).equals(Crypto.fingerprint(next.identity()))){String blob=api.call("/key-backup",null,reply.getString("token")).getString("backup");next.restoreKeys(Crypto.importBackup(blob,password.toCharArray()),user);}
  next.account(reply);next.rooms(api.call("/rooms",null,next.token()).getJSONArray("rooms"));
  try{api.call("/key-backup",new JSONObject().put("backup",Crypto.exportBackup(next.keyBackup(),password.toCharArray())),next.token());}catch(Exception ignored){}
  runOnUiThread(()->{if(ChatService.instance!=null)ChatService.instance.running=false;stopService(new Intent(this,ChatService.class));ChatService.shared=next;vault=next;mediaCache.evictAll();search="";filter=0;chat="";chats();startChat();});
 }
 void logoutAccount(){if(LiveCall.current!=null)LiveCall.current.end("Звонок завершён",true);CreatorVideo.cancel=true;task(()->{Vault old=vault;try{api.call("/logout",new JSONObject(),old.token());}finally{if(ChatService.instance!=null)ChatService.instance.running=false;stopService(new Intent(this,ChatService.class));synchronized(old){old.data.remove("token");old.save();}Vault empty=Vault.guest(this);ChatService.shared=empty;runOnUiThread(()->{getSystemService(NotificationManager.class).cancelAll();vault=empty;chat="";search="";filter=0;mediaCache.evictAll();auth(false);});}});}
 void startChat(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},10);startForegroundService(new Intent(this,ChatService.class));}
 void chats(){base("chats");LinearLayout header=row();header.addView(button("☰",false,()->menu()),new LinearLayout.LayoutParams(dp(46),dp(46)));BrandMark brand=new BrandMark(this,light);header.addView(brand,new LinearLayout.LayoutParams(0,dp(54),1));header.addView(button("＋",true,()->findPeer()));root.addView(header);network=label(ChatService.state,11,MUTED);network.setPadding(dp(60),0,0,0);root.addView(network);TextView quietStatus=label("",11,light?0xff286ca6:0xff8adaff);quietStatus.setVisibility(View.GONE);quietStatus.setPadding(dp(60),dp(6),0,0);quietStatus.setOnClickListener(v->focusMode());root.addView(quietStatus);quietStatus.post(()->NotificationSheet.bindQuiet(this,quietStatus));space(root,18);
  EditText query=field(root,"Поиск чатов",false);query.setText(search);query.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){search=s.toString();renderChats();}public void afterTextChanged(Editable e){}});
  LinearLayout tabs=row();String[] names={"Все","Личные","Группы","Каналы"};for(int i=0;i<names.length;i++){final int at=i;TextView t=button(names[i],filter==i,()->{filter=at;chats();});t.setTextSize(12);tabs.addView(t,new LinearLayout.LayoutParams(0,dp(42),1));}root.addView(tabs);space(root,14);
  ScrollView scroll=new ScrollView(this);content=col();scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));renderChats();space(root,10);
  LinearLayout nav=row();nav.setBackground(shape(CARD,24));TextView left=label("●  Чаты",14,Notices.prefs(this).getString("theme","dark").equals("light")?INK:GREEN);left.setGravity(Gravity.CENTER);nav.addView(left,new LinearLayout.LayoutParams(0,dp(53),1));TextView own=label("☰  Меню",14,MUTED);own.setGravity(Gravity.CENTER);own.setOnClickListener(v->profileMenu());nav.addView(own,new LinearLayout.LayoutParams(0,dp(53),1));root.addView(nav);campaign();if(!checkedUpdate){checkedUpdate=true;ui.postDelayed(()->Updates.check(this,false),2200);}
 }
 JSONObject last(JSONArray a,String n){for(int i=a.length()-1;i>=0;i--){JSONObject m=a.optJSONObject(i);if(m!=null&&!m.optString("kind").equals("control")&&m.optString("peer").equals(n))return m;}return null;}
 String clock(long t){return new java.text.SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date(t));}
 void renderChats(){if(!screen.equals("chats")||content==null)return;content.removeAllViews();try{
  JSONObject d=vault.copy(),contacts=d.getJSONObject("contacts"),rooms=d.getJSONObject("rooms");JSONArray messages=d.getJSONArray("messages");List<String> items=new ArrayList<>();contacts.keys().forEachRemaining(items::add);rooms.keys().forEachRemaining(k->items.add("room:"+k));
  items.sort((a,b)->{JSONObject aa=last(messages,a),bb=last(messages,b);return Long.compare(bb==null?0:bb.optLong("time"),aa==null?0:aa.optLong("time"));});int total=0;
  for(String id:items){boolean group=id.startsWith("room:");JSONObject u=group?rooms.getJSONObject(id.substring(5)):contacts.getJSONObject(id);String name=u.optString(group?"title":"name",id),kind=group?u.optString("kind"):"personal";
   if(filter==1&&group||filter==2&&!kind.equals("group")||filter==3&&!kind.equals("channel"))continue;
   if(!(name+" "+id+" "+u.optString("handle")).toLowerCase(Locale.ROOT).contains(search.toLowerCase(Locale.ROOT)))continue;total++;
   LinearLayout item=row();pad(item,12);item.setBackground(shape(CARD,23));art(u.optString("avatar","preset:0"),53,item);LinearLayout detail=col();detail.setPadding(dp(12),0,dp(6),0);TextView title=label((kind.equals("channel")?"◈ ":kind.equals("group")?"♧ ":"")+name,16,TEXT);title.setTypeface(null,1);title.setSingleLine(true);title.setEllipsize(TextUtils.TruncateAt.END);detail.addView(title);space(detail,5);JSONObject last=last(messages,id);TextView preview=label(last==null?(group?"@"+u.optString("handle")+" · "+(kind.equals("channel")?"канал":"группа"):"@"+id):Payload.preview(last),13,MUTED);preview.setSingleLine(true);preview.setEllipsize(TextUtils.TruncateAt.END);detail.addView(preview);item.addView(detail,new LinearLayout.LayoutParams(0,-2,1));item.addView(label(last==null?"":clock(last.optLong("time")),10,MUTED));item.setOnClickListener(v->openChat(id));content.addView(item,new LinearLayout.LayoutParams(-1,dp(85)));space(content,9);
  }
  if(total==0){space(content,32);Art a=new Art(this,"mascot");LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(175),dp(175));p.gravity=Gravity.CENTER_HORIZONTAL;content.addView(a,p);space(content,18);TextView empty=label("Скажи своим «привет»",21,TEXT);empty.setGravity(Gravity.CENTER);content.addView(empty);space(content,10);paragraph(content,"Нажми ＋ и найди друга по нику.\nВ меню слева можно создать группу или канал.");}
 }catch(Exception e){error(Api.message(e));}}
 void menu(){profileMenu();}
 void findPeer(){
  base("search");root.setBackground(new SearchBackdrop(this));title("Поиск людей",()->chats());
  EditText query=field(root,"Имя, @ник или название",false);query.setContentDescription("Поиск людей, групп и каналов");
  TextView state=label("Люди, группы и каналы",12,MUTED);root.addView(state);space(root,16);
  ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);LinearLayout results=col();scroll.addView(results);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));searchEmpty(results,false);
  final Vault account=vault;final View searchRoot=root;final int[] generation={0};
  query.addTextChangedListener(new TextWatcher(){Runnable pending;public void beforeTextChanged(CharSequence t,int a,int c,int f){}public void afterTextChanged(Editable e){}
   public void onTextChanged(CharSequence text,int a,int before,int count){int sequence=++generation[0];if(pending!=null)ui.removeCallbacks(pending);String q=text.toString().trim();results.removeAllViews();
    if(q.length()<2){state.setText(q.isEmpty()?"Люди, группы и каналы":"Введите минимум 2 символа");searchEmpty(results,false);return;}
    state.setText("Поиск…");ProgressBar progress=new ProgressBar(MainActivity.this);results.addView(progress,new LinearLayout.LayoutParams(dp(32),dp(32)));
    pending=()->work.execute(()->{try{if(vault!=account||root!=searchRoot)return;JSONObject found=api.call("/search?q="+java.net.URLEncoder.encode(q,"UTF-8"),null,account.token());
     runOnUiThread(()->{if(sequence!=generation[0]||root!=searchRoot||vault!=account)return;results.removeAllViews();JSONArray people=found.optJSONArray("users"),rooms=found.optJSONArray("rooms");int total=people.length()+rooms.length();state.setText(total==0?"Ничего не найдено":"Результаты · "+total);if(total==0)searchEmpty(results,true);
      for(int i=0;i<people.length();i++){JSONObject user=people.optJSONObject(i);View card=searchCard(user.optString("avatar"),user.optString("name"),"@"+user.optString("nick"),"ЧЕЛОВЕК",()->task(()->{if(vault!=account)return;account.pin(user);runOnUiThread(()->{if(vault==account)openChat(user.optString("nick"));});}));results.addView(card);space(results,10);animateEnter(card,i);}
      for(int i=0;i<rooms.length();i++){JSONObject r=rooms.optJSONObject(i);String type=r.optString("kind").equals("channel")?"КАНАЛ":"ГРУППА";View card=searchCard(r.optString("avatar"),r.optString("title"),"@"+r.optString("handle"),type,()->{
       Runnable open=()->task(()->{if(vault!=account)return;JSONObject room=api.call(r.optBoolean("joined")?"/room/"+r.optString("id"):"/room/join",r.optBoolean("joined")?null:new JSONObject().put("id",r.optString("id")),account.token());account.putRoom(room);runOnUiThread(()->{if(vault==account)openChat("room:"+r.optString("id"));});});
       if(r.optBoolean("joined"))open.run();else{LinearLayout box=col();paragraph(box,"Присоединиться к @"+r.optString("handle")+"?");space(box,14);box.addView(button("Присоединиться",true,open));sheet(r.optString("title"),box);}
      });results.addView(card);space(results,10);animateEnter(card,i);}
     });
    }catch(Exception ex){runOnUiThread(()->{if(sequence==generation[0]&&root==searchRoot){results.removeAllViews();state.setText("Не удалось выполнить поиск");paragraph(results,Api.message(ex));}});}});ui.postDelayed(pending,420);
   }
  });
 }
 void searchEmpty(LinearLayout results,boolean missing){LinearLayout empty=col();empty.setGravity(Gravity.CENTER);empty.setPadding(dp(22),dp(36),dp(22),dp(30));
  LinearLayout faces=row();faces.setGravity(Gravity.CENTER);art("preset:3",52,faces);Art middle=art("preset:0",76,faces);art("preset:7",52,faces);empty.addView(faces);space(empty,22);
  TextView title=label(missing?"Проверьте имя или @ник":"Введите имя или @ник",18,TEXT);title.setTypeface(null,1);title.setGravity(Gravity.CENTER);empty.addView(title);space(empty,8);TextView hint=label(missing?"Можно искать и по части названия":"Здесь появятся результаты поиска",13,MUTED);hint.setGravity(Gravity.CENTER);empty.addView(hint);results.addView(empty,new LinearLayout.LayoutParams(-1,-2));animateEnter(empty,0);
 }
 View searchCard(String avatar,String title,String subtitle,String badge,Runnable action){LinearLayout card=row();pad(card,14);GradientDrawable bg=shape(CARD,22);bg.setStroke(dp(1),light?0xffd9e5f3:0xff35475f);card.setBackground(bg);art(avatar,56,card);LinearLayout words=col();words.setPadding(dp(12),0,dp(8),0);TextView name=label(title,17,TEXT);name.setTypeface(null,1);words.addView(name);space(words,5);words.addView(label(subtitle,13,MUTED));space(words,5);words.addView(label(badge,9,light?0xff4d74a3:0xffb0b4fd));card.addView(words,new LinearLayout.LayoutParams(0,-2,1));card.addView(label("›",27,MUTED));card.setOnClickListener(v->action.run());return card;}
 void createRoom(String kind){LinearLayout box=col();pad(box,18);EditText title=field(box,kind.equals("group")?"Название группы":"Название канала",false),handle=field(box,"@адрес · например oldy_news",false);TextView status=label("Проверим, свободен ли адрес",12,MUTED);box.addView(status);space(box,12);watchHandle(handle,status,"");EditText members=field(box,"Ники участников через запятую · необязательно",false);Switch pub=new Switch(this);pub.setText("Публичный · виден в поиске");pub.setTextColor(TEXT);pub.setChecked(true);box.addView(pub);space(box,12);paragraph(box,kind.equals("channel")?"Публикует владелец. Подписчики читают, ставят реакции и обсуждают каждый пост в комментариях.":"Участники публикуют, отвечают и ставят реакции. Управляет владелец.");AlertDialog d=dialog().setTitle(kind.equals("group")?"Новая группа":"Новый канал").setView(box).setNegativeButton("Отмена",null).setPositiveButton("Создать",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String t=title.getText().toString(),h=handle.getText().toString().trim().replace("@","").toLowerCase(Locale.ROOT),n=members.getText().toString();boolean isPublic=pub.isChecked();if(t.trim().isEmpty()||!h.matches("[a-z0-9_]{3,24}")){error("Укажи название и @адрес: 3–24 латинских символа, цифры или _");return;}d.getButton(-1).setEnabled(false);task(()->{try{JSONObject room=api.call("/room/create",new JSONObject().put("title",t).put("kind",kind).put("handle",h).put("public",isPublic).put("members",nickList(n)),vault.token());vault.putRoom(room);runOnUiThread(()->{d.dismiss();openChat("room:"+room.optString("id"));});}finally{runOnUiThread(()->d.getButton(-1).setEnabled(true));}});}));d.show();}
 void watchHandle(EditText input,TextView status,String original){input.setInputType(145);input.addTextChangedListener(new TextWatcher(){Runnable pending;public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void afterTextChanged(Editable e){}public void onTextChanged(CharSequence text,int a,int b,int c){if(pending!=null)ui.removeCallbacks(pending);String h=text.toString().trim().replace("@","").toLowerCase(Locale.ROOT);if(h.equals(original)){status.setText("Текущий адрес");return;}if(!h.matches("[a-z0-9_]{3,24}")){status.setText("3–24 латинских символа, цифры или _");return;}status.setText("Проверяем @"+h+"…");pending=()->work.execute(()->{try{JSONObject r=api.call("/handles?handle="+h,null,"");runOnUiThread(()->{if(input.getText().toString().trim().replace("@","").equalsIgnoreCase(h)){status.setText(r.optBoolean("available")?"✓ @"+h+" свободен":"Этот адрес уже занят");status.setTextColor(r.optBoolean("available")?(light?0xff24765e:0xff8cddc0):0xffe57e8c);}});}catch(Exception ex){runOnUiThread(()->status.setText("Не удалось проверить. Проверь подключение."));}});ui.postDelayed(pending,450);}});}
 JSONArray nickList(String s)throws Exception{JSONArray a=new JSONArray();for(String n:s.toLowerCase(Locale.ROOT).split("[,\\s]+")){n=n.replace("@","").trim();if(n.isEmpty())continue;if(!n.matches("[a-z0-9_]{3,24}"))throw new Exception("Проверь ники участников");a.put(n);}return a;}
 void openChat(String target){final Vault account=vault;selectedMotion=-1;typingExpanded=false;chat=target;replyTo=null;compose=null;base("chat");try{
  boolean group=Conversation.community(target);JSONObject u=group?vault.room(Conversation.room(target)):vault.peer(target);if(u==null){chats();return;}
  LinearLayout head=row();head.addView(iconButton("back","Назад",()->onBackPressed()),new LinearLayout.LayoutParams(dp(44),dp(48)));Art avatar=art(u.optString("avatar","preset:0"),42,head);avatar.setOnClickListener(v->chatInfo());LinearLayout info=col();info.setPadding(dp(9),0,dp(4),0);TextView title=label(Conversation.thread(target)?"Комментарии":u.optString(group?"title":"name",target),20,TEXT);title.setTypeface(null,1);title.setSingleLine(true);title.setEllipsize(TextUtils.TruncateAt.END);title.setOnClickListener(v->chatInfo());info.addView(title);typing=label(group?"@"+u.optString("handle")+" · "+audience(u):"@"+target,10,MUTED);info.addView(typing);head.addView(info,new LinearLayout.LayoutParams(0,dp(52),1));if(!group){View callKey=iconButton("call","Позвонить через интернет",()->LiveCall.dial(this,target));callKey.setContentDescription("Позвонить через интернет");head.addView(callKey,new LinearLayout.LayoutParams(dp(40),dp(44)));}Art companion=art("mascot",62,head);companion.setLayoutParams(new LinearLayout.LayoutParams(dp(66),dp(56)));companion.setOnClickListener(v->Toast.makeText(this,"Старый геймер на связи 🎮",Toast.LENGTH_SHORT).show());root.addView(head);space(root,8);if(Conversation.thread(target)){JSONObject post=vault.message(Conversation.post(target));String preview=post==null?"Вернуться к публикации":post.optString("text",Payload.preview(post));TextView context=label("↳ К публикации · "+preview,12,MUTED);context.setMaxLines(2);context.setEllipsize(TextUtils.TruncateAt.END);pad(context,10);context.setBackground(shape(CARD,12));context.setOnClickListener(v->onBackPressed());root.addView(context,new LinearLayout.LayoutParams(-1,-2));space(root,8);}pinBar=col();root.addView(pinBar);
  messagesScroll=new ScrollView(this);messagesScroll.setFillViewport(true);messagesScroll.setBackground(new Wallpaper(light,Notices.prefs(this).getInt("wallpaper",0)));messagesScroll.setClipToOutline(true);content=col();content.setPadding(dp(8),dp(4),dp(8),dp(12));messagesScroll.addView(content);root.addView(messagesScroll,new LinearLayout.LayoutParams(-1,0,1));space(root,8);
  boolean canWrite=Conversation.thread(target)||(!group&&!vault.isBlocked(target))||group&&!u.optString("kind").equals("channel")||u.optString("owner").equals(vault.nick());
  replyBar=col();root.addView(replyBar);emojiPanel=col();emojiPanel.setVisibility(View.GONE);root.addView(emojiPanel);if(canWrite){LinearLayout input=row();input.setGravity(Gravity.BOTTOM);input.setBackground(shape(CARD,24));TextView plus=button("＋",false,()->attachments());input.addView(plus,new LinearLayout.LayoutParams(dp(40),dp(46)));input.addView(button("☺",false,()->emojis()),new LinearLayout.LayoutParams(dp(41),dp(46)));compose=new EditText(this);compose.setHint(Conversation.thread(target)?"Комментарий…":group?"Публикация…":"Сообщение…");compose.setTextColor(TEXT);compose.setHintTextColor(MUTED);compose.setTextSize(15);compose.setMinLines(1);compose.setMaxLines(6);compose.setMinHeight(dp(46));compose.setInputType(1|131072|16384);pad(compose,10);compose.setBackground(shape(CARD,20));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,-2,1);cp.setMargins(dp(4),0,dp(4),0);input.addView(compose,cp);sendKey=new UiIcon(this,"mic",INK);sendKey.setBackground(shape(GREEN,18));sendKey.setContentDescription("Удерживай для записи голосового");sendKey.setOnTouchListener(new View.OnTouchListener(){float startX;boolean holding;public boolean onTouch(View v,android.view.MotionEvent e){if(compose!=null&&!compose.getText().toString().trim().isEmpty())return false;if(e.getAction()==android.view.MotionEvent.ACTION_DOWN){startX=e.getX();mediaTarget=chat;if(voice==null)voice=new VoiceCapture(MainActivity.this);holding=voice.begin();v.getParent().requestDisallowInterceptTouchEvent(true);return true;}if(e.getAction()==android.view.MotionEvent.ACTION_UP){if(holding)voice.end(e.getX()>startX-dp(70));holding=false;return true;}if(e.getAction()==android.view.MotionEvent.ACTION_CANCEL){if(holding)voice.end(false);holding=false;return true;}return holding;}});sendKey.setOnClickListener(v->{if(compose!=null&&!compose.getText().toString().trim().isEmpty()){sendKey.animate().rotationBy(35).scaleX(.72f).scaleY(.72f).setDuration(100).withEndAction(()->{sendText();if(sendKey!=null)sendKey.animate().rotation(0).scaleX(1).scaleY(1).setDuration(170);});}});input.addView(sendKey,new LinearLayout.LayoutParams(dp(48),dp(48)));root.addView(input);compose.setText(vault.draft(target));sendKey.symbol(compose.getText().toString().trim().isEmpty()?"mic":"send");
   compose.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void afterTextChanged(Editable e){String value=e.toString();if(sendKey!=null){sendKey.symbol(value.trim().isEmpty()?"mic":"send");sendKey.setContentDescription(value.trim().isEmpty()?"Удерживай для записи голосового":"Отправить сообщение");}boolean expanded=value.length()>70||value.contains("\n");if(expanded!=typingExpanded){typingExpanded=expanded;compose.setMinimumHeight(dp(expanded?94:46));}work.execute(()->{try{account.draft(target,value);}catch(Exception ignored){}});}public void onTextChanged(CharSequence s,int a,int before,int count){if(!group&&System.currentTimeMillis()-lastTyping>4000){lastTyping=System.currentTimeMillis();work.execute(()->{try{api.call("/typing",new JSONObject().put("to",target),vault.token());}catch(Exception ignored){}});}}});
  }else if(!group)root.addView(button("Разблокировать собеседника",false,()->setBlock(target,false)));else paragraph(root,"◈ Публикации владельца · нажми на пост, чтобы поставить реакцию");
  renderMessages();if(voice!=null)voice.showPending();animateEnter(messagesScroll,0);if(!group)pollTyping(target);else work.execute(()->{try{ChannelHistory.syncRoom(api,account,Conversation.room(target),8);runOnUiThread(()->{if(vault==account&&chat.equals(target))renderMessages();});}catch(Exception pending){}});
 }catch(Exception e){error(Api.message(e));}}
 void pollTyping(String target){ui.postDelayed(()->{if(!active||!screen.equals("chat")||!chat.equals(target))return;work.execute(()->{try{JSONObject p=api.call("/typing/"+target,null,vault.token());runOnUiThread(()->{if(screen.equals("chat")&&chat.equals(target)&&typing!=null)typing.setText(p.optBoolean("typing")?"печатает…":"@"+target);});}catch(Exception ignored){}});pollTyping(target);},4500);}
 void sendText(){if(compose==null)return;String text=compose.getText().toString().trim();if(text.isEmpty())return;if(Crypto.bytes(text).length>10000){error("Сообщение слишком длинное");return;}try{JSONObject p=new JSONObject().put("kind","text").put("text",text);if(selectedMotion>=0){p.put("animated",selectedMotion);if(text.equals(MotionEmoji.GLYPHS[selectedMotion]))p.put("kind","sticker").put("sticker",selectedMotion);selectedMotion=-1;}if(replyTo!=null)p.put("reply",new JSONObject().put("id",replyTo.optString("id")).put("author",replyTo.optBoolean("out")?vault.nick():replyTo.optString("from")).put("text",Payload.preview(replyTo).substring(0,Math.min(140,Payload.preview(replyTo).length()))));send(p,null);}catch(Exception e){error(Api.message(e));}}
 void prepareRoom(String target)throws Exception{if(!Conversation.community(target))return;JSONObject r=api.call("/room/"+Conversation.room(target),null,vault.token());vault.putRoom(r);JSONArray a=r.getJSONArray("members");for(int i=0;i<a.length();i++){String n=a.getString(i);if(!n.equals(vault.nick()))vault.pin(api.call("/user/"+n,null,vault.token()));}}
 void send(JSONObject p,String local){String target=chat;boolean control=p.optString("kind").equals("control");String draft=compose==null?"":compose.getText().toString();if(!control&&compose!=null){compose.setText("");replyTo=null;replyBar.removeAllViews();}task(()->{try{prepareRoom(target);if(!Conversation.community(target))vault.pin(api.call("/user/"+target,null,vault.token()));if(!control&&!p.optString("text").isEmpty()){JSONObject link=LinkCards.describe(p.optString("text"));if(link!=null)p.put("link",link);}String mid=vault.queuePayload(target,p,local);if(target.startsWith("room:")&&!control){JSONObject r=vault.room(Conversation.room(target));if(r!=null&&r.optString("kind").equals("channel"))try{api.call("/threads",new JSONObject().put("room",r.optString("id")).put("post",mid),vault.token());}catch(Exception deferred){}}runOnUiThread(()->{if(chat.equals(target))renderMessages();});}catch(Exception e){if(!control)runOnUiThread(()->{if(compose!=null&&chat.equals(target))compose.setText(draft);});throw e;}});}

 void renderMessages(){if(!screen.equals("chat"))return;boolean bottom=messagesScroll.getChildCount()==0||messagesScroll.getScrollY()+messagesScroll.getHeight()+dp(100)>=content.getHeight();int scrollY=messagesScroll.getScrollY();content.removeAllViews();try{if(voicePlayer!=null&&!voicePlayer.id.isEmpty()&&vault.message(voicePlayer.id)==null)voicePlayer.release();boolean group=chat.startsWith("room:");JSONObject room=group?vault.room(Conversation.room(chat)):null;renderPin();JSONArray a=vault.copy().getJSONArray("messages");java.util.List<JSONObject> ordered=new java.util.ArrayList<>();for(int i=0;i<a.length();i++)ordered.add(a.getJSONObject(i));ordered.sort(java.util.Comparator.comparingLong(m->m.optLong("time")));String date="";for(JSONObject m:ordered){if(!m.optString("peer").equals(chat)||m.optString("kind").equals("control"))continue;String day=new java.text.SimpleDateFormat("d MMMM",new Locale("ru")).format(new Date(m.optLong("time")));if(!day.equals(date)){date=day;LinearLayout dayRow=row();dayRow.setGravity(Gravity.CENTER);TextView d=label(day,11,MUTED);d.setGravity(Gravity.CENTER);d.setPadding(dp(12),dp(5),dp(12),dp(5));d.setBackground(shape(light?0xdfffffff:0xd0253446,20));dayRow.addView(d);space(content,8);content.addView(dayRow);space(content,12);}boolean out=m.optBoolean("out");LinearLayout line=row();line.setGravity(out&&!group?Gravity.RIGHT:Gravity.LEFT);LinearLayout bubble=col();bubble.setMinimumWidth(dp(76));pad(bubble,12);int fill=group?CARD:out?(light?0xffe0eeff:0xff294461):CARD;GradientDrawable border=shape(fill,group?18:20);if(group)border.setStroke(dp(1),light?0xffccd9e9:0xff42556b);bubble.setBackground(border);bubble.setElevation(dp(group?2:0));bubble.setTag(m.optString("id"));int color=TEXT;
   if(group||Conversation.thread(chat)){LinearLayout authorRow=row();String author=room!=null&&room.optString("kind").equals("channel")?room.optString("title"):"@"+(out?vault.nick():m.optString("from"));TextView authorView=label(author,13,light?0xff376daf:0xffa0ceff);authorView.setTypeface(null,1);authorView.setSingleLine(true);authorView.setEllipsize(TextUtils.TruncateAt.END);authorRow.addView(authorView,new LinearLayout.LayoutParams(0,-2,1));TextView more=label("⋯",21,MUTED);more.setPadding(dp(8),0,0,0);more.setOnClickListener(v->messageMenu(m));authorRow.addView(more);bubble.addView(authorRow);space(bubble,8);}
   JSONObject reply=m.optJSONObject("reply");if(reply!=null){TextView quote=label("↳ @"+reply.optString("author")+"\n"+reply.optString("text"),12,MUTED);quote.setMaxLines(3);pad(quote,9);quote.setBackground(shape(light?0xffeff4fa:0xff172330,9));quote.setOnClickListener(v->jump(reply.optString("id")));bubble.addView(quote,new LinearLayout.LayoutParams(-1,-2));space(bubble,8);}
   String kind=m.optString("kind","text");if(kind.equals("sticker")){if(m.has("animated")){MotionEmoji animated=new MotionEmoji(this,m.optInt("animated"));bubble.addView(animated,new LinearLayout.LayoutParams(dp(110),dp(110)));}else art("sticker:"+m.optInt("sticker"),106,bubble);}else if(kind.equals("file")){if(!m.optString("cloud_video").isEmpty()){addVideo(bubble,m,group);}else if(m.optString("mime").startsWith("image/")){ImageView picture=new ImageView(this);picture.setScaleType(ImageView.ScaleType.CENTER_CROP);picture.setBackground(shape(light?0xffe7edf5:0xff16212e,12));picture.setClipToOutline(true);bubble.addView(picture,new LinearLayout.LayoutParams(group?-1:dp(218),dp(190)));photoPreview(m,picture);picture.setOnClickListener(v->openMedia(m));}else if(m.optString("mime").startsWith("audio/")){bubble.addView(new VoiceNoteView(this,m),new LinearLayout.LayoutParams(group?-1:Math.min(dp(250),getResources().getDisplayMetrics().widthPixels-dp(100)),-2));}else bubble.addView(label(Payload.preview(m),16,color),new LinearLayout.LayoutParams(-2,-2));space(bubble,6);TextView action=label(m.has("local")?"↗ Открыть · "+size(m.optLong("size")):!m.optString("cloud_video").isEmpty()?"▶ Смотреть · "+size(m.optLong("size")):!m.optString("cloud_blob").isEmpty()?"↗ Открыть · "+size(m.optLong("size")):Rtc.status.getOrDefault(m.optString("id"),"↓ Загрузить · "+size(m.optLong("size"))),12,MUTED);action.setOnClickListener(v->openMedia(m));if(!m.optString("mime").startsWith("audio/"))bubble.addView(action,new LinearLayout.LayoutParams(-2,-2));}
   if(!m.optString("text").isEmpty()&&!kind.equals("sticker")){TextView text=label(m.optString("text"),16,color);if(m.has("animated"))MotionText.apply(text,m.optInt("animated"));text.setLineSpacing(dp(2),1);if(!group)text.setMaxWidth(dp(247));text.setOnClickListener(v->messageMenu(m));bubble.addView(text,new LinearLayout.LayoutParams(group?-1:-2,-2));}
   JSONObject link=m.optJSONObject("link");if(link==null&&!LinkCards.first(m.optString("text")).isEmpty()){link=new JSONObject().put("url",LinkCards.first(m.optString("text"))).put("title","Открыть ссылку").put("site","Ссылка");String video=LinkCards.youtube(link.optString("url"));if(!video.isEmpty())link.put("video",video).put("site","YouTube").put("title","Видео на YouTube");}if(link!=null)addLink(bubble,link,group);
   space(bubble,8);LinearLayout foot=row();TextView time=label((vault.saved(m.optString("id"))?"★  ":"")+clock(m.optLong("time"))+(out?(m.optString("status").equals("delivered")?"  ✓✓":m.optString("status").equals("stored")?"  ☁":"  ◷"):""),10,MUTED);time.setGravity(Gravity.RIGHT);foot.setGravity(Gravity.RIGHT);foot.addView(time,new LinearLayout.LayoutParams(-2,-2));bubble.addView(foot,new LinearLayout.LayoutParams(-1,-2));addReactions(bubble,m);if(group&&room!=null&&room.optString("kind").equals("channel"))addComments(bubble,m);bubble.setOnClickListener(v->messageMenu(m));line.addView(bubble,new LinearLayout.LayoutParams(group?-1:-2,-2));content.addView(line);space(content,group?14:8);
  }messagesScroll.post(()->{if(bottom)messagesScroll.fullScroll(View.FOCUS_DOWN);else messagesScroll.scrollTo(0,scrollY);});
 }catch(Exception e){error(Api.message(e));}}

 String size(long b){return b>=1048576?String.format(Locale.ROOT,"%.1f МБ",b/1048576.):Math.max(1,b/1024)+" КБ";}
 void emojis(){if(emojiPanel==null||compose==null)return;if(emojiPanel.getVisibility()==View.VISIBLE){emojiPanel.setVisibility(View.GONE);return;}((android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(compose.getWindowToken(),0);emojiPanel.removeAllViews();emojiPanel.setVisibility(View.VISIBLE);emojiPanel.setBackground(shape(CARD,18));LinearLayout tabs=row();tabs.addView(button("Смайлы",false,()->fillEmojis(false)),new LinearLayout.LayoutParams(0,dp(40),1));tabs.addView(button("✦ Живые",false,()->fillEmojis(true)),new LinearLayout.LayoutParams(0,dp(40),1));tabs.addView(button("×",false,()->emojiPanel.setVisibility(View.GONE)),new LinearLayout.LayoutParams(dp(38),dp(40)));emojiPanel.addView(tabs);fillEmojis(false);animateEnter(emojiPanel,0);}
 void fillEmojis(boolean animated){if(emojiPanel==null)return;while(emojiPanel.getChildCount()>1)emojiPanel.removeViewAt(1);HorizontalScrollView scroll=new HorizontalScrollView(this);scroll.setHorizontalScrollBarEnabled(false);LinearLayout strip=row();scroll.addView(strip);String[] emojis=animated?MotionEmoji.GLYPHS:"😀 😃 😄 😁 😂 🥰 😍 😘 😉 😊 😎 🥳 🤔 😮 🤯 😢 😭 😡 😴 👍 👎 ❤️ 🔥 🎮 🕹 🎉 ✨ 🙏 💪 🤝 👀 ☕ 🍿 🚀 💯".split(" ");for(int i=0;i<emojis.length;i++){final int n=i;LinearLayout tile=col();tile.setGravity(Gravity.CENTER);View face;if(animated)face=new MotionEmoji(this,i);else{TextView t=label(emojis[i],29,TEXT);t.setGravity(Gravity.CENTER);face=t;}tile.addView(face,new LinearLayout.LayoutParams(dp(56),dp(66)));tile.setOnClickListener(v->{int at=Math.max(0,compose.getSelectionStart());compose.getText().insert(at,emojis[n]);if(animated)selectedMotion=n;compose.setSelection(Math.min(compose.length(),at+emojis[n].length()));face.animate().scaleX(1.18f).scaleY(1.18f).setDuration(100).withEndAction(()->face.animate().scaleX(1).scaleY(1).setDuration(140));});strip.addView(tile);}emojiPanel.addView(scroll,new LinearLayout.LayoutParams(-1,dp(80)));}
 void chatInfo(){if(!Conversation.community(chat)){personMenu(chat);return;}final Vault account=vault;String target=chat;task(()->{JSONObject r=api.call("/room/"+Conversation.room(target),null,account.token());account.putRoom(r);runOnUiThread(()->{if(vault==account)ProfileSheet.room(this,r);});});}
 void editRoom(JSONObject r){LinearLayout b=col();pad(b,18);EditText title=field(b,"Название",false),handle=field(b,"@адрес",false);title.setText(r.optString("title"));handle.setText(r.optString("handle"));TextView available=label("Текущий адрес",12,MUTED);b.addView(available);watchHandle(handle,available,r.optString("handle"));space(b,10);EditText members=field(b,"Ники через запятую",false);List<String> names=new ArrayList<>();JSONArray a=r.optJSONArray("members");for(int i=0;i<a.length();i++)names.add(a.optString(i));members.setText(String.join(", ",names));Switch pub=new Switch(this);pub.setText("Публичный · виден в поиске");pub.setTextColor(TEXT);pub.setChecked(r.optBoolean("public"));b.addView(pub);AlertDialog d=dialog().setTitle("Настройки сообщества").setView(b).setNegativeButton("Отмена",null).setPositiveButton("Сохранить",null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String t=title.getText().toString(),h=handle.getText().toString(),n=members.getText().toString();boolean visible=pub.isChecked();task(()->{JSONObject updated=api.call("/room/update",new JSONObject().put("id",r.optString("id")).put("title",t).put("handle",h).put("public",visible).put("members",nickList(n)),vault.token());vault.putRoom(updated);runOnUiThread(()->{d.dismiss();openChat("room:"+r.optString("id"));});});}));d.show();}
 void settings(){base("settings");title("Настройки",()->{if(vault.token().isEmpty())auth(false);else chats();});ScrollView scroll=new ScrollView(this);LinearLayout b=col();scroll.addView(b);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  if(!vault.token().isEmpty())try{JSONObject d=vault.copy();LinearLayout profile=row();Art av=art(d.optString("avatar","preset:0"),70,profile);av.setOnClickListener(v->avatarPicker(""));LinearLayout text=col();text.setPadding(dp(16),0,0,0);TextView name=label(d.optString("name",vault.nick()),22,TEXT);name.setTypeface(null,1);text.addView(name);text.addView(label("@"+vault.nick(),13,MUTED));profile.addView(text);profile.setOnClickListener(v->editProfile());b.addView(profile);space(b,13);b.addView(button("Изменить профиль и фото",false,()->editProfile()));space(b,22);}catch(Exception ignored){}
  b.addView(button("☁ Защита и резервная копия",false,()->cloudSettings()));space(b,10);b.addView(button("↻ Обновления · "+Updates.versionName(this),false,()->Updates.check(this,true)));space(b,18);paragraph(b,"ПОДКЛЮЧЕНИЕ");space(b,10);network=label(ChatService.state,17,TEXT);b.addView(network);space(b,9);b.addView(button("Проверить подключение",false,()->task(()->{JSONObject h=api.check();if(!h.optString("service").equals("oldy-chat"))throw new Exception("Не удалось проверить подключение");ChatService.state="Подключено";runOnUiThread(()->{if(network!=null)network.setText("Подключено");if(!vault.token().isEmpty())startChat();Toast.makeText(this,"Подключено",Toast.LENGTH_SHORT).show();});})));space(b,24);
  paragraph(b,"ОФОРМЛЕНИЕ");space(b,10);LinearLayout themes=row();String[] modes={"light","dark"},labels={"☀ Светлая","☾ Тёмная"};for(int i=0;i<2;i++){final String m=modes[i];themes.addView(button(labels[i],Notices.prefs(this).getString("theme","dark").equals(m),()->{Notices.prefs(this).edit().putString("theme",m).apply();settings();}),new LinearLayout.LayoutParams(0,dp(51),1));}b.addView(themes);space(b,10);b.addView(button("Обои чатов",false,()->wallpaperPicker()));space(b,8);toggle(b,"Анимации","animations",true);space(b,20);
  paragraph(b,"УВЕДОМЛЕНИЯ");space(b,9);toggle(b,"Новые сообщения","notifications",true);toggle(b,"Звук уведомлений","sound",true);toggle(b,"Вибрация","vibration",true);toggle(b,"Показывать текст","preview",false);space(b,8);b.addView(button("Все чаты без звука на 25 минут",false,()->focusMode()));space(b,8);b.addView(button("♫ Звуки · "+Notices.TONE_NAMES[Notices.tone(this)],false,()->soundPicker()));space(b,10);b.addView(button("Разрешения уведомлений",false,()->startActivity(new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName()))));space(b,10);b.addView(button("Доставка с выключенным экраном",false,()->background()));space(b,20);
  if(!vault.nick().isEmpty()){b.addView(button("Сохранить резервную копию",false,()->backup(false)));space(b,10);}if(vault.token().isEmpty())b.addView(button("Восстановить из копии",false,()->backup(true)));
  if(!vault.token().isEmpty()){b.addView(button("Выйти из аккаунта",false,()->dialog().setTitle("Выйти?").setMessage("История останется на этом телефоне.").setNegativeButton("Отмена",null).setPositiveButton("Выйти",(d,w)->logoutAccount()).show()));space(b,12);}
  space(b,12);b.addView(button("О приложении",false,()->error("OldЫ Chat · 0.4.1 beta\n\nЛичная переписка, группы и каналы с отдельными комментариями к постам. MP4 владельца приложения — до 2 ГБ, с просмотром внутри чата. Обычные прямые вложения — до 25 МБ. История дублируется на сервере в зашифрованном виде. Для восстановления на новом телефоне включи резервирование ключей в разделе «Защита и резервная копия».\n\nРекламные интеграции выключены до настройки владельцем.")));space(b,14);paragraph(b,"OldЫ Chat · 0.4.1 beta");
 }
 void toggle(LinearLayout b,String label,String key,boolean def){Switch s=new Switch(this);s.setText(label);s.setTextColor(TEXT);s.setTextSize(15);s.setThumbTintList(android.content.res.ColorStateList.valueOf(GREEN));s.setTrackTintList(android.content.res.ColorStateList.valueOf(MUTED));pad(s,10);s.setChecked(Notices.prefs(this).getBoolean(key,def));s.setOnCheckedChangeListener((v,on)->{Notices.prefs(this).edit().putBoolean(key,on).apply();if(on&&key.equals("notifications")&&Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},10);});b.addView(s,new LinearLayout.LayoutParams(-1,dp(50)));}
 void background(){PowerManager p=getSystemService(PowerManager.class);dialog().setTitle("Сообщения при погашенном экране").setMessage("Разреши чату работать в фоне. Это может увеличить расход батареи. На Xiaomi и некоторых других телефонах также включи автозапуск в настройках приложения.\n\n"+(p.isIgnoringBatteryOptimizations(getPackageName())?"Ограничение батареи уже снято.":"Сейчас Android может задерживать доставку.")).setNegativeButton("Закрыть",null).setPositiveButton(p.isIgnoringBatteryOptimizations(getPackageName())?"Настройки приложения":"Разрешить",(d,w)->{Intent i=p.isIgnoringBatteryOptimizations(getPackageName())?new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())):new Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,Uri.parse("package:"+getPackageName()));try{startActivity(i);}catch(Exception e){startActivity(new Intent(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS));}}).show();}
 void editProfile(){try{JSONObject data=vault.copy();LinearLayout b=col();pad(b,18);Art a=art(data.optString("avatar","preset:0"),85,b);a.setOnClickListener(v->avatarPicker(""));space(b,10);b.addView(button("Выбрать аватар",false,()->avatarPicker("")));space(b,15);EditText name=field(b,"Имя",false),bio=field(b,"О себе",false);name.setText(data.optString("name"));bio.setText(data.optString("bio"));dialog().setTitle("Твой профиль").setView(b).setNegativeButton("Отмена",null).setPositiveButton("Сохранить",(d,w)->{String n=name.getText().toString(),about=bio.getText().toString();task(()->{vault.profile(api.call("/profile",new JSONObject().put("name",n).put("bio",about),vault.token()));runOnUiThread(()->settings());});}).show();}catch(Exception e){error(Api.message(e));}}
 void avatarPicker(String room){avatarRoom=room;LinearLayout b=col();pad(b,15);GridLayout grid=new GridLayout(this);grid.setColumnCount(4);b.addView(grid);AlertDialog d=dialog().setTitle("Выбери себя").setView(b).setNegativeButton("Закрыть",null).create();for(int i=0;i<12;i++){final int n=i;Art a=new Art(this,"preset:"+i);GridLayout.LayoutParams tile=new GridLayout.LayoutParams();tile.width=dp(62);tile.height=dp(62);tile.setMargins(dp(3),dp(5),dp(3),dp(5));grid.addView(a,tile);a.setOnClickListener(v->{d.dismiss();task(()->uploadAvatar(new JSONObject().put("avatar","preset:"+n),room));});}space(b,12);b.addView(button("Загрузить своё фото",true,()->{avatarRoom=room;d.dismiss();Intent pick=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(pick,31);}));space(b,10);paragraph(b,"Фото профиля будет храниться на сервере OldЫ Chat.");d.show();}
 void uploadAvatar(JSONObject p,String room)throws Exception{JSONObject r;if(room.isEmpty()){r=api.call("/profile",p,vault.token());vault.profile(r);}else{p.put("id",room);r=api.call("/room/update",p,vault.token());vault.putRoom(r);}runOnUiThread(()->{if(room.isEmpty())settings();else openChat("room:"+room);});}
 void attachments(){boolean channel=false,creator=false;try{JSONObject r=chat.startsWith("room:")?vault.room(Conversation.room(chat)):null;channel=r!=null&&r.optString("kind").equals("channel");creator=channel&&vault.copy().optBoolean("creator_video")&&r.optString("owner").equals(vault.nick());}catch(Exception ignored){}List<String> choices=new ArrayList<>();List<Integer> actions=new ArrayList<>();choices.add("📷 Фото");actions.add(0);if(channel){if(creator){choices.add("★ MP4 в канал · до 2 ГБ");actions.add(3);}}else{choices.add("▶ Видео до 25 МБ");actions.add(1);}choices.add("◉ Записать видеокружок");actions.add(4);choices.add("🎙 Голосовое сообщение");actions.add(2);dialog().setTitle(channel?"Добавить к публикации":"Вложение").setItems(choices.toArray(new String[0]),(d,choice)->{int w=actions.get(choice);mediaTarget=chat;if(w==4){startActivityForResult(new Intent(this,RoundActivity.class),35);return;}if(w==3){startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("video/mp4").addCategory(Intent.CATEGORY_OPENABLE).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION),34);return;}if(w==2)record();else{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType(w==0?"image/*":"video/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,w==0?32:33);}}).show();}
 void record(){if(voice==null)voice=new VoiceCapture(this);voice.begin();}
 void stopRecording(boolean send){if(recorder==null)return;try{recorder.stop();}catch(Exception e){send=false;}recorder.release();recorder=null;File file=recording;if(send){String target=mediaTarget;task(()->{try{JSONObject p=MediaFiles.importFile(this,Uri.fromFile(file),"audio/mp4","Голосовое сообщение");String local=p.getString("local");p.remove("local");prepareRoom(target);vault.queuePayload(target,p,local);runOnUiThread(()->renderMessages());}finally{file.delete();}});}else if(file!=null)file.delete();}
 public void onRequestPermissionsResult(int request,String[] p,int[] result){super.onRequestPermissionsResult(request,p,result);if(request==11&&result.length>0&&result[0]==PackageManager.PERMISSION_GRANTED)Toast.makeText(this,"Микрофон разрешён. Удерживай кнопку и говори.",Toast.LENGTH_LONG).show();}
 void openMedia(JSONObject m){if(m.optString("mime").startsWith("audio/")&&(!m.optString("cloud_blob").isEmpty()||m.has("local"))){if(voicePlayer==null)voicePlayer=new VoicePlayer(this);voicePlayer.toggle(m);return;}if(!m.optString("cloud_video").isEmpty()){startActivity(new Intent(this,VideoActivity.class).putExtra("video",m.optString("cloud_video")).putExtra("size",m.optLong("size")).putExtra("title",m.optString("name","Видео")));return;}if(!m.has("local")){if(!m.optString("cloud_blob").isEmpty()){final Vault account=vault;Toast.makeText(this,"Загружаем вложение…",Toast.LENGTH_SHORT).show();task(()->{CloudMedia.download(this,account,m);JSONObject loaded=account.message(m.getString("id"));runOnUiThread(()->{if(vault==account&&loaded!=null){renderMessages();openMedia(loaded);}});});return;}if(m.optBoolean("out")){error("Этот файл остался на прежнем телефоне.");return;}if(ChatService.instance==null){startChat();error("Подключаемся. Нажмите на вложение ещё раз.");}else{ChatService.instance.rtc.request(m);renderMessages();}return;}task(()->{byte[] bytes=MediaFiles.bytes(this,m.getString("local"));String mime=m.optString("mime");runOnUiThread(()->{if(mime.startsWith("image/")){BitmapFactory.Options options=new BitmapFactory.Options();options.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if((long)options.outWidth*options.outHeight>60000000){error("Изображение слишком большое");return;}options.inJustDecodeBounds=false;options.inSampleSize=Math.max(1,Math.max(options.outWidth,options.outHeight)/1600);Bitmap bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if(bitmap==null){error("Не удалось открыть изображение");return;}ImageView image=new ImageView(this);image.setImageBitmap(bitmap);image.setAdjustViewBounds(true);dialog().setView(image).setPositiveButton("Закрыть",null).show();}else if(mime.startsWith("video/"))startActivity(new Intent(this,VideoActivity.class).putExtra("local",m.optString("local")));else play(bytes,mime);});});}
 void play(byte[] data,String mime){try{if(player!=null)player.release();player=new MediaPlayer();MediaPlayer current=player;current.setDataSource(new MediaDataSource(){public long getSize(){return data.length;}public int readAt(long p,byte[] out,int off,int n){if(p>=data.length)return -1;int size=Math.min(n,data.length-(int)p);System.arraycopy(data,(int)p,out,off,size);return size;}public void close(){}});LinearLayout b=col();pad(b,18);if(mime.startsWith("video/")){SurfaceView video=new SurfaceView(this);b.addView(video,new LinearLayout.LayoutParams(-1,dp(300)));video.getHolder().addCallback(new SurfaceHolder.Callback(){public void surfaceCreated(SurfaceHolder h){current.setDisplay(h);current.prepareAsync();}public void surfaceChanged(SurfaceHolder h,int f,int w,int ht){}public void surfaceDestroyed(SurfaceHolder h){}});}else current.prepareAsync();b.addView(button("⏯ Пауза / продолжить",false,()->{try{if(current.isPlaying())current.pause();else current.start();}catch(Exception ignored){}}));current.setOnPreparedListener(p->p.start());current.setOnErrorListener((p,w,e)->{error("Не удалось воспроизвести этот формат");return true;});AlertDialog d=dialog().setTitle(mime.startsWith("video/")?"Видео":"Голосовое сообщение").setView(b).setPositiveButton("Закрыть",null).create();d.setOnDismissListener(x->{current.release();if(player==current)player=null;});d.show();}catch(Exception e){error("Не удалось открыть запись");}}
 void campaign(){work.execute(()->{try{JSONObject ad=api.call("/campaign",null,vault.token());if(!ad.optBoolean("enabled"))return;int revision=ad.optInt("revision");android.content.SharedPreferences seen=getSharedPreferences("campaign",0);if(revision<=seen.getInt("seen",0))return;Uri uri=Uri.parse(ad.getString("url"));if(!"https".equals(uri.getScheme())||uri.getHost()==null)return;runOnUiThread(()->{if(isFinishing()||!screen.equals("chats"))return;seen.edit().putInt("seen",revision).apply();dialog().setTitle("Реклама · "+ad.optString("title")).setMessage(ad.optString("text")).setNegativeButton("Закрыть",null).setPositiveButton("Подробнее",(d,w)->{try{startActivity(new Intent(Intent.ACTION_VIEW,uri));}catch(Exception e){error("Не удалось открыть браузер");}}).show();});}catch(Exception ignored){}});}
 void backup(boolean restore){LinearLayout b=col();pad(b,18);EditText p=field(b,"Пароль копии · от 10 символов",true);dialog().setTitle(restore?"Восстановить копию":"Сохранить копию").setMessage("Запомни этот пароль. Он понадобится для восстановления аккаунта и истории. Фото, видео и голосовые в копию не входят.").setView(b).setNegativeButton("Отмена",null).setPositiveButton("Продолжить",(d,w)->{char[] password=p.getText().toString().toCharArray();if(password.length<10){error("Нужно минимум 10 символов");return;}if(restore){restorePassword=password;startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),22);}else task(()->{try{backupText=Crypto.exportBackup(vault.backup(),password);runOnUiThread(()->startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/octet-stream").putExtra(Intent.EXTRA_TITLE,"OldyChat-backup.oldy").addCategory(Intent.CATEGORY_OPENABLE),21));}finally{Arrays.fill(password,'\0');}});}).show();}
 protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(result!=RESULT_OK||data==null||data.getData()==null){if(r==21)backupText=null;if(r==22&&restorePassword!=null)Arrays.fill(restorePassword,'\0');return;}Uri uri=data.getData();
  if(r==35){String target=mediaTarget;File f=new File(uri.getPath());task(()->CloudMedia.round(this,f,target));return;}
  if(r==21)task(()->{try(OutputStream o=getContentResolver().openOutputStream(uri)){o.write(Crypto.bytes(backupText));backupText=null;runOnUiThread(()->error("Копия сохранена."));}});
  if(r==22)task(()->{try{String raw=Api.read(getContentResolver().openInputStream(uri),50000000);vault.restore(Crypto.importBackup(raw,restorePassword));runOnUiThread(()->{auth(false);error("Копия восстановлена. Войди с ником и паролем.");});}finally{Arrays.fill(restorePassword,'\0');}});
  if(r==34){try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}CreatorVideo.upload(this,uri,mediaTarget,compose==null?"":compose.getText().toString().trim());}
  if(r==31){String room=avatarRoom;task(()->{BitmapFactory.Options opt=new BitmapFactory.Options();opt.inJustDecodeBounds=true;try(InputStream in=getContentResolver().openInputStream(uri)){BitmapFactory.decodeStream(in,null,opt);}if(opt.outWidth<1||opt.outHeight<1)throw new Exception("Не удалось открыть фото");opt.inSampleSize=Math.max(1,Math.max(opt.outWidth,opt.outHeight)/512);opt.inJustDecodeBounds=false;Bitmap bm;try(InputStream in=getContentResolver().openInputStream(uri)){bm=BitmapFactory.decodeStream(in,null,opt);}if(bm==null)throw new Exception("Не удалось открыть фото");ByteArrayOutputStream out=new ByteArrayOutputStream();bm.compress(Bitmap.CompressFormat.JPEG,85,out);bm.recycle();uploadAvatar(new JSONObject().put("photo",Crypto.b64(out.toByteArray())),room);});}
  if(r==32||r==33){String target=mediaTarget;String caption=compose==null?"":compose.getText().toString().trim();Toast.makeText(this,"Загружаем вложение…",Toast.LENGTH_SHORT).show();task(()->{String mime=getContentResolver().getType(uri);if(mime==null||!mime.matches("image/(jpeg|png|webp)|video/(mp4|webm)"))throw new Exception("Выберите фото или видео");CloudMedia.attach(this,uri,mime,mime.startsWith("image/")?"Фото":"Видео",target,caption);});}
 }
 void sheet(String heading,LinearLayout body){Dialog d=panel(heading,body);d.show();Window w=d.getWindow();if(w!=null)w.setLayout(-1,-2);animateEnter(body,0);}
 Dialog panel(String heading,LinearLayout body){final Dialog d=new Dialog(this);if(activeSheet!=null)activeSheet.dismiss();activeSheet=d;LinearLayout box=col();pad(box,20);GradientDrawable backdrop=new GradientDrawable(GradientDrawable.Orientation.TL_BR,light?new int[]{0xfff6f9ff,0xffffffff}:new int[]{0xff23344d,0xff172132});backdrop.setCornerRadii(new float[]{dp(28),dp(28),dp(28),dp(28),0,0,0,0});box.setBackground(backdrop);TextView grip=label("━━",17,MUTED);grip.setGravity(Gravity.CENTER);box.addView(grip);TextView title=label(heading,23,TEXT);title.setTypeface(null,1);box.addView(title);space(box,16);ScrollView scroll=new ScrollView(this);scroll.setFillViewport(false);scroll.addView(body);box.addView(scroll,new LinearLayout.LayoutParams(-1,-2));scroll.setOnHierarchyChangeListener(null);scroll.post(()->{int max=(int)(getResources().getDisplayMetrics().heightPixels*.68);if(scroll.getHeight()>max)scroll.setLayoutParams(new LinearLayout.LayoutParams(-1,max));});space(box,12);box.addView(button("Закрыть",true,()->d.dismiss()));d.setContentView(box);Window w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.setGravity(Gravity.BOTTOM);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);w.setDimAmount(.4f);}d.setOnDismissListener(x->{if(activeSheet==d)activeSheet=null;});return d;}
 View menuTile(String icon,String title,String detail,Runnable action){LinearLayout tile=row();pad(tile,10);tile.setBackground(shape(light?0xffedf3fc:0xff233349,17));TextView mark=label(icon,23,light?0xff4670ad:0xffa7cfff);mark.setGravity(Gravity.CENTER);tile.addView(mark,new LinearLayout.LayoutParams(dp(42),dp(46)));LinearLayout words=col();TextView name=label(title,15,TEXT);name.setTypeface(null,1);words.addView(name);space(words,3);words.addView(label(detail,11,MUTED));tile.addView(words,new LinearLayout.LayoutParams(0,-2,1));tile.addView(label("›",21,MUTED));tile.setOnClickListener(v->{if(activeSheet!=null)activeSheet.dismiss();action.run();});return tile;}
 void profileMenu(){LinearLayout b=col();try{JSONObject me=vault.copy();LinearLayout hero=row();pad(hero,14);GradientDrawable glow=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{0xff4966a1,0xff775fad,0xffa46e91});glow.setCornerRadius(dp(22));hero.setBackground(glow);art(me.optString("avatar","preset:0"),64,hero);LinearLayout names=col();names.setPadding(dp(14),0,0,0);TextView name=label(me.optString("name"),21,0xffffffff);name.setTypeface(null,1);names.addView(name);names.addView(label("@"+vault.nick(),13,0xffe0e9ff));hero.addView(names,new LinearLayout.LayoutParams(0,-2,1));hero.addView(new MotionEmoji(this,3),new LinearLayout.LayoutParams(dp(48),dp(48)));b.addView(hero);space(b,14);}catch(Exception ignored){}
  b.addView(menuTile("☺","Мой профиль","Аватар и немного о себе",()->editProfile()));space(b,7);b.addView(menuTile("★","Избранное","Важное всегда под рукой",()->savedMessages()));space(b,7);b.addView(menuTile("✦","Капсула дня","Личные мысли и планы",()->capsule()));space(b,7);b.addView(menuTile("◷","Все чаты без звука",Notices.quietUntil(this,vault)>System.currentTimeMillis()?"Осталось "+NotificationSheet.remaining(Notices.quietUntil(this,vault)):"Отключить звук и вибрацию на 25 минут",()->focusMode()));space(b,7);b.addView(menuTile("▥","Пульс общения","Твоя активность на этом устройстве",()->conversationStats()));space(b,7);b.addView(menuTile("♧","Создать группу","Общение своим кругом",()->createRoom("group")));space(b,7);b.addView(menuTile("◈","Создать канал","Твои публикации и аудитория",()->createRoom("channel")));space(b,7);b.addView(menuTile("⊘","Чёрный список","Заблокированные контакты",()->blacklist()));space(b,7);b.addView(menuTile("⚙","Настройки","Обои, звуки и обновления",()->settings()));sheet("Меню",b);
 }
 void conversationStats(){try{JSONArray messages=vault.copy().getJSONArray("messages");int sent=0,received=0;Set<String> days=new HashSet<>(),chats=new HashSet<>();for(int i=0;i<messages.length();i++){JSONObject m=messages.getJSONObject(i);if(m.optString("kind").equals("control"))continue;if(m.optBoolean("out"))sent++;else received++;days.add(new java.text.SimpleDateFormat("yyyy-MM-dd",Locale.ROOT).format(new Date(m.optLong("time"))));chats.add(m.optString("peer"));}LinearLayout b=col();paragraph(b,"Статистика сохранённой истории этого аккаунта на телефоне. Удалённые сообщения не учитываются.");space(b,15);b.addView(searchCard("preset:3",sent+" отправлено",received+" получено","СООБЩЕНИЯ",()->{}));space(b,10);b.addView(searchCard("preset:7",days.size()+" активных дней",chats.size()+" чатов","ТВОЙ РИТМ",()->{}));sheet("Пульс общения",b);}catch(Exception e){error(Api.message(e));}}
 void wallpaperPicker(){LinearLayout b=col();String[] names={"Аркада · геймпады и портативки","Созвездия · прохладные оттенки","Бумага · тёплые оттенки"};for(int i=0;i<3;i++){final int style=i;TextView t=button(names[i],false,()->{Notices.prefs(this).edit().putInt("wallpaper",style).apply();Toast.makeText(this,"Обои сохранены",Toast.LENGTH_SHORT).show();if(screen.equals("chat"))openChat(chat);});t.setBackground(new Wallpaper(light,i));b.addView(t,new LinearLayout.LayoutParams(-1,dp(92)));space(b,10);}sheet("Обои для разговоров",b);}
 void messageMenu(JSONObject m){try{LinearLayout b=col();LinearLayout reactions=row();JSONObject current=vault.reactions(m.optString("id")).optJSONObject(vault.nick());String mine=current==null?"":current.optString("emoji");Dialog d=panel(Conversation.community(chat)?"Публикация":"Сообщение",b);pad(b,16);for(String emoji:Vault.REACTIONS){TextView t=button(emoji,mine.equals(emoji),()->{d.dismiss();control(m,"reaction",mine.equals(emoji)?"":emoji);});t.setPadding(0,dp(12),0,dp(12));t.setTextSize(24);reactions.addView(t,new LinearLayout.LayoutParams(0,dp(50),1));}b.addView(reactions);space(b,12);
  if(compose!=null){b.addView(button("↳  Ответить",false,()->{d.dismiss();replyTo=m;renderReply();compose.requestFocus();}));space(b,6);}
  b.addView(button("⧉  Копировать текст",false,()->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("OldЫ Chat",m.optString("text")));d.dismiss();Toast.makeText(this,"Скопировано",Toast.LENGTH_SHORT).show();}));space(b,6);
  b.addView(button(vault.saved(m.optString("id"))?"★  Убрать из избранного":"☆  В избранное",false,()->{d.dismiss();task(()->{vault.bookmark(m.optString("id"));runOnUiThread(()->renderMessages());});}));space(b,6);
  JSONObject room=Conversation.community(chat)?vault.room(Conversation.room(chat)):null;if(room==null||room.optString("owner").equals(vault.nick())){boolean pinned=vault.pinned(chat).equals(m.optString("id"));b.addView(button(pinned?"⌁  Открепить":"⌁  Закрепить для всех",false,()->{d.dismiss();control(m,pinned?"unpin":"pin","");}));space(b,6);}
  if(chat.startsWith("room:")){String link="oldy://comments/"+Conversation.room(chat)+"/"+m.optString("id");b.addView(button("⧉ Ссылка на комментарии",false,()->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("Комментарии OldЫ Chat",link));d.dismiss();Toast.makeText(this,"Ссылка скопирована",Toast.LENGTH_SHORT).show();}));space(b,6);}
  if(m.optString("kind").equals("file")){b.addView(button("↗  Открыть вложение",false,()->{d.dismiss();openMedia(m);}));space(b,6);}
  if(m.optBoolean("out")||vault.moderator()||!Conversation.community(chat)){TextView del=button("Удалить для всех",false,()->{d.dismiss();deletePost(m);});del.setTextColor(light?0xffb73953:0xffff92a6);b.addView(del);space(b,6);}
  if(!m.optBoolean("out")){String from=m.optString("from",chat);b.addView(button("☺  Профиль @"+from,false,()->{d.dismiss();personMenu(from);}));}
  d.show();if(d.getWindow()!=null)d.getWindow().setLayout(-1,-2);animateEnter(b,0);
 }catch(Exception e){error(Api.message(e));}}
 void control(JSONObject m,String op,String emoji){try{send(new JSONObject().put("kind","control").put("op",op).put("mid",m.optString("id")).put("emoji",emoji),null);}catch(Exception e){error(Api.message(e));}}
 void addReactions(LinearLayout bubble,JSONObject m)throws Exception{JSONObject all=vault.reactions(m.optString("id"));if(all.length()==0)return;LinearLayout row=row();for(String emoji:Vault.REACTIONS){int count=0;boolean mine=false;Iterator<String> users=all.keys();while(users.hasNext()){String n=users.next();if(emoji.equals(all.optJSONObject(n).optString("emoji"))){count++;if(n.equals(vault.nick()))mine=true;}}if(count==0)continue;final boolean selected=mine;TextView t=label(emoji+" "+count,14,mine?INK:TEXT);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(5),dp(8),dp(5));t.setBackground(shape(mine?GREEN:(light?0xffedf3fa:0xff303e50),18));t.setOnClickListener(v->control(m,"reaction",selected?"":emoji));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.rightMargin=dp(4);row.addView(t,lp);}if(row.getChildCount()>0){space(bubble,8);HorizontalScrollView h=new HorizontalScrollView(this);h.setHorizontalScrollBarEnabled(false);h.addView(row);bubble.addView(h);}}
 void renderPin()throws Exception{if(pinBar==null)return;pinBar.removeAllViews();String id=vault.pinned(chat);if(id.isEmpty())return;JSONObject m=vault.message(id);TextView p=label("⌁ Закреплённая публикация\n"+(m==null?"Ожидаем публикацию на этом устройстве":Payload.preview(m)),12,light?0xff366aaf:0xffa0ceff);p.setMaxLines(2);p.setEllipsize(TextUtils.TruncateAt.END);pad(p,10);p.setBackground(shape(CARD,14));p.setOnClickListener(v->jump(id));pinBar.addView(p,new LinearLayout.LayoutParams(-1,-2));space(pinBar,8);}
 void jump(String id){View found=content.findViewWithTag(id);if(found==null){Toast.makeText(this,"Публикации пока нет на этом телефоне",Toast.LENGTH_SHORT).show();return;}View line=(View)found.getParent();messagesScroll.smoothScrollTo(0,line.getTop());found.animate().alpha(.45f).setDuration(130).withEndAction(()->found.animate().alpha(1).setDuration(300));}
 void renderReply(){replyBar.removeAllViews();if(replyTo==null)return;String text=Payload.preview(replyTo);TextView q=label("↳ Ответ · "+text.substring(0,Math.min(80,text.length()))+"   ×",12,MUTED);pad(q,8);q.setMaxLines(2);q.setBackground(shape(CARD,10));q.setOnClickListener(v->{replyTo=null;replyBar.removeAllViews();});replyBar.addView(q);space(replyBar,6);}
 void savedMessages(){LinearLayout b=col();try{JSONArray a=vault.copy().getJSONArray("messages");int count=0;for(int i=a.length()-1;i>=0;i--){JSONObject m=a.getJSONObject(i);if(!vault.saved(m.optString("id")))continue;count++;b.addView(button(Payload.preview(m)+"\n"+new java.text.SimpleDateFormat("d MMM · HH:mm",new Locale("ru")).format(new Date(m.optLong("time"))),false,()->{openChat(m.optString("peer"));ui.postDelayed(()->jump(m.optString("id")),150);}));space(b,8);}if(count==0)paragraph(b,"Нажми на сообщение или пост и выбери «В избранное». Всё важное будет здесь.");sheet("★ Избранное",b);}catch(Exception e){error(Api.message(e));}}
 void blacklist(){task(()->{JSONArray a=api.call("/blocks",null,vault.token()).getJSONArray("blocked");vault.blocks(a);runOnUiThread(()->{LinearLayout b=col();if(a.length()==0)paragraph(b,"Здесь появятся люди, которых ты заблокируешь в личных сообщениях.");for(int i=0;i<a.length();i++){String n=a.optString(i);b.addView(button("@"+n+"  ·  разблокировать",false,()->setBlock(n,false)));space(b,8);}sheet("Чёрный список ЛС",b);});});}
 void setBlock(String target,boolean blocked){task(()->{api.call("/blocks",new JSONObject().put("target",target).put("blocked",blocked),vault.token());vault.blocks(api.call("/blocks",null,vault.token()).getJSONArray("blocked"));runOnUiThread(()->{Toast.makeText(this,blocked?"Личные сообщения заблокированы":"Собеседник разблокирован",Toast.LENGTH_SHORT).show();if(screen.equals("chat")&&chat.equals(target))openChat(target);});});}
 void personMenu(String target){if(target.isEmpty()||target.equals(vault.nick())){editProfile();return;}final Vault account=vault;final String context=chat;task(()->{JSONObject u=api.call("/user/"+target,null,account.token());account.pin(u);JSONObject r=Conversation.community(context)?account.room(Conversation.room(context)):null;runOnUiThread(()->{if(vault==account)ProfileSheet.person(this,u,r);});});}
 void roomBan(JSONObject r,String target,boolean banned){task(()->{JSONObject updated=api.call("/room/ban",new JSONObject().put("id",r.optString("id")).put("target",target).put("banned",banned),vault.token());vault.putRoom(updated);runOnUiThread(()->{Toast.makeText(this,banned?"Участник заблокирован":"Доступ снова разрешён",Toast.LENGTH_SHORT).show();if(chat.equals("room:"+r.optString("id")))openChat(chat);});});}
 void emailSettings(){try{JSONObject me=vault.copy();LinearLayout b=col();pad(b,16);EditText email=field(b,"Электронная почта",false);email.setInputType(33);email.setText(me.optString("email"));paragraph(b,me.optBoolean("email_verified")?"✓ Адрес подтверждён":"Адрес используется для входа. Подтверждение почты требует подключения отправки писем на сервере.");space(b,12);b.addView(button("Сохранить e-mail",true,()->{String value=email.getText().toString().trim();task(()->{vault.profile(api.call("/email/link",new JSONObject().put("email",value),vault.token()));runOnUiThread(()->Toast.makeText(this,"E-mail сохранён",Toast.LENGTH_SHORT).show());});}));space(b,8);b.addView(button("Отправить код подтверждения",false,()->task(()->{api.call("/email/request",new JSONObject(),vault.token());runOnUiThread(()->{LinearLayout codeBox=col();pad(codeBox,16);EditText code=field(codeBox,"Код из письма",false);code.setInputType(2);dialog().setTitle("Подтвердить почту").setView(codeBox).setNegativeButton("Отмена",null).setPositiveButton("Подтвердить",(x,w)->{String c=code.getText().toString().trim();task(()->{vault.profile(api.call("/email/verify",new JSONObject().put("code",c),vault.token()));runOnUiThread(()->Toast.makeText(this,"Почта подтверждена",Toast.LENGTH_SHORT).show());});}).show();});})));sheet("✉ Электронная почта",b);}catch(Exception e){error(Api.message(e));}}
 String makeThumb(String local)throws Exception{byte[] bytes=MediaFiles.bytes(this,local);BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);o.inSampleSize=Math.max(1,Math.max(o.outWidth,o.outHeight)/180);o.inJustDecodeBounds=false;Bitmap bm=BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);if(bm==null)return "";float scale=Math.min(1,180f/Math.max(bm.getWidth(),bm.getHeight()));Bitmap small=Bitmap.createScaledBitmap(bm,Math.max(1,(int)(bm.getWidth()*scale)),Math.max(1,(int)(bm.getHeight()*scale)),true);ByteArrayOutputStream out=new ByteArrayOutputStream();small.compress(Bitmap.CompressFormat.JPEG,45,out);if(small!=bm)small.recycle();bm.recycle();return out.size()<=7000?Crypto.b64(out.toByteArray()):"";}
 void photoPreview(JSONObject m,ImageView view){final Vault account=vault;String key=m.optString("id"),cacheKey=key+(m.has("local")?":full":":thumb");Bitmap cached=mediaCache.get(cacheKey);if(cached!=null){view.setImageBitmap(cached);return;}work.execute(()->{try{byte[] bytes=m.has("local")?MediaFiles.bytes(this,m.getString("local")):Crypto.un64(m.optString("thumb"));if(bytes.length==0)return;BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);o.inSampleSize=Math.max(1,Math.max(o.outWidth,o.outHeight)/700);o.inJustDecodeBounds=false;Bitmap image=BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);if(image!=null&&vault==account){mediaCache.put(cacheKey,image);runOnUiThread(()->{if(vault==account)view.setImageBitmap(image);});}}catch(Exception ignored){}});}
 void addLink(LinearLayout bubble,JSONObject link,boolean group){String url=link.optString("url");try{java.net.URI uri=new java.net.URI(url);if(!("https".equals(uri.getScheme())||"http".equals(uri.getScheme()))||uri.getHost()==null||uri.getUserInfo()!=null)return;}catch(Exception e){return;}space(bubble,10);LinearLayout card=col();pad(card,10);GradientDrawable bg=shape(light?0xffedf5ff:0xff17293d,12);bg.setStroke(dp(1),light?0xffbfdbf8:0xff365879);card.setBackground(bg);TextView provider=label(link.optString("site","Ссылка"),12,light?0xff3776b4:0xff9acfff);provider.setTypeface(null,1);card.addView(provider);space(card,4);TextView title=label(link.optString("title"),15,TEXT);title.setTypeface(null,1);title.setMaxLines(3);card.addView(title);if(!link.optString("author").isEmpty()){space(card,4);card.addView(label(link.optString("author"),12,MUTED));}String video=LinkCards.youtube(url);if(!video.isEmpty()){space(card,8);FrameLayout frame=new FrameLayout(this);ImageView image=new ImageView(this);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setBackgroundColor(light?0xffd6e3f4:0xff223954);frame.addView(image,new FrameLayout.LayoutParams(-1,-1));TextView play=label("▶",34,0xffffffff);play.setGravity(Gravity.CENTER);play.setShadowLayer(dp(5),0,dp(1),0xff263243);frame.addView(play,new FrameLayout.LayoutParams(-1,-1));card.addView(frame,new LinearLayout.LayoutParams(group?-1:dp(222),dp(150)));Bitmap cached=mediaCache.get("yt:"+video);if(cached!=null)image.setImageBitmap(cached);else Art.fetch.execute(()->{try{Bitmap pic=LinkCards.thumbnail(video);if(pic!=null){mediaCache.put("yt:"+video,pic);runOnUiThread(()->image.setImageBitmap(pic));}}catch(Exception ignored){}});}TextView open=label("Открыть ↗",12,light?0xff3672ab:0xff9acfff);space(card,7);card.addView(open);card.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception e){error("Не удалось открыть ссылку");}});bubble.addView(card,new LinearLayout.LayoutParams(group?-1:-2,-2));}


 void cloudSettings(){LinearLayout b=col();pad(b,16);paragraph(b,"Сообщения и миниатюры сохраняются на сервере в зашифрованном виде. Чтобы восстановить их на другом телефоне, сохрани защищённую паролем копию ключей. Фото и голосовые до 25 МБ также загружаются на сервер в зашифрованном виде.");space(b,14);EditText password=field(b,"Твой пароль аккаунта",true);b.addView(button("Защитить ключи в облаке",true,()->{String pass=password.getText().toString();task(()->{JSONObject login=api.call("/login",new JSONObject().put("nick",vault.nick()).put("password",pass),"");api.call("/key-backup",new JSONObject().put("backup",Crypto.exportBackup(vault.keyBackup(),pass.toCharArray())),login.getString("token"));runOnUiThread(()->Toast.makeText(this,"Копия ключей защищена паролем и сохранена",Toast.LENGTH_LONG).show());});}));space(b,12);paragraph(b,"После сохранения ключей доступ к аккаунту на новом телефоне восстанавливается по e-mail или нику и паролю. Выбирай длинный уникальный пароль: он защищает копию ключей.");sheet("Защита и история",b);}


 String audience(JSONObject r){int n=r.optJSONArray("members")==null?0:r.optJSONArray("members").length();String[] words=r.optString("kind").equals("channel")?new String[]{"подписчик","подписчика","подписчиков"}:new String[]{"участник","участника","участников"};int x=n%100,y=n%10;return n+" "+words[x>=11&&x<=14?2:y==1?0:y>=2&&y<=4?1:2];}
 void openComments(String room,String post){task(()->{JSONObject r=api.call("/room/"+room,null,vault.token());vault.putRoom(r);api.call("/threads",new JSONObject().put("room",room).put("post",post),vault.token());runOnUiThread(()->openChat("thread:"+room+":"+post));});}
 void addComments(LinearLayout bubble,JSONObject m){String rid=Conversation.room(chat),mid=m.optString("id");int count=0;try{JSONArray a=vault.copy().getJSONArray("messages");for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x.optString("peer").equals("thread:"+rid+":"+mid)&&!x.optString("kind").equals("control"))count++;}}catch(Exception ignored){}space(bubble,10);View divider=new View(this);divider.setBackgroundColor(light?0xffdce5ef:0xff405065);bubble.addView(divider,new LinearLayout.LayoutParams(-1,dp(1)));TextView c=label("◌  "+(count==0?"Комментировать":count+" · Комментарии")+"   ›",14,light?0xff3470ac:0xff9bcfff);c.setTypeface(null,1);c.setPadding(0,dp(12),0,dp(2));c.setOnClickListener(v->openComments(rid,mid));bubble.addView(c,new LinearLayout.LayoutParams(-1,-2));}
 void videoCover(JSONObject m,ImageView image){final Vault account=vault;String vid=m.optString("cloud_video"),cacheKey="video-cover-hq:"+vid;Bitmap cached=mediaCache.get(cacheKey);if(cached!=null){image.setImageBitmap(cached);return;}try{byte[] bytes=Crypto.un64(m.optString("thumb"));if(bytes.length>0){Bitmap thumb=BitmapFactory.decodeByteArray(bytes,0,bytes.length);if(thumb!=null)image.setImageBitmap(thumb);}}catch(Exception ignored){}
  if(!loadingImages.add(cacheKey))return;Art.fetch.execute(()->{try{for(int attempt=0;attempt<4&&vault==account;attempt++)try{JSONObject result=api.call("/video-cover/"+vid,null,account.token());byte[] bytes=Crypto.un64(result.getString("photo"));Bitmap cover=BitmapFactory.decodeByteArray(bytes,0,bytes.length);if(cover!=null&&vault==account)runOnUiThread(()->{if(vault!=account)return;mediaCache.put(cacheKey,cover);image.setImageBitmap(cover);updateCoverViews(root,vid,cover);});return;}catch(Api.Failure failure){if(failure.status!=409)return;try{Thread.sleep(1200);}catch(InterruptedException stop){Thread.currentThread().interrupt();return;}}catch(Exception unavailable){return;}}finally{runOnUiThread(()->loadingImages.remove(cacheKey));}});
 }
 void updateCoverViews(View v,String vid,Bitmap bitmap){if(v instanceof ImageView&&("video:"+vid).equals(v.getTag()))((ImageView)v).setImageBitmap(bitmap);if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)updateCoverViews(g.getChildAt(i),vid,bitmap);}}

 void addVideo(LinearLayout b,JSONObject m,boolean group){boolean round=m.optBoolean("round");AspectMediaFrame frame=new AspectMediaFrame(this,round);ImageView image=new AspectMediaFrame.Cover(this,frame);image.setTag("video:"+m.optString("cloud_video"));frame.addView(image,new FrameLayout.LayoutParams(-1,-1));videoCover(m,image);UiIcon play=new UiIcon(this,"play",0xffffffff);play.setBackground(shape(0xa5122035,28));FrameLayout.LayoutParams pp=new FrameLayout.LayoutParams(dp(62),dp(62),Gravity.CENTER);frame.addView(play,pp);TextView badge=label((round?"Кружок":"MP4")+" · "+size(m.optLong("size"))+"  ⛶",11,0xffffffff);badge.setPadding(dp(10),dp(6),dp(10),dp(6));badge.setBackgroundColor(0x99091221);FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-2,-2,Gravity.BOTTOM|Gravity.RIGHT);frame.addView(badge,bp);frame.setOnClickListener(v->openMedia(m));b.addView(frame,new LinearLayout.LayoutParams(round?dp(218):group?-1:Math.min(dp(250),getResources().getDisplayMetrics().widthPixels-dp(100)),-2));}


 void soundPicker(){LinearLayout b=col();for(int i=0;i<Notices.TONE_NAMES.length;i++){final int n=i;LinearLayout line=row();TextView choose=button((Notices.tone(this)==i?"✓ ":"")+Notices.TONE_NAMES[i],Notices.tone(this)==i,()->{Notices.prefs(this).edit().putInt("tone",n).apply();previewTone(n);Toast.makeText(this,"Звук выбран: "+Notices.TONE_NAMES[n],Toast.LENGTH_SHORT).show();});line.addView(choose,new LinearLayout.LayoutParams(0,dp(48),1));TextView listen=label("▶",20,TEXT);listen.setGravity(Gravity.CENTER);listen.setOnClickListener(v->previewTone(n));line.addView(listen,new LinearLayout.LayoutParams(dp(48),dp(48)));b.addView(line);space(b,7);}space(b,8);b.addView(button("Громкость уведомлений Android",false,()->startActivity(new Intent(Settings.ACTION_SOUND_SETTINGS))));space(b,8);paragraph(b,"Новые мелодии звучат ярче. Итоговая громкость зависит от системной громкости уведомлений и режима «Не беспокоить».");sheet("♫ Выбери звук",b);}
 void previewTone(int index){try{MediaPlayer sound=MediaPlayer.create(this,Notices.TONES[index],new android.media.AudioAttributes.Builder().setUsage(android.media.AudioAttributes.USAGE_NOTIFICATION).build(),0);if(sound!=null){sound.setVolume(1,1);sound.setOnCompletionListener(MediaPlayer::release);sound.start();}}catch(Exception e){error("Не удалось воспроизвести звук");}}

 void deletePost(JSONObject m){String target=m.optString("peer");dialog().setTitle("Удалить для всех?").setMessage("Сообщение, вложение на сервере и комментарии к этому посту будут удалены.").setNegativeButton("Отмена",null).setPositiveButton("Удалить",(d,w)->task(()->{if(m.optBoolean("out"))ChatService.register(api,vault,m);JSONObject result=api.call("/posts/delete",new JSONObject().put("mid",m.getString("id")).put("room",Conversation.community(target)?Conversation.room(target):""),vault.token());vault.deletion(result);mediaCache.evictAll();runOnUiThread(()->{renderMessages();Toast.makeText(this,result.optBoolean("media_cleanup_pending")?"Пост удалён. Завершаем очистку файла.":"Удалено вместе с вложением на сервере",Toast.LENGTH_LONG).show();});})).show();}
 void deleteRoom(JSONObject room){dialog().setTitle("Удалить «"+room.optString("title")+"»?").setMessage("Все публикации, комментарии и файлы этого сообщества будут удалены для всех участников. Отменить это действие нельзя.").setNegativeButton("Отмена",null).setPositiveButton("Удалить",(d,w)->task(()->{JSONObject r=api.call("/room/delete",new JSONObject().put("room",room.getString("id")),vault.token());vault.deletion(r);runOnUiThread(()->chats());})).show();}
 void animateEnter(View view,int index){if(!Notices.prefs(this).getBoolean("motion",true))return;view.setAlpha(0);view.setTranslationY(dp(12));view.setScaleX(.975f);view.setScaleY(.975f);view.animate().alpha(1).translationY(0).scaleX(1).scaleY(1).setStartDelay(Math.min(index,5)*35L).setDuration(260).setInterpolator(new android.view.animation.DecelerateInterpolator());}
 void focusMode(){NotificationSheet.quiet(this);}
 void capsule(){try{LinearLayout b=col();paragraph(b,"Личная капсула дня — мысли и планы, которые видишь только ты. Сохраняется в зашифрованном хранилище этого аккаунта на телефоне.");space(b,12);EditText note=field(b,"Что хочется сохранить сегодня?",false);note.setSingleLine(false);note.setMinLines(3);String day=new java.text.SimpleDateFormat("yyyy-MM-dd",Locale.ROOT).format(new Date());note.setText(vault.bucket("capsules").optString(day));b.addView(button("Сохранить капсулу ✦",true,()->task(()->{synchronized(vault){vault.bucket("capsules").put(day,note.getText().toString());vault.save();}runOnUiThread(()->Toast.makeText(this,"Капсула сохранена",Toast.LENGTH_SHORT).show());})));space(b,12);JSONObject all=vault.bucket("capsules");all.keys().forEachRemaining(date->{TextView entry=label(date+" · "+all.optString(date),13,MUTED);pad(entry,8);b.addView(entry);});sheet("✦ Капсула дня",b);}catch(Exception e){error(Api.message(e));}}

}
