package chat.oldy;
import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.media.*;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
 int BG,CARD,GREEN,TEXT,MUTED,INK=0xff182416;
 final ExecutorService work=Executors.newSingleThreadExecutor();final Handler ui=new Handler(Looper.getMainLooper());
 Vault vault;Api api;LinearLayout root,content;ScrollView messagesScroll;TextView network,typing;EditText compose;String screen="",chat="",search="",avatarRoom="",mediaTarget="";
 VideoPublish videoPublish;VoiceCapture voice;VoicePlayer voicePlayer;LinearLayout emojiPanel;UiIcon sendKey;int selectedMotion=-1;boolean typingExpanded;String focusAccount="",settingsSection="";
 boolean registeredReceiver,active,checkedUpdate;String backupText;char[] restorePassword;MediaRecorder recorder;File recording;MediaPlayer player;long lastTyping;int filter;Dialog activeSheet;JSONObject replyTo;LinearLayout pinBar,replyBar;boolean light,cyber;ChatDiscovery discovery;boolean showArchive;final android.util.LruCache<String,Bitmap> mediaCache=new android.util.LruCache<String,Bitmap>(32*1024*1024){protected int sizeOf(String key,Bitmap image){return image.getAllocationByteCount();}};final Set<String> loadingImages=new HashSet<>();
 interface Job{void run()throws Exception;}
 final BroadcastReceiver refresh=new BroadcastReceiver(){public void onReceive(Context c,Intent i){if(network!=null)network.setText(I18n.t(ChatService.state));if(screen.equals("chats"))renderChats();if(screen.equals("chat")){try{if(Conversation.community(chat)&&vault.room(Conversation.room(chat))==null){chats();return;}if(Conversation.thread(chat)&&vault.isDeleted(Conversation.post(chat),Conversation.room(chat),"")){openChat("room:"+Conversation.room(chat));return;}}catch(Exception ignored){}renderMessages();}}};
 public void onCreate(Bundle b){super.onCreate(b);api=new Api(this);File[] stale=getCacheDir().listFiles((dir,name)->name.startsWith("voice-")&&name.endsWith(".m4a"));if(stale!=null)for(File f:stale)f.delete();try{vault=ChatService.vault(this);}catch(Exception e){dialog().setTitle(I18n.t("Не удалось открыть историю")).setMessage(I18n.t("Данные сохранены. Попробуйте перезапустить приложение.")).setPositiveButton(I18n.t("Закрыть"),(d,w)->finish()).show();return;}
  if(!vault.token().isEmpty())startChat();
  if(b!=null){if(vault.token().isEmpty())auth(false);else{chats();String restore=b.getString("chat","");if(!restore.isEmpty())openChat(restore);else openFromIntent(getIntent());}}
  else{splash();ui.postDelayed(()->{if(isFinishing()||isDestroyed()||!screen.equals("splash"))return;root.animate().alpha(0f).setDuration(160).withEndAction(()->{if(isFinishing()||isDestroyed())return;if(vault.token().isEmpty())auth(false);else{chats();openFromIntent(getIntent());}}).start();},2500);}
 }
 protected void onSaveInstanceState(Bundle b){super.onSaveInstanceState(b);if(screen.equals("chat"))b.putString("chat",chat);}
 public void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);if(vault!=null&&!vault.token().isEmpty())openFromIntent(i);}
 long shownRevision=-1;final Runnable liveTick=new Runnable(){public void run(){if(!active)return;if(screen.equals("chat")){try{if(Conversation.community(chat)&&vault.room(Conversation.room(chat))==null){chats();return;}if(Conversation.thread(chat)&&vault.isDeleted(Conversation.post(chat),Conversation.room(chat),"")){openChat("room:"+Conversation.room(chat));return;}long revision=vault.messageRevision();if(revision!=shownRevision){shownRevision=revision;renderMessages();}}catch(Exception ignored){}}ui.postDelayed(this,350);}};
 protected void onResume(){super.onResume();if(root instanceof ThemeLayout)((ThemeLayout)root).animateSurface(true);if(vault!=null){ChatService.visibleChat=screen.equals("chat")?chat:"";shownRevision=-1;ui.removeCallbacks(liveTick);ui.post(liveTick);}}
 protected void onPause(){if(root instanceof ThemeLayout)((ThemeLayout)root).animateSurface(false);ui.removeCallbacks(liveTick);ChatService.visibleChat="";super.onPause();}
 final Runnable updateTick=()->{if(active&&!isFinishing()){if(!vault.token().isEmpty())Updates.check(this,false);updateLoop();}};
 void updateLoop(){ui.removeCallbacks(updateTick);ui.postDelayed(updateTick,60000);}
 void openFromIntent(Intent i){Uri link=i.getData();if(link!=null&&"oldy".equals(link.getScheme())&&"comments".equals(link.getHost())){java.util.List<String> parts=link.getPathSegments();if(parts.size()==2&&parts.get(0).matches("[a-f0-9-]{36}")&&parts.get(1).matches("[a-f0-9-]{36}")){openComments(parts.get(0),parts.get(1));return;}}String target=i.getStringExtra("chat");if(target!=null&&!target.isEmpty())openChat(target);}
 protected void onStart(){super.onStart();active=true;IntentFilter f=new IntentFilter("chat.oldy.CHANGED");if(Build.VERSION.SDK_INT>=33)registerReceiver(refresh,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(refresh,f);registeredReceiver=true;if(screen.equals("chat"))ChatService.visibleChat=chat;updateLoop();}
 protected void onStop(){if(voicePlayer!=null)voicePlayer.release();active=false;ui.removeCallbacks(updateTick);ChatService.visibleChat="";if(registeredReceiver){unregisterReceiver(refresh);registeredReceiver=false;}if(recorder!=null)stopRecording(false);if(voice!=null)voice.end(false);super.onStop();}
 public void onBackPressed(){if(screen.equals("settings")&&!settingsSection.isEmpty()){settings();return;}if(screen.equals("videos")||screen.equals("own")){chats();return;}if(screen.equals("chat")&&Conversation.thread(chat)){String r=Conversation.room(chat),post=Conversation.post(chat);openChat("room:"+r);ui.postDelayed(()->jump(post),100);return;}if(screen.equals("chat")||screen.equals("settings")||screen.equals("search")||screen.equals("contacts")||screen.equals("verify")){if(vault.token().isEmpty())auth(false);else chats();}else super.onBackPressed();}
 protected void onDestroy(){if(discovery!=null)discovery.close();ui.removeCallbacksAndMessages(null);work.shutdownNow();super.onDestroy();}
 void colors(){String theme=Notices.prefs(this).getString("theme","dark");light=theme.equals("light");cyber=theme.equals("cyber");BG=light?0xfff7f9fc:0xff111720;CARD=light?0xffffffff:0xff202a37;GREEN=light?0xffb8dbff:0xffa0ceff;TEXT=light?0xff19283d:0xfff0f5ff;MUTED=light?0xff718098:0xff9cacbf;INK=0xff173959;if(cyber){BG=0xff090c18;CARD=0xff171a30;GREEN=0xff5cf5ef;TEXT=0xfff1f2ff;MUTED=0xffb1a8c8;INK=0xff101b2b;}getWindow().setStatusBarColor(Color.TRANSPARENT);getWindow().setNavigationBarColor(Color.TRANSPARENT);if(Build.VERSION.SDK_INT>=29){getWindow().setStatusBarContrastEnforced(false);getWindow().setNavigationBarContrastEnforced(false);}if(Build.VERSION.SDK_INT>=30)getWindow().setDecorFitsSystemWindows(false);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LAYOUT_STABLE|View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN|View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION|(light?View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR:0));if(Build.VERSION.SDK_INT>=30){WindowInsetsController bars=getWindow().getInsetsController();if(bars!=null){int mask=WindowInsetsController.APPEARANCE_LIGHT_STATUS_BARS|WindowInsetsController.APPEARANCE_LIGHT_NAVIGATION_BARS;bars.setSystemBarsAppearance(light?mask:0,mask);}}}
 AlertDialog.Builder dialog(){return new AlertDialog.Builder(this,Notices.prefs(this).getString("theme","dark").equals("light")?android.R.style.Theme_Material_Light_Dialog_Alert:android.R.style.Theme_Material_Dialog_Alert);}
 int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
 GradientDrawable shape(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
 LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
 LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 void pad(View v,int p){v.setPadding(dp(p),dp(p),dp(p),dp(p));}
 void space(LinearLayout l,int h){l.addView(new View(this),new LinearLayout.LayoutParams(1,dp(h)));}
 TextView label(String s,int size,int color){TextView v=new TextView(this);v.setText(s);if(cyber&&size<=13)v.setTypeface(Typeface.create("monospace",Typeface.NORMAL));v.setTextSize(size);v.setTextColor(color);return v;}
 TextView button(String s,boolean primary,Runnable action){TextView v=label(s,15,primary?INK:TEXT);v.setGravity(Gravity.CENTER);v.setTypeface(null,1);v.setIncludeFontPadding(false);v.setPadding(dp(13),dp(8),dp(13),dp(8));v.setMinHeight(dp(40));v.setBackground(shape(primary?GREEN:CARD,18));v.setContentDescription(s);v.setOnClickListener(w->{if(activeSheet!=null){activeSheet.dismiss();activeSheet=null;}action.run();});return v;}
 void base(String s){if(voicePlayer!=null)voicePlayer.release();if(voice!=null&&voice.running)voice.end(false);if(activeSheet!=null){activeSheet.dismiss();activeSheet=null;}emojiPanel=null;sendKey=null;screen=s;ChatService.visibleChat=s.equals("chat")&&active?chat:"";colors();root=s.equals("splash")?col():new ThemeLayout(this,light,cyber);if(s.equals("splash"))root.setBackgroundColor(BG);root.setPadding(dp(16),dp(10),dp(16),dp(10));root.setOnApplyWindowInsetsListener((v,insets)->{int left,top,right,bottom;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets x=insets.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.displayCutout()|WindowInsets.Type.ime());left=x.left;top=x.top;right=x.right;bottom=x.bottom;}else{left=insets.getSystemWindowInsetLeft();top=insets.getSystemWindowInsetTop();right=insets.getSystemWindowInsetRight();bottom=insets.getSystemWindowInsetBottom();}v.setPadding(dp(16)+left,dp(10)+top,dp(16)+right,dp(10)+bottom);return insets;});setContentView(root);root.requestApplyInsets();network=null;typing=null;}
 void refreshAppearance(){if(screen.equals("chat"))openChat(chat);else if(screen.equals("settings"))settings();else if(screen.equals("chats"))chats();}
 GradientDrawable glass(int radius){GradientDrawable d=shape(light?0xe8faffff:0xe6172639,radius);d.setStroke(dp(1),light?0xbfffffff:0x80649db7);return d;}

 View iconButton(String symbol,String description,Runnable action){UiIcon v=new UiIcon(this,symbol,light?0xff1469a1:0xff9ae6ff);v.setContentDescription(description);GradientDrawable bg=shape(light?0xffdef0ff:0xff1d3549,16);bg.setStroke(dp(1),light?0xffbfdcf4:0xff356783);v.setBackground(bg);v.setOnClickListener(x->action.run());return v;}
 void title(String s,Runnable back){LinearLayout r=row();r.setBackground(glass(23));pad(r,5);if(back!=null){View b=iconButton("back",I18n.t("Назад"),back);r.addView(b,new LinearLayout.LayoutParams(dp(44),dp(46)));}TextView t=label(s,25,TEXT);t.setTypeface(null,1);t.setPadding(dp(12),0,0,0);r.addView(t,new LinearLayout.LayoutParams(0,dp(56),1));t.setGravity(Gravity.CENTER_VERTICAL);root.addView(r);space(root,12);}
 void paragraph(LinearLayout l,String s){TextView t=label(s,13,MUTED);t.setLineSpacing(dp(3),1);l.addView(t);}
 EditText field(LinearLayout l,String hint,boolean password){EditText e=new EditText(this);e.setSingleLine(true);e.setTextSize(16);e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setHint(hint);pad(e,15);e.setBackground(shape(CARD,17));e.setInputType(password?129:1);l.addView(e,new LinearLayout.LayoutParams(-1,dp(56)));space(l,10);return e;}
 void task(Job job){work.execute(()->{try{job.run();}catch(Exception e){runOnUiThread(()->error(Api.message(e)));}});}
 void error(String s){if(!isFinishing())dialog().setTitle(I18n.t("OldЫ Chat")).setMessage(s).setPositiveButton(I18n.t("Понятно"),null).show();}
 Art art(String key,int size,LinearLayout l){Art a=new Art(this,key);l.addView(a,new LinearLayout.LayoutParams(dp(size),dp(size)));return a;}
 void splash(){base("splash");root.setGravity(Gravity.CENTER);root.setBackground(new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{0xff0d1228,0xff172851,0xff123443}));getWindow().getDecorView().setSystemUiVisibility(0);getWindow().setStatusBarColor(0xff142337);getWindow().setNavigationBarColor(0xff103b4d);WelcomeArt art=new WelcomeArt(this);int size=Math.min(dp(300),getResources().getDisplayMetrics().widthPixels-dp(48));root.addView(art,new LinearLayout.LayoutParams(size,size));space(root,22);TextView h=label(I18n.t("Добро пожаловать\nв OldЫ Chat"),30,0xfff0f8ff);h.setGravity(Gravity.CENTER);h.setTypeface(Typeface.create("sans-serif-condensed",Typeface.BOLD));h.setLineSpacing(dp(3),1);root.addView(h);space(root,15);TextView sub=label(I18n.t("Общайтесь без цензуры.\nГоворите о том, что вам интересно."),15,0xffb8d5e8);sub.setGravity(Gravity.CENTER);sub.setLineSpacing(dp(5),1);root.addView(sub);if(android.animation.ValueAnimator.areAnimatorsEnabled()){h.setAlpha(0);h.setTranslationY(dp(10));h.animate().alpha(1).translationY(0).setStartDelay(140).setDuration(450).start();sub.setAlpha(0);sub.animate().alpha(1).setStartDelay(400).setDuration(400).start();}}
 void auth(boolean signup){EmailAuth.show(this,signup);}
 void verifySignup(String nick,String password,String name,String email,String ticket){base("verify");title(I18n.t("Подтверди почту"),()->auth(true));paragraph(root,I18n.t("Мы отправили шестизначный код на ")+email+I18n.t(". До подтверждения аккаунт не создаётся."));space(root,18);EditText code=field(root,I18n.t("Код из письма"),false);code.setInputType(2);root.addView(button(I18n.t("Подтвердить и создать аккаунт"),true,()->{String value=code.getText().toString().trim();if(!value.matches("[0-9]{6}")){error(I18n.t("Введи шесть цифр из письма"));return;}task(()->{JSONObject id=Crypto.identity();JSONObject body=new JSONObject().put("nick",nick).put("password",Crypto.hex(Crypto.random(32))).put("name",name).put("email",email).put("email_only",true).put("ticket",ticket).put("code",value).put("enc",id.getString("enc")).put("sig",id.getString("sig"));loginAccount(nick,password,new JSONObject().put("reply",api.call("/register",body,"")).put("identity",id));});}));space(root,12);root.addView(button(I18n.t("Прислать новый код"),false,()->task(()->{JSONObject next=api.call("/signup/request",new JSONObject().put("email",email).put("nick",nick),"");runOnUiThread(()->verifySignup(nick,password,name,email,next.optString("ticket")));})));}
 void loginAccount(String login,String password,JSONObject signup)throws Exception{
  JSONObject reply=signup==null?api.call("/login",new JSONObject().put("nick",login).put("password",password),""):signup.getJSONObject("reply"),user=reply.getJSONObject("user");
  Vault next=new Vault(this,user.getString("nick"),signup!=null);if(signup!=null)next.data.put("identity",signup.getJSONObject("identity"));
  if(!Crypto.fingerprint(user).equals(Crypto.fingerprint(next.identity()))){String blob=api.call("/key-backup",null,reply.getString("token")).getString("backup");next.restoreKeys(Crypto.importBackup(blob,password.toCharArray()),user);}
  next.account(reply);next.rooms(api.call("/rooms",null,next.token()).getJSONArray("rooms"));
  try{api.call("/key-backup",new JSONObject().put("backup",Crypto.exportBackup(next.keyBackup(),password.toCharArray())),next.token());}catch(Exception ignored){}
  runOnUiThread(()->{if(ChatService.instance!=null)ChatService.instance.running=false;stopService(new Intent(this,ChatService.class));ChatService.shared=next;vault=next;mediaCache.evictAll();search="";filter=0;chat="";chats();startChat();});
 }
 void logoutAccount(){try{if(!vault.copy().optBoolean("email_verified")){emailSettings();error(I18n.t("Подтверди почту перед выходом, чтобы затем войти по коду."));return;}}catch(Exception e){error(Api.message(e));return;}if(LiveCall.current!=null)LiveCall.current.end(I18n.t("Звонок завершён"),true);CreatorVideo.cancel=true;task(()->{Vault old=vault;try{api.call("/logout",new JSONObject(),old.token());}finally{if(ChatService.instance!=null)ChatService.instance.running=false;stopService(new Intent(this,ChatService.class));synchronized(old){old.data.remove("token");old.save();}Vault empty=Vault.guest(this);ChatService.shared=empty;runOnUiThread(()->{getSystemService(NotificationManager.class).cancelAll();vault=empty;chat="";search="";filter=0;mediaCache.evictAll();auth(false);});}});}
 void startChat(){final Vault owner=vault;work.execute(()->{try{JSONObject me=api.call("/me",null,owner.token());owner.profile(me);if(me.optBoolean("email_verified"))api.call("/account/email-only",new JSONObject(),owner.token());}catch(Exception ignored){}});if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},10);startForegroundService(new Intent(this,ChatService.class));}
 void chats(){base("chats");LinearLayout header=row();header.setBackground(glass(24));pad(header,6);header.addView(button("☰",false,()->menu()),new LinearLayout.LayoutParams(dp(46),dp(46)));BrandMark brand=new BrandMark(this,light);header.addView(brand,new LinearLayout.LayoutParams(0,dp(54),1));header.addView(button("＋",true,()->findPeer()));root.addView(header);network=label(I18n.t(ChatService.state),11,MUTED);network.setPadding(dp(60),0,0,0);root.addView(network);TextView quietStatus=label("",11,light?0xff286ca6:0xff8adaff);quietStatus.setVisibility(View.GONE);quietStatus.setPadding(dp(60),dp(6),0,0);quietStatus.setOnClickListener(v->focusMode());root.addView(quietStatus);quietStatus.post(()->NotificationSheet.bindQuiet(this,quietStatus));space(root,18);
  EditText query=field(root,I18n.t("Поиск чатов"),false);query.setText(search);query.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){search=s.toString();if(discovery==null)discovery=new ChatDiscovery(MainActivity.this);discovery.changed();}public void afterTextChanged(Editable e){}});
  LinearLayout tabs=row();String[] names={I18n.t("Все"),I18n.t("Личные"),I18n.t("Группы"),I18n.t("Каналы")};for(int i=0;i<names.length;i++){final int at=i;TextView t=button(names[i],filter==i,()->{filter=at;chats();});t.setTextSize(12);tabs.addView(t,new LinearLayout.LayoutParams(0,dp(42),1));}root.addView(tabs);space(root,14);
  ScrollView scroll=new ScrollView(this);content=col();scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));renderChats();if(discovery==null)discovery=new ChatDiscovery(this);discovery.changed();space(root,10);
  SettingsHome.navigation(this,0);campaign();if(!checkedUpdate){checkedUpdate=true;ui.postDelayed(()->Updates.check(this,false),2200);}
 }
 JSONObject last(JSONArray a,String n){for(int i=a.length()-1;i>=0;i--){JSONObject m=a.optJSONObject(i);if(m!=null&&!m.optString("kind").equals("control")&&m.optString("peer").equals(n))return m;}return null;}
 String clock(long t){return new java.text.SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date(t));}
 void renderChats(){if(!screen.equals("chats")||content==null)return;content.removeAllViews();try{
  JSONObject d=vault.copy(),contacts=d.getJSONObject("contacts"),rooms=d.getJSONObject("rooms");JSONArray messages=d.getJSONArray("messages");List<String> items=new ArrayList<>();contacts.keys().forEachRemaining(items::add);rooms.keys().forEachRemaining(k->items.add("room:"+k));
  items.sort((a,b)->{JSONObject aa=last(messages,a),bb=last(messages,b);return Long.compare(bb==null?0:bb.optLong("time"),aa==null?0:aa.optLong("time"));});int total=0;Set<String> shown=new HashSet<>();
  for(String id:items){boolean group=id.startsWith("room:");JSONObject u=group?rooms.getJSONObject(id.substring(5)):contacts.getJSONObject(id);String name=u.optString(group?"title":"name",id),kind=group?u.optString("kind"):"personal";
   if(filter==1&&group||filter==2&&!kind.equals("group")||filter==3&&!kind.equals("channel"))continue;
   if(vault.hiddenChat(id))continue;if(!ChatDiscovery.matches(name+" "+id+" "+u.optString("handle"),search))continue;if(vault.archived(id)!=showArchive)continue;total++;shown.add(id);
   LinearLayout item=row();pad(item,12);item.setBackground(shape(CARD,23));art(u.optString("avatar","preset:0"),53,item);LinearLayout detail=col();detail.setPadding(dp(12),0,dp(6),0);TextView title=label((kind.equals("channel")?"◈ ":kind.equals("group")?"♧ ":"")+name,16,TEXT);title.setTypeface(null,1);title.setSingleLine(true);title.setEllipsize(TextUtils.TruncateAt.END);detail.addView(title);space(detail,5);JSONObject last=last(messages,id);TextView preview=label(last==null?(group?"@"+u.optString("handle")+" · "+(kind.equals("channel")?I18n.t("канал"):I18n.t("группа")):"@"+id):Payload.preview(last),13,MUTED);preview.setSingleLine(true);preview.setEllipsize(TextUtils.TruncateAt.END);detail.addView(preview);item.addView(detail,new LinearLayout.LayoutParams(0,-2,1));item.addView(label(last==null?"":clock(last.optLong("time")),10,MUTED));item.setOnClickListener(v->openChat(id));item.setOnLongClickListener(v->{chatListMenu(id);return true;});content.addView(item,new LinearLayout.LayoutParams(-1,dp(85)));space(content,9);
  }
  if(total==0&&search.trim().isEmpty()){if(showArchive){paragraph(content,I18n.t("В архиве пока нет чатов"));return;}space(content,32);Art a=new Art(this,"mascot");LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(175),dp(175));p.gravity=Gravity.CENTER_HORIZONTAL;content.addView(a,p);space(content,18);TextView empty=label(I18n.t("Скажи своим «привет»"),21,TEXT);empty.setGravity(Gravity.CENTER);content.addView(empty);space(content,10);paragraph(content,I18n.t("Нажми ＋ и найди друга по нику.\nВ меню слева можно создать группу или канал."));}
 if(discovery!=null)discovery.render(d,shown);
 }catch(Exception e){error(Api.message(e));}}
 void chatListMenu(String target){ChatActions.show(this,target);}
 void menu(){profileMenu();}
 void findPeer(){
  base("search");title(I18n.t("Поиск людей"),()->chats());ContactDiscovery.tabs(this,false);
  EditText query=field(root,I18n.t("Имя, @ник или название"),false);query.setContentDescription(I18n.t("Поиск людей, групп и каналов"));
  TextView state=label(I18n.t("Люди, группы и каналы"),12,MUTED);root.addView(state);space(root,16);
  ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);LinearLayout results=col();scroll.addView(results);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));searchEmpty(results,false);
  final Vault account=vault;final View searchRoot=root;final int[] generation={0};
  query.addTextChangedListener(new TextWatcher(){Runnable pending;public void beforeTextChanged(CharSequence t,int a,int c,int f){}public void afterTextChanged(Editable e){}
   public void onTextChanged(CharSequence text,int a,int before,int count){int sequence=++generation[0];if(pending!=null)ui.removeCallbacks(pending);String q=text.toString().trim();results.removeAllViews();
    if(q.isEmpty()){state.setText(q.isEmpty()?I18n.t("Люди, группы и каналы"):I18n.t("Введите минимум 2 символа"));searchEmpty(results,false);return;}
    state.setText(I18n.t("Поиск…"));ProgressBar progress=new ProgressBar(MainActivity.this);results.addView(progress,new LinearLayout.LayoutParams(dp(32),dp(32)));
    pending=()->work.execute(()->{try{if(vault!=account||root!=searchRoot)return;JSONObject found=api.call("/search?q="+java.net.URLEncoder.encode(q,"UTF-8"),null,account.token());
     runOnUiThread(()->{if(sequence!=generation[0]||root!=searchRoot||vault!=account)return;results.removeAllViews();JSONArray people=found.optJSONArray("users"),rooms=found.optJSONArray("rooms");int total=people.length()+rooms.length();state.setText(total==0?I18n.t("Ничего не найдено"):I18n.t("Результаты · ")+total);if(total==0)searchEmpty(results,true);
      for(int i=0;i<people.length();i++){JSONObject user=people.optJSONObject(i);View card=searchCard(user.optString("avatar"),user.optString("name"),"@"+user.optString("nick"),I18n.t("ЧЕЛОВЕК"),()->task(()->{if(vault!=account)return;account.pin(user);runOnUiThread(()->{if(vault==account)openChat(user.optString("nick"));});}));results.addView(card);space(results,10);animateEnter(card,i);}
      for(int i=0;i<rooms.length();i++){JSONObject r=rooms.optJSONObject(i);String type=r.optString("kind").equals("channel")?I18n.t("КАНАЛ"):I18n.t("ГРУППА");View card=searchCard(r.optString("avatar"),r.optString("title"),"@"+r.optString("handle"),type,()->{
       Runnable open=()->task(()->{if(vault!=account)return;JSONObject room=api.call(r.optBoolean("joined")?"/room/"+r.optString("id"):"/room/join",r.optBoolean("joined")?null:new JSONObject().put("id",r.optString("id")),account.token());account.putRoom(room);runOnUiThread(()->{if(vault==account)openChat("room:"+r.optString("id"));});});
       if(r.optBoolean("joined"))open.run();else{LinearLayout box=col();paragraph(box,I18n.t("Присоединиться к @")+r.optString("handle")+"?");space(box,14);box.addView(button(I18n.t("Присоединиться"),true,open));sheet(r.optString("title"),box);}
      });results.addView(card);space(results,10);animateEnter(card,i);}
     });
    }catch(Exception ex){runOnUiThread(()->{if(sequence==generation[0]&&root==searchRoot){results.removeAllViews();state.setText(I18n.t("Не удалось выполнить поиск"));paragraph(results,Api.message(ex));}});}});ui.postDelayed(pending,420);
   }
  });
 }
 void searchEmpty(LinearLayout results,boolean missing){LinearLayout empty=col();empty.setGravity(Gravity.CENTER);empty.setPadding(dp(22),dp(36),dp(22),dp(30));
  LinearLayout faces=row();faces.setGravity(Gravity.CENTER);art("preset:3",52,faces);Art middle=art("preset:0",76,faces);art("preset:7",52,faces);empty.addView(faces);space(empty,22);
  TextView title=label(missing?I18n.t("Проверьте имя или @ник"):I18n.t("Введите имя или @ник"),18,TEXT);title.setTypeface(null,1);title.setGravity(Gravity.CENTER);empty.addView(title);space(empty,8);TextView hint=label(missing?I18n.t("Можно искать и по части названия"):I18n.t("Здесь появятся результаты поиска"),13,MUTED);hint.setGravity(Gravity.CENTER);empty.addView(hint);results.addView(empty,new LinearLayout.LayoutParams(-1,-2));animateEnter(empty,0);
 }
 View searchCard(String avatar,String title,String subtitle,String badge,Runnable action){LinearLayout card=row();pad(card,14);GradientDrawable bg=shape(CARD,22);bg.setStroke(dp(1),light?0xffd9e5f3:0xff35475f);card.setBackground(bg);art(avatar,56,card);LinearLayout words=col();words.setPadding(dp(12),0,dp(8),0);TextView name=label(title,17,TEXT);name.setTypeface(null,1);words.addView(name);space(words,5);words.addView(label(subtitle,13,MUTED));space(words,5);words.addView(label(badge,9,light?0xff4d74a3:0xffb0b4fd));card.addView(words,new LinearLayout.LayoutParams(0,-2,1));card.addView(label("›",27,MUTED));card.setOnClickListener(v->action.run());return card;}
 void createRoom(String kind){LinearLayout box=col();pad(box,18);EditText title=field(box,kind.equals("group")?I18n.t("Название группы"):I18n.t("Название канала"),false),handle=field(box,I18n.t("@адрес · например oldy_news"),false);TextView status=label(I18n.t("Проверим, свободен ли адрес"),12,MUTED);box.addView(status);space(box,12);watchHandle(handle,status,"");EditText members=field(box,I18n.t("Ники участников через запятую · необязательно"),false);Switch pub=new Switch(this);pub.setText(I18n.t("Публичный · виден в поиске"));pub.setTextColor(TEXT);pub.setChecked(true);box.addView(pub);space(box,12);paragraph(box,kind.equals("channel")?I18n.t("Публикует владелец. Подписчики читают, ставят реакции и обсуждают каждый пост в комментариях."):I18n.t("Участники публикуют, отвечают и ставят реакции. Управляет владелец."));AlertDialog d=dialog().setTitle(kind.equals("group")?I18n.t("Новая группа"):I18n.t("Новый канал")).setView(box).setNegativeButton(I18n.t("Отмена"),null).setPositiveButton(I18n.t("Создать"),null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String t=title.getText().toString(),h=handle.getText().toString().trim().replace("@","").toLowerCase(Locale.ROOT),n=members.getText().toString();boolean isPublic=pub.isChecked();if(t.trim().isEmpty()||!h.matches("[a-z0-9_]{3,24}")){error(I18n.t("Укажи название и @адрес: 3–24 латинских символа, цифры или _"));return;}d.getButton(-1).setEnabled(false);task(()->{try{JSONObject room=api.call("/room/create",new JSONObject().put("title",t).put("kind",kind).put("handle",h).put("public",isPublic).put("members",nickList(n)),vault.token());vault.putRoom(room);runOnUiThread(()->{d.dismiss();openChat("room:"+room.optString("id"));});}finally{runOnUiThread(()->d.getButton(-1).setEnabled(true));}});}));d.show();}
 void watchHandle(EditText input,TextView status,String original){input.setInputType(145);input.addTextChangedListener(new TextWatcher(){Runnable pending;public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void afterTextChanged(Editable e){}public void onTextChanged(CharSequence text,int a,int b,int c){if(pending!=null)ui.removeCallbacks(pending);String h=text.toString().trim().replace("@","").toLowerCase(Locale.ROOT);if(h.equals(original)){status.setText(I18n.t("Текущий адрес"));return;}if(!h.matches("[a-z0-9_]{3,24}")){status.setText(I18n.t("3–24 латинских символа, цифры или _"));return;}status.setText(I18n.t("Проверяем @")+h+"…");pending=()->work.execute(()->{try{JSONObject r=api.call("/handles?handle="+h,null,"");runOnUiThread(()->{if(input.getText().toString().trim().replace("@","").equalsIgnoreCase(h)){status.setText(r.optBoolean("available")?"✓ @"+h+I18n.t(" свободен"):I18n.t("Этот адрес уже занят"));status.setTextColor(r.optBoolean("available")?(light?0xff24765e:0xff8cddc0):0xffe57e8c);}});}catch(Exception ex){runOnUiThread(()->status.setText(I18n.t("Не удалось проверить. Проверь подключение.")));}});ui.postDelayed(pending,450);}});}
 JSONArray nickList(String s)throws Exception{JSONArray a=new JSONArray();for(String n:s.toLowerCase(Locale.ROOT).split("[,\\s]+")){n=n.replace("@","").trim();if(n.isEmpty())continue;if(!n.matches("[a-z0-9_]{3,24}"))throw new Exception(I18n.t("Проверь ники участников"));a.put(n);}return a;}
 void openChat(String target){final Vault account=vault;selectedMotion=-1;typingExpanded=false;chat=target;replyTo=null;compose=null;base("chat");try{
  boolean group=Conversation.community(target);JSONObject u=group?vault.room(Conversation.room(target)):vault.peer(target);if(u==null){chats();return;}
  LinearLayout head=row();head.setBackground(glass(24));pad(head,7);head.addView(iconButton("back",I18n.t("Назад"),()->onBackPressed()),new LinearLayout.LayoutParams(dp(44),dp(48)));Art avatar=art(u.optString("avatar","preset:0"),42,head);avatar.setOnClickListener(v->chatInfo());LinearLayout info=col();info.setPadding(dp(9),0,dp(4),0);TextView title=label(Conversation.thread(target)?I18n.t("Комментарии"):u.optString(group?"title":"name",target),20,TEXT);title.setTypeface(null,1);title.setSingleLine(true);title.setEllipsize(TextUtils.TruncateAt.END);title.setOnClickListener(v->chatInfo());info.addView(title);typing=label(group?"@"+u.optString("handle")+" · "+audience(u):"@"+target,10,MUTED);info.addView(typing);head.addView(info,new LinearLayout.LayoutParams(0,dp(52),1));if(!group){View callKey=iconButton("call",I18n.t("Позвонить через интернет"),()->LiveCall.dial(this,target));callKey.setContentDescription(I18n.t("Позвонить через интернет"));head.addView(callKey,new LinearLayout.LayoutParams(dp(40),dp(44)));}Art companion=art("mascot",62,head);companion.setLayoutParams(new LinearLayout.LayoutParams(dp(50),dp(52)));companion.setOnClickListener(v->Toast.makeText(this,I18n.t("Старый геймер на связи 🎮"),Toast.LENGTH_SHORT).show());root.addView(head);space(root,8);if(Conversation.thread(target)){JSONObject post=vault.message(Conversation.post(target));String preview=post==null?I18n.t("Вернуться к публикации"):post.optString("text",Payload.preview(post));TextView context=label(I18n.t("↳ К публикации · ")+preview,12,MUTED);context.setMaxLines(2);context.setEllipsize(TextUtils.TruncateAt.END);pad(context,10);context.setBackground(shape(CARD,12));context.setOnClickListener(v->onBackPressed());root.addView(context,new LinearLayout.LayoutParams(-1,-2));space(root,8);}pinBar=col();root.addView(pinBar);
  messagesScroll=new ScrollView(this);messagesScroll.setFillViewport(true);messagesScroll.setBackgroundColor(Color.TRANSPARENT);content=col();content.setPadding(dp(8),dp(4),dp(8),dp(12));messagesScroll.addView(content);root.addView(messagesScroll,new LinearLayout.LayoutParams(-1,0,1));space(root,8);
  boolean canWrite=Conversation.thread(target)||(!group&&!vault.isBlocked(target))||group&&!u.optString("kind").equals("channel")||u.optString("owner").equals(vault.nick());
  replyBar=col();root.addView(replyBar);emojiPanel=col();emojiPanel.setVisibility(View.GONE);root.addView(emojiPanel);if(canWrite){LinearLayout input=row();input.setGravity(Gravity.BOTTOM);input.setBackground(glass(25));TextView plus=button("＋",false,()->attachments());input.addView(plus,new LinearLayout.LayoutParams(dp(40),dp(46)));input.addView(button("☺",false,()->emojis()),new LinearLayout.LayoutParams(dp(41),dp(46)));compose=new EditText(this);compose.setHint(Conversation.thread(target)?I18n.t("Комментарий…"):group?I18n.t("Публикация…"):I18n.t("Сообщение…"));compose.setTextColor(TEXT);compose.setHintTextColor(MUTED);compose.setTextSize(15);compose.setMinLines(1);compose.setMaxLines(6);compose.setMinHeight(dp(46));compose.setInputType(1|131072|16384);pad(compose,10);compose.setBackground(shape(CARD,20));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,-2,1);cp.setMargins(dp(4),0,dp(4),0);input.addView(compose,cp);sendKey=new UiIcon(this,"mic",INK);sendKey.setBackground(shape(GREEN,18));sendKey.setContentDescription(I18n.t("Удерживай для записи голосового"));sendKey.setOnTouchListener(new VoiceGesture(this));sendKey.setOnClickListener(v->{if(compose!=null&&!compose.getText().toString().trim().isEmpty()){sendKey.animate().rotationBy(35).scaleX(.72f).scaleY(.72f).setDuration(100).withEndAction(()->{sendText();if(sendKey!=null)sendKey.animate().rotation(0).scaleX(1).scaleY(1).setDuration(170);});}});input.addView(sendKey,new LinearLayout.LayoutParams(dp(48),dp(48)));root.addView(input);compose.setText(vault.draft(target));sendKey.symbol(compose.getText().toString().trim().isEmpty()?"mic":"send");
   compose.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void afterTextChanged(Editable e){String value=e.toString();if(sendKey!=null){sendKey.symbol(value.trim().isEmpty()?"mic":"send");sendKey.setContentDescription(value.trim().isEmpty()?I18n.t("Удерживай для записи голосового"):I18n.t("Отправить сообщение"));}boolean expanded=value.length()>70||value.contains("\n");if(expanded!=typingExpanded){typingExpanded=expanded;compose.setMinimumHeight(dp(expanded?94:46));}work.execute(()->{try{account.draft(target,value);}catch(Exception ignored){}});}public void onTextChanged(CharSequence s,int a,int before,int count){if(!group&&System.currentTimeMillis()-lastTyping>4000){lastTyping=System.currentTimeMillis();work.execute(()->{try{api.call("/typing",new JSONObject().put("to",target),vault.token());}catch(Exception ignored){}});}}});
  }else if(!group)root.addView(button(I18n.t("Разблокировать собеседника"),false,()->setBlock(target,false)));else paragraph(root,I18n.t("◈ Публикации владельца · нажми на пост, чтобы поставить реакцию"));
  renderMessages();if(voice!=null)voice.showPending();animateEnter(messagesScroll,0);if(!group)pollTyping(target);else work.execute(()->{try{ChannelHistory.syncRoom(api,account,Conversation.room(target),8);runOnUiThread(()->{if(vault==account&&chat.equals(target))renderMessages();});}catch(Exception pending){}});
 }catch(Exception e){error(Api.message(e));}}
 void pollTyping(String target){ui.postDelayed(()->{if(!active||!screen.equals("chat")||!chat.equals(target))return;work.execute(()->{try{JSONObject p=api.call("/typing/"+target,null,vault.token());runOnUiThread(()->{if(screen.equals("chat")&&chat.equals(target)&&typing!=null)typing.setText(p.optBoolean("typing")?I18n.t("печатает…"):"@"+target);});}catch(Exception ignored){}});pollTyping(target);},4500);}
 void sendText(){if(compose==null)return;String text=compose.getText().toString().trim();if(text.isEmpty())return;if(Crypto.bytes(text).length>10000){error(I18n.t("Сообщение слишком длинное"));return;}try{JSONObject p=new JSONObject().put("kind","text").put("text",text);if(selectedMotion>=0){p.put("animated",selectedMotion);if(text.equals(MotionEmoji.GLYPHS[selectedMotion]))p.put("kind","sticker").put("sticker",selectedMotion);selectedMotion=-1;}if(replyTo!=null)p.put("reply",new JSONObject().put("id",replyTo.optString("id")).put("author",replyTo.optBoolean("out")?vault.nick():replyTo.optString("from")).put("text",Payload.preview(replyTo).substring(0,Math.min(140,Payload.preview(replyTo).length()))));send(p,null);}catch(Exception e){error(Api.message(e));}}
 void prepareRoom(String target)throws Exception{if(!Conversation.community(target))return;JSONObject r=api.call("/room/"+Conversation.room(target),null,vault.token());vault.putRoom(r);JSONArray a=r.getJSONArray("members");for(int i=0;i<a.length();i++){String n=a.getString(i);if(!n.equals(vault.nick()))vault.pin(api.call("/user/"+n,null,vault.token()));}}
 void send(JSONObject p,String local){String target=chat;boolean control=p.optString("kind").equals("control");String draft=compose==null?"":compose.getText().toString();if(!control&&compose!=null){compose.setText("");replyTo=null;replyBar.removeAllViews();}task(()->{try{prepareRoom(target);if(!Conversation.community(target))vault.pin(api.call("/user/"+target,null,vault.token()));if(!control&&!p.optString("text").isEmpty()){JSONObject link=LinkCards.describe(p.optString("text"));if(link!=null)p.put("link",link);}String mid=vault.queuePayload(target,p,local);if(target.startsWith("room:")&&!control){JSONObject r=vault.room(Conversation.room(target));if(r!=null&&r.optString("kind").equals("channel"))try{api.call("/threads",new JSONObject().put("room",r.optString("id")).put("post",mid),vault.token());}catch(Exception deferred){}}runOnUiThread(()->{if(chat.equals(target))renderMessages();});}catch(Exception e){if(!control)runOnUiThread(()->{if(compose!=null&&chat.equals(target))compose.setText(draft);});throw e;}});}

 void renderMessages(){if(!screen.equals("chat"))return;boolean bottom=messagesScroll.getChildCount()==0||messagesScroll.getScrollY()+messagesScroll.getHeight()+dp(100)>=content.getHeight();int scrollY=messagesScroll.getScrollY();content.removeAllViews();try{if(voicePlayer!=null&&!voicePlayer.id.isEmpty()&&vault.message(voicePlayer.id)==null)voicePlayer.release();boolean group=chat.startsWith("room:");JSONObject room=group?vault.room(Conversation.room(chat)):null;renderPin();JSONArray a=vault.copy().getJSONArray("messages");java.util.List<JSONObject> ordered=new java.util.ArrayList<>();for(int i=0;i<a.length();i++)ordered.add(a.getJSONObject(i));ordered.sort(java.util.Comparator.comparingLong(m->m.optLong("time")));String date="";for(JSONObject m:ordered){if(!m.optString("peer").equals(chat)||m.optString("kind").equals("control"))continue;String day=new java.text.SimpleDateFormat("d MMMM",I18n.locale()).format(new Date(m.optLong("time")));if(!day.equals(date)){date=day;LinearLayout dayRow=row();dayRow.setGravity(Gravity.CENTER);TextView d=label(day,11,MUTED);d.setGravity(Gravity.CENTER);d.setPadding(dp(12),dp(5),dp(12),dp(5));d.setBackground(shape(light?0xdfffffff:0xd0253446,20));dayRow.addView(d);space(content,8);content.addView(dayRow);space(content,12);}boolean out=m.optBoolean("out");LinearLayout line=row();line.setGravity(out&&!group?Gravity.RIGHT:Gravity.LEFT);LinearLayout bubble=col();bubble.setMinimumWidth(dp(76));pad(bubble,12);int fill=group?CARD:out?(light?0xffe0eeff:0xff294461):CARD;GradientDrawable border=shape(fill,group?18:20);if(group)border.setStroke(dp(1),light?0xffccd9e9:0xff42556b);bubble.setBackground(border);bubble.setElevation(dp(group?2:0));bubble.setTag(m.optString("id"));int color=TEXT;
   if(group||Conversation.thread(chat)){LinearLayout authorRow=row();String author=room!=null&&room.optString("kind").equals("channel")?room.optString("title"):"@"+(out?vault.nick():m.optString("from"));TextView authorView=label(author,13,light?0xff376daf:0xffa0ceff);authorView.setTypeface(null,1);authorView.setSingleLine(true);authorView.setEllipsize(TextUtils.TruncateAt.END);authorRow.addView(authorView,new LinearLayout.LayoutParams(0,-2,1));TextView more=label("⋯",21,MUTED);more.setPadding(dp(8),0,0,0);more.setOnClickListener(v->messageMenu(m));authorRow.addView(more);bubble.addView(authorRow);space(bubble,8);}
   JSONObject reply=m.optJSONObject("reply");if(reply!=null){TextView quote=label("↳ @"+reply.optString("author")+"\n"+reply.optString("text"),12,MUTED);quote.setMaxLines(3);pad(quote,9);quote.setBackground(shape(light?0xffeff4fa:0xff172330,9));quote.setOnClickListener(v->jump(reply.optString("id")));bubble.addView(quote,new LinearLayout.LayoutParams(-1,-2));space(bubble,8);}
   String kind=m.optString("kind","text");if(kind.equals("sticker")){if(m.optInt("sticker")>=100){bubble.addView(new GamerSticker(this,m.optInt("sticker")-100),new LinearLayout.LayoutParams(dp(150),dp(150)));}else if(m.has("animated")){MotionEmoji animated=new MotionEmoji(this,m.optInt("animated"));bubble.addView(animated,new LinearLayout.LayoutParams(dp(110),dp(110)));}else art("sticker:"+m.optInt("sticker"),106,bubble);}else if(kind.equals("file")){if(m.optBoolean("custom_sticker")){PersonalStickers.render(this,bubble,m);}else if(!m.optString("cloud_video").isEmpty()){addVideo(bubble,m,group);}else if(m.optString("mime").startsWith("image/")){ImageView picture=new ImageView(this);picture.setScaleType(ImageView.ScaleType.CENTER_CROP);picture.setBackground(shape(light?0xffe7edf5:0xff16212e,12));picture.setClipToOutline(true);bubble.addView(picture,new LinearLayout.LayoutParams(group?-1:dp(218),dp(190)));photoPreview(m,picture);picture.setOnClickListener(v->openMedia(m));}else if(m.optString("mime").startsWith("audio/")){bubble.addView(new VoiceNoteView(this,m),new LinearLayout.LayoutParams(group?-1:Math.min(dp(250),getResources().getDisplayMetrics().widthPixels-dp(100)),-2));}else bubble.addView(label(Payload.preview(m),16,color),new LinearLayout.LayoutParams(-2,-2));space(bubble,6);TextView action=label(m.has("local")?I18n.t("↗ Открыть · ")+size(m.optLong("size")):!m.optString("cloud_video").isEmpty()?I18n.t("▶ Смотреть · ")+size(m.optLong("size")):!m.optString("cloud_blob").isEmpty()?I18n.t("↗ Открыть · ")+size(m.optLong("size")):Rtc.status.getOrDefault(m.optString("id"),I18n.t("↓ Загрузить · ")+size(m.optLong("size"))),12,MUTED);action.setOnClickListener(v->openMedia(m));if(!m.optString("mime").startsWith("audio/")&&!m.optBoolean("custom_sticker"))bubble.addView(action,new LinearLayout.LayoutParams(-2,-2));}
   if(!m.optString("text").isEmpty()&&!kind.equals("sticker")){TextView text=label(m.optString("text"),Math.max(14,Math.min(22,Notices.prefs(this).getInt("message_text_size",16))),color);if(m.has("animated"))MotionText.apply(text,m.optInt("animated"));text.setLineSpacing(dp(2),1);if(!group)text.setMaxWidth(dp(247));text.setOnClickListener(v->messageMenu(m));bubble.addView(text,new LinearLayout.LayoutParams(group?-1:-2,-2));}
   JSONObject link=m.optJSONObject("link");if(link==null&&!LinkCards.first(m.optString("text")).isEmpty()){link=new JSONObject().put("url",LinkCards.first(m.optString("text"))).put("title",I18n.t("Открыть ссылку")).put("site",I18n.t("Ссылка"));String video=LinkCards.youtube(link.optString("url"));if(!video.isEmpty())link.put("video",video).put("site","YouTube").put("title",I18n.t("Видео на YouTube"));}if(link!=null)addLink(bubble,link,group);
   space(bubble,8);LinearLayout foot=row();TextView time=label((vault.saved(m.optString("id"))?"★  ":"")+clock(m.optLong("time"))+(out?(m.optString("status").equals("delivered")?"  ✓✓":m.optString("status").equals("stored")?"  ☁":"  ◷"):""),10,MUTED);time.setGravity(Gravity.RIGHT);foot.setGravity(Gravity.RIGHT);foot.addView(time,new LinearLayout.LayoutParams(-2,-2));bubble.addView(foot,new LinearLayout.LayoutParams(-1,-2));addReactions(bubble,m);if(group&&room!=null&&room.optString("kind").equals("channel"))addComments(bubble,m);bubble.setOnClickListener(v->messageMenu(m));line.addView(bubble,new LinearLayout.LayoutParams(group?-1:-2,-2));content.addView(line);space(content,group?14:8);
  }messagesScroll.post(()->{if(bottom)messagesScroll.fullScroll(View.FOCUS_DOWN);else messagesScroll.scrollTo(0,scrollY);});
 }catch(Exception e){error(Api.message(e));}}

 String size(long b){return b>=1048576?String.format(Locale.ROOT,I18n.t("%.1f МБ"),b/1048576.):Math.max(1,b/1024)+I18n.t(" КБ");}
 void emojis(){EmojiTray.show(this);}
 void fillEmojis(boolean animated){EmojiTray.fill(this,animated?5:0);}
 void chatInfo(){if(!Conversation.community(chat)){personMenu(chat);return;}final Vault account=vault;String target=chat;task(()->{JSONObject r=api.call("/room/"+Conversation.room(target),null,account.token());account.putRoom(r);runOnUiThread(()->{if(vault==account)ProfileSheet.room(this,r);});});}
 void editRoom(JSONObject r){LinearLayout b=col();pad(b,18);EditText title=field(b,I18n.t("Название"),false),handle=field(b,I18n.t("@адрес"),false);title.setText(r.optString("title"));handle.setText(r.optString("handle"));TextView available=label(I18n.t("Текущий адрес"),12,MUTED);b.addView(available);watchHandle(handle,available,r.optString("handle"));space(b,10);EditText members=field(b,I18n.t("Ники через запятую"),false);List<String> names=new ArrayList<>();JSONArray a=r.optJSONArray("members");for(int i=0;i<a.length();i++)names.add(a.optString(i));members.setText(String.join(", ",names));Switch pub=new Switch(this);pub.setText(I18n.t("Публичный · виден в поиске"));pub.setTextColor(TEXT);pub.setChecked(r.optBoolean("public"));b.addView(pub);AlertDialog d=dialog().setTitle(I18n.t("Настройки сообщества")).setView(b).setNegativeButton(I18n.t("Отмена"),null).setPositiveButton(I18n.t("Сохранить"),null).create();d.setOnShowListener(x->d.getButton(-1).setOnClickListener(v->{String t=title.getText().toString(),h=handle.getText().toString(),n=members.getText().toString();boolean visible=pub.isChecked();task(()->{JSONObject updated=api.call("/room/update",new JSONObject().put("id",r.optString("id")).put("title",t).put("handle",h).put("public",visible).put("members",nickList(n)),vault.token());vault.putRoom(updated);runOnUiThread(()->{d.dismiss();openChat("room:"+r.optString("id"));});});}));d.show();}
 void settings(){SettingsHome.show(this);}
 void legacySettings(){base("settings");title(I18n.t("Настройки"),()->{if(vault.token().isEmpty())auth(false);else chats();});ScrollView scroll=new ScrollView(this);LinearLayout b=col();scroll.addView(b);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  if(!vault.token().isEmpty())try{JSONObject d=vault.copy();LinearLayout profile=row();Art av=art(d.optString("avatar","preset:0"),70,profile);av.setOnClickListener(v->avatarPicker(""));LinearLayout text=col();text.setPadding(dp(16),0,0,0);TextView name=label(d.optString("name",vault.nick()),22,TEXT);name.setTypeface(null,1);text.addView(name);text.addView(label("@"+vault.nick(),13,MUTED));profile.addView(text);profile.setOnClickListener(v->editProfile());b.addView(profile);space(b,13);b.addView(button(I18n.t("Изменить профиль и фото"),false,()->editProfile()));space(b,22);}catch(Exception ignored){}
  b.addView(button(I18n.t("☁ Защита и резервная копия"),false,()->cloudSettings()));space(b,10);b.addView(button(I18n.t("↻ Обновления · ")+Updates.versionName(this),false,()->Updates.check(this,true)));space(b,18);paragraph(b,I18n.t("ПОДКЛЮЧЕНИЕ"));space(b,10);network=label(I18n.t(ChatService.state),17,TEXT);b.addView(network);space(b,9);b.addView(button(I18n.t("Проверить подключение"),false,()->task(()->{JSONObject h=api.check();if(!h.optString("service").equals("oldy-chat"))throw new Exception(I18n.t("Не удалось проверить подключение"));ChatService.state="Подключено";runOnUiThread(()->{if(network!=null)network.setText(I18n.t("Подключено"));if(!vault.token().isEmpty())startChat();Toast.makeText(this,I18n.t("Подключено"),Toast.LENGTH_SHORT).show();});})));space(b,24);
  paragraph(b,I18n.t("ЯЗЫК / LANGUAGE"));space(b,10);LinearLayout languages=row();for(String code:new String[]{"ru","en"}){languages.addView(button(code.equals("ru")?I18n.t("Русский"):"English",I18n.language().equals(code),()->{I18n.setLanguage(this,code);settings();}),new LinearLayout.LayoutParams(0,dp(52),1));}b.addView(languages);space(b,18);
  paragraph(b,I18n.t("ОФОРМЛЕНИЕ"));space(b,10);LinearLayout themes=row();String[] modes={"light","dark","cyber"},labels={I18n.t("☀ Светлая"),I18n.t("☾ Тёмная"),I18n.t("⚡ Киберпанк")};for(int i=0;i<3;i++){final String m=modes[i];themes.addView(button(labels[i],Notices.prefs(this).getString("theme","dark").equals(m),()->{Notices.prefs(this).edit().putString("theme",m).apply();settings();}),new LinearLayout.LayoutParams(0,dp(51),1));}b.addView(themes);space(b,10);b.addView(button(I18n.t("Обои чатов"),false,()->wallpaperPicker()));space(b,8);toggle(b,I18n.t("Анимации"),"animations",true);space(b,20);
  paragraph(b,I18n.t("УВЕДОМЛЕНИЯ"));space(b,9);toggle(b,I18n.t("Новые сообщения"),"notifications",true);toggle(b,I18n.t("Звук уведомлений"),"sound",true);toggle(b,I18n.t("Вибрация"),"vibration",true);toggle(b,I18n.t("Показывать текст"),"preview",false);space(b,8);b.addView(button(I18n.t("Все чаты без звука на 25 минут"),false,()->focusMode()));space(b,8);b.addView(button(I18n.t("♫ Звуки · ")+I18n.t(Notices.TONE_NAMES[Notices.tone(this)]),false,()->soundPicker()));space(b,10);b.addView(button(I18n.t("Разрешения уведомлений"),false,()->startActivity(new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName()))));space(b,10);b.addView(button(I18n.t("Доставка с выключенным экраном"),false,()->background()));space(b,20);
  if(!vault.nick().isEmpty()){b.addView(button(I18n.t("Сохранить резервную копию"),false,()->backup(false)));space(b,10);}if(vault.token().isEmpty())b.addView(button(I18n.t("Восстановить из копии"),false,()->backup(true)));
  if(!vault.token().isEmpty()){b.addView(button(I18n.t("Выйти из аккаунта"),false,()->dialog().setTitle(I18n.t("Выйти?")).setMessage(I18n.t("История останется на этом телефоне.")).setNegativeButton(I18n.t("Отмена"),null).setPositiveButton(I18n.t("Выйти"),(d,w)->logoutAccount()).show()));space(b,12);}
  space(b,12);b.addView(button(I18n.t("О приложении"),false,()->error(I18n.t("OldЫ Chat · 0.5 beta\n\nЛичная переписка, группы и каналы с отдельными комментариями к постам. MP4 владельца приложения — до 2 ГБ, с просмотром внутри чата. Обычные прямые вложения — до 25 МБ. История дублируется на сервере в зашифрованном виде. Для восстановления на новом телефоне включи резервирование ключей в разделе «Защита и резервная копия».\n\nРекламные интеграции выключены до настройки владельцем."))));space(b,14);paragraph(b,I18n.t("OldЫ Chat · 0.5 beta"));
 }
 void toggle(LinearLayout b,String label,String key,boolean def){Switch s=new Switch(this);s.setText(label);s.setTextColor(TEXT);s.setTextSize(15);s.setThumbTintList(android.content.res.ColorStateList.valueOf(GREEN));s.setTrackTintList(android.content.res.ColorStateList.valueOf(MUTED));pad(s,10);s.setChecked(Notices.prefs(this).getBoolean(key,def));s.setOnCheckedChangeListener((v,on)->{Notices.prefs(this).edit().putBoolean(key,on).apply();if(on&&key.equals("notifications")&&Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},10);});b.addView(s,new LinearLayout.LayoutParams(-1,dp(50)));}
 void background(){PowerManager p=getSystemService(PowerManager.class);dialog().setTitle(I18n.t("Сообщения при погашенном экране")).setMessage(I18n.t("Разреши чату работать в фоне. Это может увеличить расход батареи. На Xiaomi и некоторых других телефонах также включи автозапуск в настройках приложения.\n\n")+(p.isIgnoringBatteryOptimizations(getPackageName())?I18n.t("Ограничение батареи уже снято."):I18n.t("Сейчас Android может задерживать доставку."))).setNegativeButton(I18n.t("Закрыть"),null).setPositiveButton(p.isIgnoringBatteryOptimizations(getPackageName())?I18n.t("Настройки приложения"):I18n.t("Разрешить"),(d,w)->{Intent i=p.isIgnoringBatteryOptimizations(getPackageName())?new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())):new Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,Uri.parse("package:"+getPackageName()));try{startActivity(i);}catch(Exception e){startActivity(new Intent(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS));}}).show();}
 void editProfile(){ProfileEditor.show(this);}
 void avatarPicker(String room){avatarRoom=room;LinearLayout b=col();pad(b,15);GridLayout grid=new GridLayout(this);grid.setColumnCount(4);b.addView(grid);AlertDialog d=dialog().setTitle(I18n.t("Выбери себя")).setView(b).setNegativeButton(I18n.t("Закрыть"),null).create();for(int i=0;i<12;i++){final int n=i;Art a=new Art(this,"preset:"+i);GridLayout.LayoutParams tile=new GridLayout.LayoutParams();tile.width=dp(62);tile.height=dp(62);tile.setMargins(dp(3),dp(5),dp(3),dp(5));grid.addView(a,tile);a.setOnClickListener(v->{d.dismiss();task(()->uploadAvatar(new JSONObject().put("avatar","preset:"+n),room));});}space(b,12);b.addView(button(I18n.t("Загрузить своё фото"),true,()->{avatarRoom=room;d.dismiss();Intent pick=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(pick,31);}));space(b,10);paragraph(b,I18n.t("Фото профиля будет храниться на сервере OldЫ Chat."));d.show();}
 void uploadAvatar(JSONObject p,String room)throws Exception{JSONObject r;if(room.isEmpty()){r=api.call("/profile",p,vault.token());vault.profile(r);}else{p.put("id",room);r=api.call("/room/update",p,vault.token());vault.putRoom(r);}runOnUiThread(()->{if(room.isEmpty())editProfile();else openChat("room:"+room);});}
 void attachments(){boolean channel=false,creator=false;try{JSONObject r=chat.startsWith("room:")?vault.room(Conversation.room(chat)):null;channel=r!=null&&r.optString("kind").equals("channel");creator=channel&&vault.copy().optBoolean("creator_video")&&r.optString("owner").equals(vault.nick());}catch(Exception ignored){}List<String> choices=new ArrayList<>();List<Integer> actions=new ArrayList<>();choices.add(I18n.t("📷 Фото"));actions.add(0);if(channel){if(creator){choices.add(I18n.t("★ MP4 в канал · до 2 ГБ"));actions.add(3);}}else{choices.add(I18n.t("▶ Видео до 25 МБ"));actions.add(1);}choices.add(I18n.t("◉ Записать видеокружок"));actions.add(4);choices.add(I18n.t("🎙 Голосовое сообщение"));actions.add(2);choices.add(I18n.t("♫ Аудиофайл"));actions.add(5);dialog().setTitle(channel?I18n.t("Добавить к публикации"):I18n.t("Вложение")).setItems(choices.toArray(new String[0]),(d,choice)->{int w=actions.get(choice);mediaTarget=chat;if(w==5){startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("audio/*").addCategory(Intent.CATEGORY_OPENABLE),40);return;}if(w==4){startActivityForResult(new Intent(this,RoundActivity.class),35);return;}if(w==3){startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("video/mp4").addCategory(Intent.CATEGORY_OPENABLE).addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION),34);return;}if(w==2)record();else{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType(w==0?"image/*":"video/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,w==0?32:33);}}).show();}
 void record(){if(voice==null)voice=new VoiceCapture(this);voice.begin();}
 void stopRecording(boolean send){if(recorder==null)return;try{recorder.stop();}catch(Exception e){send=false;}recorder.release();recorder=null;File file=recording;if(send){String target=mediaTarget;task(()->{try{JSONObject p=MediaFiles.importFile(this,Uri.fromFile(file),"audio/mp4",I18n.t("Голосовое сообщение"));String local=p.getString("local");p.remove("local");prepareRoom(target);vault.queuePayload(target,p,local);runOnUiThread(()->renderMessages());}finally{file.delete();}});}else if(file!=null)file.delete();}
 public void onRequestPermissionsResult(int request,String[] p,int[] result){super.onRequestPermissionsResult(request,p,result);if(request==ContactDiscovery.PERMISSION){if(result.length>0&&result[0]==PackageManager.PERMISSION_GRANTED)ContactDiscovery.scan(this);else Toast.makeText(this,I18n.t("Доступ к контактам не разрешён. Можно искать по @нику."),Toast.LENGTH_LONG).show();return;}if(request==11&&result.length>0&&result[0]==PackageManager.PERMISSION_GRANTED)Toast.makeText(this,I18n.t("Микрофон разрешён. Удерживай кнопку и говори."),Toast.LENGTH_LONG).show();}
 void openMedia(JSONObject m){if(m.optString("mime").startsWith("audio/")&&(!m.optString("cloud_blob").isEmpty()||m.has("local"))){if(voicePlayer==null)voicePlayer=new VoicePlayer(this);voicePlayer.toggle(m);return;}if(!m.optString("cloud_video").isEmpty()){startActivity(new Intent(this,VideoActivity.class).putExtra("video",m.optString("cloud_video")).putExtra("size",m.optLong("size")).putExtra("title",m.optString("name",I18n.t("Видео"))));return;}if(!m.has("local")){if(!m.optString("cloud_blob").isEmpty()){final Vault account=vault;Toast.makeText(this,I18n.t("Загружаем вложение…"),Toast.LENGTH_SHORT).show();task(()->{CloudMedia.download(this,account,m);JSONObject loaded=account.message(m.getString("id"));runOnUiThread(()->{if(vault==account&&loaded!=null){renderMessages();openMedia(loaded);}});});return;}if(m.optBoolean("out")){error(I18n.t("Этот файл остался на прежнем телефоне."));return;}if(ChatService.instance==null){startChat();error(I18n.t("Подключаемся. Нажмите на вложение ещё раз."));}else{ChatService.instance.rtc.request(m);renderMessages();}return;}task(()->{byte[] bytes=MediaFiles.bytes(this,m.getString("local"));String mime=m.optString("mime");runOnUiThread(()->{if(mime.startsWith("image/")){BitmapFactory.Options options=new BitmapFactory.Options();options.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if((long)options.outWidth*options.outHeight>60000000){error(I18n.t("Изображение слишком большое"));return;}options.inJustDecodeBounds=false;options.inSampleSize=Math.max(1,Math.max(options.outWidth,options.outHeight)/1600);Bitmap bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if(bitmap==null){error(I18n.t("Не удалось открыть изображение"));return;}ImageView image=new ImageView(this);image.setImageBitmap(bitmap);image.setAdjustViewBounds(true);dialog().setView(image).setPositiveButton(I18n.t("Закрыть"),null).show();}else if(mime.startsWith("video/"))startActivity(new Intent(this,VideoActivity.class).putExtra("local",m.optString("local")));else play(bytes,mime);});});}
 void play(byte[] data,String mime){try{if(player!=null)player.release();player=new MediaPlayer();MediaPlayer current=player;current.setDataSource(new MediaDataSource(){public long getSize(){return data.length;}public int readAt(long p,byte[] out,int off,int n){if(p>=data.length)return -1;int size=Math.min(n,data.length-(int)p);System.arraycopy(data,(int)p,out,off,size);return size;}public void close(){}});LinearLayout b=col();pad(b,18);if(mime.startsWith("video/")){SurfaceView video=new SurfaceView(this);b.addView(video,new LinearLayout.LayoutParams(-1,dp(300)));video.getHolder().addCallback(new SurfaceHolder.Callback(){public void surfaceCreated(SurfaceHolder h){current.setDisplay(h);current.prepareAsync();}public void surfaceChanged(SurfaceHolder h,int f,int w,int ht){}public void surfaceDestroyed(SurfaceHolder h){}});}else current.prepareAsync();b.addView(button(I18n.t("⏯ Пауза / продолжить"),false,()->{try{if(current.isPlaying())current.pause();else current.start();}catch(Exception ignored){}}));current.setOnPreparedListener(p->p.start());current.setOnErrorListener((p,w,e)->{error(I18n.t("Не удалось воспроизвести этот формат"));return true;});AlertDialog d=dialog().setTitle(mime.startsWith("video/")?I18n.t("Видео"):I18n.t("Голосовое сообщение")).setView(b).setPositiveButton(I18n.t("Закрыть"),null).create();d.setOnDismissListener(x->{current.release();if(player==current)player=null;});d.show();}catch(Exception e){error(I18n.t("Не удалось открыть запись"));}}
 void campaign(){work.execute(()->{try{JSONObject ad=api.call("/campaign",null,vault.token());if(!ad.optBoolean("enabled"))return;int revision=ad.optInt("revision");android.content.SharedPreferences seen=getSharedPreferences("campaign",0);if(revision<=seen.getInt("seen",0))return;Uri uri=Uri.parse(ad.getString("url"));if(!"https".equals(uri.getScheme())||uri.getHost()==null)return;runOnUiThread(()->{if(isFinishing()||!screen.equals("chats"))return;seen.edit().putInt("seen",revision).apply();dialog().setTitle(I18n.t("Реклама · ")+ad.optString("title")).setMessage(ad.optString("text")).setNegativeButton(I18n.t("Закрыть"),null).setPositiveButton(I18n.t("Подробнее"),(d,w)->{try{startActivity(new Intent(Intent.ACTION_VIEW,uri));}catch(Exception e){error(I18n.t("Не удалось открыть браузер"));}}).show();});}catch(Exception ignored){}});}
 void backup(boolean restore){LinearLayout b=col();pad(b,18);EditText p=field(b,I18n.t("Пароль копии · от 10 символов"),true);dialog().setTitle(restore?I18n.t("Восстановить копию"):I18n.t("Сохранить копию")).setMessage(I18n.t("Запомни этот пароль. Он понадобится для восстановления аккаунта и истории. Фото, видео и голосовые в копию не входят.")).setView(b).setNegativeButton(I18n.t("Отмена"),null).setPositiveButton(I18n.t("Продолжить"),(d,w)->{char[] password=p.getText().toString().toCharArray();if(password.length<10){error(I18n.t("Нужно минимум 10 символов"));return;}if(restore){restorePassword=password;startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),22);}else task(()->{try{backupText=Crypto.exportBackup(vault.backup(),password);runOnUiThread(()->startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/octet-stream").putExtra(Intent.EXTRA_TITLE,"OldyChat-backup.oldy").addCategory(Intent.CATEGORY_OPENABLE),21));}finally{Arrays.fill(password,'\0');}});}).show();}
 protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(result!=RESULT_OK||data==null||data.getData()==null){if(r==21)backupText=null;if(r==22&&restorePassword!=null)Arrays.fill(restorePassword,'\0');return;}Uri uri=data.getData();
  if(r==PersonalStickers.EDITOR){PersonalStickers.show(this);return;}
  if(r==WallpaperPhoto.REQUEST){task(()->{WallpaperPhoto.importPhoto(this,uri);Notices.prefs(this).edit().putBoolean("wallpaper_photo",true).apply();runOnUiThread(()->{refreshAppearance();Toast.makeText(this,I18n.t("Обои сохранены"),Toast.LENGTH_SHORT).show();});});return;}
  if(r==35){String target=mediaTarget;File f=new File(uri.getPath());task(()->CloudMedia.round(this,f,target));return;}
  if(r==21)task(()->{try(OutputStream o=getContentResolver().openOutputStream(uri)){o.write(Crypto.bytes(backupText));backupText=null;runOnUiThread(()->error(I18n.t("Копия сохранена.")));}});
  if(r==22)task(()->{try{String raw=Api.read(getContentResolver().openInputStream(uri),50000000);vault.restore(Crypto.importBackup(raw,restorePassword));runOnUiThread(()->{auth(false);error(I18n.t("Копия восстановлена. Войди по почте и коду."));});}finally{Arrays.fill(restorePassword,'\0');}});
  if(r==34){try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}videoPublish=new VideoPublish(this,uri,mediaTarget,compose==null?"":compose.getText().toString().trim());videoPublish.show();}
  if(r==39&&videoPublish!=null)videoPublish.cover(uri);
  if(r==40){String target=mediaTarget,caption=compose==null?"":compose.getText().toString().trim();task(()->{String mime=getContentResolver().getType(uri);if(mime==null||!mime.matches("audio/(mp4|ogg|mpeg|wav|x-wav|flac|opus|x-flac)"))throw new Exception(I18n.t("Выбери MP3, WAV, M4A, OGG или FLAC"));JSONObject details=new JSONObject();android.media.MediaMetadataRetriever reader=new android.media.MediaMetadataRetriever();try{reader.setDataSource(this,uri);String duration=reader.extractMetadata(android.media.MediaMetadataRetriever.METADATA_KEY_DURATION);if(duration!=null)details.put("duration",Long.parseLong(duration));}finally{reader.release();}CloudMedia.attach(this,uri,mime,I18n.t("Аудиофайл"),target,caption,details);});}

  if(r==31){String room=avatarRoom;task(()->{BitmapFactory.Options opt=new BitmapFactory.Options();opt.inJustDecodeBounds=true;try(InputStream in=getContentResolver().openInputStream(uri)){BitmapFactory.decodeStream(in,null,opt);}if(opt.outWidth<1||opt.outHeight<1)throw new Exception(I18n.t("Не удалось открыть фото"));opt.inSampleSize=Math.max(1,Math.max(opt.outWidth,opt.outHeight)/512);opt.inJustDecodeBounds=false;Bitmap bm;try(InputStream in=getContentResolver().openInputStream(uri)){bm=BitmapFactory.decodeStream(in,null,opt);}if(bm==null)throw new Exception(I18n.t("Не удалось открыть фото"));ByteArrayOutputStream out=new ByteArrayOutputStream();bm.compress(Bitmap.CompressFormat.JPEG,85,out);bm.recycle();uploadAvatar(new JSONObject().put("photo",Crypto.b64(out.toByteArray())),room);});}
  if(r==32||r==33){String target=mediaTarget;String caption=compose==null?"":compose.getText().toString().trim();Toast.makeText(this,I18n.t("Загружаем вложение…"),Toast.LENGTH_SHORT).show();task(()->{String mime=getContentResolver().getType(uri);if(mime==null||!mime.matches("image/(jpeg|png|webp)|video/(mp4|webm)"))throw new Exception(I18n.t("Выберите фото или видео"));CloudMedia.attach(this,uri,mime,mime.startsWith("image/")?I18n.t("Фото"):I18n.t("Видео"),target,caption);});}
 }
 void sheet(String heading,LinearLayout body){Dialog d=panel(heading,body);d.show();Window w=d.getWindow();if(w!=null)w.setLayout(-1,-2);animateEnter(body,0);}
 Dialog panel(String heading,LinearLayout body){final Dialog d=new Dialog(this);if(activeSheet!=null)activeSheet.dismiss();activeSheet=d;LinearLayout box=col();pad(box,20);GradientDrawable backdrop=new GradientDrawable(GradientDrawable.Orientation.TL_BR,light?new int[]{0xfff6f9ff,0xffffffff}:new int[]{0xff23344d,0xff172132});backdrop.setCornerRadii(new float[]{dp(28),dp(28),dp(28),dp(28),0,0,0,0});box.setBackground(backdrop);TextView grip=label("━━",17,MUTED);grip.setGravity(Gravity.CENTER);box.addView(grip);TextView title=label(heading,23,TEXT);title.setTypeface(null,1);box.addView(title);space(box,16);ScrollView scroll=new ScrollView(this){protected void onMeasure(int widthSpec,int heightSpec){int cap=(int)(getResources().getDisplayMetrics().heightPixels*.60f);if(View.MeasureSpec.getMode(heightSpec)!=View.MeasureSpec.UNSPECIFIED)cap=Math.min(cap,View.MeasureSpec.getSize(heightSpec));super.onMeasure(widthSpec,View.MeasureSpec.makeMeasureSpec(cap,View.MeasureSpec.AT_MOST));}};scroll.setFillViewport(false);scroll.addView(body);box.addView(scroll,new LinearLayout.LayoutParams(-1,-2));space(box,12);box.addView(button(I18n.t("Закрыть"),true,()->d.dismiss()));d.setContentView(box);Window w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.setGravity(Gravity.BOTTOM);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);w.setDimAmount(.4f);}d.setOnDismissListener(x->{if(activeSheet==d)activeSheet=null;});return d;}
 View menuTile(String icon,String title,String detail,Runnable action){LinearLayout tile=row();pad(tile,10);tile.setBackground(shape(light?0xffedf3fc:0xff233349,17));TextView mark=label(icon,23,light?0xff4670ad:0xffa7cfff);mark.setGravity(Gravity.CENTER);tile.addView(mark,new LinearLayout.LayoutParams(dp(42),dp(46)));LinearLayout words=col();TextView name=label(title,15,TEXT);name.setTypeface(null,1);words.addView(name);space(words,3);words.addView(label(detail,11,MUTED));tile.addView(words,new LinearLayout.LayoutParams(0,-2,1));tile.addView(label("›",21,MUTED));tile.setOnClickListener(v->{if(activeSheet!=null)activeSheet.dismiss();action.run();});return tile;}
 void profileMenu(){LinearLayout b=col();try{JSONObject me=vault.copy();LinearLayout hero=row();pad(hero,14);GradientDrawable glow=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{0xff4966a1,0xff775fad,0xffa46e91});glow.setCornerRadius(dp(22));hero.setBackground(glow);art(me.optString("avatar","preset:0"),64,hero);LinearLayout names=col();names.setPadding(dp(14),0,0,0);TextView name=label(me.optString("name"),21,0xffffffff);name.setTypeface(null,1);names.addView(name);names.addView(label("@"+vault.nick(),13,0xffe0e9ff));hero.addView(names,new LinearLayout.LayoutParams(0,-2,1));hero.addView(new MotionEmoji(this,3),new LinearLayout.LayoutParams(dp(48),dp(48)));hero.setOnClickListener(v->editProfile());hero.setOnLongClickListener(v->{editProfile();return true;});b.addView(hero);space(b,14);}catch(Exception ignored){}
  b.addView(menuTile("☺",I18n.t("Мой профиль"),I18n.t("Аватар и немного о себе"),()->editProfile()));space(b,7);b.addView(menuTile("▣",I18n.t("Приложения и игры"),I18n.t("Аудиомастерская и мини-игры"),()->MiniApps.show(this)));space(b,7);b.addView(menuTile("▤",I18n.t("Архив"),I18n.t("Скрытые из списка разговоры"),()->{showArchive=true;chats();}));space(b,7);b.addView(menuTile("★",I18n.t("Избранное"),I18n.t("Важное всегда под рукой"),()->savedMessages()));space(b,7);b.addView(menuTile("✦",I18n.t("Капсула дня"),I18n.t("Личные мысли и планы"),()->capsule()));space(b,7);b.addView(menuTile("◷",I18n.t("Все чаты без звука"),Notices.quietUntil(this,vault)>System.currentTimeMillis()?I18n.t("Осталось ")+NotificationSheet.remaining(Notices.quietUntil(this,vault)):I18n.t("Отключить звук и вибрацию на 25 минут"),()->focusMode()));space(b,7);b.addView(menuTile("▥",I18n.t("Пульс общения"),I18n.t("Твоя активность на этом устройстве"),()->conversationStats()));space(b,7);b.addView(menuTile("♧",I18n.t("Создать группу"),I18n.t("Общение своим кругом"),()->createRoom("group")));space(b,7);b.addView(menuTile("◈",I18n.t("Создать канал"),I18n.t("Твои публикации и аудитория"),()->createRoom("channel")));space(b,7);b.addView(menuTile("⊘",I18n.t("Чёрный список"),I18n.t("Заблокированные контакты"),()->blacklist()));space(b,7);b.addView(menuTile("⚙",I18n.t("Настройки"),I18n.t("Обои, звуки и обновления"),()->settings()));sheet(I18n.t("Меню"),b);
 }
 void conversationStats(){try{JSONArray messages=vault.copy().getJSONArray("messages");int sent=0,received=0;Set<String> days=new HashSet<>(),chats=new HashSet<>();for(int i=0;i<messages.length();i++){JSONObject m=messages.getJSONObject(i);if(m.optString("kind").equals("control"))continue;if(m.optBoolean("out"))sent++;else received++;days.add(new java.text.SimpleDateFormat("yyyy-MM-dd",Locale.ROOT).format(new Date(m.optLong("time"))));chats.add(m.optString("peer"));}LinearLayout b=col();paragraph(b,I18n.t("Статистика сохранённой истории этого аккаунта на телефоне. Удалённые сообщения не учитываются."));space(b,15);b.addView(searchCard("preset:3",sent+I18n.t(" отправлено"),received+I18n.t(" получено"),I18n.t("СООБЩЕНИЯ"),()->{}));space(b,10);b.addView(searchCard("preset:7",days.size()+I18n.t(" активных дней"),chats.size()+I18n.t(" чатов"),I18n.t("ТВОЙ РИТМ"),()->{}));sheet(I18n.t("Пульс общения"),b);}catch(Exception e){error(Api.message(e));}}
 void wallpaperPicker(){WallpaperPicker.show(this);}

 void messageMenu(JSONObject m){try{LinearLayout b=col();LinearLayout reactions=row();JSONObject current=vault.reactions(m.optString("id")).optJSONObject(vault.nick());String mine=current==null?"":current.optString("emoji");Dialog d=panel(Conversation.community(chat)?I18n.t("Публикация"):I18n.t("Сообщение"),b);pad(b,16);for(String emoji:Vault.REACTIONS){TextView t=button(emoji,mine.equals(emoji),()->{d.dismiss();control(m,"reaction",mine.equals(emoji)?"":emoji);});t.setPadding(0,dp(12),0,dp(12));t.setTextSize(24);reactions.addView(t,new LinearLayout.LayoutParams(0,dp(50),1));}b.addView(reactions);space(b,12);
  if(compose!=null){b.addView(button(I18n.t("↳  Ответить"),false,()->{d.dismiss();replyTo=m;renderReply();compose.requestFocus();}));space(b,6);}
  b.addView(button(I18n.t("⧉  Копировать текст"),false,()->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText(I18n.t("OldЫ Chat"),m.optString("text")));d.dismiss();Toast.makeText(this,I18n.t("Скопировано"),Toast.LENGTH_SHORT).show();}));space(b,6);
  b.addView(button(vault.saved(m.optString("id"))?I18n.t("★  Убрать из избранного"):I18n.t("☆  В избранное"),false,()->{d.dismiss();task(()->{vault.bookmark(m.optString("id"));runOnUiThread(()->renderMessages());});}));space(b,6);
  JSONObject room=Conversation.community(chat)?vault.room(Conversation.room(chat)):null;if(room==null||room.optString("owner").equals(vault.nick())){boolean pinned=vault.pinned(chat).equals(m.optString("id"));b.addView(button(pinned?I18n.t("⌁  Открепить"):I18n.t("⌁  Закрепить для всех"),false,()->{d.dismiss();control(m,pinned?"unpin":"pin","");}));space(b,6);}
  if(chat.startsWith("room:")){String link="oldy://comments/"+Conversation.room(chat)+"/"+m.optString("id");b.addView(button(I18n.t("⧉ Ссылка на комментарии"),false,()->{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText(I18n.t("Комментарии OldЫ Chat"),link));d.dismiss();Toast.makeText(this,I18n.t("Ссылка скопирована"),Toast.LENGTH_SHORT).show();}));space(b,6);}
  if(m.optString("kind").equals("file")){b.addView(button(I18n.t("↗  Открыть вложение"),false,()->{d.dismiss();openMedia(m);}));space(b,6);}
  if(m.optBoolean("out")||vault.moderator()||!Conversation.community(chat)){TextView del=button(I18n.t("Удалить для всех"),false,()->{d.dismiss();deletePost(m);});del.setTextColor(light?0xffb73953:0xffff92a6);b.addView(del);space(b,6);}
  if(!m.optBoolean("out")){String from=m.optString("from",chat);b.addView(button(I18n.t("☺  Профиль @")+from,false,()->{d.dismiss();personMenu(from);}));}
  d.show();if(d.getWindow()!=null)d.getWindow().setLayout(-1,-2);animateEnter(b,0);
 }catch(Exception e){error(Api.message(e));}}
 void control(JSONObject m,String op,String emoji){try{send(new JSONObject().put("kind","control").put("op",op).put("mid",m.optString("id")).put("emoji",emoji),null);}catch(Exception e){error(Api.message(e));}}
 void addReactions(LinearLayout bubble,JSONObject m)throws Exception{JSONObject all=vault.reactions(m.optString("id"));if(all.length()==0)return;LinearLayout row=row();for(String emoji:Vault.REACTIONS){int count=0;boolean mine=false;Iterator<String> users=all.keys();while(users.hasNext()){String n=users.next();if(emoji.equals(all.optJSONObject(n).optString("emoji"))){count++;if(n.equals(vault.nick()))mine=true;}}if(count==0)continue;final boolean selected=mine;TextView t=label(emoji+" "+count,14,mine?INK:TEXT);t.setGravity(Gravity.CENTER);t.setPadding(dp(8),dp(5),dp(8),dp(5));t.setBackground(shape(mine?GREEN:(light?0xffedf3fa:0xff303e50),18));t.setOnClickListener(v->control(m,"reaction",selected?"":emoji));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-2,-2);lp.rightMargin=dp(4);row.addView(t,lp);}if(row.getChildCount()>0){space(bubble,8);HorizontalScrollView h=new HorizontalScrollView(this);h.setHorizontalScrollBarEnabled(false);h.addView(row);bubble.addView(h);}}
 void renderPin()throws Exception{if(pinBar==null)return;pinBar.removeAllViews();String id=vault.pinned(chat);if(id.isEmpty())return;JSONObject m=vault.message(id);TextView p=label(I18n.t("⌁ Закреплённая публикация\n")+(m==null?I18n.t("Ожидаем публикацию на этом устройстве"):Payload.preview(m)),12,light?0xff366aaf:0xffa0ceff);p.setMaxLines(2);p.setEllipsize(TextUtils.TruncateAt.END);pad(p,10);p.setBackground(shape(CARD,14));p.setOnClickListener(v->jump(id));pinBar.addView(p,new LinearLayout.LayoutParams(-1,-2));space(pinBar,8);}
 void jump(String id){View found=content.findViewWithTag(id);if(found==null){Toast.makeText(this,I18n.t("Публикации пока нет на этом телефоне"),Toast.LENGTH_SHORT).show();return;}View line=(View)found.getParent();messagesScroll.smoothScrollTo(0,line.getTop());found.animate().alpha(.45f).setDuration(130).withEndAction(()->found.animate().alpha(1).setDuration(300));}
 void renderReply(){replyBar.removeAllViews();if(replyTo==null)return;String text=Payload.preview(replyTo);TextView q=label(I18n.t("↳ Ответ · ")+text.substring(0,Math.min(80,text.length()))+"   ×",12,MUTED);pad(q,8);q.setMaxLines(2);q.setBackground(shape(CARD,10));q.setOnClickListener(v->{replyTo=null;replyBar.removeAllViews();});replyBar.addView(q);space(replyBar,6);}
 void savedMessages(){LinearLayout b=col();try{JSONArray a=vault.copy().getJSONArray("messages");int count=0;for(int i=a.length()-1;i>=0;i--){JSONObject m=a.getJSONObject(i);if(!vault.saved(m.optString("id")))continue;count++;b.addView(button(Payload.preview(m)+"\n"+new java.text.SimpleDateFormat("d MMM · HH:mm",I18n.locale()).format(new Date(m.optLong("time"))),false,()->{openChat(m.optString("peer"));ui.postDelayed(()->jump(m.optString("id")),150);}));space(b,8);}if(count==0)paragraph(b,I18n.t("Нажми на сообщение или пост и выбери «В избранное». Всё важное будет здесь."));sheet(I18n.t("★ Избранное"),b);}catch(Exception e){error(Api.message(e));}}
 void blacklist(){task(()->{JSONArray a=api.call("/blocks",null,vault.token()).getJSONArray("blocked");vault.blocks(a);runOnUiThread(()->{LinearLayout b=col();if(a.length()==0)paragraph(b,I18n.t("Здесь появятся люди, которых ты заблокируешь в личных сообщениях."));for(int i=0;i<a.length();i++){String n=a.optString(i);b.addView(button("@"+n+I18n.t("  ·  разблокировать"),false,()->setBlock(n,false)));space(b,8);}sheet(I18n.t("Чёрный список ЛС"),b);});});}
 void setBlock(String target,boolean blocked){task(()->{api.call("/blocks",new JSONObject().put("target",target).put("blocked",blocked),vault.token());vault.blocks(api.call("/blocks",null,vault.token()).getJSONArray("blocked"));runOnUiThread(()->{Toast.makeText(this,blocked?I18n.t("Личные сообщения заблокированы"):I18n.t("Собеседник разблокирован"),Toast.LENGTH_SHORT).show();if(screen.equals("chat")&&chat.equals(target))openChat(target);});});}
 void personMenu(String target){if(target.isEmpty()||target.equals(vault.nick())){editProfile();return;}final Vault account=vault;final String context=chat;task(()->{JSONObject u=api.call("/user/"+target,null,account.token());account.pin(u);JSONObject r=Conversation.community(context)?account.room(Conversation.room(context)):null;runOnUiThread(()->{if(vault==account)ProfileSheet.person(this,u,r);});});}
 void roomBan(JSONObject r,String target,boolean banned){task(()->{JSONObject updated=api.call("/room/ban",new JSONObject().put("id",r.optString("id")).put("target",target).put("banned",banned),vault.token());vault.putRoom(updated);runOnUiThread(()->{Toast.makeText(this,banned?I18n.t("Участник заблокирован"):I18n.t("Доступ снова разрешён"),Toast.LENGTH_SHORT).show();if(chat.equals("room:"+r.optString("id")))openChat(chat);});});}
 void emailSettings(){EmailAuth.link(this);}

 String makeThumb(String local)throws Exception{byte[] bytes=MediaFiles.bytes(this,local);BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);o.inSampleSize=Math.max(1,Math.max(o.outWidth,o.outHeight)/180);o.inJustDecodeBounds=false;Bitmap bm=BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);if(bm==null)return "";float scale=Math.min(1,180f/Math.max(bm.getWidth(),bm.getHeight()));Bitmap small=Bitmap.createScaledBitmap(bm,Math.max(1,(int)(bm.getWidth()*scale)),Math.max(1,(int)(bm.getHeight()*scale)),true);ByteArrayOutputStream out=new ByteArrayOutputStream();small.compress(Bitmap.CompressFormat.WEBP,55,out);if(small!=bm)small.recycle();bm.recycle();return out.size()<=7000?Crypto.b64(out.toByteArray()):"";}
 void photoPreview(JSONObject m,ImageView view){final Vault account=vault;String key=m.optString("id"),cacheKey=key+(m.has("local")?":full":":thumb");Bitmap cached=mediaCache.get(cacheKey);if(cached!=null){view.setImageBitmap(cached);return;}work.execute(()->{try{byte[] bytes=m.has("local")?MediaFiles.bytes(this,m.getString("local")):Crypto.un64(m.optString("thumb"));if(bytes.length==0)return;BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);o.inSampleSize=Math.max(1,Math.max(o.outWidth,o.outHeight)/700);o.inJustDecodeBounds=false;Bitmap image=BitmapFactory.decodeByteArray(bytes,0,bytes.length,o);if(image!=null&&vault==account){mediaCache.put(cacheKey,image);runOnUiThread(()->{if(vault==account)view.setImageBitmap(image);});}}catch(Exception ignored){}});}
 void addLink(LinearLayout bubble,JSONObject link,boolean group){String url=link.optString("url");YouTubeLinkDetector.Target yt=YouTubeLinkDetector.parse(url);if(yt!=null){YouTubeCards.add(this,bubble,yt,link,group);return;}try{java.net.URI uri=new java.net.URI(url);if(!("https".equals(uri.getScheme())||"http".equals(uri.getScheme()))||uri.getHost()==null||uri.getUserInfo()!=null)return;}catch(Exception e){return;}space(bubble,10);LinearLayout card=col();pad(card,10);GradientDrawable bg=shape(light?0xffedf5ff:0xff17293d,12);bg.setStroke(dp(1),light?0xffbfdbf8:0xff365879);card.setBackground(bg);TextView provider=label(link.optString("site",I18n.t("Ссылка")),12,light?0xff3776b4:0xff9acfff);provider.setTypeface(null,1);card.addView(provider);space(card,4);TextView title=label(link.optString("title"),15,TEXT);title.setTypeface(null,1);title.setMaxLines(3);card.addView(title);if(!link.optString("author").isEmpty()){space(card,4);card.addView(label(link.optString("author"),12,MUTED));}String video=LinkCards.youtube(url);if(!video.isEmpty()){space(card,8);FrameLayout frame=new FrameLayout(this);ImageView image=new ImageView(this);image.setScaleType(ImageView.ScaleType.CENTER_CROP);image.setBackgroundColor(light?0xffd6e3f4:0xff223954);frame.addView(image,new FrameLayout.LayoutParams(-1,-1));TextView play=label("▶",34,0xffffffff);play.setGravity(Gravity.CENTER);play.setShadowLayer(dp(5),0,dp(1),0xff263243);frame.addView(play,new FrameLayout.LayoutParams(-1,-1));card.addView(frame,new LinearLayout.LayoutParams(group?-1:dp(222),dp(150)));Bitmap cached=mediaCache.get("yt:"+video);if(cached!=null)image.setImageBitmap(cached);else Art.fetch.execute(()->{try{Bitmap pic=LinkCards.thumbnail(video);if(pic!=null){mediaCache.put("yt:"+video,pic);runOnUiThread(()->image.setImageBitmap(pic));}}catch(Exception ignored){}});}TextView open=label(I18n.t("Открыть ↗"),12,light?0xff3672ab:0xff9acfff);space(card,7);card.addView(open);card.setOnClickListener(v->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception e){error(I18n.t("Не удалось открыть ссылку"));}});bubble.addView(card,new LinearLayout.LayoutParams(group?-1:-2,-2));}


 void cloudSettings(){if(vault.token().isEmpty()){error(I18n.t("Сначала войди в аккаунт"));return;}final Vault owner=vault;LinearLayout b=col();paragraph(b,I18n.t("Копия ключей позволяет открыть защищённую переписку на другом телефоне. Для неё нужен отдельный пароль. Обычный вход на этом телефоне — по e-mail и коду."));space(b,14);EditText password=field(b,I18n.t("Пароль резервной копии · от 10 символов"),true);b.addView(button(I18n.t("Сохранить защищённую копию"),true,()->{String pass=password.getText().toString();if(pass.length()<10||pass.length()>128){error(I18n.t("Пароль копии: от 10 до 128 символов"));return;}task(()->{api.call("/key-backup",new JSONObject().put("backup",Crypto.exportBackup(owner.keyBackup(),pass.toCharArray())),owner.token());runOnUiThread(()->Toast.makeText(this,I18n.t("Копия ключей сохранена. Запомни пароль."),Toast.LENGTH_LONG).show());});}));space(b,12);b.addView(button(I18n.t("Создать личный ключ восстановления"),false,()->RecoveryKeys.show(this,owner)));space(b,12);paragraph(b,I18n.t("Личный ключ открывает только твою историю. Общего ключа для чтения чужих переписок нет."));sheet(I18n.t("Защита и резервная копия"),b);}

 String audience(JSONObject r){int n=r.optJSONArray("members")==null?0:r.optJSONArray("members").length();if(I18n.english())return n+" "+(r.optString("kind").equals("channel")?(n==1?"subscriber":"subscribers"):(n==1?"member":"members"));String[] words=r.optString("kind").equals("channel")?new String[]{I18n.t("подписчик"),I18n.t("подписчика"),I18n.t("подписчиков")}:new String[]{I18n.t("участник"),I18n.t("участника"),I18n.t("участников")};int x=n%100,y=n%10;return n+" "+words[x>=11&&x<=14?2:y==1?0:y>=2&&y<=4?1:2];}
 void openComments(String room,String post){task(()->{JSONObject r=api.call("/room/"+room,null,vault.token());vault.putRoom(r);api.call("/threads",new JSONObject().put("room",room).put("post",post),vault.token());runOnUiThread(()->openChat("thread:"+room+":"+post));});}
 void addComments(LinearLayout bubble,JSONObject m){String rid=Conversation.room(chat),mid=m.optString("id");int count=0;try{JSONArray a=vault.copy().getJSONArray("messages");for(int i=0;i<a.length();i++){JSONObject x=a.optJSONObject(i);if(x.optString("peer").equals("thread:"+rid+":"+mid)&&!x.optString("kind").equals("control"))count++;}}catch(Exception ignored){}space(bubble,10);View divider=new View(this);divider.setBackgroundColor(light?0xffdce5ef:0xff405065);bubble.addView(divider,new LinearLayout.LayoutParams(-1,dp(1)));TextView c=label("◌  "+(count==0?I18n.t("Комментировать"):count+I18n.t(" · Комментарии"))+"   ›",14,light?0xff3470ac:0xff9bcfff);c.setTypeface(null,1);c.setPadding(0,dp(12),0,dp(2));c.setOnClickListener(v->openComments(rid,mid));bubble.addView(c,new LinearLayout.LayoutParams(-1,-2));}
 void videoCover(JSONObject m,ImageView image){final Vault account=vault;String vid=m.optString("cloud_video"),cacheKey="video-cover-hq:"+vid;Bitmap cached=mediaCache.get(cacheKey);if(cached!=null){image.setImageBitmap(cached);return;}try{byte[] bytes=Crypto.un64(m.optString("thumb"));if(bytes.length>0){Bitmap thumb=BitmapFactory.decodeByteArray(bytes,0,bytes.length);if(thumb!=null)image.setImageBitmap(thumb);}}catch(Exception ignored){}
  if(!loadingImages.add(cacheKey))return;Art.fetch.execute(()->{try{for(int attempt=0;attempt<4&&vault==account;attempt++)try{JSONObject result=api.call("/video-cover/"+vid,null,account.token());byte[] bytes=Crypto.un64(result.getString("photo"));Bitmap cover=BitmapFactory.decodeByteArray(bytes,0,bytes.length);if(cover!=null&&vault==account)runOnUiThread(()->{if(vault!=account)return;mediaCache.put(cacheKey,cover);image.setImageBitmap(cover);updateCoverViews(root,vid,cover);});return;}catch(Api.Failure failure){if(failure.status!=409)return;try{Thread.sleep(1200);}catch(InterruptedException stop){Thread.currentThread().interrupt();return;}}catch(Exception unavailable){return;}}finally{runOnUiThread(()->loadingImages.remove(cacheKey));}});
 }
 void updateCoverViews(View v,String vid,Bitmap bitmap){if(v instanceof ImageView&&("video:"+vid).equals(v.getTag()))((ImageView)v).setImageBitmap(bitmap);if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)updateCoverViews(g.getChildAt(i),vid,bitmap);}}

 void addVideo(LinearLayout b,JSONObject m,boolean group){boolean round=m.optBoolean("round");AspectMediaFrame frame=new AspectMediaFrame(this,round);ImageView image=new AspectMediaFrame.Cover(this,frame);image.setTag("video:"+m.optString("cloud_video"));frame.addView(image,new FrameLayout.LayoutParams(-1,-1));videoCover(m,image);NeonPlay play=new NeonPlay(this);FrameLayout.LayoutParams pp=new FrameLayout.LayoutParams(dp(58),dp(58),Gravity.CENTER);frame.addView(play,pp);TextView badge=label((round?I18n.t("Кружок"):"MP4")+" · "+size(m.optLong("size"))+"  ⛶",11,0xffffffff);badge.setPadding(dp(10),dp(6),dp(10),dp(6));badge.setBackgroundColor(0x99091221);FrameLayout.LayoutParams bp=new FrameLayout.LayoutParams(-2,-2,Gravity.BOTTOM|Gravity.RIGHT);frame.addView(badge,bp);frame.setOnClickListener(v->openMedia(m));LinearLayout.LayoutParams coverSize=new LinearLayout.LayoutParams(round?dp(218):Math.min(dp(340),getResources().getDisplayMetrics().widthPixels-dp(84)),-2);coverSize.gravity=Gravity.CENTER_HORIZONTAL;b.addView(frame,coverSize);}


 void soundPicker(){LinearLayout b=col();for(int i=0;i<Notices.TONE_NAMES.length;i++){final int n=i;LinearLayout line=row();TextView choose=button((Notices.tone(this)==i?"✓ ":"")+I18n.t(Notices.TONE_NAMES[i]),Notices.tone(this)==i,()->{Notices.prefs(this).edit().putInt("tone",n).apply();previewTone(n);Toast.makeText(this,I18n.t("Звук выбран: ")+I18n.t(Notices.TONE_NAMES[n]),Toast.LENGTH_SHORT).show();});line.addView(choose,new LinearLayout.LayoutParams(0,dp(48),1));TextView listen=label("▶",20,TEXT);listen.setGravity(Gravity.CENTER);listen.setOnClickListener(v->previewTone(n));line.addView(listen,new LinearLayout.LayoutParams(dp(48),dp(48)));b.addView(line);space(b,7);}space(b,8);b.addView(button(I18n.t("Громкость уведомлений Android"),false,()->startActivity(new Intent(Settings.ACTION_SOUND_SETTINGS))));space(b,8);paragraph(b,I18n.t("Новые мелодии звучат ярче. Итоговая громкость зависит от системной громкости уведомлений и режима «Не беспокоить»."));sheet(I18n.t("♫ Выбери звук"),b);}
 void previewTone(int index){try{MediaPlayer sound=MediaPlayer.create(this,Notices.TONES[index],new android.media.AudioAttributes.Builder().setUsage(android.media.AudioAttributes.USAGE_NOTIFICATION).build(),0);if(sound!=null){sound.setVolume(1,1);sound.setOnCompletionListener(MediaPlayer::release);sound.start();}}catch(Exception e){error(I18n.t("Не удалось воспроизвести звук"));}}

 void deletePost(JSONObject m){String target=m.optString("peer");dialog().setTitle(I18n.t("Удалить для всех?")).setMessage(I18n.t("Сообщение, вложение на сервере и комментарии к этому посту будут удалены.")).setNegativeButton(I18n.t("Отмена"),null).setPositiveButton(I18n.t("Удалить"),(d,w)->task(()->{if(m.optBoolean("out"))ChatService.register(api,vault,m);JSONObject result=api.call("/posts/delete",new JSONObject().put("mid",m.getString("id")).put("room",Conversation.community(target)?Conversation.room(target):""),vault.token());vault.deletion(result);mediaCache.evictAll();runOnUiThread(()->{renderMessages();Toast.makeText(this,result.optBoolean("media_cleanup_pending")?I18n.t("Пост удалён. Завершаем очистку файла."):I18n.t("Удалено вместе с вложением на сервере"),Toast.LENGTH_LONG).show();});})).show();}
 void deleteRoom(JSONObject room){dialog().setTitle(I18n.t("Удалить «")+room.optString("title")+"»?").setMessage(I18n.t("Все публикации, комментарии и файлы этого сообщества будут удалены для всех участников. Отменить это действие нельзя.")).setNegativeButton(I18n.t("Отмена"),null).setPositiveButton(I18n.t("Удалить"),(d,w)->task(()->{JSONObject r=api.call("/room/delete",new JSONObject().put("room",room.getString("id")),vault.token());vault.deletion(r);runOnUiThread(()->chats());})).show();}
 void animateEnter(View view,int index){view.animate().cancel();view.setAlpha(1);view.setTranslationY(0);view.setScaleX(1);view.setScaleY(1);if(!android.animation.ValueAnimator.areAnimatorsEnabled()||!Notices.prefs(this).getBoolean("animations",Notices.prefs(this).getBoolean("motion",true)))return;view.setAlpha(0);view.setTranslationY(dp(12));view.setScaleX(.975f);view.setScaleY(.975f);view.animate().alpha(1).translationY(0).scaleX(1).scaleY(1).setStartDelay(Math.min(index,5)*35L).setDuration(260).setInterpolator(new android.view.animation.DecelerateInterpolator());}
 void focusMode(){NotificationSheet.quiet(this);}
 void capsule(){try{LinearLayout b=col();paragraph(b,I18n.t("Личная капсула дня — мысли и планы, которые видишь только ты. Сохраняется в зашифрованном хранилище этого аккаунта на телефоне."));space(b,12);EditText note=field(b,I18n.t("Что хочется сохранить сегодня?"),false);note.setSingleLine(false);note.setMinLines(3);String day=new java.text.SimpleDateFormat("yyyy-MM-dd",Locale.ROOT).format(new Date());note.setText(vault.bucket("capsules").optString(day));b.addView(button(I18n.t("Сохранить капсулу ✦"),true,()->task(()->{synchronized(vault){vault.bucket("capsules").put(day,note.getText().toString());vault.save();}runOnUiThread(()->Toast.makeText(this,I18n.t("Капсула сохранена"),Toast.LENGTH_SHORT).show());})));space(b,12);JSONObject all=vault.bucket("capsules");all.keys().forEachRemaining(date->{TextView entry=label(date+" · "+all.optString(date),13,MUTED);pad(entry,8);b.addView(entry);});sheet(I18n.t("✦ Капсула дня"),b);}catch(Exception e){error(Api.message(e));}}

}
