package chat.oldy;
import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.media.*;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
 int BG,CARD,GREEN,TEXT,MUTED,INK=0xff182416;
 final ExecutorService work=Executors.newSingleThreadExecutor();final Handler ui=new Handler(Looper.getMainLooper());
 Vault vault;Api api;LinearLayout root,content;ScrollView messagesScroll;TextView network,typing;EditText compose;String screen="",chat="",search="",avatarRoom="",mediaTarget="";
 boolean registeredReceiver,active;String backupText;char[] restorePassword;MediaRecorder recorder;File recording;MediaPlayer player;long lastTyping;int filter;
 interface Job{void run()throws Exception;}
 final BroadcastReceiver refresh=new BroadcastReceiver(){public void onReceive(Context c,Intent i){if(network!=null)network.setText(ChatService.state);if(screen.equals("chats"))renderChats();if(screen.equals("chat"))renderMessages();}};
 public void onCreate(Bundle b){super.onCreate(b);api=new Api(this);try{vault=ChatService.vault(this);}catch(Exception e){dialog().setTitle("Не удалось открыть историю").setMessage("Данные сохранены. Попробуйте перезапустить приложение.").setPositiveButton("Закрыть",(d,w)->finish()).show();return;}
  splash();ui.postDelayed(()->{if(isFinishing())return;if(vault.token().isEmpty())auth(false);else{chats();startChat();openFromIntent(getIntent());}},1300);
 }
 public void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);if(vault!=null&&!vault.token().isEmpty())openFromIntent(i);}
 void openFromIntent(Intent i){String target=i.getStringExtra("chat");if(target!=null&&!target.isEmpty())openChat(target);}
 protected void onStart(){super.onStart();active=true;IntentFilter f=new IntentFilter("chat.oldy.CHANGED");if(Build.VERSION.SDK_INT>=33)registerReceiver(refresh,f,Context.RECEIVER_NOT_EXPORTED);else registerReceiver(refresh,f);registeredReceiver=true;if(screen.equals("chat"))ChatService.visibleChat=chat;}
 protected void onStop(){active=false;ChatService.visibleChat="";if(registeredReceiver){unregisterReceiver(refresh);registeredReceiver=false;}if(recorder!=null)stopRecording(false);super.onStop();}
 public void onBackPressed(){if(screen.equals("chat")||screen.equals("settings")){if(vault.token().isEmpty())auth(false);else chats();}else super.onBackPressed();}
 void colors(){String theme=Notices.prefs(this).getString("theme","dark");BG=theme.equals("light")?0xfff4f6ef:theme.equals("green")?0xff123629:0xff101712;CARD=theme.equals("light")?0xffffffff:theme.equals("green")?0xff204b3a:0xff202b23;GREEN=theme.equals("light")?0xffd1f6a4:0xffbaf77b;TEXT=theme.equals("light")?0xff18281d:0xfff2f6ed;MUTED=theme.equals("light")?0xff63766b:0xffa2b4a5;getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(BG);getWindow().getDecorView().setSystemUiVisibility(theme.equals("light")?View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR:0);}
 AlertDialog.Builder dialog(){return new AlertDialog.Builder(this,Notices.prefs(this).getString("theme","dark").equals("light")?android.R.style.Theme_Material_Light_Dialog_Alert:android.R.style.Theme_Material_Dialog_Alert);}
 int dp(float v){return Math.round(v*getResources().getDisplayMetrics().density);}
 GradientDrawable shape(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
 LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(1);return l;}
 LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setGravity(Gravity.CENTER_VERTICAL);return l;}
 void pad(View v,int p){v.setPadding(dp(p),dp(p),dp(p),dp(p));}
 void space(LinearLayout l,int h){l.addView(new View(this),new LinearLayout.LayoutParams(1,dp(h)));}
 TextView label(String s,int size,int color){TextView v=new TextView(this);v.setText(s);v.setTextSize(size);v.setTextColor(color);return v;}
 TextView button(String s,boolean primary,Runnable action){TextView v=label(s,15,primary?INK:TEXT);v.setGravity(Gravity.CENTER);v.setTypeface(null,1);pad(v,13);v.setBackground(shape(primary?GREEN:CARD,18));v.setContentDescription(s);v.setOnClickListener(w->action.run());return v;}
 void base(String s){screen=s;ChatService.visibleChat=s.equals("chat")&&active?chat:"";colors();root=col();root.setBackgroundColor(BG);root.setPadding(dp(18),dp(12),dp(18),dp(10));if(Build.VERSION.SDK_INT>=35)root.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets x=insets.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.ime());v.setPadding(dp(18)+x.left,dp(12)+x.top,dp(18)+x.right,dp(10)+x.bottom);return insets;});setContentView(root);network=null;typing=null;}
 void title(String s,Runnable back){LinearLayout r=row();if(back!=null){TextView b=button("‹",false,back);r.addView(b,new LinearLayout.LayoutParams(dp(44),dp(46)));}TextView t=label(s,25,TEXT);t.setTypeface(null,1);t.setPadding(dp(12),0,0,0);r.addView(t,new LinearLayout.LayoutParams(0,dp(56),1));t.setGravity(Gravity.CENTER_VERTICAL);root.addView(r);space(root,12);}
 void paragraph(LinearLayout l,String s){TextView t=label(s,13,MUTED);t.setLineSpacing(dp(3),1);l.addView(t);}
 EditText field(LinearLayout l,String hint,boolean password){EditText e=new EditText(this);e.setSingleLine(true);e.setTextSize(16);e.setTextColor(TEXT);e.setHintTextColor(MUTED);e.setHint(hint);pad(e,15);e.setBackground(shape(CARD,17));e.setInputType(password?129:1);l.addView(e,new LinearLayout.LayoutParams(-1,dp(56)));space(l,10);return e;}
 void task(Job job){work.execute(()->{try{job.run();}catch(Exception e){runOnUiThread(()->error(Api.message(e)));}});}
 void error(String s){if(!isFinishing())dialog().setTitle("OldЫ Chat").setMessage(s).setPositiveButton("Понятно",null).show();}
 Art art(String key,int size,LinearLayout l){Art a=new Art(this,key);l.addView(a,new LinearLayout.LayoutParams(dp(size),dp(size)));return a;}
 void splash(){base("splash");root.setGravity(Gravity.CENTER);art("mascot",260,root);space(root,26);TextView h=label("OldЫ Chat",38,TEXT);h.setTypeface(null,1);root.addView(h);space(root,9);root.addView(label("ХОРОШО, КОГДА СВОИ РЯДОМ",10,MUTED));space(root,26);ProgressBar p=new ProgressBar(this);p.setIndeterminateTintList(android.content.res.ColorStateList.valueOf(GREEN));root.addView(p,new LinearLayout.LayoutParams(dp(25),dp(25)));}
 void auth(boolean signup){base("auth");ScrollView s=new ScrollView(this);LinearLayout b=col();s.addView(b);root.addView(s);
  LinearLayout top=row();TextView brand=label("OldЫ Chat",23,TEXT);brand.setTypeface(null,1);top.addView(brand,new LinearLayout.LayoutParams(0,dp(48),1));top.addView(button("⚙",false,()->settings()));b.addView(top);space(b,14);
  Art a=new Art(this,"mascot");LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(dp(180),dp(180));ap.gravity=Gravity.CENTER_HORIZONTAL;b.addView(a,ap);space(b,18);
  TextView hello=label(signup?"Давай знакомиться":"Привет, это свои",27,TEXT);hello.setTypeface(null,1);b.addView(hello);space(b,7);paragraph(b,"Разговоры, которые хочется продолжать.");space(b,20);
  LinearLayout tabs=row();tabs.addView(button("Войти",!signup,()->auth(false)),new LinearLayout.LayoutParams(0,dp(48),1));tabs.addView(button("Регистрация",signup,()->auth(true)),new LinearLayout.LayoutParams(0,dp(48),1));b.addView(tabs);space(b,18);
  EditText name=signup?field(b,"Как тебя зовут?",false):null;EditText nick=field(b,"Ник · латиница, цифры, _",false);nick.setInputType(145);if(!vault.nick().isEmpty())nick.setText(vault.nick());EditText pass=field(b,"Пароль · минимум 8 символов",true);
  TextView submit=button(signup?"Создать аккаунт  →":"Войти в чат  →",true,()->{});submit.setOnClickListener(v->{String n=nick.getText().toString().trim().toLowerCase(Locale.ROOT),p=pass.getText().toString(),display=name==null?"":name.getText().toString().trim();if(!n.matches("[a-z0-9_]{3,24}")||p.length()<8||p.length()>128){error("Ник: 3–24 латинские буквы, цифры или _. Пароль: 8–128 символов.");return;}submit.setEnabled(false);submit.setText("Подключаемся…");task(()->{try{api.check();JSONObject body=new JSONObject().put("nick",n).put("password",p);if(signup){JSONObject id=vault.identity();body.put("name",display).put("enc",id.getString("enc")).put("sig",id.getString("sig"));}vault.account(api.call(signup?"/register":"/login",body,""));runOnUiThread(()->{chats();startChat();});}finally{runOnUiThread(()->{submit.setEnabled(true);submit.setText(signup?"Создать аккаунт  →":"Войти в чат  →");});}});});b.addView(submit);space(b,14);paragraph(b,"Без номера телефона. Без SMS.");space(b,10);
 }
 void startChat(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},10);startForegroundService(new Intent(this,ChatService.class));}
 void chats(){base("chats");LinearLayout header=row();header.addView(button("☰",false,()->menu()),new LinearLayout.LayoutParams(dp(46),dp(46)));TextView brand=label("OldЫ Chat",27,TEXT);brand.setTypeface(null,1);brand.setPadding(dp(12),0,0,0);header.addView(brand,new LinearLayout.LayoutParams(0,dp(54),1));header.addView(button("＋",true,()->findPeer()));root.addView(header);network=label(ChatService.state,11,MUTED);network.setPadding(dp(60),0,0,0);root.addView(network);space(root,18);
  EditText query=field(root,"⌕  Найти разговор",false);query.setText(search);query.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void onTextChanged(CharSequence s,int a,int b,int c){search=s.toString();renderChats();}public void afterTextChanged(Editable e){}});
  LinearLayout tabs=row();String[] names={"Все","Личные","Группы","Каналы"};for(int i=0;i<names.length;i++){final int at=i;TextView t=button(names[i],filter==i,()->{filter=at;chats();});t.setTextSize(12);tabs.addView(t,new LinearLayout.LayoutParams(0,dp(42),1));}root.addView(tabs);space(root,14);
  ScrollView scroll=new ScrollView(this);content=col();scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));renderChats();space(root,10);
  LinearLayout nav=row();nav.setBackground(shape(CARD,24));TextView left=label("●  Чаты",14,Notices.prefs(this).getString("theme","dark").equals("light")?INK:GREEN);left.setGravity(Gravity.CENTER);nav.addView(left,new LinearLayout.LayoutParams(0,dp(53),1));TextView own=label("@"+vault.nick(),14,MUTED);own.setGravity(Gravity.CENTER);own.setOnClickListener(v->settings());nav.addView(own,new LinearLayout.LayoutParams(0,dp(53),1));root.addView(nav);campaign();
 }
 JSONObject last(JSONArray a,String n){for(int i=a.length()-1;i>=0;i--){JSONObject m=a.optJSONObject(i);if(m!=null&&m.optString("peer").equals(n))return m;}return null;}
 String clock(long t){return new java.text.SimpleDateFormat("HH:mm",Locale.getDefault()).format(new Date(t));}
 void renderChats(){if(!screen.equals("chats")||content==null)return;content.removeAllViews();try{
  JSONObject d=vault.copy(),contacts=d.getJSONObject("contacts"),rooms=d.getJSONObject("rooms");JSONArray messages=d.getJSONArray("messages");List<String> items=new ArrayList<>();contacts.keys().forEachRemaining(items::add);rooms.keys().forEachRemaining(k->items.add("room:"+k));
  items.sort((a,b)->{JSONObject aa=last(messages,a),bb=last(messages,b);return Long.compare(bb==null?0:bb.optLong("time"),aa==null?0:aa.optLong("time"));});int total=0;
  for(String id:items){boolean group=id.startsWith("room:");JSONObject u=group?rooms.getJSONObject(id.substring(5)):contacts.getJSONObject(id);String name=u.optString(group?"title":"name",id),kind=group?u.optString("kind"):"personal";
   if(filter==1&&group||filter==2&&!kind.equals("group")||filter==3&&!kind.equals("channel"))continue;
   if(!(name+" "+id).toLowerCase(Locale.ROOT).contains(search.toLowerCase(Locale.ROOT)))continue;total++;
   LinearLayout item=row();pad(item,12);item.setBackground(shape(CARD,23));art(u.optString("avatar","preset:0"),53,item);LinearLayout detail=col();detail.setPadding(dp(12),0,dp(6),0);TextView title=label((kind.equals("channel")?"◈ ":kind.equals("group")?"◉ ":"")+name,16,TEXT);title.setTypeface(null,1);title.setSingleLine(true);title.setEllipsize(TextUtils.TruncateAt.END);detail.addView(title);space(detail,5);JSONObject last=last(messages,id);TextView preview=label(last==null?(group?u.getJSONArray("members").length()+" участников":"@"+id):Payload.preview(last),13,MUTED);preview.setSingleLine(true);preview.setEllipsize(TextUtils.TruncateAt.END);detail.addView(preview);item.addView(detail,new LinearLayout.LayoutParams(0,-2,1));item.addView(label(last==null?"":clock(last.optLong("time")),10,MUTED));item.setOnClickListener(v->openChat(id));content.addView(item,new LinearLayout.LayoutParams(-1,dp(85)));space(content,9);
  }
  if(total==0){space(content,32);Art a=new Art(this,"mascot");LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(175),dp(175));p.gravity=Gravity.CENTER_HORIZONTAL;content.addView(a,p);space(content,18);TextView empty=label("Скажи своим «привет»",21,TEXT);empty.setGravity(Gravity.CENTER);content.addView(empty);space(content,10);paragraph(content,"Нажми ＋ и найди друга по нику.\nВ меню слева можно создать группу или канал.");}
 }catch(Exception e){error(Api.message(e));}}
 void menu(){dialog().setTitle("OldЫ Chat").setItems(new String[]{"＋ Новый разговор","◉ Создать группу","◈ Создать канал","⚙ Настройки"},(d,w)->{if(w==0)findPeer();if(w==1)createRoom("group");if(w==2)createRoom("channel");if(w==3)settings();}).show();}
 void findPeer(){LinearLayout box=col();pad(box,16);EditText query=field(box,"Ник друга",false);query.setInputType(145);ScrollView scroll=new ScrollView(this);LinearLayout results=col();scroll.addView(results);box.addView(scroll,new LinearLayout.LayoutParams(-1,dp(220)));AlertDialog d=dialog().setTitle("Новый разговор").setView(box).setNegativeButton("Закрыть",null).create();box.addView(button("Найти",true,()->{String q=query.getText().toString().trim().toLowerCase(Locale.ROOT);if(!q.matches("[a-z0-9_]{1,24}")){error("Введите ник латиницей");return;}task(()->{JSONArray users=api.call("/users?q="+q,null,vault.token()).getJSONArray("users");runOnUiThread(()->{results.removeAllViews();if(users.length()==0)paragraph(results,"Никого не нашли. Проверь написание.");for(int i=0;i<users.length();i++){JSONObject u=users.optJSONObject(i);LinearLayout r=row();art(u.optString("avatar","preset:0"),44,r);TextView name=button(u.optString("name")+" · @"+u.optString("nick"),false,()->task(()->{vault.pin(u);runOnUiThread(()->{d.dismiss();openChat(u.optString("nick"));});}));r.addView(name,new LinearLayout.LayoutParams(0,-2,1));results.addView(r);space(results,8);}});});}));d.show();}
 void createRoom(String kind){LinearLayout box=col();pad(box,18);EditText title=field(box,kind.equals("group")?"Название группы":"Название канала",false),members=field(box,"Ники участников через запятую",false);paragraph(box,"До 50 участников. Укажи ники тех, кого хочешь добавить.");dialog().setTitle(kind.equals("group")?"Новая группа":"Новый канал").setView(box).setNegativeButton("Отмена",null).setPositiveButton("Создать",(d,w)->{String t=title.getText().toString(),n=members.getText().toString();task(()->{JSONObject body=new JSONObject().put("title",t).put("kind",kind).put("members",nickList(n));JSONObject room=api.call("/room/create",body,vault.token());vault.putRoom(room);runOnUiThread(()->openChat("room:"+room.optString("id")));});}).show();}
 JSONArray nickList(String s)throws Exception{JSONArray a=new JSONArray();for(String n:s.toLowerCase(Locale.ROOT).split("[,\\s]+")){n=n.replace("@","").trim();if(n.isEmpty())continue;if(!n.matches("[a-z0-9_]{3,24}"))throw new Exception("Проверь ники участников");a.put(n);}return a;}
 void openChat(String target){chat=target;base("chat");try{
  boolean group=target.startsWith("room:");JSONObject u=group?vault.room(target.substring(5)):vault.peer(target);if(u==null){chats();return;}
  LinearLayout head=row();head.addView(button("‹",false,()->chats()),new LinearLayout.LayoutParams(dp(38),dp(44)));Art avatar=art(u.optString("avatar","preset:0"),42,head);avatar.setOnClickListener(v->chatInfo());LinearLayout info=col();info.setPadding(dp(9),0,dp(4),0);TextView title=label(u.optString(group?"title":"name",target),20,TEXT);title.setTypeface(null,1);title.setSingleLine(true);title.setEllipsize(TextUtils.TruncateAt.END);title.setOnClickListener(v->chatInfo());info.addView(title);typing=label(group?u.getJSONArray("members").length()+" участников":"@"+target,11,MUTED);info.addView(typing);head.addView(info,new LinearLayout.LayoutParams(0,dp(52),1));art("mascot",48,head);root.addView(head);space(root,12);
  messagesScroll=new ScrollView(this);messagesScroll.setFillViewport(true);content=col();messagesScroll.addView(content);root.addView(messagesScroll,new LinearLayout.LayoutParams(-1,0,1));space(root,8);
  boolean canWrite=!group||!u.optString("kind").equals("channel")||u.optString("owner").equals(vault.nick());
  if(canWrite){LinearLayout input=row();TextView plus=button("＋",false,()->attachments());input.addView(plus,new LinearLayout.LayoutParams(dp(40),dp(46)));input.addView(button("☺",false,()->emojis()),new LinearLayout.LayoutParams(dp(41),dp(46)));compose=new EditText(this);compose.setHint("Сообщение…");compose.setTextColor(TEXT);compose.setHintTextColor(MUTED);compose.setTextSize(15);compose.setMaxLines(5);compose.setInputType(1|131072|16384);pad(compose,10);compose.setBackground(shape(CARD,20));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,-2,1);cp.setMargins(dp(4),0,dp(4),0);input.addView(compose,cp);input.addView(button("↑",true,()->sendText()),new LinearLayout.LayoutParams(dp(43),dp(46)));root.addView(input);
   compose.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int f){}public void afterTextChanged(Editable e){}public void onTextChanged(CharSequence s,int a,int before,int count){if(!group&&System.currentTimeMillis()-lastTyping>4000){lastTyping=System.currentTimeMillis();work.execute(()->{try{api.call("/typing",new JSONObject().put("to",target),vault.token());}catch(Exception ignored){}});}}});
  }else paragraph(root,"Публикации автора канала");
  renderMessages();if(!group)pollTyping(target);
 }catch(Exception e){error(Api.message(e));}}
 void pollTyping(String target){ui.postDelayed(()->{if(!active||!screen.equals("chat")||!chat.equals(target))return;work.execute(()->{try{JSONObject p=api.call("/typing/"+target,null,vault.token());runOnUiThread(()->{if(screen.equals("chat")&&chat.equals(target)&&typing!=null)typing.setText(p.optBoolean("typing")?"печатает…":"@"+target);});}catch(Exception ignored){}});pollTyping(target);},4500);}
 void sendText(){String text=compose.getText().toString().trim();if(text.isEmpty())return;if(Crypto.bytes(text).length>12000){error("Сообщение слишком длинное");return;}try{send(new JSONObject().put("kind","text").put("text",text),null);}catch(Exception e){error(Api.message(e));}}
 void send(JSONObject p,String local){String target=chat;String draft=compose==null?"":compose.getText().toString();if(compose!=null)compose.setText("");task(()->{try{if(target.startsWith("room:")){JSONObject r=api.call("/room/"+target.substring(5),null,vault.token());vault.putRoom(r);JSONArray a=r.getJSONArray("members");for(int i=0;i<a.length();i++){String n=a.getString(i);if(!n.equals(vault.nick()))vault.pin(api.call("/user/"+n,null,vault.token()));}}vault.queuePayload(target,p,local);runOnUiThread(()->{if(chat.equals(target))renderMessages();});}catch(Exception e){runOnUiThread(()->{if(compose!=null&&chat.equals(target))compose.setText(draft);});throw e;}});}
 void renderMessages(){if(!screen.equals("chat"))return;boolean bottom=messagesScroll.getChildCount()==0||messagesScroll.getScrollY()+messagesScroll.getHeight()+dp(100)>=content.getHeight();content.removeAllViews();try{JSONArray a=vault.copy().getJSONArray("messages");String date="";for(int i=0;i<a.length();i++){JSONObject m=a.getJSONObject(i);if(!m.optString("peer").equals(chat))continue;String day=new java.text.SimpleDateFormat("d MMMM",new Locale("ru")).format(new Date(m.optLong("time")));if(!day.equals(date)){date=day;TextView d=label(day,10,MUTED);d.setGravity(Gravity.CENTER);pad(d,12);content.addView(d);}boolean out=m.optBoolean("out");LinearLayout line=row();line.setGravity(out?Gravity.RIGHT:Gravity.LEFT);LinearLayout bubble=col();pad(bubble,11);bubble.setBackground(shape(out?GREEN:CARD,21));int color=out?INK:TEXT;
   if(chat.startsWith("room:")&&!out){TextView author=label("@"+m.optString("from"),11,out?INK:MUTED);bubble.addView(author);space(bubble,5);}
   String kind=m.optString("kind","text");if(kind.equals("sticker")){art("sticker:"+m.optInt("sticker"),106,bubble);}else if(kind.equals("file")){TextView media=label(Payload.preview(m),16,color);bubble.addView(media);space(bubble,5);String mid=m.getString("id");TextView action=label(m.has("local")?"▶ Открыть · "+size(m.optLong("size")):Rtc.status.getOrDefault(mid,"↓ Скачать · "+size(m.optLong("size"))),11,out?0xff537340:MUTED);action.setMaxWidth(dp(210));bubble.addView(action);bubble.setOnClickListener(v->openMedia(m));}else{TextView text=label(m.optString("text"),16,color);text.setMaxWidth(dp(238));text.setTextIsSelectable(true);bubble.addView(text);}
   TextView time=label(clock(m.optLong("time"))+(out?(m.optString("status").equals("delivered")?"  ✓✓":"  ◷"):""),10,out?0xff58744a:MUTED);time.setGravity(Gravity.RIGHT);space(bubble,3);bubble.addView(time);line.addView(bubble);content.addView(line);space(content,8);
  }if(bottom)messagesScroll.post(()->messagesScroll.fullScroll(View.FOCUS_DOWN));
 }catch(Exception e){error(Api.message(e));}}
 String size(long b){return b>=1048576?String.format(Locale.ROOT,"%.1f МБ",b/1048576.):Math.max(1,b/1024)+" КБ";}
 void emojis(){LinearLayout box=col();pad(box,12);ScrollView scroll=new ScrollView(this);GridLayout grid=new GridLayout(this);grid.setColumnCount(6);scroll.addView(grid);box.addView(scroll,new LinearLayout.LayoutParams(-1,dp(350)));LinearLayout tabs=row();box.addView(tabs);AlertDialog d=dialog().setTitle("Настроение").setView(box).setNegativeButton("Закрыть",null).create();
  String[] groups={"😀 😃 😄 😁 😆 😅 😂 🤣 🥲 😊 😇 🙂 🙃 🫠 😉 😌 😍 🥰 😘 😗 😙 😚 😋 😛 😝 😜 🤪 🤨 🧐 🤓 😎 🥸 🤩 🥳 🙂‍↔️ 🙂‍↕️ 😏 😒 😞 😔 😟 😕 🙁 ☹️ 😣 😖 😫 😩 🥺 🥹 😢 😭 😤 😠 😡 🤬 🤯 😳 🥵 🥶 😶‍🌫️ 😱 😨 😰 😥 😓 🤗 🤔 🫣 🤭 🫢 🫡 🤫 🫥 🤥 😶 😐 😑 😬 🫨 🫤 😮‍💨 🙄 😯 😦 😧 😮 😲 🥱 😴 🤤 😪 😵 😵‍💫 🫩 🤐 🥴 🤢 🤮 🤧 😷 🤒 🤕 🤑 🤠 😈 👿 👹 👺 🤡 💩 👻 💀 ☠️ 👽 👾 🤖 🎃 😺 😸 😹 😻 😼 😽 🙀 😿 😾", "👋 🤚 🖐 ✋ 🖖 🫱 🫲 🫳 🫴 🫸 🫷 👌 🤌 🤏 ✌️ 🤞 🫰 🤟 🤘 🤙 👈 👉 👆 🖕 👇 ☝️ 🫵 👍 👎 ✊ 👊 🤛 🤜 👏 🙌 🫶 👐 🤲 🤝 🙏 💪 🦾 🦿 🦵 🦶 👂 🦻 👃 🧠 🫀 🫁 🦷 🦴 👀 👁 👅 👄 🫦 💋 ❤️ 🧡 💛 💚 💙 💜 🤎 🖤 🩶 🤍 🩷 🩵 ❤️‍🔥 ❤️‍🩹 💔 ❣️ 💕 💞 💓 💗 💖 💘 💝 💟 💯 💢 💥 💫 💦 💨 🕳 💬 👁️‍🗨️ 🗨 🗯 💭 💤", "🐶 🐱 🐭 🐹 🐰 🦊 🐻 🐼 🐻‍❄️ 🐨 🐯 🦁 🐮 🐷 🐸 🐵 🦄 🐝 🐛 🦋 🐌 🐞 🦀 🐙 🦑 🦐 🦞 🐠 🐟 🐬 🐳 🦈 🦭 🐊 🦖 🦕 🐉 🦜 🦉 🦚 🦩 🕊 🐕 🦮 🐈‍⬛ 🐎 🦓 🦒 🦔 🐿 🦫 🦦 🦥 🦨 🦘 🦬 🐏 🦙 🐐 🦌 🫎 🪿 🌵 🌲 🌳 🌴 🪴 🌱 🍀 ☘️ 🍃 🍂 🍁 🍄 🌷 🌹 🥀 🌺 🌸 🌼 🌻 🌞 🌝 🌚 🌙 ⭐ 🌟 ✨ ⚡ ☄️ 🔥 🌈 ☀️ 🌤 ⛅ 🌧 ⛈ 🌨 ❄️ ☃️ ⛄ 🌊", "🍏 🍎 🍐 🍊 🍋 🍌 🍉 🍇 🍓 🫐 🍒 🍑 🥭 🍍 🥥 🥝 🍅 🍆 🥑 🥦 🥬 🥒 🌶 🫑 🌽 🥕 🫒 🧄 🧅 🥔 🍠 🥐 🥯 🍞 🥖 🥨 🧀 🥚 🍳 🧈 🥞 🧇 🥓 🥩 🍗 🍖 🌭 🍔 🍟 🍕 🫓 🥪 🥙 🧆 🌮 🌯 🫔 🥗 🥘 🫕 🍝 🍜 🍲 🍛 🍣 🍱 🥟 🍙 🍘 🍚 🍢 🍡 🍧 🍨 🍦 🥧 🧁 🍰 🎂 🍮 🍭 🍬 🍫 🍿 🍩 🍪 🥛 ☕ 🍵 🧋 🥤 🧃 🍺 🥂 🍷 🍹 🧉", "🎮 🕹 🎲 🧩 ♟ 🎯 🎳 🎰 🎨 🎭 🎬 🎤 🎧 🎼 🎹 🥁 🎸 🎺 🎷 🎻 🪕 ⚽ 🏀 🏈 ⚾ 🎾 🏐 🏉 🥏 🏓 🏸 🏒 🏑 🥍 🏏 🏹 🥊 🥋 🛹 🛼 🛷 ⛸ 🎿 🏂 🏋️ 🤸 🤾 🏊 🚴 🏆 🥇 🥈 🥉 🏅 🎖 🎗 🎫 🎟 🚗 🚕 🚌 🚎 🏎 🚓 🚑 🚒 🚚 🚛 🚜 🛵 🏍 🛺 🚲 🛴 🚨 🚀 🛸 ✈️ 🛩 🚁 🚢 ⛵ ⚓ 🏠 🏡 🏘 🏙 🌃 🌆 🌇 🌉 🗼 🗽 🏰 🏝 🏖 ⛺ 💎 💍 💡 🔦 🕯 📱 💻 ⌨️ 🖥 🖱 📷 📸 📹 🎥 📺 📻 ⏰ ⌚ 🧭 🔋 🪫 🔌 🪄 🎁 🎈 🎉 🎊 🪅 🪩 🧸 🪆 ✅ ☑️ ✔️ ❌ ❎ ➕ ➖ ➗ ✖️ ♻️ 🔴 🟠 🟡 🟢 🔵 🟣 ⚫ ⚪ 🟤 🟩 🟨 🟦 🟪 🟥 🟧 🏁 🚩 🏳️‍🌈 🇷🇺 🇧🇾 🇰🇿 🇦🇲 🇨🇳 🇮🇳 🇧🇷"};
  java.util.function.IntConsumer fill=idx->{grid.removeAllViews();if(idx==5){for(int i=0;i<12;i++){final int n=i;Art a=new Art(this,"sticker:"+i);grid.addView(a,new ViewGroup.LayoutParams(dp(43),dp(52)));a.setOnClickListener(v->{try{send(new JSONObject().put("kind","sticker").put("sticker",n).put("text","Oldy Pop "+(n+1)),null);d.dismiss();}catch(Exception e){error(Api.message(e));}});}}else for(String emoji:groups[idx].split(" ")){TextView t=label(emoji,25,TEXT);t.setGravity(Gravity.CENTER);grid.addView(t,new ViewGroup.LayoutParams(dp(43),dp(45)));t.setOnClickListener(v->{if(compose!=null)compose.getText().insert(Math.max(0,compose.getSelectionStart()),emoji);});}};
  String[] icons={"☺","♡","♧","☕","☆","✨"};for(int i=0;i<icons.length;i++){final int n=i;tabs.addView(button(icons[i],false,()->fill.accept(n)),new LinearLayout.LayoutParams(0,dp(45),1));}fill.accept(0);d.show();
 }
 void chatInfo(){task(()->{boolean group=chat.startsWith("room:");String target=chat;JSONObject u=api.call(group?"/room/"+target.substring(5):"/user/"+target,null,vault.token());if(group)vault.putRoom(u);else vault.pin(u);runOnUiThread(()->{
  LinearLayout b=col();pad(b,18);art(u.optString("avatar","preset:0"),92,b);space(b,16);paragraph(b,group?u.optString("kind").equals("channel")?"Канал":"Группа":"@"+target);space(b,10);
  if(group){JSONArray members=u.optJSONArray("members");List<String> names=new ArrayList<>();for(int i=0;i<members.length();i++)names.add("@"+members.optString(i));paragraph(b,String.join(", ",names));space(b,14);if(u.optString("owner").equals(vault.nick())){b.addView(button("Аватар чата",false,()->avatarPicker(target.substring(5))));space(b,10);b.addView(button("Изменить участников",false,()->editRoom(u)));}else b.addView(button("Покинуть",false,()->task(()->{api.call("/room/leave",new JSONObject().put("id",u.optString("id")),vault.token());vault.rooms(api.call("/rooms",null,vault.token()).getJSONArray("rooms"));runOnUiThread(()->chats());})));}
  else paragraph(b,u.optString("bio").isEmpty()?"На связи в OldЫ Chat":u.optString("bio"));dialog().setTitle(u.optString(group?"title":"name")).setView(b).setPositiveButton("Закрыть",null).show();
 });});}
 void editRoom(JSONObject r){LinearLayout b=col();pad(b,18);EditText title=field(b,"Название",false),members=field(b,"Ники через запятую",false);title.setText(r.optString("title"));List<String> names=new ArrayList<>();JSONArray a=r.optJSONArray("members");for(int i=0;i<a.length();i++)names.add(a.optString(i));members.setText(String.join(", ",names));dialog().setTitle("Изменить чат").setView(b).setNegativeButton("Отмена",null).setPositiveButton("Сохранить",(d,w)->{String t=title.getText().toString(),n=members.getText().toString();task(()->{JSONArray list=nickList(n);JSONObject x=api.call("/room/update",new JSONObject().put("id",r.getString("id")).put("title",t).put("members",list),vault.token());vault.putRoom(x);runOnUiThread(()->openChat("room:"+r.optString("id")));});}).show();}
 void settings(){base("settings");title("Настройки",()->{if(vault.token().isEmpty())auth(false);else chats();});ScrollView scroll=new ScrollView(this);LinearLayout b=col();scroll.addView(b);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
  if(!vault.token().isEmpty())try{JSONObject d=vault.copy();LinearLayout profile=row();Art av=art(d.optString("avatar","preset:0"),70,profile);av.setOnClickListener(v->avatarPicker(""));LinearLayout text=col();text.setPadding(dp(16),0,0,0);TextView name=label(d.optString("name",vault.nick()),22,TEXT);name.setTypeface(null,1);text.addView(name);text.addView(label("@"+vault.nick(),13,MUTED));profile.addView(text);profile.setOnClickListener(v->editProfile());b.addView(profile);space(b,13);b.addView(button("Изменить профиль и фото",false,()->editProfile()));space(b,22);}catch(Exception ignored){}
  paragraph(b,"ПОДКЛЮЧЕНИЕ");space(b,10);network=label(ChatService.state,17,TEXT);b.addView(network);space(b,9);b.addView(button("Проверить подключение",false,()->task(()->{JSONObject h=api.check();if(!h.optString("service").equals("oldy-chat"))throw new Exception("Не удалось проверить подключение");ChatService.state="Подключено";runOnUiThread(()->{if(network!=null)network.setText("Подключено");if(!vault.token().isEmpty())startChat();Toast.makeText(this,"Подключено",Toast.LENGTH_SHORT).show();});})));space(b,24);
  paragraph(b,"ОФОРМЛЕНИЕ");space(b,10);LinearLayout themes=row();String[] modes={"light","dark","green"},labels={"Светлая","Тёмная","Зелёная"};for(int i=0;i<3;i++){final String m=modes[i];themes.addView(button(labels[i],Notices.prefs(this).getString("theme","dark").equals(m),()->{Notices.prefs(this).edit().putString("theme",m).apply();settings();}),new LinearLayout.LayoutParams(0,dp(51),1));}b.addView(themes);space(b,8);toggle(b,"Анимации","animations",true);space(b,20);
  paragraph(b,"УВЕДОМЛЕНИЯ");space(b,9);toggle(b,"Новые сообщения","notifications",true);toggle(b,"Звук Oldy Pop","sound",true);toggle(b,"Вибрация","vibration",true);toggle(b,"Показывать текст","preview",false);space(b,8);b.addView(button("Послушать звук ♪",false,()->{try{MediaPlayer p=MediaPlayer.create(this,R.raw.oldy_chime);p.setOnCompletionListener(x->x.release());p.start();}catch(Exception ignored){}}));space(b,10);b.addView(button("Разрешения уведомлений",false,()->startActivity(new Intent(Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(Settings.EXTRA_APP_PACKAGE,getPackageName()))));space(b,10);b.addView(button("Доставка с выключенным экраном",false,()->background()));space(b,20);
  if(!vault.nick().isEmpty()){b.addView(button("Сохранить резервную копию",false,()->backup(false)));space(b,10);}if(vault.token().isEmpty())b.addView(button("Восстановить из копии",false,()->backup(true)));
  if(!vault.token().isEmpty()){b.addView(button("Выйти из аккаунта",false,()->dialog().setTitle("Выйти?").setMessage("История останется на этом телефоне.").setNegativeButton("Отмена",null).setPositiveButton("Выйти",(d,w)->task(()->{try{api.call("/logout",new JSONObject(),vault.token());}finally{synchronized(vault){vault.data.remove("token");vault.save();}stopService(new Intent(this,ChatService.class));runOnUiThread(()->auth(false));}})).show()));space(b,12);}
  space(b,12);b.addView(button("О приложении",false,()->error("OldЫ Chat · 0.2 beta\n\nПрямые вложения — до 25 МБ. Для передачи откройте чат на обоих телефонах. История и вложения остаются на устройствах; аватарки и состав групп — на сервере. Резервная копия переносит аккаунт и текстовую историю. Медиа в неё не входят.\n\nРекламные интеграции выключены до настройки владельцем.")));space(b,14);paragraph(b,"OldЫ Chat · 0.2 beta");
 }
 void toggle(LinearLayout b,String label,String key,boolean def){Switch s=new Switch(this);s.setText(label);s.setTextColor(TEXT);s.setTextSize(15);pad(s,10);s.setChecked(Notices.prefs(this).getBoolean(key,def));s.setOnCheckedChangeListener((v,on)->{Notices.prefs(this).edit().putBoolean(key,on).apply();if(on&&key.equals("notifications")&&Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},10);});b.addView(s,new LinearLayout.LayoutParams(-1,dp(50)));}
 void background(){PowerManager p=getSystemService(PowerManager.class);dialog().setTitle("Сообщения при погашенном экране").setMessage("Разреши чату работать в фоне. Это может увеличить расход батареи. На Xiaomi и некоторых других телефонах также включи автозапуск в настройках приложения.\n\n"+(p.isIgnoringBatteryOptimizations(getPackageName())?"Ограничение батареи уже снято.":"Сейчас Android может задерживать доставку.")).setNegativeButton("Закрыть",null).setPositiveButton(p.isIgnoringBatteryOptimizations(getPackageName())?"Настройки приложения":"Разрешить",(d,w)->{Intent i=p.isIgnoringBatteryOptimizations(getPackageName())?new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())):new Intent(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS,Uri.parse("package:"+getPackageName()));try{startActivity(i);}catch(Exception e){startActivity(new Intent(Settings.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS));}}).show();}
 void editProfile(){try{JSONObject data=vault.copy();LinearLayout b=col();pad(b,18);Art a=art(data.optString("avatar","preset:0"),85,b);a.setOnClickListener(v->avatarPicker(""));space(b,10);b.addView(button("Выбрать аватар",false,()->avatarPicker("")));space(b,15);EditText name=field(b,"Имя",false),bio=field(b,"О себе",false);name.setText(data.optString("name"));bio.setText(data.optString("bio"));dialog().setTitle("Твой профиль").setView(b).setNegativeButton("Отмена",null).setPositiveButton("Сохранить",(d,w)->{String n=name.getText().toString(),about=bio.getText().toString();task(()->{vault.profile(api.call("/profile",new JSONObject().put("name",n).put("bio",about),vault.token()));runOnUiThread(()->settings());});}).show();}catch(Exception e){error(Api.message(e));}}
 void avatarPicker(String room){avatarRoom=room;LinearLayout b=col();pad(b,15);GridLayout grid=new GridLayout(this);grid.setColumnCount(4);b.addView(grid);AlertDialog d=dialog().setTitle("Выбери себя").setView(b).setNegativeButton("Закрыть",null).create();for(int i=0;i<12;i++){final int n=i;Art a=new Art(this,"preset:"+i);grid.addView(a,new ViewGroup.LayoutParams(dp(62),dp(70)));a.setOnClickListener(v->{d.dismiss();task(()->uploadAvatar(new JSONObject().put("avatar","preset:"+n),room));});}space(b,12);b.addView(button("Загрузить своё фото",true,()->{avatarRoom=room;d.dismiss();Intent pick=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(pick,31);}));space(b,10);paragraph(b,"Фото профиля будет храниться на сервере OldЫ Chat.");d.show();}
 void uploadAvatar(JSONObject p,String room)throws Exception{JSONObject r;if(room.isEmpty()){r=api.call("/profile",p,vault.token());vault.profile(r);}else{p.put("id",room);r=api.call("/room/update",p,vault.token());vault.putRoom(r);}runOnUiThread(()->{if(room.isEmpty())settings();else openChat("room:"+room);});}
 void attachments(){if(chat.startsWith("room:")){error("Фото, видео и голосовые пока доступны в личных разговорах.");return;}dialog().setTitle("Отправить").setItems(new String[]{"📷 Фото","▶ Видео","🎙 Голосовое сообщение"},(d,w)->{mediaTarget=chat;if(w==2)record();else{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT).setType(w==0?"image/*":"video/*").addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,w==0?32:33);}}).show();}
 void record(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},11);return;}try{recording=new File(getCacheDir(),"voice-"+System.currentTimeMillis()+".m4a");recorder=new MediaRecorder();recorder.setAudioSource(MediaRecorder.AudioSource.MIC);recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);recorder.setAudioEncodingBitRate(64000);recorder.setAudioSamplingRate(44100);recorder.setMaxDuration(180000);recorder.setOutputFile(recording.getAbsolutePath());recorder.prepare();recorder.start();AlertDialog d=dialog().setTitle("● Записываем голос").setMessage("Говори — я слушаю. До 3 минут.").setNegativeButton("Отмена",(v,w)->stopRecording(false)).setPositiveButton("Отправить",(v,w)->stopRecording(true)).create();d.setOnCancelListener(v->stopRecording(false));recorder.setOnInfoListener((r,what,extra)->{if(what==MediaRecorder.MEDIA_RECORDER_INFO_MAX_DURATION_REACHED){d.dismiss();stopRecording(true);}});d.show();}catch(Exception e){stopRecording(false);error("Не удалось включить микрофон");}}
 void stopRecording(boolean send){if(recorder==null)return;try{recorder.stop();}catch(Exception e){send=false;}recorder.release();recorder=null;File file=recording;if(send){String target=mediaTarget;task(()->{try{JSONObject p=MediaFiles.importFile(this,Uri.fromFile(file),"audio/mp4","Голосовое сообщение");String local=p.getString("local");p.remove("local");vault.queuePayload(target,p,local);runOnUiThread(()->renderMessages());}finally{file.delete();}});}else if(file!=null)file.delete();}
 public void onRequestPermissionsResult(int request,String[] p,int[] result){super.onRequestPermissionsResult(request,p,result);if(request==11&&result.length>0&&result[0]==PackageManager.PERMISSION_GRANTED)record();}
 void openMedia(JSONObject m){if(!m.has("local")){if(m.optBoolean("out")){error("Этот файл остался на прежнем телефоне.");return;}if(ChatService.instance==null){startChat();error("Подключаемся. Нажмите на вложение ещё раз.");}else{ChatService.instance.rtc.request(m);renderMessages();}return;}task(()->{byte[] bytes=MediaFiles.bytes(this,m.getString("local"));String mime=m.optString("mime");runOnUiThread(()->{if(mime.startsWith("image/")){BitmapFactory.Options options=new BitmapFactory.Options();options.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if((long)options.outWidth*options.outHeight>60000000){error("Изображение слишком большое");return;}options.inJustDecodeBounds=false;options.inSampleSize=Math.max(1,Math.max(options.outWidth,options.outHeight)/1600);Bitmap bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);if(bitmap==null){error("Не удалось открыть изображение");return;}ImageView image=new ImageView(this);image.setImageBitmap(bitmap);image.setAdjustViewBounds(true);dialog().setView(image).setPositiveButton("Закрыть",(d,w)->bitmap.recycle()).show();}else play(bytes,mime);});});}
 void play(byte[] data,String mime){try{if(player!=null)player.release();player=new MediaPlayer();MediaPlayer current=player;current.setDataSource(new MediaDataSource(){public long getSize(){return data.length;}public int readAt(long p,byte[] out,int off,int n){if(p>=data.length)return -1;int size=Math.min(n,data.length-(int)p);System.arraycopy(data,(int)p,out,off,size);return size;}public void close(){}});LinearLayout b=col();pad(b,18);if(mime.startsWith("video/")){SurfaceView video=new SurfaceView(this);b.addView(video,new LinearLayout.LayoutParams(-1,dp(300)));video.getHolder().addCallback(new SurfaceHolder.Callback(){public void surfaceCreated(SurfaceHolder h){current.setDisplay(h);current.prepareAsync();}public void surfaceChanged(SurfaceHolder h,int f,int w,int ht){}public void surfaceDestroyed(SurfaceHolder h){}});}else current.prepareAsync();b.addView(button("⏯ Пауза / продолжить",false,()->{try{if(current.isPlaying())current.pause();else current.start();}catch(Exception ignored){}}));current.setOnPreparedListener(p->p.start());current.setOnErrorListener((p,w,e)->{error("Не удалось воспроизвести этот формат");return true;});AlertDialog d=dialog().setTitle(mime.startsWith("video/")?"Видео":"Голосовое сообщение").setView(b).setPositiveButton("Закрыть",null).create();d.setOnDismissListener(x->{current.release();if(player==current)player=null;});d.show();}catch(Exception e){error("Не удалось открыть запись");}}
 void campaign(){work.execute(()->{try{JSONObject ad=api.call("/campaign",null,vault.token());if(!ad.optBoolean("enabled"))return;int revision=ad.optInt("revision");android.content.SharedPreferences seen=getSharedPreferences("campaign",0);if(revision<=seen.getInt("seen",0))return;Uri uri=Uri.parse(ad.getString("url"));if(!"https".equals(uri.getScheme())||uri.getHost()==null)return;runOnUiThread(()->{if(isFinishing()||!screen.equals("chats"))return;seen.edit().putInt("seen",revision).apply();dialog().setTitle("Реклама · "+ad.optString("title")).setMessage(ad.optString("text")).setNegativeButton("Закрыть",null).setPositiveButton("Подробнее",(d,w)->{try{startActivity(new Intent(Intent.ACTION_VIEW,uri));}catch(Exception e){error("Не удалось открыть браузер");}}).show();});}catch(Exception ignored){}});}
 void backup(boolean restore){LinearLayout b=col();pad(b,18);EditText p=field(b,"Пароль копии · от 10 символов",true);dialog().setTitle(restore?"Восстановить копию":"Сохранить копию").setMessage("Запомни этот пароль. Он понадобится для восстановления аккаунта и истории. Фото, видео и голосовые в копию не входят.").setView(b).setNegativeButton("Отмена",null).setPositiveButton("Продолжить",(d,w)->{char[] password=p.getText().toString().toCharArray();if(password.length<10){error("Нужно минимум 10 символов");return;}if(restore){restorePassword=password;startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("*/*").addCategory(Intent.CATEGORY_OPENABLE),22);}else task(()->{try{backupText=Crypto.exportBackup(vault.backup(),password);runOnUiThread(()->startActivityForResult(new Intent(Intent.ACTION_CREATE_DOCUMENT).setType("application/octet-stream").putExtra(Intent.EXTRA_TITLE,"OldyChat-backup.oldy").addCategory(Intent.CATEGORY_OPENABLE),21));}finally{Arrays.fill(password,'\0');}});}).show();}
 protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(result!=RESULT_OK||data==null||data.getData()==null){if(r==21)backupText=null;if(r==22&&restorePassword!=null)Arrays.fill(restorePassword,'\0');return;}Uri uri=data.getData();
  if(r==21)task(()->{try(OutputStream o=getContentResolver().openOutputStream(uri)){o.write(Crypto.bytes(backupText));backupText=null;runOnUiThread(()->error("Копия сохранена."));}});
  if(r==22)task(()->{try{String raw=Api.read(getContentResolver().openInputStream(uri),50000000);vault.restore(Crypto.importBackup(raw,restorePassword));runOnUiThread(()->{auth(false);error("Копия восстановлена. Войди с ником и паролем.");});}finally{Arrays.fill(restorePassword,'\0');}});
  if(r==31){String room=avatarRoom;task(()->{BitmapFactory.Options opt=new BitmapFactory.Options();opt.inJustDecodeBounds=true;try(InputStream in=getContentResolver().openInputStream(uri)){BitmapFactory.decodeStream(in,null,opt);}if(opt.outWidth<1||opt.outHeight<1)throw new Exception("Не удалось открыть фото");opt.inSampleSize=Math.max(1,Math.max(opt.outWidth,opt.outHeight)/512);opt.inJustDecodeBounds=false;Bitmap bm;try(InputStream in=getContentResolver().openInputStream(uri)){bm=BitmapFactory.decodeStream(in,null,opt);}if(bm==null)throw new Exception("Не удалось открыть фото");ByteArrayOutputStream out=new ByteArrayOutputStream();bm.compress(Bitmap.CompressFormat.JPEG,85,out);bm.recycle();uploadAvatar(new JSONObject().put("photo",Crypto.b64(out.toByteArray())),room);});}
  if(r==32||r==33){String target=mediaTarget;task(()->{String mime=getContentResolver().getType(uri);if(mime==null||!mime.matches("image/(jpeg|png|webp)|video/(mp4|webm)"))throw new Exception("Выберите JPG, PNG, WebP, MP4 или WebM");JSONObject p=MediaFiles.importFile(this,uri,mime,mime.startsWith("video/")?"Видео":"Фото");String local=p.getString("local");p.remove("local");vault.queuePayload(target,p,local);runOnUiThread(()->renderMessages());});}
 }
}
