package chat.oldy;
import android.view.*;import android.widget.*;import org.json.JSONObject;

/** Conversation-owned selection survives live rebuilding of message bubbles. */
final class MessageSelection {
 static void bind(MainActivity a,View view,JSONObject message){if(message.optString("id").equals(view.getTag()))view.setAlpha(a.selectedMessage!=null&&message.optString("id").equals(a.selectedMessage.optString("id"))?.72f:1);view.setOnLongClickListener(v->{v.performHapticFeedback(HapticFeedbackConstants.LONG_PRESS);show(a,message);return true;});if(view instanceof ViewGroup){ViewGroup g=(ViewGroup)view;for(int i=0;i<g.getChildCount();i++)bind(a,g.getChildAt(i),message);}}
 static void clear(MainActivity a){if(a.selectedMessage==null)return;String id=a.selectedMessage.optString("id");a.selectedMessage=null;if(a.selectionBar!=null&&a.selectionBar.getParent() instanceof ViewGroup)((ViewGroup)a.selectionBar.getParent()).removeView(a.selectionBar);if(a.selectionHeader!=null)a.selectionHeader.setVisibility(View.VISIBLE);a.selectionBar=null;a.selectionHeader=null;if(a.content!=null){View bubble=a.content.findViewWithTag(id);if(bubble!=null)bubble.setAlpha(1);}}
 static void show(MainActivity a,JSONObject message){if(!a.screen.equals("chat"))return;clear(a);a.selectedMessage=message;a.selectionHeader=a.root.getChildAt(0);if(a.selectionHeader!=null)a.selectionHeader.setVisibility(View.GONE);LinearLayout bar=a.row();a.selectionBar=bar;bar.setGravity(Gravity.CENTER_VERTICAL);bar.setBackground(a.glass(24));a.pad(bar,4);bar.addView(key(a,"close","Отмена",()->clear(a)),new LinearLayout.LayoutParams(a.dp(42),a.dp(48)));TextView count=a.label(I18n.t("Выбрано 1"),14,a.TEXT);count.setTypeface(null,1);count.setSingleLine(true);count.setEllipsize(android.text.TextUtils.TruncateAt.END);bar.addView(count,new LinearLayout.LayoutParams(0,-2,1));bar.addView(key(a,"reply","Ответить",()->{clear(a);if(a.compose!=null){a.replyTo=message;a.renderReply();a.compose.requestFocus();}}),new LinearLayout.LayoutParams(a.dp(42),a.dp(48)));bar.addView(key(a,"copy","Копировать",()->{clear(a);a.getSystemService(android.content.ClipboardManager.class).setPrimaryClip(android.content.ClipData.newPlainText("Oldi",message.optString("text")));}),new LinearLayout.LayoutParams(a.dp(42),a.dp(48)));bar.addView(key(a,"more","Действия",()->{clear(a);a.messageMenu(message);}),new LinearLayout.LayoutParams(a.dp(42),a.dp(48)));try{if(message.optBoolean("out")||a.vault.moderator()||!Conversation.community(a.chat))bar.addView(key(a,"delete","Удалить",()->{clear(a);a.deletePost(message);}),new LinearLayout.LayoutParams(a.dp(42),a.dp(48)));}catch(Exception ignored){}a.root.addView(bar,0,new LinearLayout.LayoutParams(-1,a.dp(68)));if(a.content!=null){View bubble=a.content.findViewWithTag(message.optString("id"));if(bubble!=null)bubble.setAlpha(.72f);}}
 static View key(MainActivity a,String icon,String label,Runnable action){UiIcon v=new UiIcon(a,icon,a.TEXT);v.setContentDescription(I18n.t(label));v.setOnClickListener(w->action.run());v.setOnLongClickListener(w->{Toast.makeText(a,I18n.t(label),Toast.LENGTH_SHORT).show();return true;});return v;}
}
