package chat.oldy;
import android.content.Context;import android.net.*;import org.json.*;import java.net.*;import javax.net.ssl.HttpsURLConnection;

final class NetworkDiagnostics {
 static Network physical(Context c){ConnectivityManager cm=(ConnectivityManager)c.getSystemService(Context.CONNECTIVITY_SERVICE);Network active=cm.getActiveNetwork(),best=null;int score=-1;for(Network n:cm.getAllNetworks()){NetworkCapabilities caps=cm.getNetworkCapabilities(n);if(caps==null||!caps.hasCapability(NetworkCapabilities.NET_CAPABILITY_NOT_VPN)||!caps.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET))continue;if(n.equals(active))return n;int rank=(caps.hasCapability(NetworkCapabilities.NET_CAPABILITY_VALIDATED)?4:0)+(caps.hasTransport(NetworkCapabilities.TRANSPORT_WIFI)?2:caps.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR)?1:0);if(rank>score){score=rank;best=n;}}return best;}
 static boolean otherVpn(Context c){if(TunnelStateRepository.on())return false;ConnectivityManager cm=(ConnectivityManager)c.getSystemService(Context.CONNECTIVITY_SERVICE);for(Network n:cm.getAllNetworks()){NetworkCapabilities caps=cm.getNetworkCapabilities(n);if(caps!=null&&caps.hasTransport(NetworkCapabilities.TRANSPORT_VPN))return true;}return false;}
 static String network(Context c){Network n=physical(c);if(n==null)return I18n.t("Нет сети");NetworkCapabilities caps=((ConnectivityManager)c.getSystemService(Context.CONNECTIVITY_SERVICE)).getNetworkCapabilities(n);return caps!=null&&caps.hasTransport(NetworkCapabilities.TRANSPORT_WIFI)?"Wi-Fi":caps!=null&&caps.hasTransport(NetworkCapabilities.TRANSPORT_CELLULAR)?"Mobile":I18n.t("Другая сеть");}
 static JSONObject check(Context c){JSONObject j=new JSONObject();try{j.put("local_tunnel",TunnelStateRepository.on()?"ON":"OFF").put("network",network(c)).put("mode",TunnelStateRepository.mode(c)).put("last_error",TunnelStateRepository.lastError(c)).put("webview_route",TunnelStateRepository.webPort>0&&TunnelStateRepository.on()?"local CONNECT":"TUN fallback").put("webview_connections",TunnelStateRepository.webConnections).put("webview_received",TunnelStateRepository.webRx);Network n=physical(c);if(n==null){j.put("dns","OFFLINE");return j;}boolean dns=true;for(String host:new String[]{"www.youtube.com","googlevideo.com"}){boolean resolved;try{resolved=n.getAllByName(host).length>0;}catch(Exception e){resolved=false;}j.put(host+"_dns",resolved?"OK":"FAILED");dns&=resolved;}j.put("dns",dns?"OK":"PARTIAL");j.put("youtube_https",probe(n,"https://www.youtube.com/"));j.put("googlevideo_https",probe(n,"https://googlevideo.com/"));j.put("tun_tx_bytes",TunnelStateRepository.txBytes).put("tun_rx_bytes",TunnelStateRepository.rxBytes);if(TunnelStateRepository.on())j.put("youtube_via_local",probe(null,"https://www.youtube.com/"));j.put("scope","Oldy YouTube only; direct device connection; no remote VPN");}catch(Exception e){try{j.put("error","DIAGNOSTIC_FAILED");}catch(Exception ignored){}}return j;}
 static String probe(Network n,String url){HttpsURLConnection c=null;try{c=(HttpsURLConnection)(n==null?new URL(url).openConnection():n.openConnection(new URL(url)));c.setRequestMethod("HEAD");c.setConnectTimeout(5000);c.setReadTimeout(5000);c.setInstanceFollowRedirects(false);int status=c.getResponseCode();return "TLS OK · HTTP "+status;}catch(Exception e){return "UNREACHABLE";}finally{if(c!=null)c.disconnect();}}
}
