package chat.oldy;
import android.app.Dialog;import android.graphics.Typeface;import android.view.*;import android.widget.*;import java.util.Locale;
/** Explicit states and wall-clock deadlines survive screen changes and app restarts. */
final class NotificationSheet {
 static String remaining(long end){long seconds=Math.max(0,(end-System.currentTimeMillis()+999)/1000);return seconds>=3600?String.format(Locale.ROOT,"%d:%02d:%02d",seconds/3600,seconds%3600/60,seconds%60):String.format(Locale.ROOT,"%02d:%02d",seconds/60,seconds%60);}
 static String status(MainActivity a,String peer){long end=Notices.muteUntil(a,a.vault,peer);return end==-1?I18n.t("Выключены бессрочно"):end>System.currentTimeMillis()?I18n.t("Выключены · ещё ")+remaining(end):I18n.t("Уведомления включены");}
 static void quiet(MainActivity a){Vault owner=a.vault;LinearLayout b=a.col();a.paragraph(b,I18n.t("Сообщения продолжают приходить во все чаты. На 25 минут отключаются только звук и вибрация уведомлений."));a.space(b,18);TextView clock=a.label("",42,a.light?0xff2468aa:0xff8bdcff);clock.setTypeface(Typeface.create("sans-serif-light",0));clock.setGravity(Gravity.CENTER);b.addView(clock,new LinearLayout.LayoutParams(-1,a.dp(68)));TextView state=a.label("",13,a.MUTED);state.setGravity(Gravity.CENTER);b.addView(state,new LinearLayout.LayoutParams(-1,-2));a.space(b,18);TextView action=a.button("",true,()->{});b.addView(action,new LinearLayout.LayoutParams(-1,a.dp(52)));a.sheet(I18n.t("Все чаты без звука"),b);Dialog dialog=a.activeSheet;
  Runnable update=()->{boolean enabled=Notices.quietUntil(a,owner)>System.currentTimeMillis();clock.setText(enabled?remaining(Notices.quietUntil(a,owner)):"25:00");state.setText(enabled?I18n.t("До возвращения обычного режима"):I18n.t("Таймер выключен"));action.setText(enabled?I18n.t("Выключить сейчас"):I18n.t("Без звука на 25 минут"));};action.setOnClickListener(v->{Notices.quiet(a,owner,Notices.quietUntil(a,owner)>System.currentTimeMillis()?0:System.currentTimeMillis()+25*60000L);update.run();});ticker(a,dialog,update);
 }
 static void chat(MainActivity a,String peer){Vault owner=a.vault;LinearLayout b=a.col();TextView state=a.label("",15,a.TEXT);state.setTypeface(null,1);b.addView(state,new LinearLayout.LayoutParams(-1,-2));a.space(b,6);a.paragraph(b,I18n.t("Настройка действует только для этого чата. История и новые сообщения остаются доступны."));a.space(b,14);
  Switch toggle=new Switch(a);toggle.setText(I18n.t("Уведомления"));toggle.setTextSize(17);toggle.setTextColor(a.TEXT);toggle.setChecked(!Notices.muted(a,owner,peer,System.currentTimeMillis()));a.pad(toggle,12);toggle.setBackground(a.shape(a.light?0xffedf4ff:0xff172638,16));b.addView(toggle,new LinearLayout.LayoutParams(-1,a.dp(56)));a.space(b,14);
  String[] labels={I18n.t("На 30 минут"),I18n.t("На 1 час"),I18n.t("На 12 часов"),I18n.t("Навсегда")};long[] durations={30*60000L,60*60000L,12*3600000L,-1};TextView[] choices=new TextView[4];final long[] selected={0};
  for(int i=0;i<labels.length;i++){final long d=durations[i];TextView choice=a.button(labels[i],false,()->{});choices[i]=choice;choice.setGravity(Gravity.CENTER_VERTICAL);b.addView(choice,new LinearLayout.LayoutParams(-1,a.dp(48)));a.space(b,7);choice.setOnClickListener(v->{selected[0]=d;Notices.mute(a,owner,peer,d==-1?-1:System.currentTimeMillis()+d);toggle.setChecked(false);state.setText(status(a,peer));for(int j=0;j<choices.length;j++)choices[j].setText((durations[j]==d?"✓  ":"")+labels[j]);});}
  final boolean[] updating={false};toggle.setOnCheckedChangeListener((v,on)->{if(updating[0])return;Notices.mute(a,owner,peer,on?0:(Notices.muted(a,owner,peer,System.currentTimeMillis())?Notices.muteUntil(a,owner,peer):-1));if(on){selected[0]=0;for(int j=0;j<choices.length;j++)choices[j].setText(labels[j]);}state.setText(status(a,peer));});
  a.sheet(I18n.t("Уведомления чата"),b);Dialog dialog=a.activeSheet;ticker(a,dialog,()->{updating[0]=true;toggle.setChecked(!Notices.muted(a,owner,peer,System.currentTimeMillis()));updating[0]=false;state.setText(status(a,peer));});
 }
 static void ticker(MainActivity a,Dialog dialog,Runnable update){new Runnable(){public void run(){if(dialog==null||!dialog.isShowing()||a.isDestroyed())return;update.run();a.ui.postDelayed(this,1000);}}.run();}
 static void bindQuiet(MainActivity a,TextView label){Vault owner=a.vault;new Runnable(){public void run(){if(!label.isAttachedToWindow()||a.vault!=owner)return;long end=Notices.quietUntil(a,owner);label.setVisibility(end>System.currentTimeMillis()?View.VISIBLE:View.GONE);label.setText(I18n.t("Все чаты без звука · ")+remaining(end));a.ui.postDelayed(this,1000);}}.run();}
}
