package chat.oldy;

import android.app.*;import android.content.*;import android.content.pm.ActivityInfo;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.net.*;import android.net.http.SslError;import android.os.*;import android.view.*;import android.webkit.*;import android.widget.*;import org.json.*;import java.util.*;import java.util.concurrent.*;

/** Official IFrame API in a local trusted document. No JavaScript interface is exposed.
 * Native code only polls bounded player state; navigation and downloads cannot invoke app APIs. */
public final class OldiYouTubePlayer extends Activity {
 static final String ORIGIN="https://chat.oldy";static final int VPN_REQUEST=710;
 final Handler ui=new Handler(Looper.getMainLooper());final ExecutorService work=Executors.newSingleThreadExecutor();
 YouTubeLinkDetector.Target target;VideoLibraryStore library;WebView web;LinearLayout body,controls;FrameLayout frame;TextView title,status,shield,favorite,later,resume;ThemeLayout root;
 View fullscreen;WebChromeClient.CustomViewCallback fullscreenCallback;boolean foreground,loaded,requestedTunnel,tunnelWasOn,startedPermission;int generation;long lastPoll,loadedAt;double position,duration,resumeAt;String videoId="",videoTitle="";int textColor,muted,card,accent;boolean light;
 static void open(Context c,YouTubeLinkDetector.Target target,String title){c.startActivity(new Intent(c,OldiYouTubePlayer.class).putExtra("youtube_url",target.url()).putExtra("video_title",title));}
 static void external(Context c,YouTubeLinkDetector.Target t){try{c.startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(t.url())));}catch(Exception e){Toast.makeText(c,I18n.t("Не удалось открыть YouTube"),Toast.LENGTH_LONG).show();}}
 public void onCreate(Bundle state){super.onCreate(state);I18n.init(this);target=YouTubeLinkDetector.parse(getIntent().getStringExtra("youtube_url"));if(target==null){finish();return;}
  try{Vault vault=ChatService.vault(this);if(vault.token().isEmpty()){finish();return;}library=new VideoLibraryStore(this,vault.nick());}catch(Exception failure){finish();return;}
  videoId=target.videoId;videoTitle=getIntent().getStringExtra("video_title");if(videoTitle==null||videoTitle.length()>300)videoTitle="YouTube";light=Notices.prefs(this).getString("theme","dark").equals("light");textColor=light?0xff19283d:0xffedf5ff;muted=light?0xff576d85:0xffa8b8cf;card=light?0xeefaffff:0xee19283d;accent=light?0xffc0e1ff:0xff6fd9dd;
  root=new ThemeLayout(this,light,Notices.prefs(this).getString("theme","dark").equals("cyber"));root.setOrientation(1);root.setPadding(dp(12),dp(8),dp(12),dp(8));setContentView(root);getWindow().setStatusBarColor(Color.TRANSPARENT);getWindow().setNavigationBarColor(Color.TRANSPARENT);if(Build.VERSION.SDK_INT>=30)getWindow().setDecorFitsSystemWindows(false);root.setOnApplyWindowInsetsListener((v,insets)->{int l=insets.getSystemWindowInsetLeft(),t=insets.getSystemWindowInsetTop(),r=insets.getSystemWindowInsetRight(),b=insets.getSystemWindowInsetBottom();v.setPadding(dp(12)+l,dp(8)+t,dp(12)+r,dp(8)+b);return insets;});root.requestApplyInsets();
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.addView(button("‹",this::finish),new LinearLayout.LayoutParams(dp(48),dp(48)));TextView heading=label("YouTube · Oldi",20);head.addView(heading,new LinearLayout.LayoutParams(0,-2,1));head.addView(button("⤢",this::rotate),new LinearLayout.LayoutParams(dp(48),dp(48)));root.addView(head);
  frame=new FrameLayout(this);frame.setBackgroundColor(Color.BLACK);root.addView(frame,new LinearLayout.LayoutParams(-1,dp(230)));ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(1);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));title=label(videoTitle,19);body.addView(title);shield=label(I18n.t("Прямой просмотр · HTTPS"),13);shield.setTextColor(muted);shield.setOnClickListener(v->new AlertDialog.Builder(this).setTitle(I18n.t("Соединение Oldi")).setMessage(I18n.t("Видео передаётся напрямую между YouTube и вашим устройством. Сервер Oldi не передаёт видеопоток. Локальный режим не меняет ваш IP и не гарантирует обход блокировок. Шифрование обеспечивает HTTPS сервиса YouTube.")).setPositiveButton(I18n.t("Понятно"),null).show());body.addView(shield);
  status=label(I18n.t("Подготовка просмотра…"),13);body.addView(status);resume=button("",()->{if(web!=null)web.evaluateJavascript("if(window.oldiPlayer){oldiPlayer.seekTo("+(int)resumeAt+",true);oldiPlayer.playVideo();}",null);});resume.setVisibility(View.GONE);body.addView(resume);
  controls=new LinearLayout(this);controls.setOrientation(1);favorite=button(I18n.t("☆ В избранное"),()->toggle("favorite"));later=button(I18n.t("◷ Смотреть позже"),()->toggle("later"));controls.addView(favorite);controls.addView(later);controls.addView(button(I18n.t("Открыть в YouTube"),()->external(this,currentTarget())));controls.addView(button(I18n.t("Открыть обычно · без локального режима"),()->{requestedTunnel=false;LocalTunnelService.stop(this);loadPlayer();}));controls.addView(button(I18n.t("Проверить соединение"),this::diagnostics));body.addView(controls);
  refreshSaved();root.addOnLayoutChangeListener((v,l,t,r,b,ol,ot,or,ob)->fit());ui.post(this::chooseMode);
 }
 YouTubeLinkDetector.Target currentTarget(){return new YouTubeLinkDetector.Target(videoId.isEmpty()?target.videoId:videoId,target.playlistId,(int)position);}
 void chooseMode(){if(isFinishing())return;String mode=TunnelStateRepository.mode(this);if(mode.equals("off")){loadPlayer();return;}if(mode.equals("ask")){new AlertDialog.Builder(this).setTitle(I18n.t("Просмотр YouTube")).setMessage(I18n.t("Для просмотра включить локальный сетевой режим Oldi?")).setPositiveButton(I18n.t("Включить"),(d,w)->consent()).setNegativeButton(I18n.t("Открыть обычно"),(d,w)->loadPlayer()).setOnCancelListener(d->loadPlayer()).show();}else consent();}
 void consent(){if(NetworkDiagnostics.otherVpn(this)){status.setText(I18n.t("Уже работает другой VPN. Открываем обычный встроенный просмотр."));loadPlayer();return;}if(!Notices.prefs(this).getBoolean("youtube_vpn_disclosure",false)){new AlertDialog.Builder(this).setTitle(I18n.t("Локальный сетевой режим")).setMessage(I18n.t("Android запросит разрешение VPN. Oldi обработает DNS и соединения YouTube внутри приложения и отправит их через ваш интернет напрямую в YouTube. Другие приложения не включаются в VPN. Удалённого VPN-сервера нет. Видео, сетевые пакеты и история просмотра не передаются серверу Oldi. Ваш IP остаётся прежним. Режим можно отключить в настройках.")).setPositiveButton(I18n.t("Согласен, продолжить"),(d,w)->{Notices.prefs(this).edit().putBoolean("youtube_vpn_disclosure",true).apply();permission();}).setNegativeButton(I18n.t("Открыть обычно"),(d,w)->loadPlayer()).setOnCancelListener(d->loadPlayer()).show();}else permission();}
 void permission(){try{Intent request=android.net.VpnService.prepare(this);if(request!=null){startedPermission=true;startActivityForResult(request,VPN_REQUEST);}else startLocal();}catch(Exception e){TunnelStateRepository.fail(this,"VPN_UNAVAILABLE");loadPlayer();}}
 protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r==VPN_REQUEST){startedPermission=false;if(result==RESULT_OK)startLocal();else{TunnelStateRepository.fail(this,"VPN_PERMISSION_DENIED");loadPlayer();status.setText(I18n.t("Разрешение VPN отклонено. Доступен обычный просмотр."));}}}
 void startLocal(){requestedTunnel=true;try{LocalTunnelService.start(this);long deadline=SystemClock.elapsedRealtime()+7000;ui.post(new Runnable(){public void run(){if(isFinishing()||isDestroyed())return;if(TunnelStateRepository.on()){tunnelWasOn=true;loadPlayer();}else if(SystemClock.elapsedRealtime()<deadline)ui.postDelayed(this,200);else{requestedTunnel=false;LocalTunnelService.stop(OldiYouTubePlayer.this);loadPlayer();status.setText(I18n.t("Локальный режим не запустился. Открыт обычный просмотр."));}}});}catch(Exception e){requestedTunnel=false;TunnelStateRepository.fail(this,"VPN_START_DENIED");loadPlayer();}}
 void loadPlayer(){if(isFinishing()||isDestroyed())return;generation++;loaded=true;loadedAt=SystemClock.elapsedRealtime();if(web!=null){frame.removeView(web);web.stopLoading();web.destroy();}web=new WebView(this);frame.addView(web,new FrameLayout.LayoutParams(-1,-1));WebSettings settings=web.getSettings();settings.setJavaScriptEnabled(true);settings.setDomStorageEnabled(true);settings.setAllowFileAccess(false);settings.setAllowContentAccess(false);settings.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);settings.setMediaPlaybackRequiresUserGesture(true);settings.setJavaScriptCanOpenWindowsAutomatically(false);settings.setSupportMultipleWindows(false);settings.setSaveFormData(false);settings.setGeolocationEnabled(false);settings.setSafeBrowsingEnabled(true);CookieManager.getInstance().setAcceptThirdPartyCookies(web,true);
  web.setDownloadListener((url,userAgent,disposition,mime,length)->status.setText(I18n.t("Скачивание YouTube-видео не поддерживается")));
  web.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest request){Uri u=request.getUrl();if(request.isForMainFrame()){if(request.hasGesture()&&"https".equals(u.getScheme())&&u.getUserInfo()==null)try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception ignored){}return true;}return !"https".equals(u.getScheme());}public void onReceivedSslError(WebView v,SslErrorHandler handler,SslError error){handler.cancel();status.setText(I18n.t("Не удалось подтвердить безопасность соединения YouTube"));}public void onReceivedError(WebView v,WebResourceRequest request,WebResourceError error){if(request.isForMainFrame())status.setText(I18n.t("YouTube недоступен. Проверьте сеть или откройте видео во внешнем YouTube."));}public boolean onRenderProcessGone(WebView v,RenderProcessGoneDetail detail){frame.removeView(v);v.destroy();if(web==v)web=null;status.setText(I18n.t("Плеер остановился. Откройте видео снова."));return true;}});
  web.setWebChromeClient(new WebChromeClient(){public void onPermissionRequest(PermissionRequest request){request.deny();}public void onGeolocationPermissionsShowPrompt(String origin,GeolocationPermissions.Callback callback){callback.invoke(origin,false,false);}public void onShowCustomView(View view,CustomViewCallback callback){if(fullscreen!=null){callback.onCustomViewHidden();return;}fullscreen=view;fullscreenCallback=callback;((android.widget.FrameLayout)getWindow().getDecorView()).addView(view,new FrameLayout.LayoutParams(-1,-1));getWindow().getDecorView().setSystemUiVisibility(5894);}public void onHideCustomView(){hideFullscreen();}});
  try{String html;try(java.io.InputStream in=getAssets().open("youtube-player.html")){html=Api.read(in,30000);}JSONObject config=new JSONObject().put("videoId",videoId.isEmpty()?target.videoId:videoId).put("playlistId",target.playlistId).put("start",Math.max(target.startSeconds,(int)position)).put("hl",I18n.language());html=html.replace("__OLDI_CONFIG__",config.toString());web.loadDataWithBaseURL(ORIGIN+"/youtube/",html,"text/html","UTF-8",null);status.setText(I18n.t("Нажмите ▶ в плеере YouTube"));}catch(Exception e){status.setText(I18n.t("Не удалось открыть плеер"));}fit();
 }
 void hideFullscreen(){if(fullscreen==null)return;((android.widget.FrameLayout)getWindow().getDecorView()).removeView(fullscreen);fullscreen=null;if(fullscreenCallback!=null)fullscreenCallback.onCustomViewHidden();fullscreenCallback=null;getWindow().getDecorView().setSystemUiVisibility(0);setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED);fit();}
 void rotate(){boolean landscape=getResources().getConfiguration().orientation==android.content.res.Configuration.ORIENTATION_LANDSCAPE;setRequestedOrientation(landscape?ActivityInfo.SCREEN_ORIENTATION_PORTRAIT:ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);}
 void fit(){if(frame==null||root==null)return;int usable=root.getHeight()-root.getPaddingTop()-root.getPaddingBottom();boolean landscape=getResources().getConfiguration().orientation==android.content.res.Configuration.ORIENTATION_LANDSCAPE;int height=landscape?Math.max(dp(200),usable-dp(65)):Math.max(dp(210),(root.getWidth()-root.getPaddingLeft()-root.getPaddingRight())*9/16);LinearLayout.LayoutParams lp=(LinearLayout.LayoutParams)frame.getLayoutParams();if(lp.height!=height){lp.height=height;frame.setLayoutParams(lp);}}
 final Runnable poll=new Runnable(){public void run(){if(!foreground)return;shield.setText(I18n.t(TunnelStateRepository.on()?"🛡 Защищённое соединение Oldi":"Прямой просмотр · HTTPS"));if(requestedTunnel&&tunnelWasOn&&!TunnelStateRepository.on()){requestedTunnel=false;tunnelWasOn=false;loadPlayer();status.setText(I18n.t("Сеть изменилась. Локальный режим отключён; доступен обычный просмотр."));}snapshot();ui.postDelayed(this,2000);}};
 void snapshot(){if(web==null||!loaded)return;int seq=generation;web.evaluateJavascript("JSON.stringify(window.oldiSnapshot?window.oldiSnapshot():{})",raw->{if(seq!=generation||isDestroyed()||raw==null||raw.length()>5000)return;try{Object value=new JSONTokener(raw).nextValue();if(!(value instanceof String))return;JSONObject state=new JSONObject((String)value);int code=state.optInt("error");if(code!=0){status.setText(errorText(code));return;}if(!state.optBoolean("ready")){if(SystemClock.elapsedRealtime()-loadedAt>18000)status.setText(I18n.t("YouTube не отвечает. Проверьте соединение или откройте видео снаружи."));return;}
   String id=state.optString("id");if(!YouTubeLinkDetector.video(id))return;boolean changed=!id.equals(videoId);videoId=id;String t=state.optString("title");if(!t.isEmpty()){videoTitle=t.substring(0,Math.min(300,t.length()));title.setText(videoTitle);}double p=state.optDouble("position",0),dur=state.optDouble("duration",0);if(!Double.isFinite(p)||!Double.isFinite(dur)||p<0||p>86400||dur<0||dur>86400)return;position=p;duration=dur;long now=SystemClock.elapsedRealtime();double watched=foreground&&state.optInt("state")==1&&lastPoll>0?Math.min(3,(now-lastPoll)/1000.0):0;lastPoll=now;if(state.optInt("state")==1)resume.setVisibility(View.GONE);final String currentId=id,currentTitle=videoTitle;int playbackState=state.optInt("state",-1);if(playbackState==1||playbackState==2||playbackState==0)work.execute(()->{try{library.update(currentId,currentTitle,p,dur,watched);}catch(Exception ignored){}});if(changed)refreshSaved();
  }catch(Exception ignored){}});}
 static String errorText(int code){if(code==101||code==150)return I18n.t("Это видео нельзя воспроизвести внутри Oldi. Откройте во внешнем YouTube.");if(code==100)return I18n.t("Видео удалено или доступ ограничен владельцем");if(code==153)return I18n.t("YouTube не подтвердил встроенный плеер. Обновите Android System WebView или откройте YouTube.");if(code==5)return I18n.t("YouTube не смог воспроизвести видео. Возможны ограничения региона, возраста или формата.");return I18n.t("YouTube недоступен. Проверьте сеть или откройте видео во внешнем YouTube.");}
 void refreshSaved(){if(!YouTubeLinkDetector.video(videoId)){favorite.setVisibility(View.GONE);later.setVisibility(View.GONE);return;}favorite.setVisibility(View.VISIBLE);later.setVisibility(View.VISIBLE);String id=videoId;work.execute(()->{try{JSONObject saved=library.get(id);runOnUiThread(()->{if(!id.equals(videoId)||isDestroyed())return;favorite.setText(I18n.t(saved.optBoolean("favorite")?"★ В избранном":"☆ В избранное"));later.setText(I18n.t(saved.optBoolean("later")?"✓ Смотреть позже":"◷ Смотреть позже"));double savedPosition=saved.optDouble("position",0);if(savedPosition>=5&&savedPosition<Math.max(30,saved.optDouble("duration",86400)-5)){resumeAt=savedPosition;resume.setText(I18n.t("Продолжить с ")+VideoLibraryStore.time(resumeAt));resume.setVisibility(View.VISIBLE);}});}catch(Exception ignored){}});}
 void toggle(String field){String id=videoId;if(!YouTubeLinkDetector.video(id))return;work.execute(()->{try{library.toggle(id,field);runOnUiThread(this::refreshSaved);}catch(Exception ignored){}});}
 void diagnostics(){status.setText(I18n.t("Проверяем соединение…"));work.execute(()->{JSONObject report=NetworkDiagnostics.check(this);runOnUiThread(()->{if(isDestroyed())return;new AlertDialog.Builder(this).setTitle(I18n.t("YouTube в Oldi")).setMessage(report.toString()).setPositiveButton(I18n.t("Закрыть"),null).show();});});}
 protected void onResume(){super.onResume();if(root==null)return;foreground=true;if(root!=null)root.animateSurface(true);if(web!=null)web.onResume();ui.removeCallbacks(poll);ui.post(poll);if(requestedTunnel&&TunnelStateRepository.on())try{LocalTunnelService.start(this);}catch(Exception ignored){}}
 protected void onPause(){snapshot();foreground=false;lastPoll=0;ui.removeCallbacks(poll);if(root!=null)root.animateSurface(false);if(web!=null){web.evaluateJavascript("if(window.oldiPlayer)oldiPlayer.pauseVideo();",null);web.onPause();}if(!startedPermission)LocalTunnelService.idle(this);super.onPause();}
 protected void onDestroy(){ui.removeCallbacksAndMessages(null);hideFullscreen();if(web!=null){web.stopLoading();frame.removeView(web);web.destroy();web=null;}work.shutdown();LocalTunnelService.idle(this);super.onDestroy();}
 public void onBackPressed(){if(fullscreen!=null)hideFullscreen();else super.onBackPressed();}
 int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}TextView label(String s,int size){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(textColor);t.setPadding(dp(8),dp(10),dp(8),dp(10));return t;}
 TextView button(String s,Runnable action){TextView t=label(s,15);t.setGravity(Gravity.CENTER);t.setMinHeight(dp(48));GradientDrawable d=new GradientDrawable();d.setColor(card);d.setCornerRadius(dp(14));t.setBackground(d);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(5),0,dp(5));t.setLayoutParams(lp);t.setOnClickListener(v->action.run());return t;}
}
