package chat.oldy;
import android.content.*;import android.graphics.*;import android.net.Uri;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.util.*;

final class PersonalStickers {
 static final int EDITOR=720;
 static void show(MainActivity a){LinearLayout b=a.col();b.addView(a.button(I18n.t("＋ Создать стикер из фото"),true,()->a.startActivityForResult(new Intent(a,StickerEditorActivity.class),EDITOR)));a.space(b,10);b.addView(a.button(I18n.t("Мои предложения на продажу"),false,()->StickerMarket.show(a)));a.space(b,12);a.paragraph(b,I18n.t("Ваша личная коллекция. Получатели видят стикер, но он не добавляется автоматически в их наборы."));a.space(b,12);GridLayout grid=new GridLayout(a);grid.setColumnCount(3);b.addView(grid);a.sheet(I18n.t("Мои стикеры"),b);final Vault account=a.vault;
  a.task(()->{PersonalStickerStore store=new PersonalStickerStore(a,account.nick());List<JSONObject> items=store.list();a.runOnUiThread(()->{if(a.vault!=account)return;if(items.isEmpty())a.paragraph(b,I18n.t("Выберите фото, обрежьте нужный фрагмент и сохраните свой первый стикер."));for(int i=0;i<items.size();i++){JSONObject item=items.get(i);ImageView image=new ImageView(a);image.setImageBitmap(PersonalStickerStore.image(item));image.setScaleType(ImageView.ScaleType.FIT_CENTER);image.setContentDescription(item.optString("title"));GridLayout.LayoutParams lp=new GridLayout.LayoutParams(GridLayout.spec(i/3),GridLayout.spec(i%3,1f));lp.width=0;lp.height=a.dp(112);lp.setMargins(a.dp(4),a.dp(4),a.dp(4),a.dp(4));grid.addView(image,lp);image.setOnClickListener(v->full(a,store,item,chosen->chooseRecipient(a,chosen)));image.setOnLongClickListener(v->{a.dialog().setTitle(item.optString("title")).setItems(new String[]{I18n.t("Отправить стикер"),I18n.t("Предложить на продажу"),I18n.t("Удалить из коллекции")},(d,w)->{if(w==0)full(a,store,item,chosen->chooseRecipient(a,chosen));if(w==1)full(a,store,item,chosen->StickerMarket.offer(a,chosen));if(w==2)a.dialog().setTitle(I18n.t("Удалить стикер?")).setMessage(I18n.t("Уже отправленные сообщения сохранятся у участников.")).setNegativeButton(I18n.t("Отмена"),null).setPositiveButton(I18n.t("Удалить"),(x,y)->a.task(()->{store.remove(item.optString("id"));a.runOnUiThread(()->show(a));})).show();}).show();return true;});}});});
 }
 static void full(MainActivity a,PersonalStickerStore store,JSONObject summary,java.util.function.Consumer<JSONObject> action){Vault owner=a.vault;a.task(()->{JSONObject item=store.read(summary.getString("id"));a.runOnUiThread(()->{if(a.vault==owner)action.accept(item);});});}
 static void chooseRecipient(MainActivity a,JSONObject item){if(a.screen.equals("chat")&&!a.chat.isEmpty()){send(a,item,a.chat);return;}try{JSONObject data=a.vault.copy(),contacts=data.getJSONObject("contacts"),rooms=data.getJSONObject("rooms");List<String> ids=new ArrayList<>(),names=new ArrayList<>();Iterator<String> keys=contacts.keys();while(keys.hasNext()){String id=keys.next();if(a.vault.isBlocked(id))continue;ids.add(id);names.add(contacts.getJSONObject(id).optString("name",id)+" · @"+id);}keys=rooms.keys();while(keys.hasNext()){String id=keys.next();JSONObject r=rooms.getJSONObject(id);if(r.optString("kind").equals("channel")&&!r.optString("owner").equals(a.vault.nick()))continue;ids.add("room:"+id);names.add(r.optString("title"));}if(ids.isEmpty()){a.error(I18n.t("Сначала добавьте собеседника или создайте чат"));return;}a.dialog().setTitle(I18n.t("Кому отправить стикер?")).setItems(names.toArray(new String[0]),(d,w)->send(a,item,ids.get(w))).show();}catch(Exception e){a.error(Api.message(e));}}
 static void send(MainActivity a,JSONObject item,String target){final Vault account=a.vault;if(!item.optString("owner").equals(account.nick()))return;if(a.activeSheet!=null)a.activeSheet.dismiss();Toast.makeText(a,I18n.t("Отправляем стикер…"),Toast.LENGTH_SHORT).show();a.task(()->{if(a.vault!=account)throw new IOException(I18n.t("Аккаунт изменился"));File temp=new File(a.getCacheDir(),"sticker-send-"+UUID.randomUUID()+".webp");try{byte[] bytes=Crypto.un64(item.getString("image"));java.nio.file.Files.write(temp.toPath(),bytes);JSONObject extra=new JSONObject().put("custom_sticker",true).put("sticker_id",item.getString("id")).put("sticker_author",account.nick());CloudMedia.attach(a,Uri.fromFile(temp),"image/webp",item.optString("title",I18n.t("Стикер")),target,"",extra);a.runOnUiThread(()->{if(a.vault==account&&!a.screen.equals("chat"))a.openChat(target);});}finally{temp.delete();}});}
 static void render(MainActivity a,LinearLayout bubble,JSONObject message){bubble.setBackgroundColor(Color.TRANSPARENT);ImageView image=new ImageView(a);image.setScaleType(ImageView.ScaleType.FIT_CENTER);image.setContentDescription(I18n.t("Авторский стикер")+" · @"+message.optString("sticker_author"));bubble.addView(image,new LinearLayout.LayoutParams(a.dp(190),a.dp(190)));a.photoPreview(message,image);image.setOnClickListener(v->a.messageMenu(message));if(!message.has("local")&&!message.optString("cloud_blob").isEmpty()&&a.loadingImages.add("sticker:"+message.optString("id"))){Vault owner=a.vault;a.work.execute(()->{try{CloudMedia.download(a,owner,message);a.runOnUiThread(()->{if(a.vault==owner)try{a.photoPreview(owner.message(message.optString("id")),image);}catch(Exception ignored){}});}catch(Exception ignored){}finally{a.runOnUiThread(()->a.loadingImages.remove("sticker:"+message.optString("id")));}});}}
}
