package chat.oldy;
import android.content.Context;import android.graphics.*;import org.json.*;import java.io.*;import java.util.*;

/** Creator-owned local collection. Receiving a message never adds a sticker to this store. */
final class PersonalStickerStore {
 static final Object LOCK=new Object();final File dir;final String owner;
 PersonalStickerStore(Context c,String account)throws Exception{if(!account.matches("[a-z0-9_]{3,24}"))throw new IOException();owner=account;dir=new File(c.getFilesDir(),"personal-stickers/"+account);if(!dir.isDirectory()&&!dir.mkdirs())throw new IOException();}
 File path(String id)throws Exception{if(!id.matches("[a-f0-9-]{36}"))throw new IOException();return new File(dir,id+".vault");}
 JSONObject read(String id)throws Exception{synchronized(LOCK){JSONObject j=new JSONObject(new String(Crypto.openLocal(java.nio.file.Files.readAllBytes(path(id).toPath())),java.nio.charset.StandardCharsets.UTF_8));if(!owner.equals(j.optString("owner")))throw new IOException();return j;}}
 String save(Bitmap bitmap,String title)throws Exception{synchronized(LOCK){File[] existing=dir.listFiles((d,n)->n.endsWith(".vault"));if(existing!=null&&existing.length>=300)throw new IOException(I18n.t("В личной коллекции уже 300 стикеров"));String id=UUID.randomUUID().toString();ByteArrayOutputStream image=new ByteArrayOutputStream();bitmap.compress(Bitmap.CompressFormat.WEBP,88,image);if(image.size()>350000){image.reset();bitmap.compress(Bitmap.CompressFormat.WEBP,65,image);}if(image.size()>350000)throw new IOException(I18n.t("Стикер слишком большой"));JSONObject j=new JSONObject().put("id",id).put("owner",owner).put("title",title.substring(0,Math.min(40,title.length()))).put("created_at",System.currentTimeMillis()).put("image",Crypto.b64(image.toByteArray()));write(j);return id;}}
 void write(JSONObject item)throws Exception{synchronized(LOCK){File f=path(item.getString("id"));android.util.AtomicFile file=new android.util.AtomicFile(f);FileOutputStream out=null;try{out=file.startWrite();out.write(Crypto.sealLocal(Crypto.bytes(item.toString())));file.finishWrite(out);}catch(Exception e){if(out!=null)file.failWrite(out);throw e;}}}
 List<JSONObject> list()throws Exception{synchronized(LOCK){List<JSONObject> list=new ArrayList<>();File[] files=dir.listFiles((d,n)->n.endsWith(".vault"));if(files!=null)for(File f:files){JSONObject j=read(f.getName().replace(".vault",""));list.add(j);}list.sort((a,b)->Long.compare(b.optLong("created_at"),a.optLong("created_at")));return list;}}
 void remove(String id)throws Exception{synchronized(LOCK){if(!path(id).delete())throw new IOException(I18n.t("Не удалось удалить стикер"));}}
 static Bitmap image(JSONObject item){try{byte[] bytes=Crypto.un64(item.getString("image"));if(bytes.length>350000)return null;BitmapFactory.Options bounds=new BitmapFactory.Options();bounds.inJustDecodeBounds=true;BitmapFactory.decodeByteArray(bytes,0,bytes.length,bounds);if(bounds.outWidth<1||bounds.outHeight<1||bounds.outWidth>512||bounds.outHeight>512)return null;return BitmapFactory.decodeByteArray(bytes,0,bytes.length);}catch(Exception e){return null;}}
}
