package chat.oldy;
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.view.*;import android.widget.*;import org.json.*;
final class ProfileSheet {
 final MainActivity a;final Vault owner;final JSONObject data,community;final String peer;final boolean room;
 ProfileSheet(MainActivity a,JSONObject data,JSONObject community,boolean room){this.a=a;owner=a.vault;this.data=data;this.community=community;this.room=room;peer=room?"room:"+data.optString("id"):data.optString("nick");}
 static void person(MainActivity a,JSONObject u,JSONObject community){new ProfileSheet(a,u,community,false).show();}
 static void room(MainActivity a,JSONObject r){new ProfileSheet(a,r,null,true).show();}
 void close(){if(a.activeSheet!=null)a.activeSheet.dismiss();}
 void show(){LinearLayout body=a.col();FrameLayout hero=new FrameLayout(a);hero.setBackground(a.shape(0xff243b61,22));hero.setClipToOutline(true);Art photo=new Art(a,data.optString("avatar","preset:0"));photo.portrait=true;hero.addView(photo,new FrameLayout.LayoutParams(-1,-1));View shade=new View(a);shade.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{0x00314468,0x88111d34,0xee0d1627}));hero.addView(shade,new FrameLayout.LayoutParams(-1,-1));LinearLayout identity=a.col();a.pad(identity,18);TextView name=a.label(data.optString(room?"title":"name",peer),26,0xffffffff);name.setTypeface(null,1);name.setMaxLines(2);identity.addView(name,new LinearLayout.LayoutParams(-1,-2));a.space(identity,4);identity.addView(a.label(room?(data.optString("kind").equals("channel")?I18n.t("Канал · "):I18n.t("Группа · "))+a.audience(data):"@"+peer,13,0xffd4e8ff),new LinearLayout.LayoutParams(-1,-2));hero.addView(identity,new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM));body.addView(hero,new LinearLayout.LayoutParams(-1,a.dp(235)));a.space(body,14);
  LinearLayout actions=a.row();actions.addView(action("chat",room?I18n.t("Открыть"):I18n.t("Чат"),()->a.openChat(peer)),new LinearLayout.LayoutParams(0,a.dp(78),1));actions.addView(action("bell",I18n.t("Уведомления"),()->NotificationSheet.chat(a,peer)),new LinearLayout.LayoutParams(0,a.dp(78),1));if(!room)actions.addView(action("call",I18n.t("Звонок"),()->LiveCall.dial(a,peer)),new LinearLayout.LayoutParams(0,a.dp(78),1));else actions.addView(action("share",I18n.t("@адрес"),this::copy),new LinearLayout.LayoutParams(0,a.dp(78),1));body.addView(actions);a.space(body,12);
  TextView notifications=a.label(NotificationSheet.status(a,peer),12,a.MUTED);notifications.setGravity(Gravity.CENTER);notifications.setOnClickListener(v->{close();NotificationSheet.chat(a,peer);});body.addView(notifications,new LinearLayout.LayoutParams(-1,a.dp(28)));a.space(body,8);
  TextView handle=a.button("@"+(room?data.optString("handle"):peer)+"    ⧉",false,this::copy);handle.setGravity(Gravity.CENTER_VERTICAL);body.addView(handle,new LinearLayout.LayoutParams(-1,a.dp(52)));String bio=data.optString("bio");if(!bio.isEmpty()){a.space(body,12);a.paragraph(body,bio);}a.space(body,12);
  if(room){a.paragraph(body,data.optString("kind").equals("channel")?I18n.t("Публикации владельца и отдельное обсуждение каждого поста."):I18n.t("Общение и публикации участников группы."));a.space(body,14);if(data.optString("owner").equals(owner.nick())){row(body,I18n.t("Оформление и участники"),()->a.editRoom(data));row(body,I18n.t("Изменить фото"),()->a.avatarPicker(data.optString("id")));JSONArray bans=data.optJSONArray("banned");if(bans!=null)for(int i=0;i<bans.length();i++){String n=bans.optString(i);row(body,I18n.t("Разблокировать @")+n,()->a.roomBan(data,n,false));}}else row(body,I18n.t("Покинуть сообщество"),()->a.task(()->{a.api.call("/room/leave",new JSONObject().put("id",data.optString("id")),owner.token());owner.rooms(a.api.call("/rooms",null,owner.token()).getJSONArray("rooms"));a.runOnUiThread(()->{if(a.vault==owner)a.chats();});}));
   if(data.optString("owner").equals(owner.nick())||owner.moderator()){TextView remove=row(body,I18n.t("Удалить сообщество"),()->a.deleteRoom(data));remove.setTextColor(a.light?0xffac3457:0xffff9eb1);}
  }else{TextView block=row(body,owner.isBlocked(peer)?I18n.t("Разблокировать в ЛС"):I18n.t("Заблокировать в ЛС"),()->a.setBlock(peer,!owner.isBlocked(peer)));block.setTextColor(a.light?0xffac3457:0xffff9eb1);if(community!=null&&community.optString("owner").equals(owner.nick()))row(body,I18n.t("Заблокировать в этом сообществе"),()->a.roomBan(community,peer,true));}
  a.space(body,12);LinearLayout tabs=a.row(),items=a.col();String[] categories={I18n.t("Медиа"),I18n.t("Голосовые"),I18n.t("Ссылки")};for(int i=0;i<3;i++){final int selected=i;TextView tab=a.label(categories[i],12,a.TEXT);tab.setGravity(Gravity.CENTER);tab.setTypeface(null,1);tab.setBackground(a.shape(a.light?0xffe8f2ff:0xff263d58,14));tabs.addView(tab,new LinearLayout.LayoutParams(0,a.dp(42),1));tab.setOnClickListener(v->{media(items,selected);for(int j=0;j<tabs.getChildCount();j++)tabs.getChildAt(j).setAlpha(j==selected?1:.55f);});tab.setAlpha(i==0?1:.55f);}body.addView(tabs);a.space(body,10);body.addView(items,new LinearLayout.LayoutParams(-1,-2));media(items,0);
  if(room){a.space(body,18);JSONArray members=data.optJSONArray("members");if(members!=null){a.paragraph(body,(data.optString("kind").equals("channel")?I18n.t("Подписчики"):I18n.t("Участники"))+" · "+members.length());for(int i=0;i<members.length();i++){String n=members.optString(i);row(body,"@"+n+(n.equals(data.optString("owner"))?I18n.t(" · владелец"):""),()->a.personMenu(n));}}}
  a.sheet(room?I18n.t("Сообщество"):I18n.t("Профиль"),body);Dialog dialog=a.activeSheet;NotificationSheet.ticker(a,dialog,()->notifications.setText(NotificationSheet.status(a,peer)));
 }
 void copy(){((android.content.ClipboardManager)a.getSystemService(Context.CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText(I18n.t("OldЫ Chat"),"@"+(room?data.optString("handle"):peer)));Toast.makeText(a,I18n.t("Адрес скопирован"),Toast.LENGTH_SHORT).show();}
 View action(String icon,String label,Runnable action){LinearLayout tile=a.col();tile.setGravity(Gravity.CENTER);GradientDrawable bg=a.shape(a.light?0xffe7f1ff:0xff263c57,18);tile.setBackground(bg);UiIcon mark=new UiIcon(a,icon,a.light?0xff2163a0:0xff99dbff);tile.addView(mark,new LinearLayout.LayoutParams(a.dp(36),a.dp(36)));TextView text=a.label(label,11,a.TEXT);text.setGravity(Gravity.CENTER);tile.addView(text,new LinearLayout.LayoutParams(-1,-2));tile.setContentDescription(label);tile.setOnClickListener(v->{close();action.run();});return tile;}
 TextView row(LinearLayout body,String title,Runnable action){TextView v=a.button(title,false,action);v.setGravity(Gravity.CENTER_VERTICAL);body.addView(v,new LinearLayout.LayoutParams(-1,-2));a.space(body,7);return v;}
 void media(LinearLayout items,int category){items.removeAllViews();try{JSONArray messages=owner.copy().getJSONArray("messages");int count=0;for(int i=messages.length()-1;i>=0&&count<30;i--){JSONObject m=messages.getJSONObject(i);if(!peer.equals(m.optString("peer"))||m.optString("kind").equals("control"))continue;boolean audio=m.optString("mime").startsWith("audio/"),file=m.optString("kind").equals("file");String link=LinkCards.first(m.optString("text"));if(category==0?(!file||audio):category==1?!audio:link.isEmpty())continue;count++;String label=category==2?link:(audio?I18n.t("Голосовое"):m.optString("mime").startsWith("image/")?I18n.t("Фото"):I18n.t("Видео"))+" · "+a.size(m.optLong("size"));TextView entry=a.button(label,false,()->{if(category==2)a.startActivity(new Intent(Intent.ACTION_VIEW,android.net.Uri.parse(link)));else a.openMedia(m);});entry.setGravity(Gravity.CENTER_VERTICAL);entry.setMaxLines(2);entry.setEllipsize(android.text.TextUtils.TruncateAt.END);items.addView(entry,new LinearLayout.LayoutParams(-1,-2));a.space(items,6);}if(count==0)a.paragraph(items,category==0?I18n.t("Фотографии и видео появятся здесь"):category==1?I18n.t("Здесь будут голосовые сообщения"):I18n.t("Здесь будут ссылки из переписки"));}catch(Exception e){a.paragraph(items,I18n.t("Не удалось открыть историю"));}}
}
