package chat.oldy;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.net.Uri;
import android.os.*;
import android.view.*;
import android.widget.*;
import org.webrtc.*;
import java.io.*;
import java.util.concurrent.*;

public class RoundActivity extends Activity {
 TextureView preview;TextView status,record,swap,send;EglBase egl;EglRenderer renderer;SurfaceTextureHelper texture;CameraVideoCapturer camera;volatile RoundEncoder encoder;File file;boolean front=true,switching,finishing;volatile boolean ready;volatile int frames,switches;Handler ui=new Handler(Looper.getMainLooper());ExecutorService io=Executors.newSingleThreadExecutor();
 int dp(float n){return Math.round(n*getResources().getDisplayMetrics().density);}
 public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);LinearLayout root=new ThemeLayout(this);root.setOrientation(1);root.setGravity(Gravity.CENTER_HORIZONTAL);root.setPadding(dp(18),dp(12),dp(18),dp(12));if(Build.VERSION.SDK_INT>=35)root.setOnApplyWindowInsetsListener((v,insets)->{android.graphics.Insets x=insets.getInsets(WindowInsets.Type.systemBars());v.setPadding(dp(18)+x.left,dp(12)+x.top,dp(18)+x.right,dp(12)+x.bottom);return insets;});
  TextView title=text(I18n.t("Видеокружок"),23);title.setTypeface(null,1);root.addView(title,new LinearLayout.LayoutParams(-1,dp(42)));status=text(I18n.t("Селфи-камера · до 60 секунд"),13);root.addView(status,new LinearLayout.LayoutParams(-1,dp(40)));
  FrameLayout stage=new FrameLayout(this){protected void onMeasure(int w,int h){super.onMeasure(w,h);int side=Math.min(getMeasuredWidth(),getMeasuredHeight())-dp(12);side=Math.max(dp(80),side);if(preview!=null)preview.measure(View.MeasureSpec.makeMeasureSpec(side,View.MeasureSpec.EXACTLY),View.MeasureSpec.makeMeasureSpec(side,View.MeasureSpec.EXACTLY));}protected void onLayout(boolean c,int l,int t,int r,int b){if(preview!=null){int side=preview.getMeasuredWidth(),x=(getWidth()-side)/2,y=(getHeight()-side)/2;preview.layout(x,y,x+side,y+side);}}};preview=new TextureView(this);stage.addView(preview,new FrameLayout.LayoutParams(-1,-1,Gravity.CENTER));root.addView(stage,new LinearLayout.LayoutParams(-1,0,1));preview.setOutlineProvider(new ViewOutlineProvider(){public void getOutline(View v,Outline o){o.setOval(0,0,v.getWidth(),v.getHeight());}});preview.setClipToOutline(true);
  LinearLayout buttons=new LinearLayout(this);record=text(I18n.t("● Записать"),16);style(record,0xff3879b1);record.setOnClickListener(v->{if(encoder==null&&!ready)begin();else if(encoder!=null)stop(true);});LinearLayout.LayoutParams cell=new LinearLayout.LayoutParams(0,dp(58),1);cell.setMargins(0,dp(8),dp(6),dp(8));buttons.addView(record,cell);swap=text(I18n.t("⇄ Сменить камеру"),15);swap.setContentDescription(I18n.t("Сменить камеру"));style(swap,0xff2e4869);swap.setOnClickListener(v->switchCamera());LinearLayout.LayoutParams sc=new LinearLayout.LayoutParams(0,dp(58),1);sc.setMargins(dp(6),dp(8),0,dp(8));buttons.addView(swap,sc);root.addView(buttons,new LinearLayout.LayoutParams(-1,-2));
  send=text(I18n.t("Отправить кружок →"),17);style(send,0xff2b7a9c);send.setVisibility(View.GONE);send.setOnClickListener(v->{if(ready){setResult(RESULT_OK,new Intent().setData(Uri.fromFile(file)));file=null;finish();}});root.addView(send,new LinearLayout.LayoutParams(-1,dp(52)));TextView cancel=text(I18n.t("Отмена"),15);cancel.setOnClickListener(v->finish());root.addView(cancel,new LinearLayout.LayoutParams(-1,dp(48)));setContentView(root);
  if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.CAMERA,Manifest.permission.RECORD_AUDIO},61);else initCamera();
 }
 void style(TextView view,int color){android.graphics.drawable.GradientDrawable bg=new android.graphics.drawable.GradientDrawable();bg.setColor(color);bg.setCornerRadius(dp(18));bg.setStroke(dp(1),0xff5582a4);view.setBackground(bg);}
 TextView text(String s,int n){TextView t=new TextView(this);t.setText(s);t.setTextColor(Notices.prefs(this).getString("theme","dark").equals("light")?0xff20354b:0xffe5f2ff);t.setTextSize(n);t.setGravity(Gravity.CENTER);t.setPadding(dp(6),dp(4),dp(6),dp(4));return t;}
 public void onRequestPermissionsResult(int r,String[] p,int[] values){super.onRequestPermissionsResult(r,p,values);if(checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED)initCamera();else{status.setText(I18n.t("Для кружка нужны камера и микрофон"));record.setEnabled(false);}}
 void initCamera(){try{PeerConnectionFactory.initialize(PeerConnectionFactory.InitializationOptions.builder(this).createInitializationOptions());egl=EglBase.create();renderer=new EglRenderer("oldy-round-preview");renderer.init(egl.getEglBaseContext(),EglBase.CONFIG_PLAIN,new GlRectDrawer());renderer.setMirror(true);renderer.setLayoutAspectRatio(1);
  preview.setSurfaceTextureListener(new TextureView.SurfaceTextureListener(){public void onSurfaceTextureAvailable(SurfaceTexture s,int w,int h){renderer.createEglSurface(s);}public void onSurfaceTextureSizeChanged(SurfaceTexture s,int w,int h){}public boolean onSurfaceTextureDestroyed(SurfaceTexture s){if(renderer!=null)renderer.releaseEglSurface(()->{});return true;}public void onSurfaceTextureUpdated(SurfaceTexture s){}});if(preview.isAvailable())renderer.createEglSurface(preview.getSurfaceTexture());
  CameraEnumerator enumerator=Camera2Enumerator.isSupported(this)?new Camera2Enumerator(this):new Camera1Enumerator(true);String chosen=null;for(String name:enumerator.getDeviceNames())if(enumerator.isFrontFacing(name)){chosen=name;break;}if(chosen==null)throw new IOException(I18n.t("Селфи-камера недоступна"));
  camera=enumerator.createCapturer(chosen,new CameraVideoCapturer.CameraEventsHandler(){public void onCameraError(String s){ui.post(()->status.setText(I18n.t("Не удалось включить камеру")));}public void onCameraDisconnected(){}public void onCameraFreezed(String s){ui.post(()->status.setText(I18n.t("Камера остановилась. Повтори запись.")));}public void onCameraOpening(String n){}public void onFirstFrameAvailable(){}public void onCameraClosed(){}});
  texture=SurfaceTextureHelper.create("oldy-round-camera",egl.getEglBaseContext());camera.initialize(texture,this,new CapturerObserver(){public void onCapturerStarted(boolean s){}public void onCapturerStopped(){}public void onFrameCaptured(VideoFrame frame){frames++;if(renderer!=null)renderer.onFrame(frame);RoundEncoder e=encoder;if(e!=null)e.frame(frame);}});camera.startCapture(640,480,30);
 }catch(Exception e){status.setText(e instanceof IOException?e.getMessage():I18n.t("Не удалось включить камеру. Проверь разрешение в настройках Android."));record.setEnabled(false);}}
 void begin(){if(camera==null||frames==0||finishing)return;try{file=new File(getCacheDir(),"round-"+System.currentTimeMillis()+".mp4");encoder=new RoundEncoder(file,egl.getEglBaseContext());record.setText(I18n.t("■ Завершить"));tick();}catch(Exception e){status.setText(I18n.t("Не удалось начать запись. Проверь доступ к камере и микрофону."));}}
 void tick(){RoundEncoder e=encoder;if(e==null)return;long seconds=(System.nanoTime()-e.started)/1000000000;status.setText("● "+seconds+I18n.t(" / 60 с · камеру можно переключать"));if(seconds>=60){stop(true);return;}ui.postDelayed(this::tick,250);}
 void switchCamera(){if(camera==null||switching||ready||finishing)return;switching=true;swap.setEnabled(false);camera.switchCamera(new CameraVideoCapturer.CameraSwitchHandler(){public void onCameraSwitchDone(boolean f){front=f;switches++;if(renderer!=null)renderer.setMirror(f);ui.post(()->{switching=false;swap.setEnabled(true);swap.setText("⇄ "+(front?I18n.t("Селфи"):I18n.t("Основная")));if(encoder==null)status.setText((front?I18n.t("Селфи-камера"):I18n.t("Основная камера"))+I18n.t(" · до 60 секунд"));});}public void onCameraSwitchError(String error){ui.post(()->{switching=false;swap.setEnabled(true);status.setText(I18n.t("Эта камера сейчас недоступна"));});}});}
 void stop(boolean keep){RoundEncoder e=encoder;if(e==null||finishing)return;encoder=null;finishing=true;record.setEnabled(false);swap.setEnabled(false);status.setText(I18n.t("Сохраняем кружок…"));io.execute(()->{try{e.finish();ui.post(()->{finishing=false;if(!keep||isFinishing()||isDestroyed()){if(file!=null)file.delete();if(!isFinishing()&&!isDestroyed()){record.setEnabled(true);swap.setEnabled(true);record.setText(I18n.t("● Записать"));status.setText(I18n.t("Запись отменена"));}return;}ready=true;status.setText(I18n.t("Кружок готов · камера и звук записаны"));record.setText(I18n.t("▶ Посмотреть"));record.setEnabled(true);record.setOnClickListener(v->startActivity(new Intent(this,RoundReviewActivity.class).putExtra("path",file.getAbsolutePath())));send.setVisibility(View.VISIBLE);});}catch(Exception error){ui.post(()->{finishing=false;record.setEnabled(true);swap.setEnabled(true);status.setText(I18n.t("Не удалось сохранить кружок. Попробуй записать ещё раз."));});}});}
 protected void onPause(){super.onPause();if(encoder!=null)stop(false);}
 protected void onDestroy(){if(encoder!=null)stop(false);if(camera!=null){try{camera.stopCapture();}catch(Exception ignored){}camera.dispose();camera=null;}if(renderer!=null){renderer.release();renderer=null;}if(texture!=null)texture.dispose();if(egl!=null)egl.release();ui.removeCallbacksAndMessages(null);if(file!=null&&!finishing)file.delete();io.shutdown();super.onDestroy();}
}
