package chat.oldy;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.net.Uri;
import android.os.*;
import android.view.*;
import android.widget.*;
import org.webrtc.*;
import java.io.*;
import java.util.concurrent.*;

public class RoundActivity extends Activity {
 TextureView preview;TextView status,record,swap,send;EglBase egl;EglRenderer renderer;SurfaceTextureHelper texture;CameraVideoCapturer camera;volatile RoundEncoder encoder;File file;boolean front=true,switching,finishing;volatile boolean ready;volatile int frames,switches;Handler ui=new Handler(Looper.getMainLooper());ExecutorService io=Executors.newSingleThreadExecutor();
 public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);LinearLayout root=new LinearLayout(this);root.setOrientation(1);root.setGravity(Gravity.CENTER);root.setPadding(24,32,24,32);root.setBackgroundColor(0xff111b2a);TextView title=text("Видеокружок",25);root.addView(title);status=text("Селфи-камера · до 60 секунд",14);root.addView(status);preview=new TextureView(this);int size=Math.min(getResources().getDisplayMetrics().widthPixels-48,840);root.addView(preview,new LinearLayout.LayoutParams(size,size));preview.setOutlineProvider(new ViewOutlineProvider(){public void getOutline(View v,Outline o){o.setOval(0,0,v.getWidth(),v.getHeight());}});preview.setClipToOutline(true);
  LinearLayout buttons=new LinearLayout(this);record=text("● Записать",19);record.setOnClickListener(v->{if(encoder==null&&!ready)begin();else if(encoder!=null)stop(true);});buttons.addView(record);swap=text("⇄ Камера",18);swap.setOnClickListener(v->switchCamera());buttons.addView(swap);root.addView(buttons);send=text("Отправить кружок →",18);send.setVisibility(View.GONE);send.setOnClickListener(v->{if(ready){setResult(RESULT_OK,new Intent().setData(Uri.fromFile(file)));file=null;finish();}});root.addView(send);TextView cancel=text("Отмена",16);cancel.setOnClickListener(v->finish());root.addView(cancel);setContentView(root);
  if(checkSelfPermission(Manifest.permission.CAMERA)!=PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.CAMERA,Manifest.permission.RECORD_AUDIO},61);else initCamera();
 }
 TextView text(String s,int n){TextView t=new TextView(this);t.setText(s);t.setTextColor(0xffd9e9ff);t.setTextSize(n);t.setGravity(Gravity.CENTER);t.setPadding(15,24,15,24);return t;}
 public void onRequestPermissionsResult(int r,String[] p,int[] values){super.onRequestPermissionsResult(r,p,values);if(checkSelfPermission(Manifest.permission.CAMERA)==PackageManager.PERMISSION_GRANTED&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)==PackageManager.PERMISSION_GRANTED)initCamera();else{status.setText("Для кружка нужны камера и микрофон");record.setEnabled(false);}}
 void initCamera(){try{PeerConnectionFactory.initialize(PeerConnectionFactory.InitializationOptions.builder(this).createInitializationOptions());egl=EglBase.create();renderer=new EglRenderer("oldy-round-preview");renderer.init(egl.getEglBaseContext(),EglBase.CONFIG_PLAIN,new GlRectDrawer());renderer.setMirror(true);renderer.setLayoutAspectRatio(1);
  preview.setSurfaceTextureListener(new TextureView.SurfaceTextureListener(){public void onSurfaceTextureAvailable(SurfaceTexture s,int w,int h){renderer.createEglSurface(s);}public void onSurfaceTextureSizeChanged(SurfaceTexture s,int w,int h){}public boolean onSurfaceTextureDestroyed(SurfaceTexture s){if(renderer!=null)renderer.releaseEglSurface(()->{});return true;}public void onSurfaceTextureUpdated(SurfaceTexture s){}});if(preview.isAvailable())renderer.createEglSurface(preview.getSurfaceTexture());
  CameraEnumerator enumerator=Camera2Enumerator.isSupported(this)?new Camera2Enumerator(this):new Camera1Enumerator(true);String chosen=null;for(String name:enumerator.getDeviceNames())if(enumerator.isFrontFacing(name)){chosen=name;break;}if(chosen==null)throw new IOException("Селфи-камера недоступна");
  camera=enumerator.createCapturer(chosen,new CameraVideoCapturer.CameraEventsHandler(){public void onCameraError(String s){ui.post(()->status.setText("Не удалось включить камеру"));}public void onCameraDisconnected(){}public void onCameraFreezed(String s){ui.post(()->status.setText("Камера остановилась. Повтори запись."));}public void onCameraOpening(String n){}public void onFirstFrameAvailable(){}public void onCameraClosed(){}});
  texture=SurfaceTextureHelper.create("oldy-round-camera",egl.getEglBaseContext());camera.initialize(texture,this,new CapturerObserver(){public void onCapturerStarted(boolean s){}public void onCapturerStopped(){}public void onFrameCaptured(VideoFrame frame){frames++;if(renderer!=null)renderer.onFrame(frame);RoundEncoder e=encoder;if(e!=null)e.frame(frame);}});camera.startCapture(640,480,30);
 }catch(Exception e){status.setText(e instanceof IOException?e.getMessage():"Не удалось включить камеру. Проверь разрешение в настройках Android.");record.setEnabled(false);}}
 void begin(){if(camera==null||frames==0||finishing)return;try{file=new File(getCacheDir(),"round-"+System.currentTimeMillis()+".mp4");encoder=new RoundEncoder(file,egl.getEglBaseContext());record.setText("■ Завершить");tick();}catch(Exception e){status.setText("Не удалось начать запись. Проверь доступ к камере и микрофону.");}}
 void tick(){RoundEncoder e=encoder;if(e==null)return;long seconds=(System.nanoTime()-e.started)/1000000000;status.setText("● "+seconds+" / 60 с · камеру можно переключать");if(seconds>=60){stop(true);return;}ui.postDelayed(this::tick,250);}
 void switchCamera(){if(camera==null||switching||ready||finishing)return;switching=true;swap.setEnabled(false);camera.switchCamera(new CameraVideoCapturer.CameraSwitchHandler(){public void onCameraSwitchDone(boolean f){front=f;switches++;if(renderer!=null)renderer.setMirror(f);ui.post(()->{switching=false;swap.setEnabled(true);});}public void onCameraSwitchError(String error){ui.post(()->{switching=false;swap.setEnabled(true);status.setText("Эта камера сейчас недоступна");});}});}
 void stop(boolean keep){RoundEncoder e=encoder;if(e==null||finishing)return;encoder=null;finishing=true;record.setEnabled(false);swap.setEnabled(false);status.setText("Сохраняем кружок…");io.execute(()->{try{e.finish();ui.post(()->{finishing=false;if(!keep||isFinishing()||isDestroyed()){if(file!=null)file.delete();if(!isFinishing()&&!isDestroyed()){record.setEnabled(true);swap.setEnabled(true);record.setText("● Записать");status.setText("Запись отменена");}return;}ready=true;status.setText("Кружок готов · камера и звук записаны");record.setText("▶ Посмотреть");record.setEnabled(true);record.setOnClickListener(v->startActivity(new Intent(this,RoundReviewActivity.class).putExtra("path",file.getAbsolutePath())));send.setVisibility(View.VISIBLE);});}catch(Exception error){ui.post(()->{finishing=false;record.setEnabled(true);swap.setEnabled(true);status.setText("Не удалось сохранить кружок. Попробуй записать ещё раз.");});}});}
 protected void onPause(){super.onPause();if(encoder!=null)stop(false);}
 protected void onDestroy(){if(encoder!=null)stop(false);if(camera!=null){try{camera.stopCapture();}catch(Exception ignored){}camera.dispose();camera=null;}if(renderer!=null){renderer.release();renderer=null;}if(texture!=null)texture.dispose();if(egl!=null)egl.release();ui.removeCallbacksAndMessages(null);if(file!=null&&!finishing)file.delete();io.shutdown();super.onDestroy();}
}
