package chat.oldy;
import android.content.*;import android.graphics.Typeface;import android.view.*;import android.widget.*;import org.json.*;

/** Compact grouped settings and persistent primary navigation, using Oldy's own theme. */
final class SettingsHome {
 static LinearLayout page(MainActivity a,String title,String section){a.base("settings");a.settingsSection=section;a.title(I18n.t(title),a::settings);ScrollView scroll=new ScrollView(a);LinearLayout b=a.col();scroll.addView(b);a.root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));navigation(a,section.equals("own")?3:2);return b;}
 static void show(MainActivity a){LinearLayout b=page(a,"Настройки","");try{JSONObject profile=a.vault.copy();LinearLayout hero=a.row();a.pad(hero,16);hero.setBackground(a.glass(22));a.art(profile.optString("avatar","preset:0"),64,hero);LinearLayout words=a.col();words.setPadding(a.dp(16),0,0,0);TextView name=a.label(profile.optString("name",a.vault.nick()),23,a.TEXT);name.setTypeface(null,1);words.addView(name);words.addView(a.label("@"+a.vault.nick(),13,a.MUTED));words.addView(a.label(ProfileEditor.number(profile),11,a.MUTED));hero.addView(words,new LinearLayout.LayoutParams(0,-2,1));hero.setOnClickListener(v->a.editProfile());b.addView(hero);}catch(Exception ignored){}
  section(a,b,"АККАУНТ");LinearLayout account=group(a,b);row(a,account,"☺","Мой профиль","Имя, аватар и о себе",0xff46a6cc,a::editProfile);row(a,account,"@","Почта и вход","Подтверждение e-mail и доступ к аккаунту",0xff6989db,a::emailSettings);
  section(a,b,"ОФОРМЛЕНИЕ");LinearLayout settings=group(a,b);row(a,settings,"◐","Настройки чатов","Обои, тема и размер сообщений",0xffe49b35,()->appearance(a));row(a,settings,"♧","Конфиденциальность","Ключи, резервная копия и контакты",0xff4bab72,()->privacy(a));row(a,settings,"♬","Уведомления","Звук, вибрация и доставка сообщений",0xffde6a77,()->notifications(a));row(a,settings,"⇄","Сеть","Защищённый просмотр YouTube и соединение",0xff4ca4cd,()->network(a));row(a,settings,"▧","Данные и память","Локальная история и файлы",0xff7690bd,()->storage(a));row(a,settings,"文","Язык / Language",I18n.language().equals("en")?"English":"Русский",0xff9c73ba,()->language(a));
  section(a,b,"ВОЗМОЖНОСТИ");LinearLayout features=group(a,b);row(a,features,"▶","Мои видео","История, избранное и смотреть позже",0xffd76675,()->VideoLibraryUi.show(a,"history"));row(a,features,"▣","Мои стикеры","Создать из фото и отправить в чат",0xff9d71c3,()->PersonalStickers.show(a));row(a,features,"♫","Приложения и игры","Аудиомастерская и мини-приложения",0xff4ea6a8,()->MiniApps.show(a));row(a,features,"▤","Архив","Скрытые из списка разговоры",0xff8098a9,()->{a.showArchive=true;a.chats();});
  section(a,b,"ПРИЛОЖЕНИЕ");LinearLayout app=group(a,b);row(a,app,"↻","Обновления",Updates.versionName(a),0xff52a597,()->Updates.check(a,true));row(a,app,"i","О приложении","Oldi Chat",0xff8092b5,()->about(a));a.space(b,16);a.paragraph(b,"Oldi Chat · "+Updates.versionName(a));a.space(b,16);
 }
 static void section(MainActivity a,LinearLayout b,String text){a.space(b,18);TextView t=a.label(I18n.t(text),12,a.light?0xff487698:a.GREEN);t.setTypeface(null,Typeface.BOLD);t.setPadding(a.dp(12),0,0,a.dp(8));b.addView(t);}
 static LinearLayout group(MainActivity a,LinearLayout parent){LinearLayout g=a.col();g.setBackground(a.glass(19));g.setClipToOutline(true);parent.addView(g);return g;}
 static void row(MainActivity a,LinearLayout parent,String icon,String title,String detail,int color,Runnable action){LinearLayout row=a.row();row.setPadding(a.dp(12),a.dp(11),a.dp(12),a.dp(11));row.setMinimumHeight(a.dp(65));TextView mark=a.label(icon,20,0xffffffff);mark.setGravity(Gravity.CENTER);mark.setBackground(a.shape(color,10));row.addView(mark,new LinearLayout.LayoutParams(a.dp(34),a.dp(34)));LinearLayout words=a.col();words.setPadding(a.dp(13),0,a.dp(8),0);TextView name=a.label(I18n.t(title),15,a.TEXT);name.setTypeface(null,1);words.addView(name);if(detail!=null&&!detail.isEmpty()){a.space(words,3);TextView sub=a.label(I18n.t(detail),11,a.MUTED);sub.setMaxLines(2);words.addView(sub);}row.addView(words,new LinearLayout.LayoutParams(0,-2,1));row.addView(a.label("›",23,a.MUTED));row.setOnClickListener(v->action.run());parent.addView(row);View line=new View(a);line.setBackgroundColor(a.light?0x18758a99:0x286e879f);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,a.dp(1));lp.setMargins(a.dp(59),0,a.dp(12),0);parent.addView(line,lp);}
 static void navigation(MainActivity a,int selected){if(a.vault.token().isEmpty())return;LinearLayout nav=a.row();nav.setBackground(a.glass(23));String[] labels={"Чаты","Контакты","Настройки","Моё"},icons={"◌","♙","⚙","☺"};Runnable[] actions={()->{a.showArchive=false;a.chats();},()->ContactDiscovery.show(a),a::settings,()->own(a)};for(int i=0;i<4;i++){final int at=i;LinearLayout tab=a.col();tab.setGravity(Gravity.CENTER);tab.setPadding(0,a.dp(6),0,a.dp(6));int color=selected==i?(a.light?0xff287a9c:0xff87e4e0):a.MUTED;TextView glyph=a.label(icons[i],23,color),label=a.label(I18n.t(labels[i]),11,color);glyph.setGravity(Gravity.CENTER);label.setGravity(Gravity.CENTER);tab.addView(glyph);tab.addView(label);tab.setContentDescription(I18n.t(labels[i]));tab.setOnClickListener(v->actions[at].run());nav.addView(tab,new LinearLayout.LayoutParams(0,a.dp(60),1));}a.space(a.root,8);a.root.addView(nav);}
 static void appearance(MainActivity a){LinearLayout b=page(a,"Настройки чатов","appearance");section(a,b,"ОФОРМЛЕНИЕ");LinearLayout modes=a.row();String[] values={"light","dark","cyber"},names={"☀ Светлая","☾ Тёмная","⚡ Киберпанк"};for(int i=0;i<values.length;i++){String v=values[i];modes.addView(a.button(I18n.t(names[i]),Notices.prefs(a).getString("theme","dark").equals(v),()->{Notices.prefs(a).edit().putString("theme",v).apply();appearance(a);}),new LinearLayout.LayoutParams(0,a.dp(52),1));}b.addView(modes);a.space(b,16);LinearLayout preview=group(a,b);TextView example=a.label(I18n.t("Так будут выглядеть сообщения в чате"),Notices.prefs(a).getInt("message_text_size",16),a.TEXT);a.pad(example,18);preview.addView(example);a.space(b,12);b.addView(a.button(I18n.t("Обои чатов"),true,a::wallpaperPicker));a.space(b,12);a.paragraph(b,I18n.t("Размер текста сообщений"));SeekBar size=new SeekBar(a);size.setMax(8);size.setProgress(Notices.prefs(a).getInt("message_text_size",16)-14);size.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){Notices.prefs(a).edit().putInt("message_text_size",s.getProgress()+14).apply();}public void onProgressChanged(SeekBar s,int v,boolean fromUser){example.setTextSize(v+14);}});b.addView(size,new LinearLayout.LayoutParams(-1,a.dp(48)));a.toggle(b,I18n.t("Анимации"),"animations",true);}
 static void notifications(MainActivity a){LinearLayout b=page(a,"Уведомления","notifications");a.toggle(b,I18n.t("Новые сообщения"),"notifications",true);a.toggle(b,I18n.t("Звук уведомлений"),"sound",true);a.toggle(b,I18n.t("Вибрация"),"vibration",true);a.toggle(b,I18n.t("Показывать текст"),"preview",false);row(a,b,"♫","Звуки",Notices.TONE_NAMES[Notices.tone(a)],0xffc78399,a::soundPicker);row(a,b,"◷","Режим без звука","Настроить время тишины",0xffa68ac1,a::focusMode);row(a,b,"⚡","Доставка с выключенным экраном","Фоновая работа и батарея",0xffd8a650,a::background);row(a,b,"⚙","Разрешения уведомлений","Настройки Android",0xff7898b8,()->a.startActivity(new Intent(android.provider.Settings.ACTION_APP_NOTIFICATION_SETTINGS).putExtra(android.provider.Settings.EXTRA_APP_PACKAGE,a.getPackageName())));}
 static void privacy(MainActivity a){LinearLayout b=page(a,"Конфиденциальность","privacy");row(a,b,"♧","Защита и резервная копия","Личный ключ восстановления",0xff55a781,a::cloudSettings);row(a,b,"♙","Поиск по контактам","Только с согласия участников",0xff6ba0c7,()->ContactDiscovery.show(a));row(a,b,"⊘","Чёрный список","Заблокированные аккаунты",0xffc97783,a::blacklist);a.space(b,16);a.paragraph(b,I18n.t("Личная переписка использует шифрование между участниками. Общая история каналов, комментарии и канальные видео доступны серверу; это не сквозное шифрование. Универсального ключа владельца ко всем личным сообщениям нет."));a.space(b,16);b.addView(a.button(I18n.t("Выйти из аккаунта"),false,()->a.dialog().setTitle(I18n.t("Выйти?")).setMessage(I18n.t("История останется на этом телефоне.")).setNegativeButton(I18n.t("Отмена"),null).setPositiveButton(I18n.t("Выйти"),(d,w)->a.logoutAccount()).show()));}
 static void network(MainActivity a){LinearLayout b=page(a,"Сеть","network");row(a,b,"▶","Защищённый просмотр YouTube","Режим просмотра и диагностика",0xff4ba9b6,()->YouTubeSettings.show(a));row(a,b,"⇄","Проверить подключение",ChatService.state,0xff789ac5,()->a.task(()->{a.api.check();a.runOnUiThread(()->a.error(I18n.t("Подключено")));}));a.space(b,16);a.paragraph(b,I18n.t("Local Tunnel работает только для нужных соединений Oldi. Ваш VPS не передаёт YouTube-видео."));}
 static void language(MainActivity a){LinearLayout b=page(a,"Язык / Language","language");for(String code:new String[]{"ru","en"})row(a,b,code.equals(I18n.language())?"✓":"○",code.equals("ru")?"Русский":"English","",0xff977cb5,()->{I18n.setLanguage(a,code);show(a);});}
 static void storage(MainActivity a){LinearLayout b=page(a,"Данные и память","storage");long total=bytes(a.getFilesDir()),cache=bytes(a.getCacheDir());a.paragraph(b,I18n.t("Данные на телефоне: ")+a.size(total)+"\n"+I18n.t("Временные файлы: ")+a.size(cache));a.space(b,14);row(a,b,"▶","История видео","Удаление истории не удаляет избранное",0xffb576aa,()->VideoLibraryUi.show(a,"history"));row(a,b,"☁","Резервная копия","Защита доступа и восстановление",0xff6a9db8,a::cloudSettings);a.space(b,14);a.paragraph(b,I18n.t("Вложения и переписка не удаляются автоматически из этого раздела. Управляйте ими через меню конкретного чата."));}
 static long bytes(java.io.File file){if(file.isFile())return file.length();long count=0;java.io.File[] children=file.listFiles();if(children!=null)for(java.io.File child:children)count+=bytes(child);return count;}
 static void own(MainActivity a){LinearLayout b=page(a,"Моё","own");a.screen="own";row(a,b,"☺","Мой профиль","Аватар, идентификатор и о себе",0xff688fc2,a::editProfile);row(a,b,"▶","Мои видео","История · избранное · смотреть позже",0xffd37880,()->VideoLibraryUi.show(a,"history"));row(a,b,"▣","Мои стикеры","Личная коллекция из ваших фото",0xff9b72b5,()->PersonalStickers.show(a));row(a,b,"★","Избранные сообщения","Сохранённое из чатов",0xffd0a050,a::savedMessages);row(a,b,"♫","Приложения и игры","Аудиомастерская",0xff58a29b,()->MiniApps.show(a));row(a,b,"☰","Все возможности","Каналы, группы, архив и другое",0xff8096b7,a::profileMenu);}
 static void about(MainActivity a){a.error("Oldi Chat · "+Updates.versionName(a)+"\n\n"+I18n.t("Общайтесь, создавайте свои стикеры и смотрите YouTube внутри чата. Видео YouTube идёт напрямую на ваше устройство. Локальный сетевой модуль использует hev-socks5-tunnel (MIT) и системное шифрование HTTPS. Лицензии сторонних библиотек включены в приложение."));}
}
