package chat.oldy;
import android.app.Dialog;import android.graphics.Color;import android.view.*;import android.widget.*;

/** Four primary destinations in a compact left drawer; content tabs remain below chats. */
final class SideNavigation {
 static void show(MainActivity a){Dialog dialog=new Dialog(a);a.activeSheet=dialog;dialog.setOnDismissListener(d->{if(a.activeSheet==dialog)a.activeSheet=null;});LinearLayout panel=new ThemeLayout(a,a.light,a.cyber);panel.setPadding(a.dp(14),a.dp(26),a.dp(14),a.dp(20));TextView name=a.label("Oldi Chat",24,a.TEXT);name.setTypeface(null,1);panel.addView(name);a.space(panel,28);String[] labels={"Чаты","Контакты","Настройки","Моё"},icons={"chat","contacts","settings","profile"};Runnable[] actions={()->{a.showArchive=false;a.chats();},()->ContactDiscovery.show(a),a::settings,()->SettingsHome.own(a)};
  for(int i=0;i<labels.length;i++){int at=i;LinearLayout line=a.row();line.setBackground(a.glass(18));line.setPadding(a.dp(10),a.dp(10),a.dp(10),a.dp(10));UiIcon icon=new UiIcon(a,icons[i],a.light?0xff326376:0xffb9e2e8);icon.setFocusable(false);line.addView(icon,new LinearLayout.LayoutParams(a.dp(38),a.dp(38)));TextView text=a.label(I18n.t(labels[i]),16,a.TEXT);text.setPadding(a.dp(12),0,0,0);line.addView(text);line.setContentDescription(I18n.t(labels[i]));line.setOnClickListener(v->{panel.animate().translationX(-panel.getWidth()).alpha(.2f).setDuration(180).withEndAction(()->{dialog.dismiss();actions[at].run();}).start();});panel.addView(line,new LinearLayout.LayoutParams(-1,a.dp(62)));a.space(panel,10);}
  a.space(panel,22);panel.addView(a.button(I18n.t("Все возможности"),false,()->{dialog.dismiss();a.profileMenu();}));LinearLayout.LayoutParams spacer=new LinearLayout.LayoutParams(1,0,1);panel.addView(new View(a),spacer);panel.addView(a.button(I18n.t("Закрыть"),false,dialog::dismiss));dialog.setContentView(panel);Window window=dialog.getWindow();if(window!=null){window.setBackgroundDrawableResource(android.R.color.transparent);window.setDimAmount(.3f);window.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);window.setGravity(Gravity.START|Gravity.TOP);}dialog.show();if(window!=null){window.setLayout(Math.min(a.dp(284),a.getResources().getDisplayMetrics().widthPixels-a.dp(42)),-1);}panel.setTranslationX(-a.dp(280));panel.animate().translationX(0).setDuration(220).start();}
 static void anchor(MainActivity a){if(a.vault.token().isEmpty())return;LinearLayout row=a.row();TextView menu=a.button("☰  "+I18n.t("Меню"),false,()->show(a));menu.setTextSize(12);menu.setContentDescription(I18n.t("Открыть меню слева"));row.addView(menu,new LinearLayout.LayoutParams(a.dp(104),a.dp(42)));a.space(a.root,8);a.root.addView(row);}
 static void conversations(MainActivity a){LinearLayout tabs=a.row();tabs.setBackground(a.glass(20));String[] names={"Все","Личные","Группы","Каналы"};for(int i=0;i<names.length;i++){int at=i;TextView tab=a.button(I18n.t(names[i]),a.filter==i,()->{a.filter=at;a.chats();});tab.setTextSize(11);tab.setPadding(a.dp(3),a.dp(10),a.dp(3),a.dp(10));tabs.addView(tab,new LinearLayout.LayoutParams(0,a.dp(46),1));}a.root.addView(tabs);a.space(a.root,8);TextView youtube=a.button("▶  "+I18n.t("Просмотр YouTube"),false,()->YouTubeBrowser.open(a,"https://m.youtube.com/"));youtube.setTextColor(Color.WHITE);youtube.setBackground(a.shape(0xffbc3446,18));a.root.addView(youtube,new LinearLayout.LayoutParams(-1,a.dp(48)));}
}
