package chat.oldy;
import android.app.*;import android.content.*;import android.widget.*;import org.json.*;import org.vosk.*;import java.io.*;import java.util.concurrent.*;

/** One cancellable recognition task. Only the account's local encrypted vault receives the result. */
final class SpeechNotes {
 static final ExecutorService worker=Executors.newSingleThreadExecutor();static volatile Job job;
 static final class Job implements SpeechModels.Progress {final String account,mid;volatile String status="";volatile boolean cancel;Job(String a,String m){account=a;mid=m;}public boolean cancelled(){return cancel;}public void status(String s){status=s;}}
 static synchronized void cancel(){if(job!=null)job.cancel=true;}
 static String saved(Vault v,String mid){try{synchronized(v){JSONObject bucket=v.data.optJSONObject("transcripts");return bucket==null?"":bucket.optString(mid);}}catch(Exception ignored){return "";}}
 static void choose(MainActivity a,JSONObject message){if(message.optLong("duration")>600000){a.error(SpeechDecoder.limit());return;}Job current=job;if(current!=null){if(current.account.equals(a.vault.nick())&&current.mid.equals(message.optString("id")))current.cancel=true;else a.error(LegalCenter.tr("Дождись завершения текущей записи","Wait for the current transcription"));return;}a.dialog().setTitle(LegalCenter.tr("Язык записи","Recording language")).setItems(new String[]{"Русский","English"},(d,w)->{String lang=w==0?"ru":"en";if(SpeechModels.ready(a,lang))start(a,message,lang);else a.dialog().setTitle(LegalCenter.tr("Распознавание на телефоне","On-device transcription")).setMessage(LegalCenter.tr("Сначала загрузим языковую модель Vosk (около 45 МБ). Лучше использовать Wi-Fi. Аудио останется на телефоне. После загрузки распознавание работает без интернета.","First download the Vosk language model (about 45 MB). Wi-Fi is recommended. Audio stays on your phone; after the download, recognition works offline.")).setNegativeButton(I18n.t("Отмена"),null).setPositiveButton(LegalCenter.tr("Загрузить и распознать","Download and transcribe"),(x,y)->start(a,message,lang)).show();}).show();}
 static synchronized void start(MainActivity a,JSONObject message,String language){if(job!=null)return;final Vault owner=a.vault;Job task=new Job(owner.nick(),message.optString("id"));job=task;task.status=LegalCenter.tr("Подготавливаем аудио…","Preparing audio…");worker.execute(()->{try{JSONObject m=owner.message(task.mid);if(m==null)throw new IOException(I18n.t("Сообщение удалено"));if(!m.has("local")||!MediaFiles.path(a,m.optString("local")).isFile()){if(m.optString("cloud_blob").isEmpty())throw new IOException(LegalCenter.tr("Сначала загрузи аудиофайл из сообщения","Download the message's audio file first"));CloudMedia.download(a,owner,m);m=owner.message(task.mid);}if(task.cancelled())throw new CancellationException();byte[] audio=MediaFiles.bytes(a,m.getString("local"));SpeechDecoder.validateDuration(audio);File model=SpeechModels.ensure(a,language,task);String text=recognize(model,audio,task);
    if(task.cancelled()||owner.erased||owner!=a.vault||owner.message(task.mid)==null)throw new CancellationException();if(text.isEmpty())throw new IOException(LegalCenter.tr("Разборчивая речь не найдена. Попробуй другой язык.","No clear speech found. Try the other language."));synchronized(owner){JSONObject all=owner.data.optJSONObject("transcripts");if(all==null){all=new JSONObject();owner.data.put("transcripts",all);}all.put(task.mid,text);owner.save();}
   }catch(CancellationException ignored){}catch(Throwable failure){if(!task.cancelled())a.runOnUiThread(()->{if(!a.isFinishing()&&a.vault==owner)a.error(failure instanceof OutOfMemoryError?LegalCenter.tr("Не хватает памяти для распознавания","Not enough memory for recognition"):Api.message(failure));});}finally{if(job==task)job=null;a.runOnUiThread(()->{if(!a.isDestroyed()&&a.vault==owner&&a.screen.equals("chat"))a.renderMessages();});}});a.renderMessages();}
 static String recognize(File model,byte[] audio,SpeechModels.Progress progress)throws Exception{
  LibVosk.setLogLevel(LogLevel.WARNINGS);StringBuilder result=new StringBuilder();progress.status(LegalCenter.tr("Открываем языковую модель…","Opening language model…"));
  try(Model engine=new Model(model.getAbsolutePath());Recognizer recognizer=new Recognizer(engine,SpeechDecoder.RATE)){
   SpeechDecoder.decode(audio,new SpeechDecoder.Consumer(){int displayed=-1;public boolean cancelled(){return progress.cancelled();}public void accept(byte[] block,int length,double seconds)throws Exception{if(recognizer.acceptWaveForm(block,length))append(result,recognizer.getResult());int position=(int)seconds;if(position!=displayed){displayed=position;progress.status(LegalCenter.tr("Распознаём · ","Transcribing · ")+VideoLibraryStore.time(seconds));}}});append(result,recognizer.getFinalResult());
  }return result.toString().trim();
 }
 static void append(StringBuilder to,String json)throws Exception{String part=new JSONObject(json).optString("text").trim();if(!part.isEmpty()){if(to.length()>0)to.append(' ');if(to.length()+part.length()>60000)throw new IOException("Transcript too long");to.append(part);}}
}
