package chat.oldy;
import android.content.Context;import org.json.*;import java.io.*;import java.net.*;import java.security.*;import java.util.zip.*;

/** Data-only models. Fixed official hosts + checksum sealed into the signed APK; never remote code. */
final class SpeechModels {
 interface Progress{void status(String message);boolean cancelled();}
 static JSONObject spec(Context c,String language)throws Exception{if(!language.matches("ru|en"))throw new IOException("Unsupported language");try(InputStream in=c.getAssets().open("speech-models.json")){return new JSONObject(Api.read(in,8000)).getJSONObject(language);}}
 static File directory(Context c,String language)throws Exception{return new File(c.getNoBackupFilesDir(),"speech/"+spec(c,language).getString("name"));}
 static boolean ready(Context c,String language){try{return new File(directory(c,language),".ready").isFile();}catch(Exception e){return false;}}
 static File ensure(Context c,String language,Progress progress)throws Exception{
  File dir=directory(c,language);if(ready(c,language))return dir;JSONObject info=spec(c,language);File archive=new File(c.getCacheDir(),"speech-"+language+".part");URL url=new URL(info.getString("url"));if(!url.getProtocol().equals("https")||!url.getHost().equals("alphacephei.com")||!url.getPath().startsWith("/vosk/models/")||url.getUserInfo()!=null)throw new IOException("Invalid model source");HttpURLConnection connection=(HttpURLConnection)url.openConnection();connection.setInstanceFollowRedirects(false);connection.setConnectTimeout(15000);connection.setReadTimeout(15000);
  try{if(connection.getResponseCode()!=200)throw new IOException(LegalCenter.tr("Не удалось загрузить языковую модель. Проверь интернет и повтори.","Language model download failed. Check your connection and retry."));long expected=info.getLong("size"),total=0;int shown=-1;MessageDigest hash=MessageDigest.getInstance("SHA-256");try(InputStream in=connection.getInputStream();OutputStream out=new FileOutputStream(archive)){byte[] block=new byte[32768];int n;while((n=in.read(block))!=-1){if(progress.cancelled())throw new java.util.concurrent.CancellationException();total+=n;if(total>expected||total>70000000)throw new IOException("Invalid model size");hash.update(block,0,n);out.write(block,0,n);int percent=(int)(total*100/expected);if(percent!=shown){shown=percent;progress.status(LegalCenter.tr("Загрузка модели · ","Downloading model · ")+percent+"%");}}}if(total!=expected||!Crypto.hex(hash.digest()).equals(info.getString("sha256")))throw new IOException(LegalCenter.tr("Проверка языковой модели не пройдена","Language model verification failed"));try(InputStream in=new FileInputStream(archive)){install(c,language,in,progress);}return dir;
  }finally{connection.disconnect();archive.delete();}
 }
 static synchronized void install(Context c,String language,InputStream source,Progress progress)throws Exception{
  File target=directory(c,language),parent=target.getParentFile();parent.mkdirs();File staging=new File(parent,target.getName()+".unpack");Vault.eraseTree(staging);staging.mkdirs();boolean success=false;long total=0;int count=0;String prefix=spec(c,language).getString("name")+"/";
  try(ZipInputStream zip=new ZipInputStream(source)){ZipEntry entry;byte[] buffer=new byte[32768];while((entry=zip.getNextEntry())!=null){if(progress.cancelled())throw new java.util.concurrent.CancellationException();String name=entry.getName();if(++count>500||!name.startsWith(prefix)||name.contains("\\")||name.contains("../"))throw new IOException("Invalid model archive");String relative=name.substring(prefix.length());if(relative.isEmpty())continue;File file=new File(staging,relative);if(!file.getCanonicalPath().startsWith(staging.getCanonicalPath()+File.separator))throw new IOException("Invalid model path");if(entry.isDirectory()){file.mkdirs();continue;}file.getParentFile().mkdirs();try(OutputStream out=new FileOutputStream(file)){int n;while((n=zip.read(buffer))!=-1){total+=n;if(total>180000000)throw new IOException("Model too large");out.write(buffer,0,n);}}}
   if(!new File(staging,"am/final.mdl").isFile()||!new File(staging,"conf/model.conf").isFile())throw new IOException("Incomplete model");new File(staging,".ready").createNewFile();Vault.eraseTree(target);if(!staging.renameTo(target))throw new IOException("Cannot save speech model");success=true;
  }finally{if(!success)Vault.eraseTree(staging);}
 }
}
