package chat.oldy;
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;import java.util.concurrent.*;

/** Photo editing is local: bounded decode, contour mask, background flood selection, white outline. */
public final class StickerEditorActivity extends Activity {
 final ExecutorService work=Executors.newSingleThreadExecutor();Cutout canvas;EditText title;TextView status;Bitmap original;String account;boolean busy;LinearLayout body;
 public void onCreate(Bundle saved){super.onCreate(saved);try{account=ChatService.vault(this).nick();if(account.isEmpty()){finish();return;}}catch(Exception e){finish();return;}boolean light=Notices.prefs(this).getString("theme","dark").equals("light");ThemeLayout root=new ThemeLayout(this,light,Notices.prefs(this).getString("theme","dark").equals("cyber"));root.setOrientation(1);root.setPadding(dp(16),dp(12),dp(16),dp(12));setContentView(root);root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(dp(16)+insets.getSystemWindowInsetLeft(),dp(12)+insets.getSystemWindowInsetTop(),dp(16)+insets.getSystemWindowInsetRight(),dp(12)+insets.getSystemWindowInsetBottom());return insets;});ScrollView scroll=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(1);scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));button("‹ Назад",this::finish);TextView heading=new TextView(this);heading.setText(I18n.t("Создать стикер"));heading.setTextColor(light?0xff20354b:0xfff0f6ff);heading.setTextSize(26);body.addView(heading);canvas=new Cutout(this);body.addView(canvas,new LinearLayout.LayoutParams(-1,dp(300)));status=new TextView(this);status.setTextColor(light?0xff496178:0xffc3d5e8);status.setTextSize(13);status.setText(I18n.t("Фото остаётся на телефоне до отправки стикера"));body.addView(status);button("Выбрать фото",()->{if(!busy)startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),1);});
  LinearLayout tools=new LinearLayout(this);body.addView(tools);for(String mode:new String[]{"Контур","Фон","Сброс"}){TextView v=key(mode,()->{if(canvas.image==null)return;if(mode.equals("Сброс")){canvas.reset();status.setText(I18n.t("Изменения сброшены"));}else{canvas.mode=mode.equals("Контур")?1:2;status.setText(I18n.t(canvas.mode==1?"Обведите нужный фрагмент пальцем":"Нажмите на однотонный фон, чтобы убрать его"));}});tools.addView(v,new LinearLayout.LayoutParams(0,dp(48),1));}
  Switch outline=new Switch(this);outline.setText(I18n.t("Белая окантовка"));outline.setTextColor(light?0xff20354b:0xfff0f6ff);outline.setChecked(true);outline.setOnCheckedChangeListener((v,on)->{canvas.outline=on;canvas.invalidate();});body.addView(outline);title=new EditText(this);title.setSingleLine(true);title.setHint(I18n.t("Название стикера"));title.setTextColor(light?0xff20354b:0xfff0f6ff);title.setHintTextColor(light?0xff65788b:0xff9ab0c5);title.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(40)});body.addView(title,new LinearLayout.LayoutParams(-1,dp(52)));button("Сохранить в мои стикеры",this::save);button("Отмена",this::finish);
 }
 TextView key(String text,Runnable action){TextView v=new TextView(this);v.setText(I18n.t(text));v.setTextSize(15);v.setTextColor(0xff173849);v.setGravity(Gravity.CENTER);v.setPadding(dp(8),dp(8),dp(8),dp(8));GradientDrawable d=new GradientDrawable();d.setColor(0xffb9e5eb);d.setCornerRadius(dp(14));v.setBackground(d);v.setOnClickListener(w->action.run());return v;}
 void button(String text,Runnable action){TextView v=key(text,action);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(48));lp.topMargin=dp(8);lp.bottomMargin=dp(8);body.addView(v,lp);}int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
 protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r!=1||result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();busy=true;status.setText(I18n.t("Открываем фото…"));work.execute(()->{try{Bitmap decoded;if(Build.VERSION.SDK_INT>=28){decoded=ImageDecoder.decodeBitmap(ImageDecoder.createSource(getContentResolver(),uri),(decoder,info,source)->{int w=info.getSize().getWidth(),h=info.getSize().getHeight();if(w<=0||h<=0||(long)w*h>150000000)throw new IllegalArgumentException();float scale=Math.min(1,1024f/Math.max(w,h));decoder.setTargetSize(Math.max(1,(int)(w*scale)),Math.max(1,(int)(h*scale)));decoder.setAllocator(ImageDecoder.ALLOCATOR_SOFTWARE);});}else{BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;try(InputStream in=getContentResolver().openInputStream(uri)){BitmapFactory.decodeStream(in,null,o);}if(o.outWidth<1||o.outHeight<1||(long)o.outWidth*o.outHeight>150000000)throw new IOException();o.inSampleSize=Math.max(1,Math.max(o.outWidth,o.outHeight)/768);o.inJustDecodeBounds=false;try(InputStream in=getContentResolver().openInputStream(uri)){decoded=BitmapFactory.decodeStream(in,null,o);}}
   if(decoded==null)throw new IOException();Bitmap small=Bitmap.createBitmap(512,512,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(small);float scale=480f/Math.max(decoded.getWidth(),decoded.getHeight());float w=decoded.getWidth()*scale,h=decoded.getHeight()*scale;c.drawBitmap(decoded,null,new RectF((512-w)/2,(512-h)/2,(512+w)/2,(512+h)/2),new Paint(3));decoded.recycle();runOnUiThread(()->{busy=false;if(isDestroyed()){small.recycle();return;}canvas.setImage(small);status.setText(I18n.t("Обведите контур или уберите однотонный фон"));});
  }catch(Exception e){runOnUiThread(()->{busy=false;status.setText(I18n.t("Не удалось открыть фото"));});}});}
 void save(){if(busy||canvas.image==null)return;String name=title.getText().toString().trim();if(name.isEmpty()){title.setError(I18n.t("Укажите название"));return;}busy=true;Bitmap output=canvas.output();status.setText(I18n.t("Сохраняем стикер…"));work.execute(()->{try{String id=new PersonalStickerStore(this,account).save(output,name);runOnUiThread(()->{setResult(RESULT_OK,new Intent().setData(Uri.parse("oldy://sticker/"+id)));finish();});}catch(Exception e){runOnUiThread(()->{busy=false;status.setText(Api.message(e));});}finally{output.recycle();}});}
 protected void onDestroy(){work.shutdown();super.onDestroy();}
 static final class Cutout extends View {
  Bitmap image,source;final Paint p=new Paint(3);final Path contour=new Path();boolean drawing,outline=true;int mode=1;RectF rect=new RectF();
  Cutout(Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}void setImage(Bitmap bitmap){if(image!=null)image.recycle();if(source!=null)source.recycle();source=bitmap;image=source.copy(Bitmap.Config.ARGB_8888,true);contour.reset();invalidate();}void reset(){if(source==null)return;image.recycle();image=source.copy(Bitmap.Config.ARGB_8888,true);contour.reset();invalidate();}
  protected void onDraw(Canvas c){float side=Math.min(getWidth(),getHeight())-16;rect.set((getWidth()-side)/2,(getHeight()-side)/2,(getWidth()+side)/2,(getHeight()+side)/2);for(int x=0;x<12;x++)for(int y=0;y<12;y++){p.setColor((x+y)%2==0?0xff243444:0xff304556);c.drawRect(rect.left+x*side/12,rect.top+y*side/12,rect.left+(x+1)*side/12,rect.top+(y+1)*side/12,p);}if(image!=null){p.setColor(Color.WHITE);p.setStyle(Paint.Style.FILL);c.drawBitmap(image,null,rect,p);}if(drawing){c.save();c.translate(rect.left,rect.top);c.scale(side/512,side/512);p.setColor(0xff63fff0);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(4);c.drawPath(contour,p);p.setStyle(Paint.Style.FILL);c.restore();}}
  public boolean onTouchEvent(android.view.MotionEvent e){if(image==null)return false;float x=Math.max(0,Math.min(511,(e.getX()-rect.left)*512/rect.width())),y=Math.max(0,Math.min(511,(e.getY()-rect.top)*512/rect.height()));if(e.getActionMasked()==MotionEvent.ACTION_DOWN){getParent().requestDisallowInterceptTouchEvent(true);if(mode==2){flood((int)x,(int)y);invalidate();return true;}drawing=true;contour.reset();contour.moveTo(x,y);return true;}if(e.getActionMasked()==MotionEvent.ACTION_MOVE&&drawing){contour.lineTo(x,y);invalidate();return true;}if(e.getActionMasked()==MotionEvent.ACTION_UP&&drawing){contour.close();RectF bounds=new RectF();contour.computeBounds(bounds,true);if(bounds.width()>20&&bounds.height()>20){Bitmap mask=Bitmap.createBitmap(512,512,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(mask);Paint fill=new Paint(3);fill.setColor(Color.WHITE);c.drawPath(contour,fill);fill.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SRC_IN));c.drawBitmap(image,0,0,fill);image.recycle();image=mask;}drawing=false;contour.reset();invalidate();getParent().requestDisallowInterceptTouchEvent(false);return true;}if(e.getActionMasked()==MotionEvent.ACTION_CANCEL){drawing=false;contour.reset();getParent().requestDisallowInterceptTouchEvent(false);invalidate();}return true;}
  void flood(int x,int y){int[] pixels=new int[512*512];image.getPixels(pixels,0,512,0,0,512,512);int seed=pixels[y*512+x];boolean[] seen=new boolean[pixels.length];int[] queue=new int[pixels.length];int begin=0,end=0;queue[end++]=y*512+x;seen[y*512+x]=true;while(begin<end){int at=queue[begin++],value=pixels[at];if(Math.abs(Color.red(value)-Color.red(seed))+Math.abs(Color.green(value)-Color.green(seed))+Math.abs(Color.blue(value)-Color.blue(seed))>75)continue;pixels[at]=0;int col=at%512;for(int n:new int[]{col>0?at-1:-1,col<511?at+1:-1,at-512,at+512})if(n>=0&&n<pixels.length&&!seen[n]){seen[n]=true;queue[end++]=n;}}image.setPixels(pixels,0,512,0,0,512,512);}
  Bitmap output(){Bitmap result=Bitmap.createBitmap(512,512,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(result);Paint paint=new Paint(3);if(outline){Bitmap alpha=image.extractAlpha();paint.setColor(Color.WHITE);for(int i=0;i<20;i++){double angle=2*Math.PI*i/20;c.drawBitmap(alpha,(float)Math.cos(angle)*4,(float)Math.sin(angle)*4,paint);}alpha.recycle();}paint.setColor(Color.WHITE);c.drawBitmap(image,0,0,paint);return result;}
 }
}
