package chat.oldy;
import android.view.*;import android.widget.*;import org.json.*;

/** Real seller drafts, with checkout explicitly unavailable until merchant onboarding.
 * No demo balances, fabricated purchases, client-trusted receipts or automatic payouts. */
final class StickerMarket {
 static void show(MainActivity a){LinearLayout b=a.col();a.paragraph(b,I18n.t("Создайте предложение с вашей ценой. Продажи и выплаты появятся после подключения платёжной системы владельцем Oldi. Пока покупка недоступна, деньги не списываются."));a.space(b,12);a.paragraph(b,I18n.t("Комиссия Oldi — 15%. Комиссии платёжной системы и налоги рассчитываются отдельно."));a.space(b,12);LinearLayout items=a.col();b.addView(items);a.sheet(I18n.t("Магазин стикеров"),b);a.task(()->{JSONObject reply=a.api.call("/stickers/offers",null,a.vault.token());JSONArray offers=reply.optJSONArray("offers");a.runOnUiThread(()->{if(offers==null||offers.length()==0){a.paragraph(items,I18n.t("Предложений пока нет. Удерживайте свой стикер и выберите «Предложить на продажу»."));return;}for(int i=0;i<offers.length();i++){JSONObject offer=offers.optJSONObject(i);if(offer==null)continue;SettingsHome.row(a,items,"▣",offer.optString("title"),money(offer.optLong("price_minor"))+" · "+I18n.t("Черновик · оплата не подключена"),0xff9b78b5,()->a.error(I18n.t("Продажи ещё не включены. Это сохранённое предложение, не покупка.")));}});});}
 static String money(long minor){return String.format(java.util.Locale.ROOT,"%.2f ₽",minor/100.0);}
 static void offer(MainActivity a,JSONObject item){LinearLayout b=a.col();a.paragraph(b,I18n.t("Изображение, название и цена отправятся серверу Oldi. До подключения оплаты предложение сохранится как ваш черновик и не будет доступно для покупки."));a.space(b,10);EditText price=a.field(b,I18n.t("Ваша цена, ₽"),false);price.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL);TextView split=a.label(I18n.t("Комиссия Oldi — 15%"),13,a.MUTED);b.addView(split);CheckBox rights=new CheckBox(a);rights.setText(I18n.t("У меня есть права на продажу этого изображения"));rights.setTextColor(a.TEXT);b.addView(rights);a.space(b,12);TextView save=a.button(I18n.t("Сохранить предложение"),true,()->{});save.setOnClickListener(v->{if(!rights.isChecked()){a.error(I18n.t("Для продажи нужны права на изображение"));return;}long amount;try{amount=new java.math.BigDecimal(price.getText().toString().trim().replace(',','.')).movePointRight(2).longValueExact();if(amount<100||amount>10000000)throw new IllegalArgumentException();}catch(Exception e){price.setError(I18n.t("Цена от 1 до 100 000 ₽, не более двух знаков после запятой"));return;}long fee=amount*1500/10000;split.setText(I18n.t("Oldi: ")+money(fee)+" · "+I18n.t("Автору до внешних комиссий: ")+money(amount-fee));save.setEnabled(false);a.task(()->{try{a.api.call("/stickers/offers",new JSONObject().put("id",item.getString("id")).put("title",item.getString("title")).put("image",item.getString("image")).put("price_minor",amount).put("currency","RUB").put("rights_confirmed",true),a.vault.token());a.runOnUiThread(()->show(a));}finally{a.runOnUiThread(()->save.setEnabled(true));}});});b.addView(save);a.sheet(I18n.t("Предложить стикер на продажу"),b);}
}
