package chat.oldy;
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;import java.util.concurrent.*;import org.json.*;

/** Real generative frames, with explicit photo-sharing consent. No filter/rotation fallback. */
public final class StickerEditorActivity extends Activity {
 final ExecutorService work=Executors.newSingleThreadExecutor();final Handler ui=new Handler(Looper.getMainLooper());
 Cutout canvas;LinearLayout body;FrameLayout stage;EditText title;TextView status,createKey,saveKey,saveOnly;StickerImageView animatedPreview;ProgressBar progress;
 volatile boolean busy;volatile byte[] animation;Bitmap cartoon;String account,target,action="wave",pending="";Vault owner;Api api;
 static String tr(String ru,String en){return I18n.language().equals("en")?en:ru;}
 public void onCreate(Bundle b){super.onCreate(b);I18n.init(this);try{owner=ChatService.vault(this);if(owner.token().isEmpty()){finish();return;}account=owner.nick();api=new Api(this);}catch(Exception e){finish();return;}target=getIntent().getStringExtra("target");if(target==null)target="";
  ThemeLayout root=new ThemeLayout(this);body=root;setContentView(root);if(Build.VERSION.SDK_INT>=30)getWindow().setDecorFitsSystemWindows(false);root.setPadding(dp(14),dp(10),dp(14),dp(10));root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(dp(14)+i.getSystemWindowInsetLeft(),dp(10)+i.getSystemWindowInsetTop(),dp(14)+i.getSystemWindowInsetRight(),dp(10)+i.getSystemWindowInsetBottom());return i;});
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.addView(key("‹",this::finish),new LinearLayout.LayoutParams(dp(46),dp(46)));TextView name=new TextView(this);name.setText(tr("Мультяшный стикер","Cartoon sticker"));name.setTextSize(22);name.setTextColor(light()?0xff24324a:Color.WHITE);name.setPadding(dp(12),0,0,0);head.addView(name);body.addView(head);
  status=new TextView(this);status.setTextSize(13);status.setTextColor(light()?0xff526079:0xffc1d4e5);status.setPadding(0,dp(10),0,dp(10));status.setText(tr("Выберите фото и действие персонажа","Choose a photo and a character action"));body.addView(status);
  stage=new FrameLayout(this);stage.setMinimumHeight(dp(160));canvas=new Cutout(this);canvas.mode=0;canvas.outline=false;canvas.changed=this::invalidateAnimation;stage.addView(canvas,new FrameLayout.LayoutParams(-1,-1));animatedPreview=new StickerImageView(this);animatedPreview.setVisibility(View.GONE);stage.addView(animatedPreview,new FrameLayout.LayoutParams(-1,-1));body.addView(stage,new LinearLayout.LayoutParams(-1,0,1));
  progress=new ProgressBar(this);progress.setVisibility(View.GONE);body.addView(progress,new LinearLayout.LayoutParams(-1,dp(30)));body.addView(key(tr("Выбрать фото","Choose photo"),this::pick),new LinearLayout.LayoutParams(-1,dp(48)));
  LinearLayout moves=new LinearLayout(this);String[] keys={"wave","laugh","yes"},ru={"Машет рукой","Смеётся","Класс!"},en={"Waves","Laughs","Thumbs up"};for(int i=0;i<3;i++){int at=i;TextView key=key(tr(ru[i],en[i]),()->{if(busy)return;action=keys[at];invalidateAnimation();status.setText(tr("Действие: ","Action: ")+tr(ru[at],en[at]));});key.setTextSize(12);moves.addView(key,new LinearLayout.LayoutParams(0,dp(46),1));}body.addView(moves);
  title=new EditText(this);title.setTextSize(14);title.setTextColor(light()?0xff24324a:Color.WHITE);title.setHintTextColor(light()?0xff526079:0xffc1d4e5);title.setHint(tr("Название стикера (необязательно)","Sticker name (optional)"));title.setSingleLine(true);title.setFilters(new android.text.InputFilter[]{new android.text.InputFilter.LengthFilter(40)});body.addView(title,new LinearLayout.LayoutParams(-1,dp(44)));
  createKey=key(tr("✨ Создать стикер","✨ Create sticker"),this::create);body.addView(createKey,new LinearLayout.LayoutParams(-1,dp(52)));saveKey=key(target.isEmpty()?tr("Сохранить в мои стикеры","Save to my stickers"):tr("Сохранить и отправить","Save and send"),()->save(!target.isEmpty()));saveKey.setVisibility(View.GONE);body.addView(saveKey,new LinearLayout.LayoutParams(-1,dp(52)));saveOnly=key(tr("Только сохранить","Save only"),()->save(false));saveOnly.setVisibility(View.GONE);body.addView(saveOnly,new LinearLayout.LayoutParams(-1,dp(44)));
  pending=Notices.prefs(this).getString("sticker_pending_"+account,"");if(!pending.isEmpty()){busy=true;progress.setVisibility(View.VISIBLE);status.setText(tr("Проверяем ранее начатый стикер…","Checking your previous sticker…"));work.execute(()->poll(pending));}else if(getIntent().getBooleanExtra("pick_photo",false))ui.post(this::pick);
 }
 boolean light(){return Notices.prefs(this).getString("theme","dark").equals("light");}
 void pick(){if(busy)return;startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),1);}
 TextView key(String text,Runnable action){TextView v=new TextView(this);v.setText(text);v.setTextSize(15);v.setTextColor(0xff173849);v.setGravity(Gravity.CENTER);v.setPadding(dp(8),dp(8),dp(8),dp(8));GradientDrawable d=new GradientDrawable();d.setColor(0xffb9e5eb);d.setCornerRadius(dp(14));v.setBackground(d);v.setContentDescription(text);v.setOnClickListener(w->action.run());return v;}int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
 protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r!=1||result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();busy=true;status.setText(I18n.t("Открываем фото…"));work.execute(()->{try{Bitmap decoded;if(Build.VERSION.SDK_INT>=28){decoded=ImageDecoder.decodeBitmap(ImageDecoder.createSource(getContentResolver(),uri),(decoder,info,source)->{int w=info.getSize().getWidth(),h=info.getSize().getHeight();if(w<=0||h<=0||(long)w*h>150000000)throw new IllegalArgumentException();float scale=Math.min(1,1024f/Math.max(w,h));decoder.setTargetSize(Math.max(1,(int)(w*scale)),Math.max(1,(int)(h*scale)));decoder.setAllocator(ImageDecoder.ALLOCATOR_SOFTWARE);});}else{BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;try(InputStream in=getContentResolver().openInputStream(uri)){BitmapFactory.decodeStream(in,null,o);}if(o.outWidth<1||o.outHeight<1||(long)o.outWidth*o.outHeight>150000000)throw new IOException();o.inSampleSize=Math.max(1,Math.max(o.outWidth,o.outHeight)/768);o.inJustDecodeBounds=false;try(InputStream in=getContentResolver().openInputStream(uri)){decoded=BitmapFactory.decodeStream(in,null,o);}try(InputStream in=getContentResolver().openInputStream(uri)){android.media.ExifInterface exif=new android.media.ExifInterface(in);int orientation=exif.getAttributeInt(android.media.ExifInterface.TAG_ORIENTATION,1);Matrix rotate=new Matrix();switch(orientation){case 2:rotate.setScale(-1,1);break;case 3:rotate.setRotate(180);break;case 4:rotate.setScale(1,-1);break;case 5:rotate.setRotate(90);rotate.postScale(-1,1);break;case 6:rotate.setRotate(90);break;case 7:rotate.setRotate(-90);rotate.postScale(-1,1);break;case 8:rotate.setRotate(-90);break;}if(decoded!=null&&!rotate.isIdentity()){Bitmap upright=Bitmap.createBitmap(decoded,0,0,decoded.getWidth(),decoded.getHeight(),rotate,true);if(upright!=decoded)decoded.recycle();decoded=upright;}}catch(Exception ignored){}}
   if(decoded==null)throw new IOException();Bitmap small=Bitmap.createBitmap(512,512,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(small);float scale=480f/Math.max(decoded.getWidth(),decoded.getHeight());float w=decoded.getWidth()*scale,h=decoded.getHeight()*scale;c.drawBitmap(decoded,null,new RectF((512-w)/2,(512-h)/2,(512+w)/2,(512+h)/2),new Paint(3));decoded.recycle();runOnUiThread(()->{busy=false;if(isDestroyed()){small.recycle();return;}canvas.setImage(small);animation=null;animatedPreview.setVisibility(View.GONE);saveKey.setVisibility(View.GONE);status.setText(tr("Фото готово. Выберите действие персонажа.","Photo ready. Choose a character action."));createKey.setEnabled(true);});
  }catch(Exception e){runOnUiThread(()->{busy=false;status.setText(I18n.t("Не удалось открыть фото"));});}});}
 void invalidateAnimation(){animation=null;if(animatedPreview!=null)animatedPreview.setVisibility(View.GONE);if(canvas!=null)canvas.setVisibility(View.VISIBLE);if(saveKey!=null)saveKey.setVisibility(View.GONE);if(saveOnly!=null)saveOnly.setVisibility(View.GONE);if(createKey!=null)createKey.setVisibility(View.VISIBLE);}
 void create(){if(busy)return;if(canvas.image==null){pick();return;}busy=true;createKey.setEnabled(false);progress.setVisibility(View.VISIBLE);status.setText(tr("Проверяем доступ к генератору…","Checking generator availability…"));work.execute(()->{try{JSONObject config=api.call("/stickers/generation/config",null,owner.token());if(!config.optBoolean("enabled"))throw new Api.Failure(503,"STICKER_GENERATOR_NOT_CONFIGURED");runOnUiThread(()->{if(isDestroyed())return;busy=false;progress.setVisibility(View.GONE);createKey.setEnabled(true);new AlertDialog.Builder(this).setTitle(tr("Создать мультяшного персонажа?","Create a cartoon character?"))
 .setMessage(tr("Это фото будет передано серверу Oldi и генератору OpenAI для рисования новых кадров. Личные сообщения не отправляются. Исходное фото не сохраняется на сервере Oldi; готовый результат доступен один час. Генерация может занять больше минуты. Используйте фото, которое имеете право обработать.","This photo will be sent to the Oldi server and OpenAI to draw new frames. Private messages are not sent. Oldi does not save the source photo; the result is available for one hour. Generation may take over a minute. Use a photo you have permission to process."))
 .setPositiveButton(tr("Передать фото и создать","Send photo and create"),(d,w)->generate()).setNegativeButton(I18n.t("Отмена"),null).show();});}catch(Exception e){failure(e,true);}});}
 void generate(){if(busy||canvas.image==null)return;busy=true;createKey.setEnabled(false);progress.setVisibility(View.VISIBLE);pending=UUID.randomUUID().toString();Notices.prefs(this).edit().putString("sticker_pending_"+account,pending).apply();String id=pending,move=action;Bitmap input=canvas.source.copy(Bitmap.Config.ARGB_8888,false);status.setText(tr("Генератор рисует действия персонажа…","The generator is drawing character actions…"));work.execute(()->{try{ByteArrayOutputStream out=new ByteArrayOutputStream();input.compress(Bitmap.CompressFormat.JPEG,90,out);JSONObject request=new JSONObject().put("id",id).put("image",Crypto.b64(out.toByteArray())).put("action",move).put("consent_version",1);api.call("/stickers/generate",request,owner.token());poll(id);}catch(Exception e){failure(e,e instanceof Api.Failure);}finally{input.recycle();}});}
 void poll(String id){long began=SystemClock.elapsedRealtime();try{while(!isDestroyed()&&SystemClock.elapsedRealtime()-began<420000){JSONObject job=api.call("/stickers/generation/"+id,null,owner.token());String state=job.optString("state");if(state.equals("ready")){byte[] bytes=Crypto.un64(job.getString("image"));if(bytes.length>350000||!AnimatedStickerCodec.animated(bytes)||!Crypto.hex(java.security.MessageDigest.getInstance("SHA-256").digest(bytes)).equalsIgnoreCase(job.getString("sha256")))throw new IOException("STICKER_CHECKSUM");Bitmap poster=BitmapFactory.decodeByteArray(bytes,0,bytes.length);if(poster==null||poster.getWidth()>512||poster.getHeight()>512)throw new IOException("STICKER_FORMAT");runOnUiThread(()->display(bytes,poster));return;}if(state.equals("failed")||state.equals("expired"))throw new Api.Failure(400,state.equals("expired")?"STICKER_EXPIRED":job.optString("error","GENERATION_FAILED"));long seconds=(SystemClock.elapsedRealtime()-began)/1000;runOnUiThread(()->{if(!isDestroyed())status.setText(tr("Рисуем новые кадры · ","Drawing new frames · ")+seconds+tr(" сек. Можно вернуться в чат и открыть создание позже."," sec. You can return to the chat and reopen creation later."));});Thread.sleep(2000);}if(!isDestroyed())throw new IOException("STILL_PROCESSING");}catch(Exception e){failure(e,e instanceof Api.Failure);}}
 void display(byte[] bytes,Bitmap poster){if(isDestroyed()){poster.recycle();return;}try{if(!ChatService.vault(this).nick().equals(account)){poster.recycle();finish();return;}animatedPreview.bytes(bytes);if(cartoon!=null)cartoon.recycle();cartoon=poster;animation=bytes;busy=false;progress.setVisibility(View.GONE);canvas.setVisibility(View.GONE);animatedPreview.setVisibility(View.VISIBLE);saveKey.setVisibility(View.VISIBLE);saveOnly.setVisibility(target.isEmpty()?View.GONE:View.VISIBLE);createKey.setVisibility(View.GONE);createKey.setEnabled(true);status.setText(tr("Готово. Проверьте лицо и движение перед отправкой.","Ready. Check the face and action before sending."));}catch(Exception e){poster.recycle();failure(e,true);}}
 void failure(Exception e,boolean clear){if(clear){pending="";Notices.prefs(this).edit().remove("sticker_pending_"+account).apply();}String code=e.getMessage();String message=errorText(code);runOnUiThread(()->{if(isDestroyed())return;busy=false;progress.setVisibility(View.GONE);createKey.setEnabled(true);status.setText(message);if(!pending.isEmpty()){createKey.setText(tr("Проверить готовность","Check progress"));createKey.setOnClickListener(v->{if(busy)return;busy=true;progress.setVisibility(View.VISIBLE);work.execute(()->poll(pending));});}else{createKey.setText(tr("✨ Создать стикер","✨ Create sticker"));createKey.setOnClickListener(v->create());}});}
 static String errorText(String code){if(code==null)return tr("Не удалось создать стикер","Could not create sticker");if(code.equals("STICKER_GENERATOR_NOT_CONFIGURED"))return tr("Генератор ещё не подключён владельцем Oldi. Нужна настройка OpenAI API на сервере. Фото не отправлено.","Oldi's owner has not connected the generator yet. OpenAI API setup on the server is required. The photo was not sent.");if(code.equals("PROVIDER_CREDENTIALS")||code.equals("PROVIDER_ACCESS"))return tr("Генератор отклонил доступ. Владельцу нужно проверить API-ключ и доступность сервиса.","The generator denied access. The owner needs to check the API key and service availability.");if(code.contains("LIMIT")||code.equals("STICKER_QUEUE_FULL"))return tr("Лимит генерации или очередь заполнена. Попробуйте позже.","Generation limit or queue reached. Try later.");if(code.equals("PROVIDER_REJECTED"))return tr("Генератор отклонил запрос. Попробуйте другое фото.","The generator declined the request. Try another photo.");if(code.startsWith("ANIMATION_"))return tr("Генератор вернул неподходящие кадры. Стикер не сохранён; попробуйте другое фото.","The generator returned unsuitable frames. The sticker was not saved; try another photo.");if(code.equals("SERVER_RESTARTED")||code.equals("STICKER_EXPIRED")||code.equals("STICKER_JOB_NOT_FOUND"))return tr("Предыдущая генерация недоступна. Создайте стикер снова.","The previous generation is unavailable. Create the sticker again.");return tr("Генерация не завершена. Проверьте готовность позже; повторная проверка не создаёт платный запрос.","Generation has not completed. Check later; checking does not create a paid request.");}
 void save(boolean send){if(busy||animation==null)return;busy=true;saveKey.setEnabled(false);byte[] bytes=animation;Bitmap poster=cartoon.copy(Bitmap.Config.ARGB_8888,false);String text=title.getText().toString().trim(),name=text.isEmpty()?tr("Мой стикер","My sticker"):text;work.execute(()->{try{String id=new PersonalStickerStore(this,account).saveAnimation(bytes,poster,name);Notices.prefs(this).edit().remove("sticker_pending_"+account).apply();runOnUiThread(()->{setResult(RESULT_OK,new Intent().setData(Uri.parse("oldy://sticker/"+id)).putExtra("send_now",send).putExtra("target",target));finish();});}catch(Exception e){failure(e,false);}finally{poster.recycle();}});}
 protected void onDestroy(){ui.removeCallbacksAndMessages(null);work.shutdownNow();if(canvas!=null)canvas.release();if(cartoon!=null)cartoon.recycle();super.onDestroy();}
 static final class Cutout extends View {
  Runnable changed;Bitmap image,source,preview;final Paint p=new Paint(3);final Path contour=new Path();boolean drawing,outline=true;int mode=1;RectF rect=new RectF();
  Cutout(Context c){super(c);setLayerType(View.LAYER_TYPE_SOFTWARE,null);}void setImage(Bitmap bitmap){if(image!=null)image.recycle();if(source!=null)source.recycle();source=bitmap;image=source.copy(Bitmap.Config.ARGB_8888,true);contour.reset();refresh();}void reset(){if(source==null)return;image.recycle();image=source.copy(Bitmap.Config.ARGB_8888,true);contour.reset();refresh();}
  void refresh(){if(changed!=null)changed.run();if(preview!=null){preview.recycle();preview=null;}invalidate();}
  void release(){if(image!=null)image.recycle();if(source!=null)source.recycle();if(preview!=null)preview.recycle();image=source=preview=null;}
  protected void onDraw(Canvas c){float side=Math.min(getWidth(),getHeight())-16;rect.set((getWidth()-side)/2,(getHeight()-side)/2,(getWidth()+side)/2,(getHeight()+side)/2);for(int x=0;x<12;x++)for(int y=0;y<12;y++){p.setColor((x+y)%2==0?0xff243444:0xff304556);c.drawRect(rect.left+x*side/12,rect.top+y*side/12,rect.left+(x+1)*side/12,rect.top+(y+1)*side/12,p);}if(image!=null){p.setColor(Color.WHITE);p.setStyle(Paint.Style.FILL);if(preview==null)preview=output();c.drawBitmap(preview,null,rect,p);}if(drawing){c.save();c.translate(rect.left,rect.top);c.scale(side/512,side/512);p.setColor(0xff63fff0);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(4);c.drawPath(contour,p);p.setStyle(Paint.Style.FILL);c.restore();}}
  public boolean onTouchEvent(android.view.MotionEvent e){if(mode==0||image==null||(getContext() instanceof StickerEditorActivity&&((StickerEditorActivity)getContext()).busy))return false;float x=Math.max(0,Math.min(511,(e.getX()-rect.left)*512/rect.width())),y=Math.max(0,Math.min(511,(e.getY()-rect.top)*512/rect.height()));if(e.getActionMasked()==MotionEvent.ACTION_DOWN){getParent().requestDisallowInterceptTouchEvent(true);if(mode==2){flood((int)x,(int)y);refresh();return true;}drawing=true;contour.reset();contour.moveTo(x,y);return true;}if(e.getActionMasked()==MotionEvent.ACTION_MOVE&&drawing){contour.lineTo(x,y);invalidate();return true;}if(e.getActionMasked()==MotionEvent.ACTION_UP&&drawing){contour.close();RectF bounds=new RectF();contour.computeBounds(bounds,true);if(bounds.width()>20&&bounds.height()>20){Bitmap mask=Bitmap.createBitmap(512,512,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(mask);Paint fill=new Paint(3);fill.setColor(Color.WHITE);c.drawPath(contour,fill);fill.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.SRC_IN));c.drawBitmap(image,0,0,fill);image.recycle();image=mask;refresh();}drawing=false;contour.reset();invalidate();getParent().requestDisallowInterceptTouchEvent(false);return true;}if(e.getActionMasked()==MotionEvent.ACTION_CANCEL){drawing=false;contour.reset();getParent().requestDisallowInterceptTouchEvent(false);invalidate();}return true;}
  void flood(int x,int y){int[] pixels=new int[512*512];image.getPixels(pixels,0,512,0,0,512,512);int seed=pixels[y*512+x];boolean[] seen=new boolean[pixels.length];int[] queue=new int[pixels.length];int begin=0,end=0;queue[end++]=y*512+x;seen[y*512+x]=true;while(begin<end){int at=queue[begin++],value=pixels[at];if(Math.abs(Color.red(value)-Color.red(seed))+Math.abs(Color.green(value)-Color.green(seed))+Math.abs(Color.blue(value)-Color.blue(seed))>75)continue;pixels[at]=0;int col=at%512;for(int n:new int[]{col>0?at-1:-1,col<511?at+1:-1,at-512,at+512})if(n>=0&&n<pixels.length&&!seen[n]){seen[n]=true;queue[end++]=n;}}image.setPixels(pixels,0,512,0,0,512,512);}
  Bitmap output(){Bitmap result=Bitmap.createBitmap(512,512,Bitmap.Config.ARGB_8888);Canvas c=new Canvas(result);Paint paint=new Paint(3);if(outline){Bitmap alpha=image.extractAlpha();paint.setColor(Color.WHITE);for(int i=0;i<20;i++){double angle=2*Math.PI*i/20;c.drawBitmap(alpha,(float)Math.cos(angle)*4,(float)Math.sin(angle)*4,paint);}alpha.recycle();}paint.setColor(Color.WHITE);c.drawBitmap(image,0,0,paint);return result;}
 }
}
