package chat.oldy;
import android.app.*;import android.content.*;import android.content.pm.*;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.widget.*;import org.json.*;import javax.net.ssl.*;import java.io.*;import java.net.*;import java.security.*;import java.util.*;import java.util.concurrent.*;
final class Updates {
 static final ExecutorService io=Executors.newSingleThreadExecutor();static boolean downloading;static boolean showing;static long lastCheck;
 static int installed(Context c)throws Exception{return c.getPackageManager().getPackageInfo(c.getPackageName(),0).versionCode;}
 static String versionName(Context c){try{return c.getPackageManager().getPackageInfo(c.getPackageName(),0).versionName;}catch(Exception e){return "—";}}
 static void check(MainActivity a,boolean manual){if(!BuildConfig.DIRECT_UPDATES){if(manual)try{a.startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://play.google.com/store/apps/details?id="+a.getPackageName())));}catch(Exception ignored){}return;}if(!manual&&(showing||System.currentTimeMillis()-lastCheck<55000))return;lastCheck=System.currentTimeMillis();if(manual)Toast.makeText(a,I18n.t("Проверяем обновления…"),Toast.LENGTH_SHORT).show();io.execute(()->{try{JSONObject r=new Api(a).call("/updates",null,"");int current=installed(a);boolean newer=r.optBoolean("available")&&r.optInt("version_code")>current;if(!newer){if(manual)a.runOnUiThread(()->a.dialog().setTitle(I18n.t("Обновления")).setMessage(I18n.t("Установлена версия ")+versionName(a)+I18n.t(".\nДоступных обновлений пока нет.")).setPositiveButton(I18n.t("Хорошо"),null).show());return;}long deferred=Notices.prefs(a).getLong("update-later-"+r.optInt("version_code"),0);if(!manual&&System.currentTimeMillis()-deferred<21600000)return;a.runOnUiThread(()->{if(a.isFinishing()||showing)return;showing=true;AlertDialog prompt=a.dialog().setTitle(I18n.t("Доступно обновление ")+r.optString("version_name")).setMessage(r.optString("notes")+I18n.t("\n\nМожно продолжить пользоваться установленной версией. Аккаунт и переписка сохранятся.")).setNegativeButton(I18n.t("Позже"),(d,w)->Notices.prefs(a).edit().putLong("update-later-"+r.optInt("version_code"),System.currentTimeMillis()).apply()).setPositiveButton(I18n.t("Обновить"),(d,w)->download(a,r)).create();prompt.setOnDismissListener(x->showing=false);prompt.show();});}catch(Exception e){if(manual)a.runOnUiThread(()->a.error(I18n.t("Не удалось проверить обновления. Проверь подключение или попробуй позже.")));}});}
 static synchronized void download(MainActivity a,JSONObject release){if(!BuildConfig.DIRECT_UPDATES)return;if(downloading){Toast.makeText(a,I18n.t("Обновление уже загружается"),Toast.LENGTH_SHORT).show();return;}downloading=true;ProgressBar bar=new ProgressBar(a,null,android.R.attr.progressBarStyleHorizontal);bar.setMax(100);LinearLayout b=a.col();a.pad(b,20);b.addView(bar);TextView status=a.label(I18n.t("Загрузка безопасного обновления…"),14,a.TEXT);b.addView(status);AlertDialog d=a.dialog().setTitle(I18n.t("Обновление OldЫ Chat")).setView(b).setNegativeButton(I18n.t("Свернуть"),null).create();d.show();io.execute(()->{File temp=new File(a.getCacheDir(),"oldy-update.part"),apk=new File(a.getCacheDir(),"oldy-update.apk");try{String path=release.getString("path");if(!path.equals("/download/OldyChat-latest.apk"))throw new IOException(I18n.t("Неверный адрес обновления"));long expectedSize=release.getLong("size");if(expectedSize<1000||expectedSize>180000000)throw new IOException(I18n.t("Неверный размер обновления"));Api api=new Api(a);String base=Api.live.isEmpty()?api.url():Api.live;HttpsURLConnection c=(HttpsURLConnection)new URL(base+path).openConnection();c.setSSLSocketFactory(api.factory());c.setInstanceFollowRedirects(false);c.setConnectTimeout(15000);c.setReadTimeout(30000);MessageDigest digest=MessageDigest.getInstance("SHA-256");try{if(c.getResponseCode()!=200)throw new IOException(I18n.t("Обновление недоступно"));long size=0;try(InputStream in=c.getInputStream();OutputStream out=new FileOutputStream(temp)){byte[] buf=new byte[65536];int n;long shown=-1;while((n=in.read(buf))!=-1){size+=n;if(size>expectedSize)throw new IOException(I18n.t("Размер обновления не совпал"));digest.update(buf,0,n);out.write(buf,0,n);int percent=(int)(size*100/expectedSize);if(percent!=shown){shown=percent;a.runOnUiThread(()->{bar.setProgress(percent);status.setText(I18n.t("Загружено ")+percent+"%");});}}}if(size!=expectedSize)throw new IOException(I18n.t("Загрузка прервалась"));}finally{c.disconnect();}
   if(!Crypto.hex(digest.digest()).equalsIgnoreCase(release.getString("sha256")))throw new SecurityException(I18n.t("Проверка файла не пройдена. Запусти проверку обновлений ещё раз."));
   PackageManager pm=a.getPackageManager();PackageInfo candidate=pm.getPackageArchiveInfo(temp.getAbsolutePath(),PackageManager.GET_SIGNATURES),current=pm.getPackageInfo(a.getPackageName(),PackageManager.GET_SIGNATURES);if(candidate==null||!candidate.packageName.equals(a.getPackageName())||candidate.versionCode!=release.getInt("version_code")||candidate.versionCode<=current.versionCode||candidate.signatures==null||current.signatures==null||candidate.signatures.length!=current.signatures.length)throw new SecurityException(I18n.t("Это обновление не подходит приложению"));for(int i=0;i<current.signatures.length;i++)if(!current.signatures[i].equals(candidate.signatures[i]))throw new SecurityException(I18n.t("Подпись разработчика не совпала"));if(apk.exists()&&!apk.delete())throw new IOException();if(!temp.renameTo(apk))throw new IOException();a.runOnUiThread(()->{d.dismiss();install(a);});
  }catch(Exception e){temp.delete();a.runOnUiThread(()->{d.dismiss();a.error(e instanceof SecurityException?e.getMessage():I18n.t("Не удалось загрузить обновление. Старая версия продолжает работать; попробуй ещё раз."));});}finally{downloading=false;}});}
 static void install(MainActivity a){if(!a.getPackageManager().canRequestPackageInstalls()){a.dialog().setTitle(I18n.t("Разрешить обновления OldЫ Chat")).setMessage(I18n.t("В настройках Android разреши установку из этого приложения. Затем вернись сюда и нажми «Установить».")).setNegativeButton(I18n.t("Позже"),null).setPositiveButton(I18n.t("Открыть настройки"),(d,w)->{a.startActivity(new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,Uri.parse("package:"+a.getPackageName())));a.dialog().setTitle(I18n.t("Обновление загружено")).setNegativeButton(I18n.t("Позже"),null).setPositiveButton(I18n.t("Установить"),(x,y)->install(a)).show();}).show();return;}try{Uri uri=Uri.parse("content://chat.oldy.updates/latest.apk");Intent i=new Intent(Intent.ACTION_VIEW).setDataAndType(uri,"application/vnd.android.package-archive").addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);i.setClipData(ClipData.newRawUri("Oldy update",uri));a.startActivity(i);}catch(Exception e){a.error(I18n.t("Android не смог открыть установщик обновлений"));}}
}
