package chat.oldy;
import android.content.*;import android.graphics.*;import android.media.*;import android.net.Uri;import android.view.*;import android.widget.*;import java.io.*;

/** Choose a poster before uploading; crop a custom image to the video's own ratio. */
final class VideoPublish {
 final MainActivity a;final Uri video;final String target,caption;final Vault owner;
 Bitmap poster;byte[] custom;float ratio=16f/9;ImageView image;TextView status,publish;SeekBar timeline;boolean loading;
 VideoPublish(MainActivity a,Uri video,String target,String caption){this.a=a;this.video=video;this.target=target;this.caption=caption;owner=a.vault;}
 long durationMs=1,frameMs=1000;int generation;boolean ownCover;
 TextView inline(LinearLayout b,String title,Runnable run){TextView t=a.label(title,15,a.light?0xff366aaf:a.GREEN);t.setPadding(a.dp(16),a.dp(14),a.dp(16),a.dp(14));t.setMinHeight(a.dp(52));t.setBackground(a.shape(a.CARD,14));t.setOnClickListener(v->{if(!loading)run.run();});b.addView(t,new LinearLayout.LayoutParams(-1,-2));return t;}
 void show(){LinearLayout b=a.col();a.paragraph(b,I18n.t("Выбери кадр ползунком или загрузи свою картинку. Обложка сохранит пропорции ролика."));a.space(b,12);AspectMediaFrame frame=new AspectMediaFrame(a,false);image=new AspectMediaFrame.Cover(a,frame);b.addView(frame,new LinearLayout.LayoutParams(-1,-2));frame.addView(image,new android.widget.FrameLayout.LayoutParams(-1,-1));if(poster!=null)image.setImageBitmap(poster);
  status=a.label(ownCover?I18n.t("Твоя обложка"):I18n.t("Кадр из видео"),12,a.MUTED);a.space(b,8);b.addView(status);timeline=new SeekBar(a);timeline.setMax(1000);timeline.setProgress((int)Math.min(1000,frameMs*1000/Math.max(1,durationMs)));timeline.setContentDescription(I18n.t("Выбрать кадр из видео"));b.addView(timeline,new LinearLayout.LayoutParams(-1,a.dp(48)));timeline.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean user){if(user){frameMs=durationMs*p/1000;status.setText(I18n.t("Кадр · ")+String.format(java.util.Locale.ROOT,"%d:%02d",frameMs/60000,(frameMs/1000)%60));}}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){ownCover=false;loadFrame();}});
  inline(b,I18n.t("Загрузить свою обложку"),()->a.startActivityForResult(new Intent(Intent.ACTION_OPEN_DOCUMENT).setType("image/*").addCategory(Intent.CATEGORY_OPENABLE),39));a.space(b,8);inline(b,I18n.t("Использовать кадр из видео"),()->{ownCover=false;loadFrame();});a.space(b,14);
  publish=a.button(I18n.t("Опубликовать видео"),true,()->{if(loading||a.vault!=owner)return;CreatorVideo.upload(a,video,target,caption,custom);});publish.setEnabled(!loading);b.addView(publish);a.sheet(I18n.t("Видео и обложка"),b);if(poster==null)loadFrame();
 }
 void loadFrame(){final int task=++generation;final long at=frameMs;loading=true;if(publish!=null)publish.setEnabled(false);a.work.execute(()->{if(task!=generation)return;MediaMetadataRetriever r=new MediaMetadataRetriever();Bitmap frame=null;try{r.setDataSource(a,video);int width=Integer.parseInt(r.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_WIDTH)),height=Integer.parseInt(r.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_HEIGHT));String turn=r.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_ROTATION);int rotation=turn==null?0:Integer.parseInt(turn);ratio=rotation%180==0?(float)width/height:(float)height/width;durationMs=Math.max(1,Long.parseLong(r.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION)));int w=ratio>=1?1280:Math.max(1,Math.round(1280*ratio)),h=ratio>=1?Math.max(1,Math.round(1280/ratio)):1280;frame=r.getScaledFrameAtTime(Math.min(at,Math.max(0,durationMs-100))*1000,MediaMetadataRetriever.OPTION_CLOSEST,w,h);if(frame==null)frame=r.getFrameAtTime(0);}catch(Exception ignored){}finally{try{r.release();}catch(Exception ignored){}}final Bitmap ready=frame;final byte[] bytes=encode(frame);a.runOnUiThread(()->{if(task!=generation||a.vault!=owner){if(ready!=null)ready.recycle();return;}loading=false;poster=ready;custom=bytes;ownCover=false;if(image!=null)image.setImageBitmap(ready);if(publish!=null)publish.setEnabled(true);if(timeline!=null)timeline.setProgress((int)Math.min(1000,frameMs*1000/Math.max(1,durationMs)));if(status!=null)status.setText(ready==null?I18n.t("Не удалось получить кадр. Можно загрузить обложку."):I18n.t("Кадр из видео"));});});}
 static byte[] encode(Bitmap b){if(b==null)return null;ByteArrayOutputStream out=new ByteArrayOutputStream();b.compress(Bitmap.CompressFormat.JPEG,88,out);return out.toByteArray();}
 void cover(Uri uri){generation++;loading=true;a.work.execute(()->{try{BitmapFactory.Options options=new BitmapFactory.Options();options.inJustDecodeBounds=true;try(InputStream in=a.getContentResolver().openInputStream(uri)){BitmapFactory.decodeStream(in,null,options);}if(options.outWidth<1||options.outHeight<1||(long)options.outWidth*options.outHeight>160000000)throw new IOException(I18n.t("Не удалось открыть изображение"));options.inSampleSize=Math.max(1,Math.max(options.outWidth,options.outHeight)/1800);options.inJustDecodeBounds=false;Bitmap source;try(InputStream in=a.getContentResolver().openInputStream(uri)){source=BitmapFactory.decodeStream(in,null,options);}if(source==null)throw new IOException(I18n.t("Не удалось открыть изображение"));
   try(InputStream in=a.getContentResolver().openInputStream(uri)){int orientation=new ExifInterface(in).getAttributeInt(ExifInterface.TAG_ORIENTATION,1);Matrix matrix=new Matrix();switch(orientation){case 2:matrix.setScale(-1,1);break;case 3:matrix.setRotate(180);break;case 4:matrix.setScale(1,-1);break;case 5:matrix.setRotate(90);matrix.postScale(-1,1);break;case 6:matrix.setRotate(90);break;case 7:matrix.setRotate(270);matrix.postScale(-1,1);break;case 8:matrix.setRotate(270);break;}if(!matrix.isIdentity())source=Bitmap.createBitmap(source,0,0,source.getWidth(),source.getHeight(),matrix,true);}catch(Exception ignored){}
   int w=source.getWidth(),h=source.getHeight();if((float)w/h>ratio)w=Math.max(1,Math.round(h*ratio));else h=Math.max(1,Math.round(w/ratio));Bitmap crop=Bitmap.createBitmap(source,(source.getWidth()-w)/2,(source.getHeight()-h)/2,w,h);float scale=Math.min(1,1440f/Math.max(w,h));Bitmap output=Bitmap.createScaledBitmap(crop,Math.max(1,Math.round(w*scale)),Math.max(1,Math.round(h*scale)),true);ByteArrayOutputStream bytes=new ByteArrayOutputStream();output.compress(Bitmap.CompressFormat.JPEG,88,bytes);if(bytes.size()>1050000)throw new IOException(I18n.t("Обложка слишком большая. Выбери другое изображение"));custom=bytes.toByteArray();poster=output;ownCover=true;a.runOnUiThread(()->{loading=false;if(a.vault==owner)show();});
  }catch(Exception e){a.runOnUiThread(()->{loading=false;a.error(Api.message(e));});}});}
 static String small(byte[] full){Bitmap image=BitmapFactory.decodeByteArray(full,0,full.length);if(image==null)return "";try{for(int edge:new int[]{280,210,160,100}){float scale=(float)edge/Math.max(image.getWidth(),image.getHeight());Bitmap small=Bitmap.createScaledBitmap(image,Math.max(1,Math.round(image.getWidth()*scale)),Math.max(1,Math.round(image.getHeight()*scale)),true);ByteArrayOutputStream bytes=new ByteArrayOutputStream();small.compress(Bitmap.CompressFormat.JPEG,65,bytes);small.recycle();if(bytes.size()<=7800)return Crypto.b64(bytes.toByteArray());}return "";}finally{image.recycle();}}
}
