package chat.oldy;
import android.content.*;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;

final class VideoLibraryUi {
 static void show(MainActivity a,String tab){try{VideoLibraryStore store=new VideoLibraryStore(a,a.vault.nick());a.base("videos");a.title(I18n.t("Мои видео"),a::chats);LinearLayout tabs=a.row();String[] keys={"history","favorite","later"},names={"История","Избранное","Смотреть позже"};for(int i=0;i<keys.length;i++){String key=keys[i];tabs.addView(a.button(I18n.t(names[i]),key.equals(tab),()->show(a,key)),new LinearLayout.LayoutParams(0,a.dp(48),1));}a.root.addView(tabs);a.space(a.root,12);
  ScrollView scroll=new ScrollView(a);LinearLayout list=a.col();scroll.addView(list);a.root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));a.paragraph(list,I18n.t("История и сохранённые видео хранятся только в вашем профиле на этом телефоне."));a.space(list,12);List<JSONObject> items=store.list(tab);if(items.isEmpty())a.paragraph(list,I18n.t("Пока нет видео. Откройте YouTube-ссылку в чате."));
  for(JSONObject item:items){String id=item.optString("videoId");if(!YouTubeLinkDetector.video(id))continue;double position=item.optDouble("position",0);YouTubeLinkDetector.Target target=new YouTubeLinkDetector.Target(id,"",(int)position);LinearLayout row=a.row();a.pad(row,10);row.setBackground(a.glass(18));ImageView image=new ImageView(a);image.setScaleType(ImageView.ScaleType.CENTER_CROP);row.addView(image,new LinearLayout.LayoutParams(a.dp(104),a.dp(68)));Art.fetch.execute(()->{try{android.graphics.Bitmap bitmap=YouTubePreviewProvider.thumbnail(id);if(bitmap!=null)a.runOnUiThread(()->image.setImageBitmap(bitmap));}catch(Exception ignored){}});LinearLayout info=a.col();info.setPadding(a.dp(12),0,0,0);TextView title=a.label(item.optString("title",I18n.t("Видео на YouTube")),15,a.TEXT);title.setMaxLines(2);info.addView(title);a.space(info,5);info.addView(a.label(position>=5?I18n.t("Продолжить с ")+VideoLibraryStore.time(position):I18n.t("Смотреть в Oldi"),12,a.MUTED));row.addView(info,new LinearLayout.LayoutParams(0,-2,1));row.setOnClickListener(v->OldiYouTubePlayer.open(a,target,item.optString("title","YouTube")));row.setOnLongClickListener(v->{a.dialog().setTitle(item.optString("title","YouTube")).setItems(new String[]{I18n.t("Избранное"),I18n.t("Смотреть позже"),I18n.t("Удалить из моих видео")},(d,w)->a.task(()->{if(w==2)store.remove(id);else store.toggle(id,w==0?"favorite":"later");a.runOnUiThread(()->show(a,tab));})).show();return true;});list.addView(row);a.space(list,8);}
  if(tab.equals("history"))list.addView(a.button(I18n.t("Очистить историю просмотров"),false,()->a.dialog().setTitle(I18n.t("Очистить историю?")).setMessage(I18n.t("Избранное и «Смотреть позже» останутся на месте.")).setPositiveButton(I18n.t("Очистить"),(d,w)->a.task(()->{store.clearHistory();a.runOnUiThread(()->show(a,tab));})).setNegativeButton(I18n.t("Отмена"),null).show()));SettingsHome.navigation(a,3);
 }catch(Exception e){a.error(Api.message(e));}}
}
