package chat.oldy;
import android.app.*;import android.content.*;import android.content.res.Configuration;import android.graphics.Color;import android.media.*;import android.os.*;import android.view.*;import android.widget.*;import javax.net.ssl.*;import java.io.*;import java.net.*;
public class VideoActivity extends Activity {
 MediaPlayer player;Source source;FrameLayout root;SurfaceView surface;TextView status,play;SeekBar seek;Handler handler=new Handler(Looper.getMainLooper());volatile boolean prepared;boolean seeking;int vw=16,vh=9;
 public void onCreate(Bundle b){super.onCreate(b);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_FULLSCREEN|View.SYSTEM_UI_FLAG_HIDE_NAVIGATION|View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY);root=new FrameLayout(this);root.setBackgroundColor(Color.BLACK);surface=new SurfaceView(this);root.addView(surface,new FrameLayout.LayoutParams(-1,-1,Gravity.CENTER));LinearLayout controls=new LinearLayout(this);controls.setOrientation(1);controls.setPadding(24,16,24,24);controls.setBackgroundColor(0xbb101720);LinearLayout top=new LinearLayout(this);TextView back=text("‹ Назад");back.setOnClickListener(v->finish());top.addView(back);status=text("Подключаем видео…");top.addView(status,new LinearLayout.LayoutParams(0,-2,1));play=text("Ⅱ");play.setOnClickListener(v->{if(prepared){if(player.isPlaying()){player.pause();play.setText("▶");}else{player.start();play.setText("Ⅱ");}}});top.addView(play);controls.addView(top);seek=new SeekBar(this);controls.addView(seek);FrameLayout.LayoutParams cp=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM);root.addView(controls,cp);setContentView(root);seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int n,boolean user){}public void onStartTrackingTouch(SeekBar s){seeking=true;}public void onStopTrackingTouch(SeekBar s){if(prepared)player.seekTo((long)s.getProgress(),MediaPlayer.SEEK_CLOSEST);seeking=false;}});
  try{player=new MediaPlayer();player.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_MEDIA).setContentType(AudioAttributes.CONTENT_TYPE_MOVIE).build());source=new Source(this,getIntent().getStringExtra("video"),getIntent().getLongExtra("size",0));player.setDataSource(source);player.setOnPreparedListener(p->{prepared=true;seek.setMax(p.getDuration());p.start();tick();});player.setOnVideoSizeChangedListener((p,w,h)->{vw=w;vh=h;fit();});player.setOnErrorListener((p,what,extra)->{status.setText("Не удалось воспроизвести MP4. Проверь сеть или кодек видео.");return true;});player.setOnCompletionListener(p->play.setText("▶"));surface.getHolder().addCallback(new SurfaceHolder.Callback(){boolean started;public void surfaceCreated(SurfaceHolder h){player.setDisplay(h);if(!started){started=true;player.prepareAsync();}}public void surfaceChanged(SurfaceHolder h,int f,int w,int height){}public void surfaceDestroyed(SurfaceHolder h){player.setDisplay(null);}});}catch(Exception e){status.setText("Видео недоступно");}}
 TextView text(String s){TextView t=new TextView(this);t.setText(s);t.setTextColor(Color.WHITE);t.setTextSize(15);t.setPadding(14,14,14,14);return t;}
 void fit(){root.post(()->{if(vw<1||vh<1)return;int w=root.getWidth(),h=root.getHeight();if((long)w*vh>(long)h*vw)w=h*vw/vh;else h=w*vh/vw;surface.setLayoutParams(new FrameLayout.LayoutParams(w,h,Gravity.CENTER));});}
 String time(int ms){int sec=ms/1000;return String.format(java.util.Locale.ROOT,"%d:%02d",sec/60,sec%60);}
 void tick(){if(!prepared||player==null)return;try{int pos=player.getCurrentPosition();if(!seeking)seek.setProgress(pos);status.setText(time(pos)+" / "+time(player.getDuration()));}catch(Exception ignored){}handler.postDelayed(this::tick,500);}
 public void onConfigurationChanged(Configuration c){super.onConfigurationChanged(c);fit();}
 protected void onPause(){super.onPause();if(prepared&&player.isPlaying()){player.pause();play.setText("▶");}}
 protected void onDestroy(){handler.removeCallbacksAndMessages(null);if(source!=null)source.close();if(player!=null){player.release();player=null;}super.onDestroy();}
 static class Source extends MediaDataSource {
  final Api api;final String token,id;final long size;final android.util.LruCache<Long,byte[]> cache=new android.util.LruCache<>(4);volatile boolean closed;volatile HttpsURLConnection active;static final int BLOCK=524288;
  Source(Context c,String video,long bytes)throws Exception{if(video==null||!video.matches("[a-f0-9-]{36}")||bytes<=0||bytes>2147483648L)throw new IOException();api=new Api(c);token=ChatService.vault(c).token();id=video;size=bytes;}
  public long getSize(){return size;}
  public synchronized int readAt(long position,byte[] buffer,int offset,int length)throws IOException{if(closed||position<0)return -1;if(position>=size)return -1;if(length==0)return 0;long index=position/BLOCK,start=index*BLOCK;byte[] bytes=cache.get(index);if(bytes==null){long end=Math.min(size-1,start+BLOCK-1);try{String base=Api.live.isEmpty()?api.url():Api.live;HttpsURLConnection c=(HttpsURLConnection)new URL(base+"/video-stream/"+id).openConnection();active=c;if(closed){c.disconnect();throw new IOException("Closed");}c.setSSLSocketFactory(api.factory());c.setInstanceFollowRedirects(false);c.setRequestProperty("Authorization","Bearer "+token);c.setRequestProperty("Range","bytes="+start+"-"+end);c.setConnectTimeout(15000);c.setReadTimeout(25000);try{if(c.getResponseCode()!=206||!("bytes "+start+"-"+end+"/"+size).equals(c.getHeaderField("Content-Range")))throw new IOException("Video access denied");bytes=new byte[(int)(end-start+1)];try(InputStream in=c.getInputStream()){int got=0;while(got<bytes.length){int n=in.read(bytes,got,bytes.length-got);if(n<0)throw new EOFException();got+=n;}}cache.put(index,bytes);}finally{c.disconnect();active=null;}}catch(Exception e){throw new IOException("Video loading failed",e);}}int at=(int)(position-start),n=Math.min(length,bytes.length-at);System.arraycopy(bytes,at,buffer,offset,n);return n;}
  public void close(){closed=true;HttpsURLConnection c=active;if(c!=null)c.disconnect();cache.evictAll();}
 }
}
