package chat.oldy;
import android.*;import android.content.pm.PackageManager;import android.graphics.*;import android.media.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;import java.util.*;import org.json.*;
/** Recorder, visible input meter and a retryable upload. Only encoded audio can be sent. */
final class VoiceCapture {
 final MainActivity a;MediaRecorder recorder;File file;long started;String target;Vault account;LinearLayout bar;TextView timer,hint;Wave wave;volatile boolean running,silenced;boolean uploading,deferStop,heldAtLimit;volatile int ticks;volatile String levelError="";HandlerThread meterThread;Handler meterHandler;final Object recorderLock=new Object();float cancelAmount;ProgressBar cancelBar;final ArrayList<Integer> levels=new ArrayList<>();
 File pending;JSONObject pendingMetadata;String pendingTarget;Vault pendingAccount;final Runnable sample=this::tick;
 VoiceCapture(MainActivity activity){a=activity;}
 boolean begin(){
  if(running)return true;
  if(pending!=null&&!uploading&&pendingAccount!=a.vault){pending.delete();pending=null;pendingAccount=null;heldAtLimit=false;}
  if(uploading||pending!=null){if(!a.chat.equals(pendingTarget)){a.error(I18n.t("Есть неотправленное голосовое в другом чате. Вернитесь в него и отправьте или удалите запись."));}else showPending();return false;}
  if(a.replyBar==null||a.chat==null||a.chat.isEmpty())return false;
  if(a.checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){a.requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},11);return false;}
  if(LiveCall.current!=null){a.error(I18n.t("Заверши звонок перед записью голосового"));return false;}
  AudioManager audio=a.getSystemService(AudioManager.class);if(audio!=null&&audio.isMicrophoneMute()){a.error(I18n.t("Включи доступ к микрофону в настройках Android"));return false;}
  try{
   if(a.voicePlayer!=null)a.voicePlayer.release();if(a.player!=null){try{a.player.release();}catch(Exception ignored){}a.player=null;}target=a.chat;account=a.vault;levels.clear();ticks=0;silenced=false;cancelAmount=0;
   file=new File(a.getCacheDir(),"voice-"+System.currentTimeMillis()+".m4a");recorder=new MediaRecorder();recorder.setAudioSource(MediaRecorder.AudioSource.MIC);recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);recorder.setAudioEncodingBitRate(96000);recorder.setAudioSamplingRate(48000);recorder.setAudioChannels(1);recorder.setMaxDuration(180000);recorder.setOutputFile(file.getAbsolutePath());
   recorder.setOnInfoListener((r,what,extra)->{if(what==MediaRecorder.MEDIA_RECORDER_INFO_MAX_DURATION_REACHED){deferStop=true;end(true);deferStop=false;}});recorder.setOnErrorListener((r,what,extra)->{end(false);a.error(I18n.t("Микрофон прервал запись. Попробуй снова."));});recorder.prepare();recorder.start();try{recorder.getMaxAmplitude();}catch(RuntimeException notReady){}started=SystemClock.elapsedRealtime();running=true;
   bar=a.col();a.pad(bar,10);bar.setBackground(a.shape(a.CARD,18));LinearLayout controls=a.row();timer=a.label("● 0:00",14,0xffe85879);timer.setTypeface(null,1);controls.addView(timer,new LinearLayout.LayoutParams(0,a.dp(40),1));timer.setGravity(Gravity.CENTER_VERTICAL);
   controls.addView(icon("close",I18n.t("Отменить запись"),()->end(false)),new LinearLayout.LayoutParams(a.dp(44),a.dp(44)));controls.addView(icon("send",I18n.t("Отправить голосовое"),()->end(true)),new LinearLayout.LayoutParams(a.dp(44),a.dp(44)));bar.addView(controls,new LinearLayout.LayoutParams(-1,-2));
   wave=new Wave(a);wave.setContentDescription(I18n.t("Громкость микрофона в реальном времени"));bar.addView(wave,new LinearLayout.LayoutParams(-1,a.dp(50)));hint=a.label(I18n.t("Говори · отпусти для отправки · влево для отмены"),11,a.MUTED);hint.setPadding(0,a.dp(4),0,0);bar.addView(hint,new LinearLayout.LayoutParams(-1,-2));cancelBar=new ProgressBar(a,null,android.R.attr.progressBarStyleHorizontal);cancelBar.setMax(1000);cancelBar.setProgressTintList(android.content.res.ColorStateList.valueOf(0xffff496e));cancelBar.setProgressBackgroundTintList(android.content.res.ColorStateList.valueOf(0xff3d2033));cancelBar.setContentDescription(I18n.t("Сдвинь влево до конца шкалы, чтобы отменить"));bar.addView(cancelBar,new LinearLayout.LayoutParams(-1,a.dp(10)));a.replyBar.removeAllViews();a.replyBar.addView(bar,new LinearLayout.LayoutParams(-1,-2));meterThread=new HandlerThread("oldy-mic-level",android.os.Process.THREAD_PRIORITY_AUDIO);meterThread.start();meterHandler=new Handler(meterThread.getLooper());meterHandler.post(this::sampleMic);tick();return true;
  }catch(Exception e){end(false);a.error(I18n.t("Не удалось включить микрофон. Проверь разрешение и доступ к микрофону в Android."));return false;}
 }
 View icon(String name,String description,Runnable action){UiIcon v=new UiIcon(a,name,a.light?0xff176aab:0xff83d9ff);v.setContentDescription(description);v.setBackground(a.shape(a.light?0xffe6f2ff:0xff263b50,14));v.setOnClickListener(x->action.run());return v;}
 void sampleMic(){if(!running)return;try{synchronized(recorderLock){if(!running||recorder==null)return;int amplitude=recorder.getMaxAmplitude();synchronized(levels){levels.add(amplitude);}ticks++;levelError="";if(Build.VERSION.SDK_INT>=29&&ticks%15==0)try{AudioRecordingConfiguration config=recorder.getActiveRecordingConfiguration();silenced=config!=null&&config.isClientSilenced();}catch(Exception ignored){}}}catch(Exception e){levelError=e.getClass().getSimpleName()+": "+e.getMessage();}if(running&&meterHandler!=null)meterHandler.postDelayed(this::sampleMic,65);}
 void tick(){if(!running)return;long seconds=(SystemClock.elapsedRealtime()-started)/1000;timer.setText(String.format(Locale.ROOT,"● %d:%02d",seconds/60,seconds%60));int peak=0;synchronized(levels){for(int i=0;i<wave.values.length;i++){int at=levels.size()-wave.values.length+i;wave.values[i]=at<0?0:Wave.normalized(levels.get(at));}if(!levels.isEmpty())peak=Collections.max(levels);}wave.invalidate();hint.setText(cancelAmount>=1?I18n.t("Отпусти — запись будет удалена"):cancelAmount>0?I18n.t("← Сдвинь дальше для отмены"):silenced?I18n.t("Android отключил микрофон для этой записи"):seconds>=2&&ticks>10&&peak==0?I18n.t("Микрофон не получает звук. Проверь доступ к нему."):I18n.t("Говори · отпусти для отправки · влево для отмены"));a.ui.postDelayed(sample,70);}

 void cancelProgress(float value){cancelAmount=value;if(cancelBar!=null)cancelBar.setProgress(Math.round(value*1000));if(hint!=null)hint.setText(value>=1?I18n.t("Отпусти — запись будет удалена"):value>0?I18n.t("← Сдвинь дальше для отмены"):I18n.t("Говори · отпусти для отправки · влево для отмены"));}
 void end(boolean send){
  if(recorder==null){if(heldAtLimit){heldAtLimit=false;if(send&&cancelAmount<1)uploadPending();else discard();}return;}send=send&&cancelAmount<1;running=false;a.ui.removeCallbacks(sample);if(meterHandler!=null)meterHandler.removeCallbacksAndMessages(null);if(meterThread!=null)meterThread.quitSafely();meterHandler=null;meterThread=null;long elapsed=SystemClock.elapsedRealtime()-started;boolean valid=false;synchronized(recorderLock){try{recorder.stop();valid=file!=null&&file.length()>500&&elapsed>=700&&!silenced;}catch(Exception ignored){}try{recorder.release();}catch(Exception ignored){}recorder=null;}if(!deferStop){a.heldVoice=null;a.heldVoiceView=null;}if(a.replyBar!=null)a.replyBar.removeAllViews();File finished=file;file=null;
  if(!send||!valid){if(finished!=null)finished.delete();if(send)a.error(silenced?I18n.t("Android не передал звук микрофона. Запись не отправлена."):I18n.t("Запись не сохранилась. Удерживай микрофон и говори хотя бы секунду."));return;}
  try{byte[] points=new byte[48];for(int i=0;i<points.length;i++){int lo=i*levels.size()/48,hi=Math.max(lo+1,(i+1)*levels.size()/48),peak=0;for(int j=lo;j<hi&&j<levels.size();j++)peak=Math.max(peak,levels.get(j));points[i]=(byte)Math.round(Wave.normalized(peak)*255);}
   pending=finished;pendingTarget=target;pendingAccount=account;pendingMetadata=new JSONObject().put("duration",elapsed).put("waveform",Crypto.b64(points));if(deferStop){heldAtLimit=true;showPending();}else uploadPending();
  }catch(Exception e){finished.delete();a.error(I18n.t("Не удалось сохранить запись"));}
 }
 void uploadPending(){if(pending==null||uploading)return;if(a.vault!=pendingAccount){discard();return;}uploading=true;showPending();final File saved=pending;final Vault owner=pendingAccount;final String dest=pendingTarget;final JSONObject meta=pendingMetadata;
  a.work.execute(()->{try{MediaExtractor ex=new MediaExtractor();try{ex.setDataSource(saved.getAbsolutePath());int track=-1;for(int i=0;i<ex.getTrackCount();i++)if(ex.getTrackFormat(i).getString(MediaFormat.KEY_MIME).startsWith("audio/")){track=i;break;}if(track<0)throw new IOException(I18n.t("В записи нет аудиодорожки"));MediaFormat format=ex.getTrackFormat(track);ex.selectTrack(track);int samples=0;while(ex.getSampleTime()>=0&&samples<8){samples++;ex.advance();}if(samples<8)throw new IOException(I18n.t("Аудиозапись повреждена"));if(format.containsKey(MediaFormat.KEY_DURATION))meta.put("duration",format.getLong(MediaFormat.KEY_DURATION)/1000);}finally{ex.release();}
   if(a.vault!=owner)throw new IOException(I18n.t("Аккаунт изменился"));CloudMedia.attach(a,Uri.fromFile(saved),"audio/mp4",I18n.t("Голосовое сообщение"),dest,"",meta);saved.delete();a.runOnUiThread(()->{uploading=false;pending=null;if(a.vault==owner&&a.chat.equals(dest)&&a.replyBar!=null)a.renderReply();});
  }catch(Exception error){a.runOnUiThread(()->{uploading=false;if(a.vault!=owner){discard();return;}showPending();a.error(I18n.t("Голосовое не отправлено. Запись сохранена для повторной отправки. ")+Api.message(error));});}});
 }
 void discard(){if(uploading)return;heldAtLimit=false;if(pending!=null)pending.delete();pending=null;if(a.replyBar!=null)a.renderReply();}
 void showPending(){if(pending==null||a.replyBar==null||a.vault!=pendingAccount||!a.chat.equals(pendingTarget))return;LinearLayout box=a.col();a.pad(box,8);box.setBackground(a.shape(a.CARD,16));box.addView(a.label(uploading?I18n.t("Отправляем голосовое…"):heldAtLimit?I18n.t("Предел записи достигнут · отпусти для отправки"):I18n.t("Голосовое сохранено · отправка не завершена"),13,a.TEXT),new LinearLayout.LayoutParams(-1,-2));if(!uploading){LinearLayout actions=a.row();actions.addView(a.button(I18n.t("Повторить отправку"),true,this::uploadPending),new LinearLayout.LayoutParams(0,a.dp(44),1));actions.addView(icon("close",I18n.t("Удалить неотправленную запись"),this::discard),new LinearLayout.LayoutParams(a.dp(44),a.dp(44)));box.addView(actions);}a.replyBar.removeAllViews();a.replyBar.addView(box,new LinearLayout.LayoutParams(-1,-2));}
 static class Wave extends View{
  final float[] values=new float[40];final Paint p=new Paint(3);Wave(android.content.Context c){super(c);}
  static float normalized(int amplitude){if(amplitude<=0)return 0;double db=20*Math.log10(Math.min(32767,amplitude)/32767.0);return (float)Math.pow(Math.max(0,Math.min(1,(db+60)/60)),1.7);}
  void level(int amplitude){System.arraycopy(values,1,values,0,values.length-1);values[values.length-1]=normalized(amplitude);invalidate();}
  protected void onDraw(Canvas c){float gap=getWidth()/40f;p.setStrokeWidth(Math.max(2,gap*.52f));p.setStrokeCap(Paint.Cap.ROUND);for(int i=0;i<40;i++){float level=values[i],h=Math.max(getResources().getDisplayMetrics().density*2,level*getHeight()*.9f);p.setColor(Color.rgb((int)(55+90*level),(int)(130+100*level),240));c.drawLine(i*gap+gap/2,(getHeight()-h)/2,i*gap+gap/2,(getHeight()+h)/2,p);}}
 }
}

