package chat.oldy;
import android.*;import android.content.pm.PackageManager;import android.graphics.*;import android.media.*;import android.net.Uri;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;
/** Mic amplitude is read from the recorder, never a decorative/random waveform. */
final class VoiceCapture {
 final MainActivity a;MediaRecorder recorder;File file;long started;String target;LinearLayout bar;TextView timer;Wave wave;boolean running;
 VoiceCapture(MainActivity activity){a=activity;}
 boolean begin(){if(running)return true;if(a.checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){a.requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},11);return false;}
  try{target=a.chat;file=new File(a.getCacheDir(),"voice-"+System.currentTimeMillis()+".m4a");recorder=new MediaRecorder();recorder.setAudioSource(MediaRecorder.AudioSource.MIC);recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);recorder.setAudioEncodingBitRate(96000);recorder.setAudioSamplingRate(44100);recorder.setMaxDuration(180000);recorder.setOutputFile(file.getAbsolutePath());recorder.prepare();recorder.start();started=SystemClock.elapsedRealtime();running=true;bar=a.row();bar.setBackground(a.shape(a.CARD,16));timer=a.label("● 0:00",13,0xfff28c9b);a.pad(timer,8);bar.addView(timer);wave=new Wave(a);bar.addView(wave,new LinearLayout.LayoutParams(0,a.dp(42),1));bar.addView(a.button("×",false,()->end(false)));bar.addView(a.button("✓",true,()->end(true)));a.replyBar.removeAllViews();a.replyBar.addView(bar);recorder.setOnInfoListener((r,what,extra)->{if(what==MediaRecorder.MEDIA_RECORDER_INFO_MAX_DURATION_REACHED)end(true);});recorder.setOnErrorListener((r,what,extra)->{end(false);a.error("Микрофон прервал запись. Попробуй снова.");});tick();return true;}catch(Exception e){end(false);a.error("Не удалось включить микрофон. Проверь разрешение и доступ к микрофону в настройках Android.");return false;}
 }
 void tick(){if(!running)return;long s=(SystemClock.elapsedRealtime()-started)/1000;timer.setText(String.format(java.util.Locale.ROOT,"● %d:%02d",s/60,s%60));try{wave.level(recorder.getMaxAmplitude());}catch(Exception ignored){}a.ui.postDelayed(this::tick,70);}
 void end(boolean send){if(recorder==null)return;running=false;boolean valid=false;try{recorder.stop();valid=file!=null&&file.length()>500&&SystemClock.elapsedRealtime()-started>=700;}catch(Exception ignored){}recorder.release();recorder=null;if(a.replyBar!=null)a.replyBar.removeAllViews();File finished=file;file=null;if(!send||!valid){if(finished!=null)finished.delete();if(send)a.error("Запись слишком короткая. Удерживай микрофон и говори хотя бы секунду.");return;}String dest=target;a.task(()->{try{MediaMetadataRetriever metadata=new MediaMetadataRetriever();try{metadata.setDataSource(finished.getAbsolutePath());String duration=metadata.extractMetadata(MediaMetadataRetriever.METADATA_KEY_DURATION);if(duration==null||Long.parseLong(duration)<500)throw new IOException("Запись не сохранилась");}finally{metadata.release();}CloudMedia.attach(a,Uri.fromFile(finished),"audio/mp4","Голосовое сообщение",dest,"");}finally{finished.delete();}});}
 static class Wave extends View{float[] values=new float[36];Paint p=new Paint(3);Wave(android.content.Context c){super(c);}void level(int amplitude){System.arraycopy(values,1,values,0,values.length-1);values[values.length-1]=(float)Math.min(1,Math.log1p(Math.max(0,amplitude))/Math.log(32768));invalidate();}protected void onDraw(Canvas c){float gap=getWidth()/36f;p.setStrokeWidth(Math.max(2,gap*.48f));p.setStrokeCap(Paint.Cap.ROUND);for(int i=0;i<36;i++){float h=Math.max(2,values[i]*getHeight()*.78f);p.setColor(Color.rgb((int)(110+100*values[i]),(int)(155+70*values[i]),255));c.drawLine(i*gap+gap/2,(getHeight()-h)/2,i*gap+gap/2,(getHeight()+h)/2,p);}}}
}
