package chat.oldy;
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.GradientDrawable;import android.net.*;import android.os.*;import android.view.*;import android.webkit.*;import android.widget.*;
import androidx.browser.customtabs.*;

/** Search, recommendations and account are the official YouTube website in a Custom Tab.
 * This activity never reads browser cookies, Google passwords or OAuth tokens. */
public final class YouTubeHubActivity extends Activity {
 final Handler ui=new Handler(Looper.getMainLooper());String browser,url;TextView status;boolean launched,local,starting,permission;CustomTabsSession session;CustomTabsServiceConnection connection;WebView fallback;
 static final int VPN=731;
 public void onCreate(Bundle state){super.onCreate(state);I18n.init(this);browser=YouTubeBrowser.preferred(this);url=getIntent().getStringExtra("url");if(!YouTubeBrowser.url(url))url="https://m.youtube.com/";boolean light=Notices.prefs(this).getString("theme","dark").equals("light");ThemeLayout root=new ThemeLayout(this);setContentView(root);getWindow().setStatusBarColor(Color.TRANSPARENT);getWindow().setNavigationBarColor(Color.TRANSPARENT);if(Build.VERSION.SDK_INT>=30)getWindow().setDecorFitsSystemWindows(false);root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(dp(16)+i.getSystemWindowInsetLeft(),dp(12)+i.getSystemWindowInsetTop(),dp(16)+i.getSystemWindowInsetRight(),dp(12)+i.getSystemWindowInsetBottom());return i;});
  TextView heading=label("▶  Просмотр YouTube",23,light?0xff9f2433:0xffff9ba9);root.addView(heading);status=label(I18n.t("Открываем YouTube…"),15,light?0xff37445c:0xffc3d0df);root.addView(status);TextView retry=label(I18n.t("Открыть YouTube"),16,Color.WHITE);retry.setGravity(Gravity.CENTER);GradientDrawable bg=new GradientDrawable();bg.setColor(0xffc63748);bg.setCornerRadius(dp(16));retry.setBackground(bg);root.addView(retry,new LinearLayout.LayoutParams(-1,dp(52)));retry.setOnClickListener(v->choose());TextView back=label(I18n.t("‹ Назад в Oldi"),16,light?0xff37445c:0xffc3d0df);back.setOnClickListener(v->finish());root.addView(back);
  if(!browser.isEmpty())bind();else{status.setText(I18n.t("Для входа в Google нужен браузер с поддержкой встроенных вкладок. Доступен просмотр без входа."));}
  ui.postDelayed(this::choose,200);
 }
 void bind(){connection=new CustomTabsServiceConnection(){public void onCustomTabsServiceConnected(ComponentName name,CustomTabsClient client){client.warmup(0);session=client.newSession(new CustomTabsCallback(){public void onNavigationEvent(int event,Bundle extras){if(!local)return;if(event==TAB_SHOWN)LocalTunnelService.browser(YouTubeHubActivity.this,true);else if(event==TAB_HIDDEN)LocalTunnelService.browser(YouTubeHubActivity.this,false);}});}public void onServiceDisconnected(ComponentName name){session=null;}};CustomTabsClient.bindCustomTabsService(this,browser,connection);}
 void choose(){if(starting||isFinishing())return;String mode=TunnelStateRepository.mode(this);if(mode.equals("off")){launch(false);return;}if(mode.equals("ask")){new AlertDialog.Builder(this).setTitle(I18n.t("Просмотр YouTube")).setMessage(I18n.t("Включить локальную обработку DPI для YouTube? Видео идёт через ваш интернет, без сервера Oldi.")).setPositiveButton(I18n.t("Включить"),(d,w)->consent()).setNegativeButton(I18n.t("Открыть обычно"),(d,w)->launch(false)).show();}else consent();}
 void consent(){if(NetworkDiagnostics.otherVpn(this)){status.setText(I18n.t("Уже включён другой VPN. Используем текущее соединение."));launch(false);return;}if(!Notices.prefs(this).getBoolean("youtube_dpi_disclosure_v2",false)){new AlertDialog.Builder(this).setTitle(I18n.t("YouTube · локальная обработка DPI")).setMessage(I18n.t("Android запросит разрешение VPN. Oldi применит ByeDPI на телефоне к соединениям YouTube и входа Google. Для официальной вкладки это также касается YouTube-соединений выбранного браузера, включая его другие вкладки, пока режим включён. Остальные сайты и приложения используют обычное соединение. При ошибке DNS возможен запрос имени сервера через Google Public DNS. Видеопоток не идёт через сервер Oldi, IP не меняется. Работа зависит от способа ограничения у оператора.")).setPositiveButton(I18n.t("Включить"),(d,w)->{Notices.prefs(this).edit().putBoolean("youtube_dpi_disclosure_v2",true).apply();permit();}).setNegativeButton(I18n.t("Открыть обычно"),(d,w)->launch(false)).show();}else permit();}
 void permit(){Intent request=android.net.VpnService.prepare(this);if(request==null)startLocal();else{permission=true;startActivityForResult(request,VPN);}}
 protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==VPN){permission=false;if(result==RESULT_OK)startLocal();else{status.setText(I18n.t("Разрешение не выдано. Открываем обычный просмотр."));launch(false);}}}
 void startLocal(){starting=true;status.setText(I18n.t("Запускаем локальную обработку DPI…"));try{
  // A running embedded-player tunnel does not include the browser; restart it explicitly.
  if(TunnelStateRepository.on())LocalTunnelService.stop(this);
  long until=SystemClock.elapsedRealtime()+6000;ui.post(new Runnable(){public void run(){if(isFinishing())return;if((TunnelStateRepository.on()||NetworkDiagnostics.otherVpn(YouTubeHubActivity.this))&&SystemClock.elapsedRealtime()<until){ui.postDelayed(this,100);return;}if(NetworkDiagnostics.otherVpn(YouTubeHubActivity.this)){starting=false;status.setText(I18n.t("Дождитесь отключения предыдущего VPN и повторите."));return;}try{LocalTunnelService.startBrowser(YouTubeHubActivity.this,browser);waitForTunnel(SystemClock.elapsedRealtime()+9000);}catch(Exception e){starting=false;status.setText(I18n.t("Не удалось запустить локальный режим. Попробуйте ещё раз."));}}});
 }catch(Exception e){starting=false;status.setText(I18n.t("Не удалось запустить локальный режим. Попробуйте ещё раз."));}}
 void waitForTunnel(long end){ui.postDelayed(()->{if(isFinishing())return;if(TunnelStateRepository.on()){starting=false;launch(true);}else if(SystemClock.elapsedRealtime()<end)waitForTunnel(end);else{starting=false;LocalTunnelService.stop(this);status.setText(I18n.t("Локальный режим не запустился. Откройте диагностику в настройках сети."));}},120);}
 void launch(boolean dpi){local=dpi;if(browser.isEmpty()){guest();return;}try{CustomTabsIntent tab=new CustomTabsIntent.Builder(session).setDefaultColorSchemeParams(new CustomTabColorSchemeParams.Builder().setToolbarColor(0xffac293e).build()).setShowTitle(true).setShareState(CustomTabsIntent.SHARE_STATE_ON).setUrlBarHidingEnabled(true).build();tab.intent.setPackage(browser);tab.intent.putExtra("android.support.customtabs.extra.SEND_TO_EXTERNAL_DEFAULT_HANDLER",false);launched=true;if(local)LocalTunnelService.browser(this,true);tab.launchUrl(this,Uri.parse(url));}catch(Exception e){launched=false;status.setText(I18n.t("Не удалось открыть вкладку YouTube. Обновите браузер."));if(local)LocalTunnelService.idle(this);}}
 void guest(){if(fallback!=null)return;LinearLayout root=(LinearLayout)status.getParent();fallback=new WebView(this);WebSettings s=fallback.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);fallback.setWebViewClient(new WebViewClient(){public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){if(!YouTubeBrowser.url(r.getUrl().toString())){Toast.makeText(YouTubeHubActivity.this,I18n.t("Для входа Google откройте официальный браузер"),Toast.LENGTH_LONG).show();return true;}return false;}});root.addView(fallback,new LinearLayout.LayoutParams(-1,0,1));fallback.loadUrl(url);if(local)ui.post(heartbeat);}
 final Runnable heartbeat=new Runnable(){public void run(){if(fallback!=null&&!isFinishing()&&local){LocalTunnelService.touch(YouTubeHubActivity.this);ui.postDelayed(this,2000);}}};
 protected void onResume(){super.onResume();if(launched&&!permission){launched=false;LocalTunnelService.browser(this,false);finish();}}
 protected void onDestroy(){ui.removeCallbacksAndMessages(null);if(connection!=null)try{unbindService(connection);}catch(Exception ignored){}if(fallback!=null){fallback.stopLoading();fallback.destroy();}if(local)LocalTunnelService.idle(this);super.onDestroy();}
 int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}TextView label(String text,int size,int color){TextView v=new TextView(this);v.setText(I18n.t(text));v.setTextSize(size);v.setTextColor(color);v.setPadding(dp(8),dp(12),dp(8),dp(12));return v;}
}
