package chat.oldy;
import android.app.*;import android.content.*;import android.graphics.Color;import android.graphics.drawable.GradientDrawable;import android.net.*;import android.net.http.SslError;import android.os.*;import android.view.*;import android.webkit.*;import android.widget.*;
import java.util.concurrent.*;

/** The official YouTube site stays inside Oldi. No extraction, ad removal, cookie
 * export, JavaScript bridge or implicit external activity is used. */
public final class YouTubeHubActivity extends Activity {
 static final int VPN=731;final Handler ui=new Handler(Looper.getMainLooper());final ExecutorService work=Executors.newSingleThreadExecutor();
 ThemeLayout root;WebView web;FrameLayout content;TextView status;ProgressBar progress;EditText search;String url="https://m.youtube.com/";
 boolean local,starting,foreground,permission,loaded;int attempt;long lastRestart;View fullscreen;WebChromeClient.CustomViewCallback fullscreenCallback;
 public void onCreate(Bundle state){super.onCreate(state);I18n.init(this);String initial=getIntent().getStringExtra("url");if(YouTubeBrowser.url(initial))url=initial;root=new ThemeLayout(this);setContentView(root);getWindow().setStatusBarColor(Color.TRANSPARENT);getWindow().setNavigationBarColor(Color.TRANSPARENT);if(Build.VERSION.SDK_INT>=30)getWindow().setDecorFitsSystemWindows(false);
  root.setOnApplyWindowInsetsListener((v,i)->{v.setPadding(dp(8)+i.getSystemWindowInsetLeft(),i.getSystemWindowInsetTop(),dp(8)+i.getSystemWindowInsetRight(),i.getSystemWindowInsetBottom());return i;});
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.addView(key("‹",()->onBackPressed()),new LinearLayout.LayoutParams(dp(46),dp(48)));TextView heading=key("▶ YouTube",()->navigate("https://m.youtube.com/"));head.addView(heading,new LinearLayout.LayoutParams(0,dp(48),1));head.addView(key("⋮",this::menu),new LinearLayout.LayoutParams(dp(46),dp(48)));root.addView(head);
  LinearLayout find=new LinearLayout(this);search=new EditText(this);search.setSingleLine(true);search.setTextSize(15);search.setTextColor(Color.WHITE);search.setHintTextColor(0xffd4b9c1);search.setHint(tr("Поиск видео в YouTube","Search YouTube"));search.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH);search.setBackground(shape(0xe72a2032));search.setPadding(dp(12),0,dp(6),0);search.setOnEditorActionListener((v,a,e)->{if(a==android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH){search();return true;}return false;});find.addView(search,new LinearLayout.LayoutParams(0,dp(46),1));find.addView(key("⌕",this::search),new LinearLayout.LayoutParams(dp(48),dp(46)));root.addView(find);
  status=new TextView(this);status.setTextSize(11);status.setTextColor(Notices.prefs(this).getString("theme","dark").equals("light")?0xff612439:0xffffb9cd);status.setPadding(dp(8),dp(7),dp(8),dp(7));status.setOnClickListener(v->information());root.addView(status);progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(100);root.addView(progress,new LinearLayout.LayoutParams(-1,dp(3)));content=new FrameLayout(this);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));createWeb();if(state!=null)loaded=web.restoreState(state)!=null;if(!loaded)ui.post(this::choose);
 }
 static String tr(String ru,String en){return I18n.language().equals("en")?en:ru;}
 void createWeb(){web=new WebView(this);content.addView(web,new FrameLayout.LayoutParams(-1,-1));WebSettings s=web.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setAllowFileAccess(false);s.setAllowContentAccess(false);s.setMixedContentMode(WebSettings.MIXED_CONTENT_NEVER_ALLOW);s.setMediaPlaybackRequiresUserGesture(true);s.setJavaScriptCanOpenWindowsAutomatically(false);s.setSupportMultipleWindows(false);s.setGeolocationEnabled(false);s.setSafeBrowsingEnabled(true);CookieManager.getInstance().setAcceptThirdPartyCookies(web,true);
  web.setDownloadListener((u,a,d,m,l)->status.setText(tr("Загрузка YouTube-видео не поддерживается","YouTube video downloading is not supported")));
  web.setWebViewClient(new WebViewClient(){
   public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){if(!r.isForMainFrame())return !"https".equals(r.getUrl().getScheme());String u=r.getUrl().toString();if(YouTubeBrowser.url(u))return false;String h=r.getUrl().getHost();if(h!=null&&(h.equals("accounts.google.com")||h.equals("accounts.google.ru"))){googleSignIn();return true;}if(r.hasGesture())new AlertDialog.Builder(YouTubeHubActivity.this).setMessage(tr("Открыть эту ссылку во внешнем приложении?","Open this link in an external app?")).setPositiveButton(I18n.t("Открыть"),(d,w)->external(u)).setNegativeButton(I18n.t("Отмена"),null).show();return true;}
   public void onPageStarted(WebView v,String u,android.graphics.Bitmap icon){progress.setVisibility(View.VISIBLE);if(YouTubeBrowser.url(u))url=u;}
   public void onPageFinished(WebView v,String u){progress.setVisibility(View.GONE);loaded=true;connectionLabel();}
   public void onReceivedError(WebView v,WebResourceRequest r,WebResourceError e){if(r.isForMainFrame()){progress.setVisibility(View.GONE);status.setText(tr("YouTube не загрузился. ⋮ → Подобрать соединение","YouTube did not load. ⋮ → Find connection"));}}
   public void onReceivedSslError(WebView v,SslErrorHandler handler,SslError e){handler.cancel();status.setText(tr("Сертификат YouTube не прошёл проверку","YouTube certificate verification failed"));}
   public boolean onRenderProcessGone(WebView v,RenderProcessGoneDetail d){content.removeView(v);v.destroy();web=null;status.setText(tr("Плеер остановился. Нажмите ⋮ → Обновить","Player stopped. Tap ⋮ → Reload"));return true;}
  });
  web.setWebChromeClient(new WebChromeClient(){public void onProgressChanged(WebView v,int n){progress.setProgress(n);}public void onPermissionRequest(PermissionRequest request){request.deny();}public void onGeolocationPermissionsShowPrompt(String origin,GeolocationPermissions.Callback cb){cb.invoke(origin,false,false);}public void onShowCustomView(View v,CustomViewCallback cb){if(fullscreen!=null){cb.onCustomViewHidden();return;}fullscreen=v;fullscreenCallback=cb;((FrameLayout)getWindow().getDecorView()).addView(v,new FrameLayout.LayoutParams(-1,-1));getWindow().getDecorView().setSystemUiVisibility(5894);}public void onHideCustomView(){hideFullscreen();}});
 }
 void search(){String q=search.getText().toString().trim();if(q.isEmpty())return;((android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(search.getWindowToken(),0);search.clearFocus();navigate("https://m.youtube.com/results?search_query="+Uri.encode(q));}
 void navigate(String next){if(!YouTubeBrowser.url(next)||isFinishing())return;url=next;if(web==null)createWeb();if(local&&TunnelStateRepository.on())YouTubeWebRoute.apply(()->{if(web!=null&&!isFinishing())web.loadUrl(url);});else YouTubeWebRoute.clear(()->{if(web!=null&&!isFinishing())web.loadUrl(url);});}
 void choose(){if(starting||isFinishing())return;String mode=TunnelStateRepository.mode(this);if(mode.equals("off")){local=false;navigate(url);return;}if(mode.equals("ask")){new AlertDialog.Builder(this).setTitle(tr("YouTube внутри Oldi","YouTube inside Oldi")).setMessage(tr("Включить локальный сетевой режим для YouTube?","Enable the local network mode for YouTube?")).setPositiveButton(I18n.t("Включить"),(d,w)->consent()).setNegativeButton(I18n.t("Открыть обычно"),(d,w)->{local=false;navigate(url);}).setOnCancelListener(d->navigate(url)).show();}else consent();}
 void consent(){if(NetworkDiagnostics.otherVpn(this)){local=false;navigate(url);status.setText(tr("Используется ваше текущее VPN-соединение","Using your current VPN connection"));return;}if(!Notices.prefs(this).getBoolean("youtube_embedded_disclosure",false)){new AlertDialog.Builder(this).setTitle(tr("Локальная обработка YouTube","Local YouTube connection mode")).setMessage(tr("Android запросит разрешение VPN. Oldi изменяет передачу первых пакетов соединения YouTube на этом телефоне. Видеопоток идёт напрямую через ваш интернет, без сервера Oldi; IP не меняется. Остальные приложения не затрагиваются. При ошибке DNS может использоваться Google Public DNS. Результат зависит от ограничений оператора.","Android will ask for VPN permission. Oldi adjusts the first packets of YouTube connections on this phone. Video travels directly over your internet, without the Oldi server; your IP stays the same. Other apps are unaffected. Google Public DNS may be used if DNS fails. Results depend on your carrier's restrictions.")).setPositiveButton(I18n.t("Включить"),(d,w)->{Notices.prefs(this).edit().putBoolean("youtube_embedded_disclosure",true).apply();permit();}).setNegativeButton(I18n.t("Открыть обычно"),(d,w)->navigate(url)).show();}else permit();}
 void permit(){try{Intent request=VpnService.prepare(this);if(request==null)startLocal(false);else{permission=true;startActivityForResult(request,VPN);}}catch(Exception e){status.setText(tr("Android не разрешил запуск локального режима","Android could not start local mode"));}}
 protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(r==VPN){permission=false;if(result==RESULT_OK)startLocal(false);else{local=false;navigate(url);status.setText(tr("Разрешение VPN отклонено. Открыт обычный просмотр.","VPN permission declined. Normal playback is open."));}}}
 void startLocal(boolean restart){if(starting||isFinishing())return;local=true;starting=true;lastRestart=SystemClock.elapsedRealtime();int token=++attempt;status.setText(tr("Подключаем локальный модуль…","Connecting local module…"));if(restart)LocalTunnelService.stop(this);ui.postDelayed(()->startAfterStop(token,SystemClock.elapsedRealtime()+6000,restart),restart?200:0);}
 void startAfterStop(int token,long deadline,boolean restart){if(token!=attempt||isFinishing())return;if(restart&&(TunnelStateRepository.on()||NetworkDiagnostics.otherVpn(this))){if(SystemClock.elapsedRealtime()<deadline){ui.postDelayed(()->startAfterStop(token,deadline,true),150);return;}starting=false;status.setText(tr("Предыдущий VPN ещё отключается. Повторите.","The previous VPN is still disconnecting. Retry."));return;}try{LocalTunnelService.start(this);awaitTunnel(token,SystemClock.elapsedRealtime()+9000);}catch(Exception e){starting=false;status.setText(tr("Локальный модуль не запустился","Local module failed to start"));}}
 void awaitTunnel(int token,long deadline){if(token!=attempt||isFinishing())return;if(TunnelStateRepository.on()){starting=false;navigate(url);connectionLabel();return;}if(SystemClock.elapsedRealtime()<deadline)ui.postDelayed(()->awaitTunnel(token,deadline),150);else{starting=false;status.setText(tr("Не удалось запустить локальный режим. ⋮ → Диагностика","Could not start local mode. ⋮ → Diagnostics"));}}
 void connectionLabel(){if(starting)return;status.setText(local&&TunnelStateRepository.on()?tr("🛡 Локальная обработка · видео напрямую на телефон","🛡 Local processing · video directly to this phone"):tr("Встроенный просмотр · прямой HTTPS","In-app playback · direct HTTPS"));}
 void information(){new AlertDialog.Builder(this).setMessage(tr("Видео передаётся напрямую между YouTube и вашим устройством. Сервер Oldi не передаёт видеопоток. DPI может помочь при некоторых видах замедления, но не меняет IP и не гарантирует доступ при любом ограничении.","Video travels directly between YouTube and your device. Oldi's server does not relay video. DPI techniques may help with some throttling, but do not change your IP or guarantee access through every restriction.")).setPositiveButton(I18n.t("Понятно"),null).show();}
 void menu(){String[] options={tr("Обновить","Reload"),tr("Подобрать соединение","Find connection"),tr("Диагностика","Diagnostics"),tr("Обычное соединение","Normal connection"),tr("Вход в Google","Google sign-in")};new AlertDialog.Builder(this).setItems(options,(d,w)->{if(w==0)navigate(url);else if(w==1)strategies();else if(w==2)diagnostics();else if(w==3){attempt++;starting=false;local=false;LocalTunnelService.stop(this);YouTubeWebRoute.clear(()->navigate(url));}else googleSignIn();}).show();}
 void strategies(){String[] values={"auto","split","disorder","fake4","fake8"};String[] names={tr("Автоматически · 5 вариантов","Automatic · 5 strategies"),tr("Разделение TLS","TLS splitting"),tr("Порядок пакетов","Packet order"),tr("Дополнительный режим 1","Additional mode 1"),tr("Дополнительный режим 2","Additional mode 2")};new AlertDialog.Builder(this).setTitle(tr("Подобрать соединение","Find connection")).setItems(names,(d,w)->{Notices.prefs(this).edit().putString("youtube_dpi_strategy",values[w]).apply();if(VpnService.prepare(this)==null)startLocal(true);else consent();}).setNeutralButton(tr("Что проверить","What to check"),(d,w)->information()).show();}
 void diagnostics(){status.setText(I18n.t("Проверяем соединение…"));work.execute(()->{org.json.JSONObject r=NetworkDiagnostics.check(this);runOnUiThread(()->{if(isFinishing())return;String report=YouTubeSettings.format(r);new AlertDialog.Builder(this).setTitle(tr("Проверка YouTube","YouTube diagnostics")).setMessage(report).setPositiveButton(I18n.t("Закрыть"),null).setNeutralButton(tr("Скопировать","Copy"),(d,w)->getSystemService(ClipboardManager.class).setPrimaryClip(ClipData.newPlainText("Oldi diagnostics",report))).show();});});}
 void googleSignIn(){new AlertDialog.Builder(this).setTitle(tr("Вход в Google","Google sign-in")).setMessage(tr("Google не поддерживает вход во встроенном WebView. Поиск и просмотр здесь доступны без входа. Если нужен ваш аккаунт, его можно открыть отдельно в официальном YouTube; сессия браузера не переносится в Oldi.","Google does not support sign-in inside an embedded WebView. Search and playback here are available without signing in. Your account can be opened separately in official YouTube; browser sessions are not copied into Oldi.")).setPositiveButton(tr("Остаться в Oldi","Stay in Oldi"),null).setNegativeButton(tr("Открыть отдельно","Open externally"),(d,w)->external("https://m.youtube.com/")).show();}
 void external(String u){try{Uri uri=Uri.parse(u);if(!"https".equals(uri.getScheme())||uri.getHost()==null||uri.getUserInfo()!=null)return;startActivity(new Intent(Intent.ACTION_VIEW,uri));}catch(Exception ignored){}}
 final Runnable heartbeat=new Runnable(){public void run(){if(!foreground)return;if(local){if(TunnelStateRepository.on())LocalTunnelService.touch(YouTubeHubActivity.this);else if(!starting&&!permission&&NetworkDiagnostics.physical(YouTubeHubActivity.this)!=null&&SystemClock.elapsedRealtime()-lastRestart>10000){startLocal(false);}}ui.postDelayed(this,2000);}};
 protected void onResume(){super.onResume();foreground=true;if(web!=null)web.onResume();if(local&&TunnelStateRepository.on())YouTubeWebRoute.apply(()->{});ui.post(heartbeat);}
 protected void onPause(){foreground=false;ui.removeCallbacks(heartbeat);if(web!=null){web.evaluateJavascript("document.querySelectorAll('video').forEach(v=>v.pause())",null);web.onPause();}if(local&&!permission)LocalTunnelService.idle(this);super.onPause();}
 protected void onSaveInstanceState(Bundle b){if(web!=null)web.saveState(b);super.onSaveInstanceState(b);}
 void hideFullscreen(){if(fullscreen==null)return;((FrameLayout)getWindow().getDecorView()).removeView(fullscreen);fullscreen=null;if(fullscreenCallback!=null)fullscreenCallback.onCustomViewHidden();fullscreenCallback=null;getWindow().getDecorView().setSystemUiVisibility(0);}
 public void onBackPressed(){if(fullscreen!=null)hideFullscreen();else if(web!=null&&web.canGoBack())web.goBack();else finish();}
 protected void onDestroy(){attempt++;ui.removeCallbacksAndMessages(null);work.shutdownNow();hideFullscreen();if(web!=null){content.removeView(web);web.stopLoading();web.destroy();web=null;}YouTubeWebRoute.clear(()->{});if(local)LocalTunnelService.idle(this);super.onDestroy();}
 TextView key(String name,Runnable action){TextView v=new TextView(this);v.setText(name);v.setTextSize(18);v.setGravity(Gravity.CENTER);v.setTextColor(Color.WHITE);v.setBackground(shape(0xffbd3046));v.setContentDescription(name);v.setOnClickListener(w->action.run());return v;}
 GradientDrawable shape(int color){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(14));return d;}int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
}
