package chat.oldy;
import android.content.*;import android.view.*;import android.widget.*;import org.json.JSONObject;

final class YouTubeSettings {
 static void show(MainActivity a){LinearLayout b=SettingsHome.page(a,"YouTube в Oldi","network");SettingsHome.section(a,b,"Защищённый просмотр YouTube");String mode=TunnelStateRepository.mode(a);String[] modes={"auto","ask","off"},labels={"Автоматически","Спрашивать","Выключено"};for(int i=0;i<modes.length;i++){String key=modes[i];SettingsHome.row(a,b,key.equals(mode)?"✓":"○",labels[i],key.equals("auto")?"Включать локальный режим при открытии видео":key.equals("ask")?"Предлагать включение перед просмотром":"Обычный встроенный плеер",0xff31a1bb,()->{TunnelStateRepository.mode(a,key);if(key.equals("off"))LocalTunnelService.stop(a);show(a);});}
  b.addView(a.button(I18n.t("Обновить сетевые правила"),false,()->a.task(()->{JSONObject config=a.api.call("/youtube/config",null,a.vault.token());YouTubeDomainRules.save(a,config);a.runOnUiThread(()->a.error(I18n.t("Правила обновлены. Они применятся при следующем включении локального режима.")));})));
  a.space(b,12);a.paragraph(b,I18n.t("Видео идёт прямо из YouTube на ваш телефон. Oldi не меняет IP и не обещает доступ при блокировках. Официальный плеер сохраняет рекламу и ограничения YouTube."));a.space(b,18);TextView state=a.label("",14,a.TEXT);state.setLineSpacing(a.dp(5),1);b.addView(state);state.setText("Local Tunnel: "+(TunnelStateRepository.on()?"ON":"OFF")+"\n"+I18n.t("Сеть: ")+NetworkDiagnostics.network(a)+"\nDNS: "+I18n.t("Не проверено")+"\n"+I18n.t("Последняя ошибка: ")+TunnelStateRepository.lastError(a));a.space(b,14);
  final String[] report={""};TextView test=a.button(I18n.t("Проверить соединение"),true,()->{});test.setOnClickListener(v->{test.setEnabled(false);state.setText(I18n.t("Проверяем соединение…"));a.work.execute(()->{JSONObject result=NetworkDiagnostics.check(a);String text=format(result);a.runOnUiThread(()->{report[0]=text;state.setText(text);test.setEnabled(true);});});});b.addView(test);a.space(b,8);b.addView(a.button(I18n.t("Скопировать результат проверки"),false,()->{if(report[0].isEmpty())return;a.getSystemService(android.content.ClipboardManager.class).setPrimaryClip(ClipData.newPlainText("Oldi network diagnostic",report[0]));Toast.makeText(a,I18n.t("Результат скопирован"),Toast.LENGTH_SHORT).show();}));a.space(b,8);b.addView(a.button(I18n.t("Отключить локальный режим"),false,()->{LocalTunnelService.stop(a);show(a);}));a.space(b,12);a.paragraph(b,I18n.t("Для проверки телефона повторите тест с Wi-Fi и с мобильным интернетом. Ответ HTTP 403/404 подтверждает связь с сервером, но не гарантирует воспроизведение конкретного ролика. googlevideo.com — проверка домена; CDN конкретного видео может отличаться."));
 }
 static String format(JSONObject r){return "Oldi YouTube diagnostics\nLocal Tunnel: "+r.optString("local_tunnel","OFF")+"\nNetwork: "+r.optString("network")+"\nMode: "+r.optString("mode")+"\nDNS: "+r.optString("dns")+"\nYouTube DNS: "+r.optString("www.youtube.com_dns","—")+"\nGooglevideo DNS: "+r.optString("googlevideo.com_dns","—")+"\nYouTube HTTPS: "+r.optString("youtube_https","—")+"\nGooglevideo HTTPS: "+r.optString("googlevideo_https","—")+"\nYouTube via local: "+r.optString("youtube_via_local","—")+"\nTUN bytes: "+r.optLong("tun_tx_bytes")+" / "+r.optLong("tun_rx_bytes")+"\nLast error: "+r.optString("last_error","—")+"\nNo Oldi video proxy. No remote VPN.\n";}
}
