package chat.oldy;
import android.app.*;import android.os.*;import android.content.*;import android.media.*;import android.graphics.*;import android.view.*;import org.json.*;import java.io.*;import java.nio.*;import java.nio.file.*;import java.util.*;
/** Uses Android's actual recorder/camera/encoders; never substitutes fake media payloads. */
public class CaptureInstrumentation extends Instrumentation {
 public void onCreate(Bundle b){start();}
 void check(boolean value,String why)throws Exception{if(!value)throw new Exception(why);}
 int samples(File file,String mime)throws Exception{MediaExtractor e=new MediaExtractor();try{e.setDataSource(file.getAbsolutePath());for(int i=0;i<e.getTrackCount();i++)if(e.getTrackFormat(i).getString(MediaFormat.KEY_MIME).startsWith(mime)){e.selectTrack(i);int n=0;long last=-1;do{long time=e.getSampleTime();if(time<0)break;check(time>=last,"Capture timestamps went backwards");last=time;n++;}while(e.advance());return n;}return 0;}finally{e.release();}}
 View find(View v,Class<?> type){if(type.isInstance(v))return v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){View found=find(g.getChildAt(i),type);if(found!=null)return found;}}return null;}
 void shot(String name)throws Exception{waitForIdleSync();getUiAutomation().waitForIdle(200,5000);Thread.sleep(1000);Bitmap b=getUiAutomation().takeScreenshot();File dir=new File(getTargetContext().getExternalFilesDir(null),"review");dir.mkdirs();try(FileOutputStream o=new FileOutputStream(new File(dir,name+".png"))){b.compress(Bitmap.CompressFormat.PNG,100,o);}}
 public void onStart(){Bundle result=new Bundle();RoundActivity round=null;try{
  MainActivity a=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));Thread.sleep(2200);runOnMainSync(()->a.openChat("bobby"));Vault vault=a.vault;long started=System.currentTimeMillis();boolean[] began={false};
  runOnMainSync(()->{a.voice=new VoiceCapture(a);began[0]=a.voice.begin();});check(began[0],"Actual microphone did not start");Thread.sleep(2100);check(a.voice.running,"Recording stopped unexpectedly");Rect waveRect=new Rect();runOnMainSync(()->a.voice.wave.getGlobalVisibleRect(waveRect));check(waveRect.width()>a.dp(180)&&waveRect.height()>=a.dp(40),"Recording meter is collapsed or off screen");check(a.voice.ticks>10,"Actual recorder amplitude is not sampled: ticks="+a.voice.ticks+", error="+a.voice.levelError);check(VoiceCapture.Wave.normalized(15000)>VoiceCapture.Wave.normalized(1000)*2,"Meter does not distinguish loud and quiet input");shot("20-voice-recording");File raw=a.voice.file;runOnMainSync(()->a.voice.end(true));
  JSONObject voice=null;long deadline=System.currentTimeMillis()+25000;while(voice==null&&System.currentTimeMillis()<deadline){JSONArray messages=vault.copy().getJSONArray("messages");for(int i=0;i<messages.length();i++){JSONObject m=messages.getJSONObject(i);if(m.optLong("time")>=started&&m.optString("mime").equals("audio/mp4")&&!m.optString("cloud_blob").isEmpty()){voice=m;break;}}Thread.sleep(150);}check(voice!=null,"Voice recording was not uploaded/queued");
  byte[] audio=MediaFiles.bytes(a,voice.getString("local"));File inspect=new File(a.getCacheDir(),"voice-inspect.m4a");Files.write(inspect.toPath(),audio);check(samples(inspect,"audio/")>25,"Recorded voice has no decodable audio samples");inspect.delete();MediaFiles.path(a,voice.getString("local")).delete();CloudMedia.download(a,vault,voice);check(Arrays.equals(audio,MediaFiles.bytes(a,vault.message(voice.getString("id")).getString("local"))),"Server voice bytes differ after decryption");
  final JSONObject sent=voice;check(sent.optLong("duration")>500&&Crypto.un64(sent.optString("waveform")).length==48,"Voice duration/waveform not persisted");runOnMainSync(a::renderMessages);Thread.sleep(400);View bubble=a.content.findViewWithTag(sent.optString("id"));VoiceNoteView card=(VoiceNoteView)find(bubble,VoiceNoteView.class);check(card!=null&&card.getWidth()>=a.dp(210)&&card.getHeight()>=a.dp(44),"Voice bubble is blank or too narrow");shot("21-voice-message");runOnMainSync(()->card.play.performClick());deadline=System.currentTimeMillis()+15000;while((a.voicePlayer==null||a.voicePlayer.position(sent.optString("id"))<250)&&System.currentTimeMillis()<deadline)Thread.sleep(80);check(a.voicePlayer!=null&&a.voicePlayer.position(sent.optString("id"))>=250,"Real voice playback does not advance");runOnMainSync(()->a.voicePlayer.release());
  round=(RoundActivity)startActivitySync(new Intent(a,RoundActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));final RoundActivity r=round;deadline=System.currentTimeMillis()+15000;while(r.frames<5&&System.currentTimeMillis()<deadline)Thread.sleep(100);check(r.frames>=5,"Selfie camera did not deliver frames: "+r.status.getText());runOnMainSync(r::begin);Thread.sleep(2200);check(r.encoder!=null,"Circle encoder did not start: "+r.status.getText());Rect flip=new Rect();runOnMainSync(()->r.swap.getGlobalVisibleRect(flip));check(flip.width()>=a.dp(48)&&flip.height()>=a.dp(48),"Camera switch is not visible during recording");shot("22-round-camera-controls");runOnMainSync(()->r.swap.performClick());deadline=System.currentTimeMillis()+12000;while(r.switches==0&&System.currentTimeMillis()<deadline)Thread.sleep(100);check(r.switches>0,"Camera did not switch during recording");int initialFrames=r.frames,initialSamples=r.encoder.videoSamples;deadline=System.currentTimeMillis()+12000;while(r.encoder!=null&&(r.frames<initialFrames+12||r.encoder.videoSamples<Math.max(40,initialSamples+12))&&System.currentTimeMillis()<deadline)Thread.sleep(100);check(r.encoder!=null&&r.frames>=initialFrames+12&&r.encoder.videoSamples>=Math.max(40,initialSamples+12),"Video frames stopped after camera switch: captured="+r.frames+"/"+initialFrames+", encoded="+(r.encoder==null?-1:r.encoder.videoSamples)+"/"+initialSamples+", failure="+(r.encoder==null?"none":r.encoder.failure));runOnMainSync(()->r.stop(true));deadline=System.currentTimeMillis()+15000;while(!r.ready&&System.currentTimeMillis()<deadline)Thread.sleep(100);check(r.ready,"Circle was not finalized: "+r.status.getText());
  check(samples(r.file,"video/")>25,"Circle lacks a video track");check(samples(r.file,"audio/")>50,"Circle lacks an audio track");File review=new File(a.getExternalFilesDir(null),"review");review.mkdirs();try(InputStream source=new FileInputStream(r.file);OutputStream dest=new FileOutputStream(new File(review,"17-circle-capture.mp4"))){byte[] buffer=new byte[65536];int count;while((count=source.read(buffer))!=-1)dest.write(buffer,0,count);}runOnMainSync(r::finish);
  result.putString("stream","OLDY_CAPTURE_PASS: actual MediaRecorder AAC, encrypted server upload/download, real camera frames, switch during one continuous recording, final MP4 audio/video tracks and timestamps\n");finish(-1,result);
 }catch(Throwable e){result.putString("stream","OLDY_CAPTURE_FAIL: "+android.util.Log.getStackTraceString(e));finish(0,result);}finally{if(round!=null){RoundActivity r=round;runOnMainSync(r::finish);}}}
}
