package chat.oldy;
import android.app.*;import android.os.*;import android.content.*;import android.media.*;import org.json.*;import java.io.*;import java.nio.*;import java.nio.file.*;import java.util.*;
/** Uses Android's actual recorder/camera/encoders; never substitutes fake media payloads. */
public class CaptureInstrumentation extends Instrumentation {
 public void onCreate(Bundle b){start();}
 void check(boolean value,String why)throws Exception{if(!value)throw new Exception(why);}
 int samples(File file,String mime)throws Exception{MediaExtractor e=new MediaExtractor();try{e.setDataSource(file.getAbsolutePath());for(int i=0;i<e.getTrackCount();i++)if(e.getTrackFormat(i).getString(MediaFormat.KEY_MIME).startsWith(mime)){e.selectTrack(i);int n=0;long last=-1;do{long time=e.getSampleTime();if(time<0)break;check(time>=last,"Capture timestamps went backwards");last=time;n++;}while(e.advance());return n;}return 0;}finally{e.release();}}
 public void onStart(){Bundle result=new Bundle();RoundActivity round=null;try{
  MainActivity a=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));Thread.sleep(2200);runOnMainSync(()->a.openChat("bobby"));Vault vault=a.vault;long started=System.currentTimeMillis();boolean[] began={false};
  runOnMainSync(()->{a.voice=new VoiceCapture(a);began[0]=a.voice.begin();});check(began[0],"Actual microphone did not start");Thread.sleep(2100);check(a.voice.running,"Recording stopped unexpectedly");File raw=a.voice.file;runOnMainSync(()->a.voice.end(true));
  JSONObject voice=null;long deadline=System.currentTimeMillis()+25000;while(voice==null&&System.currentTimeMillis()<deadline){JSONArray messages=vault.copy().getJSONArray("messages");for(int i=0;i<messages.length();i++){JSONObject m=messages.getJSONObject(i);if(m.optLong("time")>=started&&m.optString("mime").equals("audio/mp4")&&!m.optString("cloud_blob").isEmpty()){voice=m;break;}}Thread.sleep(150);}check(voice!=null,"Voice recording was not uploaded/queued");
  byte[] audio=MediaFiles.bytes(a,voice.getString("local"));File inspect=new File(a.getCacheDir(),"voice-inspect.m4a");Files.write(inspect.toPath(),audio);check(samples(inspect,"audio/")>25,"Recorded voice has no decodable audio samples");inspect.delete();MediaFiles.path(a,voice.getString("local")).delete();CloudMedia.download(a,vault,voice);check(Arrays.equals(audio,MediaFiles.bytes(a,vault.message(voice.getString("id")).getString("local"))),"Server voice bytes differ after decryption");
  round=(RoundActivity)startActivitySync(new Intent(a,RoundActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));final RoundActivity r=round;deadline=System.currentTimeMillis()+15000;while(r.frames<5&&System.currentTimeMillis()<deadline)Thread.sleep(100);check(r.frames>=5,"Selfie camera did not deliver frames: "+r.status.getText());runOnMainSync(r::begin);Thread.sleep(2200);check(r.encoder!=null,"Circle encoder did not start: "+r.status.getText());int initialFrames=r.encoder.videoSamples;runOnMainSync(r::switchCamera);deadline=System.currentTimeMillis()+12000;while(r.switches==0&&System.currentTimeMillis()<deadline)Thread.sleep(100);check(r.switches>0,"Camera did not switch during recording");Thread.sleep(2200);check(r.encoder!=null&&r.encoder.videoSamples>initialFrames+8,"Video frames stopped after camera switch");runOnMainSync(()->r.stop(true));deadline=System.currentTimeMillis()+15000;while(!r.ready&&System.currentTimeMillis()<deadline)Thread.sleep(100);check(r.ready,"Circle was not finalized: "+r.status.getText());
  check(samples(r.file,"video/")>25,"Circle lacks a video track");check(samples(r.file,"audio/")>50,"Circle lacks an audio track");File review=new File(a.getExternalFilesDir(null),"review");review.mkdirs();Files.copy(r.file.toPath(),new File(review,"17-circle-capture.mp4").toPath(),StandardCopyOption.REPLACE_EXISTING);runOnMainSync(r::finish);
  result.putString("stream","OLDY_CAPTURE_PASS: actual MediaRecorder AAC, encrypted server upload/download, real camera frames, switch during one continuous recording, final MP4 audio/video tracks and timestamps\n");finish(-1,result);
 }catch(Throwable e){result.putString("stream","OLDY_CAPTURE_FAIL: "+android.util.Log.getStackTraceString(e));finish(0,result);}finally{if(round!=null){RoundActivity r=round;runOnMainSync(r::finish);}}}
}
