package chat.oldy;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import org.json.*;import java.io.*;import java.util.*;
/** UI fixtures are local to the test emulator; no production connection or messages. */
public class DesignInstrumentation extends Instrumentation {
 public void onCreate(Bundle b){start();}
 void check(boolean b,String why)throws Exception{if(!b)throw new Exception(why);}
 MainActivity activity;
 void shot(String name)throws Exception{waitForIdleSync();getUiAutomation().waitForIdle(250,5000);Thread.sleep(1200);Bitmap bitmap=getUiAutomation().takeScreenshot();File directory=new File(getTargetContext().getExternalFilesDir(null),"review");directory.mkdirs();try(FileOutputStream out=new FileOutputStream(new File(directory,name+".png"))){bitmap.compress(Bitmap.CompressFormat.PNG,100,out);}}
 public void onStart(){Bundle result=new Bundle();try{activity=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));Thread.sleep(1700);Vault v=ChatService.vault(getTargetContext());Api api=new Api(getTargetContext());JSONObject room=api.call("/room/create",new JSONObject().put("title","Старый Геймер · новости").put("kind","channel").put("handle","oldy_design").put("public",true).put("members",new JSONArray()),v.token());v.putRoom(room);String id=room.getString("id");
  Bitmap photo=BitmapFactory.decodeStream(getTargetContext().getAssets().open("avatars-v3.webp"));Bitmap tile=Bitmap.createBitmap(photo,0,0,photo.getWidth()/2,photo.getHeight()/3);ByteArrayOutputStream jpg=new ByteArrayOutputStream();tile.compress(Bitmap.CompressFormat.JPEG,80,jpg);String local=UUID.randomUUID().toString(),hash;try(MediaFiles.Writer w=new MediaFiles.Writer(getTargetContext(),local)){byte[] bytes=jpg.toByteArray();for(int at=0;at<bytes.length;at+=16000)w.put(Arrays.copyOfRange(bytes,at,Math.min(bytes.length,at+16000)));hash=w.finish();}
  String mid=v.queuePayload("room:"+id,new JSONObject().put("kind","file").put("mime","image/jpeg").put("size",jpg.size()).put("sha256",hash).put("name","Новые аватары").put("text","Свои снова рядом 🎮\nТеперь у каждого поста — свой характер. Выбирай героя, делись фото и сохраняй самое интересное."),local);
  v.applyControl("room:"+id,v.nick(),new JSONObject().put("op","pin").put("mid",mid),System.currentTimeMillis());v.applyControl("room:"+id,v.nick(),new JSONObject().put("op","reaction").put("mid",mid).put("emoji","🔥"),System.currentTimeMillis());v.save();
  runOnMainSync(()->{Notices.prefs(activity).edit().putString("theme","light").commit();activity.openChat("room:"+id);});shot("04-channel-light");check(activity.content.findViewWithTag(mid)!=null,"Post card not rendered");runOnMainSync(()->{try{activity.messageMenu(v.message(mid));}catch(Exception e){throw new RuntimeException(e);}});shot("05-post-menu");getUiAutomation().performGlobalAction(android.accessibilityservice.AccessibilityService.GLOBAL_ACTION_BACK);Thread.sleep(200);
  runOnMainSync(()->{Notices.prefs(activity).edit().putString("theme","dark").commit();activity.openChat("room:"+id);});shot("06-channel-dark");runOnMainSync(()->activity.settings());shot("07-settings");runOnMainSync(()->activity.profileMenu());shot("08-profile-menu");getUiAutomation().performGlobalAction(android.accessibilityservice.AccessibilityService.GLOBAL_ACTION_BACK);Thread.sleep(200);runOnMainSync(()->activity.avatarPicker(""));shot("09-avatars");getUiAutomation().performGlobalAction(android.accessibilityservice.AccessibilityService.GLOBAL_ACTION_BACK);
  result.putString("stream","OLDY_DESIGN_PASS: channel card, pin, photo, reaction and settings rendered\n");finish(-1,result);
 }catch(Throwable t){result.putString("stream","OLDY_DESIGN_FAIL: "+android.util.Log.getStackTraceString(t));finish(0,result);}}
}
