package chat.oldy;
import android.app.*;import android.content.*;import android.graphics.*;import android.os.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.util.*;
/** Real screens, server directory, recording gestures and persistent local chat actions. */
public class ExperienceInstrumentation extends Instrumentation {
 public void onCreate(Bundle b){start();}
 void check(boolean v,String why){if(!v)throw new AssertionError(why);}
 boolean contains(View v,String text){if(v instanceof TextView&&((TextView)v).getText().toString().contains(text))return true;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++)if(contains(((ViewGroup)v).getChildAt(i),text))return true;return false;}
 View find(View v,Class<?> type){if(type.isInstance(v))return v;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++){View found=find(((ViewGroup)v).getChildAt(i),type);if(found!=null)return found;}return null;}
 void shot(String name)throws Exception{Thread.sleep(800);Bitmap b=getUiAutomation().takeScreenshot();File folder=new File(getTargetContext().getExternalFilesDir(null),"review");folder.mkdirs();try(FileOutputStream out=new FileOutputStream(new File(folder,name+".png"))){b.compress(Bitmap.CompressFormat.PNG,100,out);}}
 void touch(VoiceGesture g,View key,int action,float x){MotionEvent e=MotionEvent.obtain(SystemClock.uptimeMillis(),SystemClock.uptimeMillis(),action,x,20,0);g.onTouch(key,e);e.recycle();}
 public void onStart(){Bundle result=new Bundle();try{
  Context c=getTargetContext();MainActivity a=(MainActivity)startActivitySync(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));Thread.sleep(2900);Vault vault=a.vault;Api api=new Api(c);JSONObject me=api.call("/me",null,vault.token());vault.profile(me);check(me.optLong("account_number")>0,"Server account ordinal missing");
  runOnMainSync(()->{I18n.setLanguage(a,"en");a.settings();});check(contains(a.root,"Settings")&&contains(a.root,"APPEARANCE"),"English settings missing");shot("30-settings-en");runOnMainSync(a::editProfile);check(contains(a.activeSheet.getWindow().getDecorView(),"Your profile")&&contains(a.activeSheet.getWindow().getDecorView(),"ACCOUNT NO."),"Structured English profile missing");shot("31-own-profile-en");runOnMainSync(()->{a.activeSheet.dismiss();I18n.setLanguage(a,"ru");Notices.prefs(a).edit().putString("theme","cyber").commit();a.chats();});check(a.cyber,"Cyberpunk theme not selected");shot("32-cyberpunk-chats");
  String title="Старый Геймер обзоры портатива "+UUID.randomUUID().toString().substring(0,5);JSONObject room=api.call("/room/create",new JSONObject().put("kind","channel").put("title",title).put("public",true).put("members",new JSONArray()),vault.token());
  // Do not put the room in the local vault: discovery must get it from the server.
  runOnMainSync(()->{a.search="портатива старый";a.filter=3;a.chats();});long deadline=System.currentTimeMillis()+8000;boolean[] found={false};while(!found[0]&&System.currentTimeMillis()<deadline){runOnMainSync(()->found[0]=contains(a.root,title));Thread.sleep(100);}check(found[0],"Main channel field did not discover the server-only title");shot("33-live-channel-search");
  runOnMainSync(()->{a.search="";a.filter=0;Notices.prefs(a).edit().putString("theme","light").putInt("wallpaper",2).commit();a.openChat("bobby");});shot("38-beige-wallpaper-light");int[] pixels=new int[2];for(int i=0;i<2;i++){Bitmap sample=Bitmap.createBitmap(300,400,Bitmap.Config.ARGB_8888);Wallpaper wallpaper=new Wallpaper(true,i==0?1:2);wallpaper.setBounds(0,0,300,400);wallpaper.draw(new Canvas(sample));pixels[i]=sample.getPixel(2,2);sample.recycle();}check(Math.abs(Color.red(pixels[0])-Color.red(pixels[1]))+Math.abs(Color.blue(pixels[0])-Color.blue(pixels[1]))>60,"Light wallpaper palettes are indistinguishable");runOnMainSync(a::wallpaperPicker);shot("39-wallpaper-gallery");runOnMainSync(()->{a.activeSheet.dismiss();});
  vault.archiveChat("bobby",true);check(new Vault(c,vault.nick(),false).archived("bobby"),"Archive did not survive reloading the account");runOnMainSync(()->{a.search="";a.filter=0;a.showArchive=true;a.chats();});shot("34-archive");vault.archiveChat("bobby",false);
  runOnMainSync(()->{a.showArchive=false;a.openChat("bobby");a.compose.setText("");});VoiceGesture gesture=new VoiceGesture(a);runOnMainSync(()->touch(gesture,a.sendKey,MotionEvent.ACTION_DOWN,200));check(a.voice.running,"Hold did not start recording");Thread.sleep(1300);runOnMainSync(()->touch(gesture,a.sendKey,MotionEvent.ACTION_MOVE,200-a.dp(100)));check(gesture.cancelled&&a.voice.cancelAmount==1,"Left drag did not latch cancellation");File file=a.voice.file;shot("35-voice-cancel-meter");runOnMainSync(()->{touch(gesture,a.sendKey,MotionEvent.ACTION_MOVE,200);touch(gesture,a.sendKey,MotionEvent.ACTION_UP,200);});check(!a.voice.running&&!file.exists()&&a.voice.pending==null,"Canceled gesture sent or retained the recording");
  runOnMainSync(()->{I18n.setLanguage(a,"en");a.auth(false);});check(contains(a.root,"Email address")&&contains(a.root,"Email me a code"),"Email-only English login missing");shot("36-email-login-en");runOnMainSync(()->{I18n.setLanguage(a,"ru");a.chats();});AudioLabActivity lab=(AudioLabActivity)startActivitySync(new Intent(c,AudioLabActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));shot("37-audio-workshop");runOnMainSync(lab::finish);
  result.putString("stream","OLDY_EXPERIENCE_PASS: English, profile ordinal, cyberpunk, server title search, persistent archive, latched recording cancellation and audio workshop\n");finish(-1,result);
 }catch(Throwable e){I18n.setLanguage(getTargetContext(),"ru");result.putString("stream","OLDY_EXPERIENCE_FAIL: "+android.util.Log.getStackTraceString(e));finish(0,result);}}
}
