package chat.oldy;
import android.app.*;import android.content.*;import android.os.*;import android.view.*;import android.widget.*;
public class LegalUiInstrumentation extends Instrumentation {
 void check(boolean value,String message){if(!value)throw new AssertionError(message);}
 View description(View v,String text){if(text.contentEquals(v.getContentDescription()==null?"":v.getContentDescription()))return v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){View found=description(g.getChildAt(i),text);if(found!=null)return found;}}return null;}
 RefreshScrollView refreshView(View v){if(v instanceof RefreshScrollView)return (RefreshScrollView)v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){RefreshScrollView result=refreshView(g.getChildAt(i));if(result!=null)return result;}}return null;}
 public void onCreate(Bundle args){super.onCreate(args);start();}
 public void onStart(){Bundle result=new Bundle();try{MainActivity a=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));Thread.sleep(2900);runOnMainSync(()->SettingsHome.show(a));waitForIdleSync();runOnMainSync(()->{View back=description(a.root,I18n.t("Назад"));check(back!=null,"Settings back control missing");check(back.getForeground() instanceof android.graphics.drawable.RippleDrawable,"Button has no visible pressed feedback");back.performClick();check(a.screen.equals("chats"),"Settings back returns to settings instead of chats");SettingsHome.appearance(a);});waitForIdleSync();runOnMainSync(()->{description(a.root,I18n.t("Назад")).performClick();check(a.screen.equals("settings")&&a.settingsSection.isEmpty(),"Subsection back does not return to settings");try{check(LegalCenter.documents(a).has("privacy"),"Privacy document missing");check(LegalCenter.documents(a).has("community"),"Community rules missing");}catch(Exception e){throw new RuntimeException(e);}});
  runOnMainSync(()->{RefreshScrollView scroll=refreshView(a.root);check(scroll!=null,"Pull-to-refresh surface missing");long now=SystemClock.uptimeMillis();MotionEvent down=MotionEvent.obtain(now,now,MotionEvent.ACTION_DOWN,40,20,0);scroll.onInterceptTouchEvent(down);down.recycle();MotionEvent move=MotionEvent.obtain(now,now+50,MotionEvent.ACTION_MOVE,40,20+a.dp(110),0);check(scroll.onInterceptTouchEvent(move),"Downward pull was not recognized");scroll.onTouchEvent(move);move.recycle();MotionEvent up=MotionEvent.obtain(now,now+100,MotionEvent.ACTION_UP,40,20+a.dp(110),0);scroll.onTouchEvent(up);up.recycle();check(scroll.refreshing,"Refresh did not begin");});
  long until=SystemClock.elapsedRealtime()+8000;while(SystemClock.elapsedRealtime()<until&&refreshView(a.root).refreshing)Thread.sleep(50);check(!refreshView(a.root).refreshing,"Refresh remained stuck");
  getUiAutomation().performGlobalAction(android.accessibilityservice.AccessibilityService.GLOBAL_ACTION_BACK);Thread.sleep(400);check(a.screen.equals("chats"),"System back did not leave settings");
  result.putString("stream","OLDI_LEGAL_UI_PASS: settings/subsection back, native ripple feedback, offline policy documents, pull-to-refresh and Android system back\n");finish(-1,result);
 }catch(Throwable e){result.putString("stream","OLDI_LEGAL_UI_FAIL: "+android.util.Log.getStackTraceString(e));finish(0,result);}}
}
