package chat.oldy;
import android.app.*;import android.content.*;import android.net.*;import android.os.*;import java.io.*;import java.net.*;import javax.net.ssl.*;

/** Emulator-only integration: real TUN DNS/UDP and opaque TLS to the official YouTube host.
 * This is not a claim of Wi-Fi, cellular, QUIC playback or handset verification. */
public class LocalTunnelInstrumentation extends Instrumentation {
 public void onCreate(Bundle b){start();}void check(boolean ok,String why){if(!ok)throw new AssertionError(why);}
 void shell(String cmd)throws Exception{try(ParcelFileDescriptor fd=getUiAutomation().executeShellCommand(cmd);InputStream in=new ParcelFileDescriptor.AutoCloseInputStream(fd)){byte[] b=new byte[1024];while(in.read(b)!=-1){}}}
 public void onStart(){Bundle result=new Bundle();Context c=getTargetContext();MainActivity a=null;try{a=(MainActivity)startActivitySync(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));Thread.sleep(2900);shell("appops set chat.oldy ACTIVATE_VPN allow");check(android.net.VpnService.prepare(c)==null,"Emulator VPN permission fixture failed");MainActivity activity=a;runOnMainSync(()->LocalTunnelService.start(activity));long end=System.currentTimeMillis()+10000;while(!TunnelStateRepository.on()&&System.currentTimeMillis()<end)Thread.sleep(100);check(TunnelStateRepository.on(),"Local TUN failed: "+TunnelStateRepository.lastError(c));Thread.sleep(1700);check(TunnelStateRepository.on(),"Native TUN exited after startup");
  InetAddress[] addresses=InetAddress.getAllByName("www.youtube.com");boolean v4=false,v6=false;InetAddress ipv6=null;for(InetAddress ip:addresses){String text=ip.getHostAddress();v4|=text.startsWith("198.18.");if(ip instanceof Inet6Address&&text.startsWith("fd66:")){v6=true;ipv6=ip;}}check(v4,"YouTube DNS did not enter local TUN");
  HttpsURLConnection request=(HttpsURLConnection)new URL("https://www.youtube.com/").openConnection();request.setConnectTimeout(20000);request.setReadTimeout(15000);request.setRequestMethod("HEAD");request.setInstanceFollowRedirects(false);int response;try{response=request.getResponseCode();}finally{request.disconnect();}check(response>=200&&response<600,"TLS through local TUN failed");
  check(TunnelStateRepository.webPort>0,"Explicit WebView proxy missing");java.net.Proxy proxy=new java.net.Proxy(java.net.Proxy.Type.HTTP,new InetSocketAddress("127.0.0.1",TunnelStateRepository.webPort));HttpsURLConnection bridge=(HttpsURLConnection)new URL("https://www.youtube.com/").openConnection(proxy);bridge.setConnectTimeout(20000);bridge.setReadTimeout(15000);bridge.setRequestMethod("HEAD");try{check(bridge.getResponseCode()>=200,"Same-UID CONNECT failed");}finally{bridge.disconnect();}
  boolean denied=false;HttpsURLConnection disallowed=(HttpsURLConnection)new URL("https://example.com/").openConnection(proxy);disallowed.setConnectTimeout(4000);disallowed.setReadTimeout(4000);try{disallowed.getResponseCode();}catch(IOException expected){denied=true;}finally{disallowed.disconnect();}check(denied,"Proxy accepted a non-YouTube domain");
  runOnMainSync(()->Notices.prefs(activity).edit().putString("youtube_mode","auto").putBoolean("youtube_embedded_disclosure",true).commit());long before=TunnelStateRepository.webConnections;YouTubeHubActivity hub=(YouTubeHubActivity)startActivitySync(new Intent(c,YouTubeHubActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));end=System.currentTimeMillis()+25000;while((TunnelStateRepository.webConnections<=before||TunnelStateRepository.webRx==0)&&System.currentTimeMillis()<end){TunnelStateRepository.refresh();Thread.sleep(150);}check(hub.web!=null&&hub.web.getParent()==hub.content,"YouTube was handed to an external browser");check(TunnelStateRepository.webConnections>before&&TunnelStateRepository.webRx>0,"Real WebView bypassed local relay");runOnMainSync(hub::finish);runOnMainSync(()->LocalTunnelService.touch(activity));
  if(ipv6!=null){try(Socket socket=new Socket()){socket.connect(new InetSocketAddress(ipv6,443),15000);try(SSLSocket tls=(SSLSocket)((SSLSocketFactory)SSLSocketFactory.getDefault()).createSocket(socket,"www.youtube.com",443,true)){SSLParameters params=tls.getSSLParameters();params.setEndpointIdentificationAlgorithm("HTTPS");tls.setSSLParameters(params);tls.setSoTimeout(15000);tls.startHandshake();}}}
  Thread.sleep(1800);check(TunnelStateRepository.on()&&TunnelStateRepository.txBytes>0&&TunnelStateRepository.rxBytes>0,"Native TUN traffic counters did not advance");runOnMainSync(()->LocalTunnelService.stop(activity));end=System.currentTimeMillis()+8000;while((TunnelStateRepository.on()||NetworkDiagnostics.otherVpn(c))&&System.currentTimeMillis()<end)Thread.sleep(100);check(!TunnelStateRepository.on(),"Local VPN did not stop");check(!NetworkDiagnostics.otherVpn(c),"VPN routes survived service stop");
  runOnMainSync(()->LocalTunnelService.start(activity));end=System.currentTimeMillis()+10000;while(!TunnelStateRepository.on()&&System.currentTimeMillis()<end)Thread.sleep(100);check(TunnelStateRepository.on(),"Local VPN failed to restart after cleanup");Thread.sleep(1700);check(TunnelStateRepository.on(),"Restarted native module exited");runOnMainSync(()->LocalTunnelService.stop(activity));end=System.currentTimeMillis()+8000;while((TunnelStateRepository.on()||NetworkDiagnostics.otherVpn(c))&&System.currentTimeMillis()<end)Thread.sleep(100);check(!NetworkDiagnostics.otherVpn(c),"Restarted VPN did not remove routes");
  result.putString("stream","OLDY_LOCAL_TUNNEL_PASS: native per-app split TUN, synthetic DNS over UDP, protected direct TCP/TLS, IPv6="+v6+", packet counters, same-UID HTTPS CONNECT and domain rejection, actual embedded WebView uses explicit local relay, service cleanup and restart; physical networks need handset validation\n");finish(-1,result);
 }catch(Throwable e){result.putString("stream","OLDY_LOCAL_TUNNEL_FAIL: "+android.util.Log.getStackTraceString(e));finish(0,result);}finally{LocalTunnelService.stop(c);}}
}
