package chat.oldy;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.os.*;import android.provider.ContactsContract;import android.view.*;import android.widget.*;import org.json.*;import java.util.*;

/** Real Android address book matching and per-account recovery without production data. */
public class PrivacyInstrumentation extends Instrumentation {
 public void onCreate(Bundle b){start();}
 void check(boolean b,String s){if(!b)throw new AssertionError(s);}
 boolean contains(View v,String text){if(v instanceof TextView&&((TextView)v).getText().toString().contains(text))return true;if(v instanceof ViewGroup)for(int i=0;i<((ViewGroup)v).getChildCount();i++)if(contains(((ViewGroup)v).getChildAt(i),text))return true;return false;}
 public void onStart(){Bundle result=new Bundle();long rawId=-1;MainActivity a=null;try{
  a=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));Thread.sleep(2900);final MainActivity activity=a;Api api=a.api;
  String nick="contacts_"+UUID.randomUUID().toString().substring(0,8),email=nick+"@example.test";JSONObject identity=Crypto.identity();JSONObject target=FixturesInstrumentation.register(api,new JSONObject().put("nick",nick).put("email",email).put("password","fixture random password 2379").put("enc",identity.getString("enc")).put("sig",identity.getString("sig")),"");
  api.call("/contacts/settings",new JSONObject().put("discoverable",true),target.getString("token"));
  runOnMainSync(()->ContactDiscovery.show(activity));waitForIdleSync();check(contains(a.root,I18n.t("Найти в контактах")),"Contact lookup is missing from UI");
  getUiAutomation().grantRuntimePermission(a.getPackageName(),Manifest.permission.READ_CONTACTS);getUiAutomation().adoptShellPermissionIdentity(Manifest.permission.WRITE_CONTACTS);
  try{ContentValues raw=new ContentValues();raw.putNull(ContactsContract.RawContacts.ACCOUNT_TYPE);raw.putNull(ContactsContract.RawContacts.ACCOUNT_NAME);Uri created=a.getContentResolver().insert(ContactsContract.RawContacts.CONTENT_URI,raw);rawId=ContentUris.parseId(created);ContentValues data=new ContentValues();data.put(ContactsContract.Data.RAW_CONTACT_ID,rawId);data.put(ContactsContract.Data.MIMETYPE,ContactsContract.CommonDataKinds.StructuredName.CONTENT_ITEM_TYPE);data.put(ContactsContract.CommonDataKinds.StructuredName.DISPLAY_NAME,"Мой знакомый");a.getContentResolver().insert(ContactsContract.Data.CONTENT_URI,data);data=new ContentValues();data.put(ContactsContract.Data.RAW_CONTACT_ID,rawId);data.put(ContactsContract.Data.MIMETYPE,ContactsContract.CommonDataKinds.Email.CONTENT_ITEM_TYPE);data.put(ContactsContract.CommonDataKinds.Email.ADDRESS,email.toUpperCase(Locale.ROOT));a.getContentResolver().insert(ContactsContract.Data.CONTENT_URI,data);}finally{getUiAutomation().dropShellPermissionIdentity();}
  check(ContactDiscovery.addresses(a).containsKey(ContactDiscovery.hash(email)),"Real contact email was not normalized and read");runOnMainSync(()->ContactDiscovery.scan(activity));long deadline=System.currentTimeMillis()+9000;boolean[] visible={false};while(!visible[0]&&System.currentTimeMillis()<deadline){Thread.sleep(120);runOnMainSync(()->visible[0]=contains(activity.root,"@"+nick));}check(visible[0],"Registered contact did not appear in the app");
  api.call("/contacts/settings",new JSONObject().put("discoverable",false),target.getString("token"));JSONObject reply=api.call("/contacts/discover",new JSONObject().put("hashes",new JSONArray().put(ContactDiscovery.hash(email))),a.vault.token());check(reply.getJSONArray("matches").length()==0,"Opt-out still permits contact discovery");
  String key=RecoveryKeys.create();check(!key.equals(RecoveryKeys.create())&&key.matches("OLDY(?:-[A-F0-9]{8}){8}"),"Personal recovery keys lack expected random format");String backup=Crypto.exportBackup(a.vault.keyBackup(),key.toCharArray());api.call("/key-backup",new JSONObject().put("backup",backup),a.vault.token());String stored=api.call("/key-backup",null,a.vault.token()).getString("backup");check(!stored.contains(key),"Recovery key was sent as plaintext");check(Crypto.importBackup(stored,key.toCharArray()).equals(a.vault.keyBackup()),"Personal key cannot reopen this account's backup");boolean denied=false;try{Crypto.importBackup(stored,RecoveryKeys.create().toCharArray());}catch(Exception expected){denied=true;}check(denied,"Another recovery key opens private history");
  result.putString("stream","OLDY_PRIVACY_PASS: actual Android contact email, normalized private lookup, discovery opt-out, per-account recovery roundtrip and wrong-key rejection\n");finish(-1,result);
 }catch(Throwable e){result.putString("stream","OLDY_PRIVACY_FAIL: "+android.util.Log.getStackTraceString(e));finish(0,result);}finally{if(rawId>=0&&a!=null)try{getUiAutomation().adoptShellPermissionIdentity(Manifest.permission.WRITE_CONTACTS);a.getContentResolver().delete(ContentUris.withAppendedId(ContactsContract.RawContacts.CONTENT_URI,rawId),null,null);}catch(Exception ignored){}finally{getUiAutomation().dropShellPermissionIdentity();}}}
}
