package chat.oldy;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.util.*;
/** Notification deadlines, account separation and real foreground delivery. */
public class RefreshInstrumentation extends Instrumentation {
 public void onCreate(Bundle b){start();}void check(boolean x,String why)throws Exception{if(!x)throw new Exception(why);}
 View text(View v,String s){if(v instanceof TextView&&((TextView)v).getText().toString().equals(s))return v;if(v instanceof ViewGroup){ViewGroup group=(ViewGroup)v;for(int i=0;i<group.getChildCount();i++){View found=text(group.getChildAt(i),s);if(found!=null)return found;}}return null;}
 void shot(String name)throws Exception{waitForIdleSync();getUiAutomation().waitForIdle(200,5000);Thread.sleep(1000);Bitmap b=getUiAutomation().takeScreenshot();File folder=new File(getTargetContext().getExternalFilesDir(null),"review");folder.mkdirs();try(FileOutputStream out=new FileOutputStream(new File(folder,name+".png"))){b.compress(Bitmap.CompressFormat.PNG,100,out);}}
 public void onStart(){Bundle result=new Bundle();try{Context c=getTargetContext();MainActivity a=(MainActivity)startActivitySync(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));Thread.sleep(2800);Vault owner=a.vault;JSONObject peer=owner.peer("bobby");check(peer!=null,"Missing peer");Notices.account(c,owner).edit().clear().commit();Notices.prefs(c).edit().putBoolean("notifications",true).putBoolean("sound",true).putBoolean("vibration",true).commit();long now=System.currentTimeMillis();
  Notices.quiet(c,owner,now+25*60000L);Notices.Policy quiet=Notices.policy(c,owner,"bobby",now);check(quiet.visible&&!quiet.sound&&!quiet.vibrate,"Global quiet suppresses notifications or plays sound");Notices.Policy expired=Notices.policy(c,owner,"bobby",now+25*60000L+1);check(expired.visible&&expired.sound&&expired.vibrate,"Quiet expiry did not restore sound/vibration");
  JSONObject m=new JSONObject().put("id",UUID.randomUUID().toString()).put("peer","bobby").put("kind","text").put("text","Test notification");Notices.show(c,owner,m,peer);NotificationManager manager=c.getSystemService(NotificationManager.class);NotificationChannel silent=manager.getNotificationChannel(Notices.channelId(c,false,false));check(silent!=null&&silent.getSound()==null&&!silent.shouldVibrate(),"Quiet Android channel has sound/vibration");
  runOnMainSync(()->a.openChat("bobby"));String mid=UUID.randomUUID().toString();owner.receiveDecoded(new JSONObject().put("id",mid).put("from","bobby").put("to",owner.nick()).put("time",now),peer,new JSONObject().put("kind","text").put("text","Приходит даже с выключенным звуком"));long deadline=System.currentTimeMillis()+4000;boolean[] visible={false};while(!visible[0]&&System.currentTimeMillis()<deadline){runOnMainSync(()->visible[0]=a.content.findViewWithTag(mid)!=null);Thread.sleep(80);}check(visible[0],"Quiet mode blocked open chat delivery");
  Notices.quiet(c,owner,0);Notices.show(c,owner,m,peer);NotificationChannel sound=manager.getNotificationChannel(Notices.channelId(c,true,true));check(sound!=null&&sound.getSound()!=null&&sound.shouldVibrate(),"Disabling quiet reused a silent notification channel");check(Notices.policy(c,owner,"bobby",now).sound,"Disabling quiet remains silent");
  Notices.mute(c,owner,"bobby",now+30*60000L);check(!Notices.policy(c,owner,"bobby",now).visible&&Notices.policy(c,owner,"another",now).visible,"Per-chat mute leaks to other chats");check(Notices.policy(c,owner,"bobby",now+30*60000L+1).visible,"Timed chat mute never expires");Notices.mute(c,owner,"bobby",-1);check(!Notices.policy(c,owner,"bobby",Long.MAX_VALUE/2).visible,"Forever mute expired");String rid=UUID.randomUUID().toString();Notices.mute(c,owner,"room:"+rid,-1);check(!Notices.policy(c,owner,"thread:"+rid+":"+UUID.randomUUID(),now).visible,"Comment thread ignores community mute");
  File isolated=new File(c.getCacheDir(),"notices-test-"+UUID.randomUUID());isolated.mkdirs();Context separate=new ContextWrapper(c){public File getFilesDir(){return isolated;}};Vault second=new Vault(separate,"notices_second",true);second.data.put("nick","notices_second");check(Notices.policy(c,second,"bobby",now).visible,"Another account inherited chat mute");Notices.account(c,owner).edit().clear().commit();
  runOnMainSync(a::focusMode);Thread.sleep(120);View on=text(a.activeSheet.getWindow().getDecorView(),"Без звука на 25 минут");check(on!=null,"Quiet action is not explicit");runOnMainSync(()->on.performClick());check(Notices.quietUntil(a,owner)>System.currentTimeMillis(),"Quiet UI did not enable");View off=text(a.activeSheet.getWindow().getDecorView(),"Выключить сейчас");check(off!=null,"Quiet UI cannot turn off");shot("23-quiet-timer");runOnMainSync(()->off.performClick());check(Notices.quietUntil(a,owner)==0,"Quiet UI remains on after off");runOnMainSync(()->{a.activeSheet.dismiss();NotificationSheet.chat(a,"bobby");});Thread.sleep(120);for(String duration:new String[]{"На 30 минут","На 1 час","На 12 часов","Навсегда"})check(text(a.activeSheet.getWindow().getDecorView(),duration)!=null,"Missing notification duration: "+duration);shot("24-chat-notifications");
  runOnMainSync(()->{a.activeSheet.dismiss();ProfileSheet.person(a,peer,null);});shot("25-person-profile");check(text(a.activeSheet.getWindow().getDecorView(),"Звонок")!=null,"Profile lacks internet calling");runOnMainSync(()->{a.activeSheet.dismiss();a.openChat("bobby");});String saved=a.chat;runOnMainSync(()->{a.onPause();a.onResume();});check(a.screen.equals("chat")&&a.chat.equals(saved),"Resume restarted splash or lost conversation");
  runOnMainSync(()->a.auth(true));Thread.sleep(120);EditText[] nick={null};findNick(a.root,nick);check(nick[0]!=null,"Registration nickname missing");runOnMainSync(()->nick[0].setText("@bobby"));deadline=System.currentTimeMillis()+8000;boolean[] taken={false};while(!taken[0]&&System.currentTimeMillis()<deadline){runOnMainSync(()->taken[0]=contains(a.root,"уже занят"));Thread.sleep(100);}check(taken[0],"Registration does not show occupied nickname live");check(!text(a.root,"Получить код на почту →").isEnabled(),"Occupied nickname can request code");runOnMainSync(()->nick[0].setText("@free_"+System.currentTimeMillis()));deadline=System.currentTimeMillis()+8000;boolean[] free={false};while(!free[0]&&System.currentTimeMillis()<deadline){runOnMainSync(()->free[0]=contains(a.root,"свободен"));Thread.sleep(100);}check(free[0]&&text(a.root,"Получить код на почту →").isEnabled(),"Available nickname remains blocked");shot("26-signup-nickname");runOnMainSync(a::chats);
  result.putString("stream","OLDY_REFRESH_PASS: audible and silent Android channels, exact deadlines, explicit off, per-chat and per-account isolation, foreground delivery while quiet, profile actions, resume preserves chat, live nickname availability\n");finish(-1,result);
 }catch(Throwable e){result.putString("stream","OLDY_REFRESH_FAIL: "+android.util.Log.getStackTraceString(e));finish(0,result);}}
 boolean contains(View v,String s){if(v instanceof TextView&&((TextView)v).getText().toString().contains(s))return true;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)if(contains(g.getChildAt(i),s))return true;}return false;}
 void findNick(View v,EditText[] found){if(v instanceof EditText&&((EditText)v).getHint()!=null&&((EditText)v).getHint().toString().startsWith("@ник"))found[0]=(EditText)v;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)findNick(g.getChildAt(i),found);}}
}
