package chat.oldy;
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;import java.nio.*;import org.json.*;

/** User-visible release regressions. AI transport uses an explicit synthetic provider fixture. */
public class UpgradeInstrumentation extends Instrumentation {
 public void onCreate(Bundle b){start();}void check(boolean b,String why){if(!b)throw new AssertionError(why);}boolean contains(View v,String text){if(v instanceof TextView&&((TextView)v).getText().toString().contains(text))return true;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)if(contains(g.getChildAt(i),text))return true;}return false;}
 void shot(String name)throws Exception{waitForIdleSync();Thread.sleep(450);Bitmap b=getUiAutomation().takeScreenshot();File dir=new File(getTargetContext().getExternalFilesDir(null),"review");dir.mkdirs();try(FileOutputStream o=new FileOutputStream(new File(dir,name+".png"))){b.compress(Bitmap.CompressFormat.PNG,100,o);}b.recycle();}
 public void onStart(){Bundle result=new Bundle();try{Context c=getTargetContext();MainActivity a=(MainActivity)startActivitySync(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));Thread.sleep(2900);runOnMainSync(()->{Notices.prefs(a).edit().putString("theme","light").putInt("wallpaper",9).putBoolean("wallpaper_photo",false).commit();a.chats();});waitForIdleSync();
  runOnMainSync(()->{View top=a.root.findViewWithTag("content-navigation"),bottom=a.root.findViewWithTag("primary-navigation");check(top!=null&&bottom!=null,"Persistent navigation missing");check(top.getY()<bottom.getY()&&bottom.getY()>a.root.getHeight()/2,"Navigation in wrong screen region");check(contains(top,"YouTube")&&contains(top,"Каналы")&&contains(top,"Группы"),"Upper destinations missing");check(contains(bottom,"Контакты")&&contains(bottom,"Моё"),"Bottom destinations missing");for(String name:EmojiTray.NAMES)check(!name.contains("стикеры"),"Personal stickers remain hidden in emoji tabs");a.menu();check(a.screen.equals("settings")&&a.activeSheet==null,"Ellipsis should open settings directly");});shot("60-direct-settings");runOnMainSync(a::chats);shot("61-youtube-main");runOnMainSync(()->{a.settings();check(a.root instanceof ThemeLayout&&((ThemeLayout)a.root).backdrop.style==9,"Settings did not share theme");check(Wallpaper.NAMES.length>=21,"Extra themes missing");Notices.prefs(a).edit().putString("theme","cyber").putInt("wallpaper",3).commit();a.chats();check(a.GREEN==0xff40fbe9,"Neon accent overwritten");});shot("62-cyber-neon");
  Bitmap source=Bitmap.createBitmap(512,512,Bitmap.Config.ARGB_8888);Canvas drawing=new Canvas(source);Paint ink=new Paint(3);ink.setColor(0xffffc595);drawing.drawCircle(256,190,105,ink);ink.setColor(0xff339ac1);drawing.drawRoundRect(140,285,370,490,35,35,ink);
  StickerEditorActivity editor=(StickerEditorActivity)startActivitySync(new Intent(c,StickerEditorActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));runOnMainSync(()->{editor.canvas.setImage(source.copy(Bitmap.Config.ARGB_8888,true));editor.title.setText("Тестовый персонаж");editor.create();});long until=SystemClock.elapsedRealtime()+10000;while(editor.busy&&SystemClock.elapsedRealtime()<until)Thread.sleep(80);check(editor.animation==null&&editor.status.getText().toString().contains("не подключён"),"Missing generator silently substituted a photo animation");
  JSONObject fixture=a.api.call("/test-sticker/enable",new JSONObject(),a.vault.token());check(fixture.optString("provider").equals("test-fixture"),"Unexpected test provider");runOnMainSync(editor::create);until=SystemClock.elapsedRealtime()+10000;android.view.accessibility.AccessibilityNodeInfo consent=null;while(consent==null&&SystemClock.elapsedRealtime()<until){android.view.accessibility.AccessibilityNodeInfo root=getUiAutomation().getRootInActiveWindow();if(root!=null){java.util.List<android.view.accessibility.AccessibilityNodeInfo> matches=root.findAccessibilityNodeInfosByText("Передать фото и создать");if(!matches.isEmpty())consent=matches.get(0);}Thread.sleep(80);}check(consent!=null,"Photo sharing consent missing");check(consent.performAction(android.view.accessibility.AccessibilityNodeInfo.ACTION_CLICK),"Could not consent to photo generation");until=SystemClock.elapsedRealtime()+25000;while(editor.animation==null&&SystemClock.elapsedRealtime()<until)Thread.sleep(100);check(editor.animation!=null,"Generative job transport failed: "+editor.status.getText());byte[] encoded=editor.animation;check(encoded.length<=350000&&AnimatedStickerCodec.animated(encoded),"Animated result invalid");Drawable drawable=ImageDecoder.decodeDrawable(ImageDecoder.createSource(ByteBuffer.wrap(encoded)));check(drawable instanceof AnimatedImageDrawable,"Recipient decoded a still image");
  runOnMainSync(()->{Rect visible=new Rect();check(editor.animatedPreview.getGlobalVisibleRect(visible)&&visible.height()>editor.dp(150),"Result hidden below scrolling content");check(editor.saveKey.getVisibility()==View.VISIBLE,"Save action missing");});shot("64-character-result-fixture");File dir=new File(c.getExternalFilesDir(null),"review");java.nio.file.Files.write(new File(dir,"63-created-sticker.webp").toPath(),encoded);PersonalStickerStore store=new PersonalStickerStore(c,a.vault.nick());String id=store.saveAnimation(encoded,editor.cartoon,"Тест кадров");check(java.util.Arrays.equals(Crypto.un64(store.read(id).getString("image")),encoded),"Animated bytes not persisted");check(store.list().get(0).getString("id").equals(id),"New sticker is not first in collection");runOnMainSync(editor::finish);store.remove(id);Notices.prefs(c).edit().remove("sticker_pending_"+a.vault.nick()).commit();source.recycle();
  runOnMainSync(()->{a.openChat("bobby");a.compose.setText("");a.attachments();});check(contains(a.getWindow().getDecorView(),"Сообщение")||a.screen.equals("chat"),"Conversation lost");getUiAutomation().performGlobalAction(android.accessibilityservice.AccessibilityService.GLOBAL_ACTION_BACK);
  String mid=a.vault.queuePayload("bobby",new JSONObject().put("kind","text").put("text","Долгое нажатие открывает действия"),null);runOnMainSync(a::renderMessages);Thread.sleep(250);runOnMainSync(()->{View bubble=a.content.findViewWithTag(mid);check(bubble!=null&&bubble.performLongClick(),"Long press did not select message");});runOnMainSync(a::renderMessages);check(a.selectedMessage!=null&&a.selectionBar!=null&&contains(a.selectionBar,"Выбрано 1"),"Selection vanished after live message refresh");shot("65-message-selection");runOnMainSync(a::onBackPressed);waitForIdleSync();Thread.sleep(350);check(a.screen.equals("chat")&&a.selectedMessage==null,"Back left chat instead of dismissing selection");
  // Exercise the actual touch path; earlier capture tests called VoiceCapture directly.
  final long down=SystemClock.uptimeMillis();final int[] xy=new int[2];runOnMainSync(()->{a.compose.setText("");a.sendKey.getLocationOnScreen(xy);xy[0]+=a.sendKey.getWidth()/2;xy[1]+=a.sendKey.getHeight()/2;});MotionEvent press=MotionEvent.obtain(down,down,MotionEvent.ACTION_DOWN,xy[0],xy[1],0);press.setSource(InputDevice.SOURCE_TOUCHSCREEN);check(getUiAutomation().injectInputEvent(press,true),"Touch injection rejected");press.recycle();Thread.sleep(1400);shot("66-microphone-hold");check(a.voice!=null&&a.voice.running&&a.voice.ticks>8,"Hold gesture failed: screen="+a.screen+", voice="+(a.voice==null?"null":a.voice.running+"/ticks="+a.voice.ticks+"/level="+a.voice.levelError)+", held="+(a.heldVoice!=null)+", coordinates="+xy[0]+","+xy[1]);runOnMainSync(()->a.root.requestLayout());Thread.sleep(150);MotionEvent move=MotionEvent.obtain(down,SystemClock.uptimeMillis(),MotionEvent.ACTION_MOVE,xy[0]-a.dp(100),xy[1],0);move.setSource(InputDevice.SOURCE_TOUCHSCREEN);check(getUiAutomation().injectInputEvent(move,true),"Move injection rejected");move.recycle();MotionEvent up=MotionEvent.obtain(down,SystemClock.uptimeMillis(),MotionEvent.ACTION_UP,xy[0]-a.dp(100),xy[1],0);up.setSource(InputDevice.SOURCE_TOUCHSCREEN);check(getUiAutomation().injectInputEvent(up,true),"Release injection rejected");up.recycle();Thread.sleep(350);check(!a.voice.running&&a.voice.pending==null,"Slide-to-cancel retained or sent recording");
  result.putString("stream","OLDI_UPGRADE_PASS: top/bottom navigation, direct settings, 21 themes with neon, honest generator-disabled state, explicit photo consent, async generated-frame transport and animated decode (synthetic provider fixture, live AI not tested), visible result and newest-first collection, long-press selection, microphone hold and slide-to-cancel\n");finish(-1,result);
 }catch(Throwable e){result.putString("stream","OLDI_UPGRADE_FAIL: "+android.util.Log.getStackTraceString(e));finish(0,result);}}
}
