package chat.oldy;
import android.app.*;import android.content.*;import android.graphics.*;import android.graphics.drawable.*;import android.os.*;import android.view.*;import android.widget.*;import java.io.*;import java.nio.*;import org.json.*;

/** Real bitmap-to-animation/decode, message long press, drawer, themes and microphone gesture. */
public class UpgradeInstrumentation extends Instrumentation {
 public void onCreate(Bundle b){start();}void check(boolean b,String why){if(!b)throw new AssertionError(why);}boolean contains(View v,String text){if(v instanceof TextView&&((TextView)v).getText().toString().contains(text))return true;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++)if(contains(g.getChildAt(i),text))return true;}return false;}
 void shot(String name)throws Exception{waitForIdleSync();Thread.sleep(450);Bitmap b=getUiAutomation().takeScreenshot();File dir=new File(getTargetContext().getExternalFilesDir(null),"review");dir.mkdirs();try(FileOutputStream o=new FileOutputStream(new File(dir,name+".png"))){b.compress(Bitmap.CompressFormat.PNG,100,o);}b.recycle();}
 public void onStart(){Bundle result=new Bundle();try{Context c=getTargetContext();MainActivity a=(MainActivity)startActivitySync(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));Thread.sleep(2900);runOnMainSync(()->{Notices.prefs(a).edit().putString("theme","light").putInt("wallpaper",9).putBoolean("wallpaper_photo",false).commit();a.chats();check(contains(a.root,"Просмотр YouTube"),"Main YouTube entry missing");a.menu();});check(a.activeSheet!=null,"Left drawer not opened");check(contains(a.activeSheet.getWindow().getDecorView(),"Контакты")&&contains(a.activeSheet.getWindow().getDecorView(),"Настройки"),"Drawer missing destinations");shot("60-left-drawer");runOnMainSync(()->{a.activeSheet.dismiss();a.chats();});shot("61-youtube-main");runOnMainSync(()->{a.settings();check(a.root instanceof ThemeLayout&&((ThemeLayout)a.root).backdrop.style==9,"Settings did not share theme");check(!contains(a.root,"Обои чатов"),"Old chat-only theme label remains");});shot("62-global-theme-settings");
  Bitmap photo=BitmapFactory.decodeStream(c.getAssets().open("avatars-v3.webp"));Bitmap cut=Bitmap.createBitmap(photo,0,0,photo.getWidth()/2,photo.getHeight()/3);Bitmap image=Bitmap.createBitmap(512,512,Bitmap.Config.ARGB_8888);new Canvas(image).drawBitmap(cut,null,new RectF(40,40,472,472),new Paint(3));cut.recycle();photo.recycle();Bitmap cartoon=CartoonSticker.create(image,1);check(!image.sameAs(cartoon),"Cartoon style did not alter the image");byte[] encoded=AnimatedStickerCodec.encode(cartoon,0);check(encoded.length<=350000&&AnimatedStickerCodec.animated(encoded),"Animated sticker container invalid");Drawable drawable=ImageDecoder.decodeDrawable(ImageDecoder.createSource(ByteBuffer.wrap(encoded)));check(drawable instanceof AnimatedImageDrawable,"Recipient decoded a still image instead of animation");
  File dir=new File(c.getExternalFilesDir(null),"review");java.nio.file.Files.write(new File(dir,"63-created-sticker.webp").toPath(),encoded);
  PersonalStickerStore store=new PersonalStickerStore(c,a.vault.nick());String id=store.saveAnimation(encoded,cartoon,"Тест движения");check(java.util.Arrays.equals(Crypto.un64(store.read(id).getString("image")),encoded),"Animated bytes not persisted");
  StickerEditorActivity editor=(StickerEditorActivity)startActivitySync(new Intent(c,StickerEditorActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));runOnMainSync(()->{editor.canvas.setImage(image.copy(Bitmap.Config.ARGB_8888,true));editor.title.setText("Мой персонаж");editor.create();});long until=SystemClock.elapsedRealtime()+25000;while(editor.animation==null&&SystemClock.elapsedRealtime()<until)Thread.sleep(100);check(editor.animation!=null,"Photo-to-animated-sticker flow failed");shot("64-cartoon-sticker-editor");runOnMainSync(editor::finish);store.remove(id);image.recycle();cartoon.recycle();
  runOnMainSync(()->{a.openChat("bobby");a.compose.setText("");a.attachments();});check(contains(a.getWindow().getDecorView(),"Сообщение")||a.screen.equals("chat"),"Conversation lost");getUiAutomation().performGlobalAction(android.accessibilityservice.AccessibilityService.GLOBAL_ACTION_BACK);
  String mid=a.vault.queuePayload("bobby",new JSONObject().put("kind","text").put("text","Долгое нажатие открывает действия"),null);runOnMainSync(a::renderMessages);Thread.sleep(250);runOnMainSync(()->{View bubble=a.content.findViewWithTag(mid);check(bubble!=null&&bubble.performLongClick(),"Long press did not select message");});runOnMainSync(a::renderMessages);check(a.selectedMessage!=null&&a.selectionBar!=null&&contains(a.selectionBar,"Выбрано 1"),"Selection vanished after live message refresh");shot("65-message-selection");runOnMainSync(a::onBackPressed);waitForIdleSync();Thread.sleep(350);check(a.screen.equals("chat")&&a.selectedMessage==null,"Back left chat instead of dismissing selection");
  // Exercise the actual touch path; earlier capture tests called VoiceCapture directly.
  final long down=SystemClock.uptimeMillis();final int[] xy=new int[2];runOnMainSync(()->{a.compose.setText("");a.sendKey.getLocationOnScreen(xy);xy[0]+=a.sendKey.getWidth()/2;xy[1]+=a.sendKey.getHeight()/2;});MotionEvent press=MotionEvent.obtain(down,down,MotionEvent.ACTION_DOWN,xy[0],xy[1],0);press.setSource(InputDevice.SOURCE_TOUCHSCREEN);check(getUiAutomation().injectInputEvent(press,true),"Touch injection rejected");press.recycle();Thread.sleep(1400);shot("66-microphone-hold");check(a.voice!=null&&a.voice.running&&a.voice.ticks>8,"Hold gesture failed: screen="+a.screen+", voice="+(a.voice==null?"null":a.voice.running+"/ticks="+a.voice.ticks+"/level="+a.voice.levelError)+", held="+(a.heldVoice!=null)+", coordinates="+xy[0]+","+xy[1]);runOnMainSync(()->a.root.requestLayout());Thread.sleep(150);MotionEvent move=MotionEvent.obtain(down,SystemClock.uptimeMillis(),MotionEvent.ACTION_MOVE,xy[0]-a.dp(100),xy[1],0);move.setSource(InputDevice.SOURCE_TOUCHSCREEN);check(getUiAutomation().injectInputEvent(move,true),"Move injection rejected");move.recycle();MotionEvent up=MotionEvent.obtain(down,SystemClock.uptimeMillis(),MotionEvent.ACTION_UP,xy[0]-a.dp(100),xy[1],0);up.setSource(InputDevice.SOURCE_TOUCHSCREEN);check(getUiAutomation().injectInputEvent(up,true),"Release injection rejected");up.recycle();Thread.sleep(350);check(!a.voice.running&&a.voice.pending==null,"Slide-to-cancel retained or sent recording");
  result.putString("stream","OLDI_UPGRADE_PASS: real animated WebP from stylized photo, decode/persistence, global theme, left drawer, YouTube main entry, long-press selection, microphone hold and slide-to-cancel\n");finish(-1,result);
 }catch(Throwable e){result.putString("stream","OLDI_UPGRADE_FAIL: "+android.util.Log.getStackTraceString(e));finish(0,result);}}
}
