package chat.oldy;
import android.app.*;import android.content.*;import android.content.pm.ActivityInfo;import android.graphics.*;import android.net.Uri;import android.os.*;import android.view.*;import android.view.inputmethod.InputMethodManager;import java.io.*;import org.json.*;

/** Exercise full-window wallpaper, photo import, motion controls, IME and rotation. */
public class WallpaperInstrumentation extends Instrumentation {
 public void onCreate(Bundle b){start();}
 void check(boolean b,String s){if(!b)throw new AssertionError(s);}
 void settle()throws Exception{waitForIdleSync();Thread.sleep(550);}
 Bitmap shot(String name)throws Exception{settle();Bitmap b=getUiAutomation().takeScreenshot();File folder=new File(getTargetContext().getExternalFilesDir(null),"review");folder.mkdirs();try(FileOutputStream out=new FileOutputStream(new File(folder,name+".png"))){b.compress(Bitmap.CompressFormat.PNG,100,out);}return b;}
 int distance(int a,int b){return Math.abs(Color.red(a)-Color.red(b))+Math.abs(Color.green(a)-Color.green(b))+Math.abs(Color.blue(a)-Color.blue(b));}
 void full(MainActivity a,Bitmap image){int[] xy=new int[2];runOnMainSync(()->a.root.getLocationOnScreen(xy));check(xy[0]==0&&xy[1]==0,"Wallpaper does not start at physical screen edge");check(a.root.getWidth()==image.getWidth()&&a.root.getHeight()==image.getHeight(),"Wallpaper does not cover system bar areas");check(distance(image.getPixel(3,image.getHeight()/2),a.BG)>25,"Flat side gutter remains");}
 public void onStart(){Bundle result=new Bundle();try{
  MainActivity a=(MainActivity)startActivitySync(new Intent(getTargetContext(),MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));Thread.sleep(2900);
  runOnMainSync(()->{Notices.prefs(a).edit().putString("theme","light").putInt("wallpaper",2).putBoolean("wallpaper_photo",false).putBoolean("animations",false).commit();a.openChat("bobby");});Bitmap beige=shot("40-fullscreen-beige");full(a,beige);check(a.messagesScroll.getBackground() instanceof android.graphics.drawable.ColorDrawable,"Messages retain separate wallpaper");int side=beige.getPixel(3,beige.getHeight()/2);beige.recycle();
  runOnMainSync(()->{Notices.prefs(a).edit().putInt("wallpaper",1).commit();a.settings();});Bitmap purple=shot("41-fullscreen-purple-settings");full(a,purple);check(distance(side,purple.getPixel(3,purple.getHeight()/2))>40,"Changing wallpaper did not recolor outside conversation");purple.recycle();
  runOnMainSync(()->{Notices.prefs(a).edit().putString("theme","cyber").putInt("wallpaper",3).commit();a.openChat("bobby");});Bitmap cyber=shot("42-fullscreen-neon");full(a,cyber);cyber.recycle();
  ThemeLayout layout=(ThemeLayout)a.root;float phase=layout.backdrop.phase;Thread.sleep(250);check(layout.backdrop.phase==phase,"Animations-off still moves the wallpaper");
  Bitmap source=Bitmap.createBitmap(1200,600,Bitmap.Config.ARGB_8888);Canvas canvas=new Canvas(source);Paint p=new Paint();p.setColor(0xffb94366);canvas.drawRect(0,0,1200,600,p);p.setShader(new LinearGradient(300,0,900,600,0xff4eae8d,0xff258f87,Shader.TileMode.CLAMP));canvas.drawRect(300,0,900,600,p);File f=new File(a.getCacheDir(),"wallpaper-test.jpg");try(FileOutputStream out=new FileOutputStream(f)){source.compress(Bitmap.CompressFormat.JPEG,95,out);}source.recycle();WallpaperPhoto.importPhoto(a,Uri.fromFile(f));f.delete();
  runOnMainSync(()->{Notices.prefs(a).edit().putString("theme","light").putBoolean("wallpaper_photo",true).putBoolean("wallpaper_glow",false).commit();a.openChat("bobby");});Bitmap custom=shot("43-custom-photo-fullscreen");full(a,custom);int mid=custom.getPixel(3,custom.getHeight()/2);check(Color.green(mid)>Color.red(mid),"Landscape photo letterboxed or cropped away from its centre");custom.recycle();check(new ThemeBackdrop(a,true,false).photo!=null,"Imported photo did not persist");
  runOnMainSync(()->{a.compose.requestFocus();((InputMethodManager)a.getSystemService(Context.INPUT_METHOD_SERVICE)).showSoftInput(a.compose,InputMethodManager.SHOW_IMPLICIT);});Thread.sleep(900);Rect box=new Rect();runOnMainSync(()->a.compose.getGlobalVisibleRect(box));check(box.height()>=a.dp(30),"Input hidden by keyboard");if(Build.VERSION.SDK_INT>=30){WindowInsets insets=a.root.getRootWindowInsets();check(insets.isVisible(WindowInsets.Type.ime()),"Keyboard fixture did not open");check(box.bottom<=a.root.getHeight()-insets.getInsets(WindowInsets.Type.ime()).bottom,"Composer overlaps the keyboard");}shot("44-wallpaper-keyboard").recycle();
  runOnMainSync(()->{((InputMethodManager)a.getSystemService(Context.INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(a.compose.getWindowToken(),0);a.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);});Thread.sleep(950);Bitmap landscape=shot("45-wallpaper-landscape");full(a,landscape);check(landscape.getWidth()>landscape.getHeight(),"Landscape fixture failed");landscape.recycle();
  runOnMainSync(()->{a.setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);Notices.prefs(a).edit().putBoolean("wallpaper_photo",false).putBoolean("wallpaper_glow",true).putBoolean("animations",true).putString("theme","dark").commit();a.chats();});settle();runOnMainSync(a::wallpaperPicker);shot("46-wallpaper-picker").recycle();runOnMainSync(()->a.activeSheet.dismiss());
  result.putString("stream","OLDY_WALLPAPER_PASS: full physical display, theme changes, photo centre crop, persisted import, static mode, keyboard and landscape\n");finish(-1,result);
 }catch(Throwable e){result.putString("stream","OLDY_WALLPAPER_FAIL: "+android.util.Log.getStackTraceString(e));finish(0,result);}}
}
