package chat.oldy;
import android.app.*;import android.content.*;import android.graphics.*;import android.os.*;import android.view.*;import java.io.*;import org.json.*;

public class YouTubeInstrumentation extends Instrumentation {
 public void onCreate(Bundle b){start();}void check(boolean ok,String why){if(!ok)throw new AssertionError(why);}
 Context isolated(){File dir=new File(getTargetContext().getFilesDir(),"youtube-sticker-tests");dir.mkdirs();return new ContextWrapper(getTargetContext()){public File getFilesDir(){return dir;}};}
 void shot(String name)throws Exception{waitForIdleSync();Thread.sleep(500);Bitmap image=getUiAutomation().takeScreenshot();File dir=new File(getTargetContext().getExternalFilesDir(null),"review");dir.mkdirs();try(FileOutputStream out=new FileOutputStream(new File(dir,name+".png"))){image.compress(Bitmap.CompressFormat.PNG,100,out);}image.recycle();}
 public void onStart(){Bundle result=new Bundle();try{Context c=getTargetContext(),local=isolated();VideoLibraryStore alice=new VideoLibraryStore(local,"library_alice"),bob=new VideoLibraryStore(local,"library_bobby");String id="M7lc1UVf-VE";alice.remove(id);alice.update(id,"Local private title",754,2000,2);alice.toggle(id,"favorite");VideoLibraryStore reopened=new VideoLibraryStore(local,"library_alice");check(reopened.get(id).getInt("position")==754,"Position not restored");check(reopened.get(id).getBoolean("favorite"),"Favorite missing");check(bob.get(id).length()==0,"History crossed accounts");check(!new String(java.nio.file.Files.readAllBytes(alice.file.getBaseFile().toPath()),java.nio.charset.StandardCharsets.ISO_8859_1).contains("Local private title"),"History stored in plaintext");alice.clearHistory();check(alice.list("history").isEmpty()&&alice.list("favorite").size()==1,"History clear lost favorite");
  YouTubeDomainRules rules=YouTubeDomainRules.load(c);check(rules.matches("rr1---sn.example.googlevideo.com")&&!rules.matches("googlevideo.com.evil.example"),"Domain boundary invalid");boolean denied=false;try{new YouTubeDomainRules(new JSONObject().put("version",1).put("enabled",true).put("domains",new JSONArray().put("youtube.com")).put("proxy","https://attacker.example"));}catch(Exception expected){denied=true;}check(denied,"Config accepted arbitrary traffic redirection");TrafficClassifier classifier=new TrafficClassifier(rules);check(classifier.host(classifier.address("www.youtube.com",true)).equals("www.youtube.com"),"IPv6 classification lost host");check(classifier.host(classifier.address("www.youtube.com",false)).equals("www.youtube.com"),"IPv4 classification lost host");
  Bitmap source=Bitmap.createBitmap(512,512,Bitmap.Config.ARGB_8888);Canvas canvas=new Canvas(source);Paint p=new Paint(3);p.setColor(0xff7ce7dc);canvas.drawCircle(256,256,160,p);PersonalStickerStore stickers=new PersonalStickerStore(local,"library_alice");String sticker=stickers.save(source,"My private sticker"),second=stickers.save(source,"Another sticker");check(!sticker.equals(second),"New stickers share identity");JSONObject mine=stickers.read(sticker);Bitmap decoded=PersonalStickerStore.image(mine);check(decoded!=null&&Color.alpha(decoded.getPixel(0,0))==0,"Sticker transparency lost");check(new PersonalStickerStore(local,"library_bobby").list().isEmpty(),"Sticker collection crossed accounts");check(!new String(java.nio.file.Files.readAllBytes(stickers.path(sticker).toPath()),java.nio.charset.StandardCharsets.ISO_8859_1).contains("My private sticker"),"Sticker plaintext on disk");decoded.recycle();
  MainActivity a=(MainActivity)startActivitySync(new Intent(c,MainActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));Thread.sleep(2800);runOnMainSync(()->{I18n.setLanguage(a,"ru");Notices.prefs(a).edit().putString("theme","light").putInt("wallpaper",2).putBoolean("wallpaper_photo",false).commit();a.settings();});shot("50-grouped-settings");runOnMainSync(()->YouTubeSettings.show(a));shot("51-youtube-settings");runOnMainSync(()->{a.openChat("bobby");LinearLayoutCard(a,id);});shot("52-youtube-card");
  StickerEditorActivity editor=(StickerEditorActivity)startActivitySync(new Intent(c,StickerEditorActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));runOnMainSync(()->{editor.canvas.setImage(source.copy(Bitmap.Config.ARGB_8888,true));editor.title.setText("My sticker");});shot("53-sticker-editor");runOnMainSync(editor::finish);source.recycle();stickers.remove(sticker);stickers.remove(second);
  runOnMainSync(()->TunnelStateRepository.mode(a,"off"));OldiYouTubePlayer viewer=(OldiYouTubePlayer)startActivitySync(new Intent(c,OldiYouTubePlayer.class).putExtra("youtube_url","https://www.youtube.com/watch?v="+id).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));Thread.sleep(2000);runOnMainSync(()->{check(viewer.web!=null,"Embedded WebView not created");check(!viewer.web.getSettings().getAllowFileAccess()&&!viewer.web.getSettings().getAllowContentAccess(),"WebView can access private files");check(viewer.web.getSettings().getMixedContentMode()==android.webkit.WebSettings.MIXED_CONTENT_NEVER_ALLOW,"Mixed content allowed");});runOnMainSync(()->viewer.onActivityResult(OldiYouTubePlayer.VPN_REQUEST,Activity.RESULT_CANCELED,null));check(viewer.status.getText().toString().contains("отклонено"),"Permission decline fallback missing");check(OldiYouTubePlayer.errorText(150).contains("нельзя воспроизвести"),"Embed refusal is not explained");shot("54-youtube-viewer");runOnMainSync(viewer::finish);runOnMainSync(()->{TunnelStateRepository.mode(a,"ask");a.chats();});
  result.putString("stream","OLDY_YOUTUBE_PASS: isolated encrypted history and stickers, resume state, favorites, safe rules, IPv4/IPv6 classifier, grouped settings, editor and embedded player/permission fallback\n");finish(-1,result);
 }catch(Throwable e){result.putString("stream","OLDY_YOUTUBE_FAIL: "+android.util.Log.getStackTraceString(e));finish(0,result);}}
 void LinearLayoutCard(MainActivity a,String id){try{a.addLink(a.content,new JSONObject().put("url","https://www.youtube.com/watch?v="+id).put("title","YouTube · Oldi").put("site","YouTube"),true);}catch(Exception e){throw new RuntimeException(e);}}
}
